[build]
builder = "nixpacks"

[build.nixpacks]
buildCmd = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Trigger rebuild Fri Apr  3 15:25:33 EDT 2026
