#!/usr/bin/env bash
# Cloud Agent — durable repository setup (runs once at build/snapshot time).
# Idempotent: safe to re-run against cached or partially prepared state.
#   - PostgreSQL 16 + pgvector (the knowledge-embeddings migration needs it)
#   - a local dev role/database matching .env.example
#   - a local .env (created only if missing — never overwrites secrets)
#   - node workspace dependencies
#   - knex migrations
set -euo pipefail
cd "$(dirname "$0")/.."

echo "[install] ensuring PostgreSQL 16 + pgvector are present"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql postgresql-contrib postgresql-16-pgvector
elif ! dpkg -s postgresql-16-pgvector >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql-16-pgvector
fi

echo "[install] starting PostgreSQL cluster"
sudo pg_ctlcluster 16 main start 2>/dev/null || true
for _ in $(seq 1 30); do sudo -u postgres pg_isready -q && break; sleep 1; done

echo "[install] ensuring dev role + database"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<'SQL'
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'waves_user') THEN
    CREATE ROLE waves_user LOGIN PASSWORD 'waves_dev_password' SUPERUSER CREATEROLE CREATEDB;
  END IF;
END $$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname = 'waves_portal'" | grep -q 1; then
  sudo -u postgres createdb -O waves_user waves_portal
fi

if [ ! -f .env ]; then
  echo "[install] writing local .env (generated dev secrets)"
  JWT="$(openssl rand -hex 32)"
  HANDOFF="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Local Cloud Agent dev environment (generated by .cursor/install.sh)
NODE_ENV=development
PORT=3001
API_URL=http://localhost:3001
CLIENT_URL=http://localhost:5173
WAVES_FDACS_LICENSE=JB351547
VITE_WAVES_FDACS_LICENSE=JB351547

DATABASE_URL=postgresql://waves_user:waves_dev_password@127.0.0.1:5432/waves_portal
DB_POOL_MIN=2
DB_POOL_MAX=10

JWT_SECRET=${JWT}
JWT_EXPIRY=7d
REFRESH_TOKEN_EXPIRY=30d
STAFF_MAINTENANCE_MODE=false
TERMINAL_HANDOFF_SECRET=${HANDOFF}

LOG_LEVEL=info
EOF
else
  echo "[install] .env already present — leaving it untouched"
fi

echo "[install] installing node dependencies"
npm install

echo "[install] running database migrations"
npm run db:migrate

echo "[install] done"
