#!/usr/bin/env bash
# Cloud Agent — durable repository setup (runs once at build/snapshot time).
# Idempotent: safe to re-run against cached or partially prepared state.
#   - PostgreSQL 16 + pgvector (the knowledge-embeddings migration needs it)
#   - a local dev role/database matching .env.example
#   - a local .env (created only if missing — never overwrites secrets)
#   - node workspace dependencies
#   - knex migrations (against the LOCAL database only)
set -euo pipefail
# Resolve our own directory BEFORE changing cwd so relative/`./install.sh`
# invocations still find lib.sh.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=.cursor/lib.sh
source "${SCRIPT_DIR}/lib.sh"
cd "${REPO_ROOT}"

# Fast pre-check: reject an obviously non-local DATABASE_URL injected via the
# secrets panel before doing any heavy work. (The authoritative check that also
# covers a cached .env / fallback vars runs right before migrations, below.)
assert_local_database_url

echo "[install] ensuring PostgreSQL 16 + pgvector are present"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql postgresql-contrib postgresql-16-pgvector
elif ! dpkg -s postgresql-16-pgvector >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql-16-pgvector
fi

echo "[install] starting PostgreSQL cluster"
sudo pg_ctlcluster 16 main start 2>/dev/null || true
# Resolve the 16/main port AFTER install/start — on a cached image with an older
# cluster on 5432 the 16 cluster lands on a different port, and every client
# below (and the generated URL) must target THAT port, not the default cluster.
PG_PORT="$(pg_local_port)"
echo "[install] PostgreSQL 16 cluster on port ${PG_PORT}"
for _ in $(seq 1 30); do sudo -u postgres pg_isready -p "${PG_PORT}" -q && break; sleep 1; done

echo "[install] ensuring dev role + database"
# Create the role if missing, otherwise RECONCILE it — a cached/partial state
# may hold waves_user with a stale password or without the privileges the
# role-creating migrations need. Either way it ends with the exact password
# baked into the local URL and the required attributes.
sudo -u postgres psql -p "${PG_PORT}" -v ON_ERROR_STOP=1 <<'SQL'
DO $$ BEGIN
  IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'waves_user') THEN
    ALTER ROLE waves_user WITH LOGIN PASSWORD 'waves_dev_password' SUPERUSER CREATEROLE CREATEDB;
  ELSE
    CREATE ROLE waves_user WITH LOGIN PASSWORD 'waves_dev_password' SUPERUSER CREATEROLE CREATEDB;
  END IF;
END $$;
SQL
if ! sudo -u postgres psql -p "${PG_PORT}" -tAc "SELECT 1 FROM pg_database WHERE datname = 'waves_portal'" | grep -q 1; then
  sudo -u postgres createdb -p "${PG_PORT}" -O waves_user waves_portal
fi

if [ ! -f .env ]; then
  echo "[install] writing local .env (generated dev secrets)"
  JWT="$(openssl rand -hex 32)"
  HANDOFF="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Local Cloud Agent dev environment (generated by .cursor/install.sh)
NODE_ENV=development
PORT=3001
API_URL=http://localhost:3001
CLIENT_URL=http://localhost:5173
WAVES_FDACS_LICENSE=JB351547
VITE_WAVES_FDACS_LICENSE=JB351547

DATABASE_URL=$(local_database_url)
DB_POOL_MIN=2
DB_POOL_MAX=10

JWT_SECRET=${JWT}
JWT_EXPIRY=7d
REFRESH_TOKEN_EXPIRY=30d
STAFF_MAINTENANCE_MODE=false
TERMINAL_HANDOFF_SECRET=${HANDOFF}

LOG_LEVEL=info
EOF
else
  echo "[install] .env already present — leaving it untouched"
fi

echo "[install] installing node dependencies"
npm install

# Authoritative DB-target guard: resolve the effective URL the way knexfile
# does (dotenv .env + fallback vars) and refuse anything non-local BEFORE we
# migrate. Runs here (post-install) because it needs node deps.
assert_local_effective_database_url

echo "[install] running database migrations"
npm run db:migrate

echo "[install] done"
