module.exports = [
  {
    event_key: 'estimate.sent',
    name: 'Estimate sent',
    audience: 'lead',
    description: 'An admin delivered an estimate.',
    fires_when: 'Immediately on estimate send',
    source: 'server/routes/admin-estimates.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'estimate.viewed',
    name: 'Estimate viewed',
    audience: 'lead',
    description: 'A lead opened an estimate link for the first time.',
    fires_when: 'When the public estimate view is first tracked',
    source: 'server/routes/estimate-public.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'estimate.followup_questions',
    name: 'Estimate questions opener',
    audience: 'lead',
    description: 'An open estimate got the touch-1 questions opener (viewed and not-yet-viewed copy variants).',
    fires_when: '48-72 hours after send while the estimate is open',
    source: 'server/services/estimate-follow-up.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'estimate.followup_checkin',
    name: 'Estimate day-5 check-in',
    audience: 'lead',
    description: 'An open estimate got the day-5 check-in (the slot the First-Year Protection Credit occupies once the offer engine ships).',
    fires_when: '5-6 days after send while the estimate is open',
    source: 'server/services/estimate-follow-up.js',
    channels_expected: ['sms'],
  },
  {
    event_key: 'estimate.expiring_soon',
    name: 'Estimate last-day notice',
    audience: 'lead',
    description: 'An open estimate expires tomorrow.',
    fires_when: 'The day before expires_at',
    source: 'server/services/estimate-follow-up.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'estimate.auto_renewed',
    name: 'Estimate auto-renewed',
    audience: 'lead',
    description: 'Waves extended an estimate expiration date automatically.',
    fires_when: 'Immediately after an eligible estimate is extended',
    source: 'server/services/estimate-auto-renew.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'invoice.sent',
    name: 'Invoice sent',
    audience: 'customer',
    description: 'An invoice was issued to a customer.',
    fires_when: 'Immediately on invoice send',
    source: 'server/services/invoice.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'invoice.paid',
    name: 'Invoice paid',
    audience: 'customer',
    description: 'A payment was recorded and a receipt can be sent.',
    fires_when: 'Immediately after payment is recorded',
    source: 'server/routes/admin-invoices.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'payment.failed',
    name: 'Payment failed',
    audience: 'customer',
    description: 'An autopay or saved-card attempt failed.',
    fires_when: 'When Stripe reports payment_intent.payment_failed',
    source: 'server/routes/stripe-webhook.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'payment.ach_processing',
    name: 'Bank payment received - processing',
    audience: 'customer',
    description: 'A customer ACH bank payment is in flight (3-5 business days to clear).',
    fires_when: 'When Stripe reports payment_intent.processing for an ACH payment',
    source: 'server/routes/stripe-webhook.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'service_report.ready',
    name: 'Service report ready',
    audience: 'customer',
    description: 'A completed service report is ready for the customer.',
    fires_when: 'After a service visit is marked complete',
    source: 'server/routes/admin-dispatch.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'project_report.ready',
    name: 'Project report ready',
    audience: 'customer',
    description: 'A project or inspection report is ready for the customer.',
    fires_when: 'After a project report is published',
    source: 'server/routes/admin-projects.js',
    channels_expected: ['email'],
  },
  {
    event_key: 'appointment.booked',
    name: 'Appointment booked',
    audience: 'customer',
    description: 'A customer appointment was booked or confirmed.',
    fires_when: 'Immediately after booking confirmation',
    source: 'server/services/appointment-reminders.js',
    channels_expected: ['email', 'sms'],
  },
  {
    event_key: 'customer.recurring_created',
    name: 'Recurring customer created',
    audience: 'customer',
    description: 'A customer started recurring service.',
    fires_when: 'Immediately after recurring customer setup',
    source: 'server/routes/booking.js',
    channels_expected: ['email', 'sms'],
  },
];
