exports.up = async function (knex) {
  // ALTER sms_log: add is_read column
  const smsColInfo = await knex('sms_log').columnInfo().catch(() => ({}));
  if (Object.keys(smsColInfo).length && !smsColInfo.is_read) {
    await knex.schema.alterTable('sms_log', (t) => {
      t.boolean('is_read').defaultTo(false);
    });
  }

  // Seed field_tech lead source if not exists
  const existing = await knex('lead_sources')
    .where({ name: 'Field Tech Observation' })
    .first();

  if (!existing) {
    await knex('lead_sources').insert({
      name: 'Field Tech Observation',
      source_type: 'direct',
      channel: 'field_observation',
      cost_type: 'free',
      is_active: true,
      notes: 'Leads generated by technicians while on-site at customer properties',
    });
  }

  // Add qa_status column to service_photos if it doesn't exist
  const photoColInfo = await knex('service_photos').columnInfo().catch(() => ({}));
  if (Object.keys(photoColInfo).length) {
    if (!photoColInfo.qa_status) {
      await knex.schema.alterTable('service_photos', (t) => {
        t.string('qa_status', 20).defaultTo('pending'); // pending, flagged, approved
      });
    }
    if (!photoColInfo.qa_notes) {
      await knex.schema.alterTable('service_photos', (t) => {
        t.text('qa_notes').nullable();
      });
    }
  }
};

exports.down = async function (knex) {
  const smsColInfo = await knex('sms_log').columnInfo().catch(() => ({}));
  if (smsColInfo.is_read) {
    await knex.schema.alterTable('sms_log', (t) => {
      t.dropColumn('is_read');
    });
  }

  const photoColInfo = await knex('service_photos').columnInfo().catch(() => ({}));
  if (photoColInfo.qa_status) {
    await knex.schema.alterTable('service_photos', (t) => {
      t.dropColumn('qa_status');
    });
  }
  if (photoColInfo.qa_notes) {
    await knex.schema.alterTable('service_photos', (t) => {
      t.dropColumn('qa_notes');
    });
  }

  await knex('lead_sources').where({ name: 'Field Tech Observation' }).del();
};
