/**
 * scheduled_services.first_application_invoice_id — durable, stamped-at-
 * source provenance for which combined first-application invoice (if any)
 * covers this visit. Owner ruling 2026-09-27 (PR #5021 P1 follow-up):
 * first-application-sibling-split.js's periodic sweep previously GUESSED
 * same-trip membership structurally (an unpriced sibling, or one with no
 * live invoice of its own) — Codex proved that guess can't tell a genuine
 * same-trip pair apart from two independently billed recurring programs
 * that simply haven't both been invoiced yet.
 *
 * Recorded instead, once, at the moment estimate-converter.js actually
 * mints the combined "First service application" invoice
 * (stampCombinedFirstApplicationInvoiceCoverage): every covered member —
 * the reserved anchor AND each promoted same-day sibling — is stamped
 * with the SAME invoices.id, in the SAME transaction that creates the
 * invoice, and ONLY when 2+ programs actually share it (a single-program
 * accept is never stamped as a pair). NULL on every visit not covered by
 * a combined invoice — the overwhelming majority. This is a SEPARATE
 * relationship from invoices.scheduled_service_id (a visit's OWN,
 * independently billed invoice) — a stamped member's invoice is never its
 * own; only the anchor's happens to coincide (invoices.scheduled_service_id
 * IS the anchor's id).
 *
 * FK ON DELETE SET NULL: an invoice row is never hard-deleted in normal
 * operation (voided instead), but the constraint keeps the column honest
 * if one ever is.
 *
 * Backfill (same migration, bounded — prod has only a handful of live
 * pairs): the OLD recognition this column replaces —
 * isAutoGeneratedPayPerApplicationInvoice's title/notes text match
 * (estimate-first-application-invoice.js) on a non-void invoice, joined to
 * its own anchor visit, with unpriced same-customer/same-estimate/
 * same-date top-level recurring siblings — stamps every live historical
 * pair once. Idempotent: reruns recompute the same deterministic mapping
 * and overwrite with the same value.
 */

exports.up = async function up(knex) {
  if (!(await knex.schema.hasTable('scheduled_services')) || !(await knex.schema.hasTable('invoices'))) return;

  if (!(await knex.schema.hasColumn('scheduled_services', 'first_application_invoice_id'))) {
    await knex.schema.alterTable('scheduled_services', (t) => {
      const col = t.uuid('first_application_invoice_id');
      col.references('id').inTable('invoices').onDelete('SET NULL');
      t.index('first_application_invoice_id');
    });
  }

  // Shared with a direct-testable/rerunnable export
  // (estimate-first-application-invoice.js backfillFirstApplicationInvoiceStamps)
  // rather than duplicated here — same logic, one place.
  const { backfillFirstApplicationInvoiceStamps } = require('../../services/estimate-first-application-invoice');
  await backfillFirstApplicationInvoiceStamps(knex);
};

exports.down = async function down(knex) {
  if (!(await knex.schema.hasTable('scheduled_services'))) return;
  if (await knex.schema.hasColumn('scheduled_services', 'first_application_invoice_id')) {
    await knex.schema.alterTable('scheduled_services', (t) => {
      t.dropColumn('first_application_invoice_id');
    });
  }
};
