/**
 * POST /:id/invoice (Charge Now mint) — sibling-lookup refusal.
 *
 * Codex round-2 P1: resolveScheduledServiceCharge used to return the SAME
 * bare 0 for a sibling-coverage lookup that came back 'error' or
 * 'needs_review' as it does for a genuinely 'covered' visit. That 0 only
 * blocked THIS endpoint's "nothing chargeable" gate when extraLineItems
 * were also empty — the instant a checkout extra carried a positive total,
 * `!(amount > 0) && extrasTotal <= 0` was false and the route minted an
 * extras-only invoice, silently dropping the visit's real setup/application
 * fee. Completion then found that own live invoice first and never raised
 * the manual-billing alert for the missing fee.
 *
 * This suite pins that an unresolved sibling lookup now refuses the ENTIRE
 * mint — base AND extras — with a retryable 409, never a partial extras
 * invoice. Follows this repo's route-test convention (no supertest
 * harness): locate the handler on router.stack and drive it directly
 * against mocked deps (mirrors admin-schedule-checkout-stacking-gate.test.js).
 */
jest.mock('../services/estimate-first-application-invoice', () => ({
  // combinedInvoiceVoidedWithoutLiveReplacement (billing-lane.js) reuses the
  // REAL, pure isAutoGeneratedPayPerApplicationInvoice (no DB, no side
  // effects) to recognize a voided combined invoice's notes — only the
  // DB-backed lookup itself is mocked below.
  ...jest.requireActual('../services/estimate-first-application-invoice'),
  findFirstApplicationInvoiceForEstimateService: jest.fn(),
}));

const mockDb = jest.fn((table) => {
  const q = {};
  let usedWhereIn = false;
  q.where = jest.fn(() => q);
  q.whereNot = jest.fn(() => q);
  q.whereNotIn = jest.fn(() => q);
  q.whereNull = jest.fn(() => q);
  q.whereIn = jest.fn(() => { usedWhereIn = true; return q; });
  q.orderBy = jest.fn(() => q);
  q.modify = jest.fn((fn) => { fn(q); return q; });
  q.leftJoin = jest.fn(() => q);
  q.join = jest.fn(() => q);
  q.forUpdate = jest.fn(() => q);
  q.noWait = jest.fn(() => q);
  q.select = jest.fn(() => q);
  q.first = jest.fn(async () => {
    if (table === 'scheduled_services') return mockDb.__svcRow;
    if (table === 'invoices') {
      // completionTerminalInvoiceLookup (pricedCoveredMemberOwnRefundHold,
      // #5237 review r2 P2) is the ONLY 'invoices' query on this table that
      // calls .whereIn('status', ...) — distinguishes its own-row-refund
      // read from isPricedCoveredMemberVisit's plain by-id anchor-identity
      // read (and from the route's own existing-invoice reuse checks, which
      // use .whereNot/.whereNotIn), which otherwise share this exact
      // table/`.first()` shape.
      if (usedWhereIn) return mockDb.__ownRefundInvoiceRow;
      // Codex round-9 P1: a legacy invoice already attached to THIS visit's
      // own scheduled_service_id (e.g. an extras-only invoice minted before
      // the sibling-coverage lookup existed) — set only by the tests below
      // that prove the reuse block never bypasses a 'covered'/'needs_review'
      // verdict.
      return mockDb.__existingInvoiceRow;
    }
    return undefined;
  });
  // Owner ruling — REFUSE AFTER A VOID: combinedInvoiceVoidedWithoutLiveReplacement's
  // own query is on table 'invoices as i' and is AWAITED DIRECTLY (mirrors
  // the real knex `.select()` thenable — `await query` resolves to the row
  // array), never through `.first()`. `mockDb.__invoiceRows` (default `[]`,
  // i.e. nothing on file anywhere in the estimate/date/customer group) is
  // the full candidate set that query would return — every existing test
  // that doesn't set it keeps every verdict unchanged.
  if (table === 'invoices as i') {
    q.then = (resolve, reject) => Promise.resolve(mockDb.__invoiceRows || []).then(resolve, reject);
    q.catch = (reject) => Promise.resolve(mockDb.__invoiceRows || []).catch(reject);
  }
  // liveBaseApplicationInvoiceVisitIdsOn (isPricedCoveredMemberVisit's own
  // "split off by hand" check) ends its plain 'invoices' chain in
  // `.select(cols)`, never `.first()` — thenable here too, so its `await`
  // resolves an array instead of this fake query-builder object itself.
  // `mockDb.__splitOffInvoiceRows` (default `[]`, i.e. no member has split
  // itself off with its own live base-application invoice) keeps every
  // existing verdict unchanged; only the tests below that prove the
  // split-off exclusion set it.
  if (table === 'invoices') {
    q.then = (resolve, reject) => Promise.resolve(mockDb.__splitOffInvoiceRows || []).then(resolve, reject);
    q.catch = (reject) => Promise.resolve(mockDb.__splitOffInvoiceRows || []).catch(reject);
  }
  return q;
});
mockDb.schema = { hasTable: jest.fn(async () => false) };
jest.mock('../models/db', () => mockDb);

const mockMint = jest.fn();
jest.mock('../services/scheduled-invoice-mint', () => ({
  mintScheduledServiceInvoiceWithDeposit: (...args) => mockMint(...args),
}));

const mockResolveForInvoice = jest.fn(async () => ({ payerId: null }));
jest.mock('../services/payer', () => ({
  resolveForInvoice: (...args) => mockResolveForInvoice(...args),
}));

const mockBuildLineItems = jest.fn(async () => ({ lineItems: [], discountIds: [] }));
jest.mock('../services/invoice', () => ({
  buildLineItemsForScheduledService: (...args) => mockBuildLineItems(...args),
  CANCELLED_SERVICE_RESOLVED_STATUSES: ['refunded', 'canceled', 'void'],
}));

const { findFirstApplicationInvoiceForEstimateService } = require('../services/estimate-first-application-invoice');
const adminScheduleRouter = require('../routes/admin-schedule');

const layer = adminScheduleRouter.stack.find(
  (l) => l.route && l.route.path === '/:id/invoice' && l.route.methods.post,
);
const handler = layer.route.stack[layer.route.stack.length - 1].handle;

// An unpriced per_application visit — the exact shape resolveScheduledServiceCharge's
// own sibling-coverage guard inspects (source_estimate_id + scheduled_date
// feed findFirstApplicationInvoiceForEstimateService). Owner ruling — REMOVE
// THE CHARGE NOW FEE FALLBACK: cust_per_application_fee is no longer read by
// this resolver at all (only completion still reads it) — deliberately
// absent from this fixture now rather than left as an inert leftover.
const SVC_ROW = {
  id: 'svc-lawn', customer_id: 'cust-1', source_estimate_id: 'est-1', scheduled_date: '2026-09-27',
  estimated_price: null, is_callback: false, prepaid_method: null, prepaid_amount: null,
  cust_monthly_rate: 74.7, cust_billing_mode: 'per_application', service_type: 'Every 6 Weeks Lawn Care',
};

// The recognized notes isAutoGeneratedPayPerApplicationInvoice checks for —
// combinedInvoiceVoidedWithoutLiveReplacement's own query resolves to rows
// like this one when the estimate's combined invoice was voided.
const RECOGNIZED_VOIDED_INVOICE = {
  id: 'inv-void', invoice_number: 'WPC-TEST-0099', status: 'void', title: 'First application',
  notes: 'Auto-generated from accepted estimate #est-1 — customer selected pay per application — first application.',
};

function makeReqRes(body) {
  const req = { params: { id: 'svc-lawn' }, body, headers: {} };
  const res = {
    statusCode: 200,
    body: undefined,
    status: jest.fn(function status(c) { this.statusCode = c; return this; }),
    json: jest.fn(function json(b) { this.body = b; return this; }),
  };
  const next = jest.fn();
  return { req, res, next };
}

beforeEach(() => {
  jest.clearAllMocks();
  mockDb.__svcRow = SVC_ROW;
  mockDb.__existingInvoiceRow = undefined;
  mockDb.__ownRefundInvoiceRow = undefined;
  mockDb.__splitOffInvoiceRows = [];
  mockDb.__invoiceRows = [];
  mockResolveForInvoice.mockResolvedValue({ payerId: null });
  mockBuildLineItems.mockResolvedValue({ lineItems: [], discountIds: [] });
});

describe('POST /:id/invoice — sibling-lookup refusal (codex round-2 P1)', () => {
  test('a lookup FAILURE refuses the whole mint with a retryable 409 — never a bare 400 "no chargeable amount"', async () => {
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/refresh and try again/i);
    expect(mockMint).not.toHaveBeenCalled();
    expect(next).not.toHaveBeenCalled();
  });

  test('a terminal/refunded sibling match (needs_review) refuses the whole mint with a retryable 409', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/manual review/i);
    expect(mockMint).not.toHaveBeenCalled();
  });

  // This is the exact bug: pre-fix, resolveScheduledServiceCharge returned
  // 0 for this verdict, `!(0 > 0) && extrasTotal <= 0` was FALSE because
  // extrasTotal is positive, and the route minted an extras-only invoice
  // for the visit — dropping the real acceptance fee. Post-fix, the
  // refusal must be checked BEFORE extras are even considered.
  test('an operator-added checkout extra does NOT slip the refusal into an extras-only mint', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: null,
      liveBeside: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
    const { req, res, next } = makeReqRes({
      extraLineItems: [{ description: 'Extra treatment', quantity: 1, unit_price: 40, amount: 40 }],
    });
    await handler(req, res, next);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(mockMint).not.toHaveBeenCalled();
  });

  // Codex round 5 P2: a callback's base charge is always zeroed by
  // completionInvoiceAmount regardless of what the sibling lookup would
  // have said (isCallback short-circuits before perApplicationBilling is
  // even consulted) — so the lookup can only ever 409 a checkout extra
  // for a trip the callback itself can never rebill. Excluded the same
  // way always-free service types already are: the lookup must never run
  // for a callback, and a positive extra must mint normally even when the
  // (unconsulted) sibling verdict would have been needs_review/error.
  test('a callback never runs the sibling lookup — a checkout extra mints normally even though the (unconsulted) verdict would refuse', async () => {
    mockDb.__svcRow = { ...SVC_ROW, is_callback: true };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: null,
    });
    mockMint.mockImplementation(async ({ buildCreateParams }) => {
      buildCreateParams();
      throw new Error('stop-after-capture');
    });
    const { req, res, next } = makeReqRes({
      extraLineItems: [{ description: 'Extra treatment', quantity: 1, unit_price: 40, amount: 40 }],
    });
    await handler(req, res, next);

    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
    expect(res.status).not.toHaveBeenCalledWith(409);
    expect(mockMint).toHaveBeenCalledTimes(1);
    expect(next).toHaveBeenCalledTimes(1);
  });

  // Owner ruling — REMOVE THE CHARGE NOW FEE FALLBACK (2026-09-27): this used
  // to prove a definitive 'none' verdict falls through to mint the
  // customer's established cust_per_application_fee. That fallback is gone
  // — Charge Now must never bill an unpriced visit from the customer-level
  // per_application_fee (main's original behavior, restored).
  //
  // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13,
  // codex pre-push P1): a 'none' verdict for this shape (unpriced,
  // non-callback, non-always-free, per_application) now refuses the WHOLE
  // mint with a 409, the same way a covered sibling visit already does
  // (round-8 P1) — not the plain 400 "nothing chargeable" every other $0
  // reason still gets. Completion bills the acceptance fee for this exact
  // shape; a bare 0 that let this route's own reuse/extras logic run past
  // it could still attach an extras-only invoice that strands that fee.
  test('a definitive "none" verdict with an established fee on file still refuses — the whole mint, a 409', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/bills its application fee at completion/i);
    expect(mockMint).not.toHaveBeenCalled();
    expect(next).not.toHaveBeenCalled();
  });

  // Owner ruling — REFUSE AFTER A VOID: the voided-combined scenario. The
  // reserved (pest) sibling's original combined acceptance invoice was
  // voided — findFirstApplicationInvoiceForEstimateService's own query
  // excludes 'void' entirely, so it reports 'none' for the promoted (lawn)
  // sibling exactly as it did before this fix, regardless of whatever
  // Charge Now reminted afterward on the reserved row (that replacement
  // carries no recognized acceptance-flow notes either way — never counts
  // as "a live recognized one"). combinedInvoiceVoidedWithoutLiveReplacement
  // must catch the voided recognized invoice and refuse the WHOLE mint with
  // a 409 — never silently charge the per-application fee on top of a trip
  // whose combined amount the reserved row still (correctly) bills once.
  test('a voided combined invoice with no live recognized replacement refuses with a 409, never a double charge', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    mockDb.__invoiceRows = [RECOGNIZED_VOIDED_INVOICE];
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/manual review/i);
    expect(mockMint).not.toHaveBeenCalled();
  });

  // The normal, unaffected case: no voided combined invoice anywhere, and
  // the sibling group has genuinely nothing minted yet — the guard must
  // not invent a review state out of nothing. With the fee fallback gone,
  // this unpriced per_application visit refuses the WHOLE mint (round 13),
  // a 409 — never the plain 400 "nothing chargeable" a lane with no fee at
  // stake would get.
  test('a normal "none" verdict with nothing on the estimate at all refuses the whole mint, a 409', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    mockDb.__invoiceRows = [];
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/bills its application fee at completion/i);
    expect(mockMint).not.toHaveBeenCalled();
    expect(next).not.toHaveBeenCalled();
  });

  // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13,
  // codex pre-push P1): the exact bug this ruling fixes. Before this fix, a
  // $0 base plus a positive checkout extra cleared this route's own
  // "amount > 0 OR extras > 0" mint gate and attached a real extras-only
  // invoice to the visit's own scheduled_service_id — completion's
  // existingCompletionInvoice lookup (complete-scheduled-service.js) would
  // then find that invoice and reuse it as-is, never re-running the fee
  // decision, silently losing the acceptance fee. The refusal must fire
  // BEFORE extras are even parsed — same as a covered sibling visit
  // (round-8 P1) — so no extra amount can ever slip past it.
  test('a normal "none" verdict with a checkout extra STILL refuses the whole mint — no extras-only invoice', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    mockDb.__invoiceRows = [];
    const { req, res, next } = makeReqRes({
      extraLineItems: [{ description: 'Extra treatment', quantity: 1, unit_price: 40, amount: 40 }],
    });
    await handler(req, res, next);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/bills its application fee at completion/i);
    expect(mockMint).not.toHaveBeenCalled();
    expect(mockBuildLineItems).not.toHaveBeenCalled();
  });

  // The lane this ruling does NOT touch (checked and cleared — see
  // prepaid-receipt-gate.test.js's own "no equivalent gap" pure-resolver
  // proof): a monthly_membership visit's fallback is `monthlyRate`, so an
  // unpriced visit with a rate on file already resolves a positive amount
  // through this SAME resolver — a checkout extra mints normally, stacked
  // on top of the base, exactly as it always has.
  test('an unpriced monthly_membership visit with a checkout extra mints normally — no equivalent gap for this lane', async () => {
    mockDb.__svcRow = { ...SVC_ROW, cust_billing_mode: 'monthly_membership', cust_monthly_rate: 74.7 };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    mockMint.mockImplementation(async ({ buildCreateParams }) => {
      buildCreateParams();
      throw new Error('stop-after-capture');
    });
    const { req, res, next } = makeReqRes({
      extraLineItems: [{ description: 'Extra treatment', quantity: 1, unit_price: 40, amount: 40 }],
    });
    await handler(req, res, next);

    expect(res.status).not.toHaveBeenCalledWith(409);
    expect(res.status).not.toHaveBeenCalledWith(400);
    expect(mockMint).toHaveBeenCalledTimes(1);
    expect(next).toHaveBeenCalledTimes(1);
    expect(mockBuildLineItems).toHaveBeenCalledWith('svc-lawn', expect.objectContaining({
      fallbackAmount: 74.7,
    }));
  });

  // Codex round-6 P1: this gate used to be `perApplicationBilling &&
  // !isCallback && !hasOwnPrice` — the CUSTOMER'S CURRENT billing mode. A
  // combined pay-per-application accept leaves the PROMOTED row unpriced
  // and its first-application invoice on the RESERVED sibling; if the
  // customer is later moved to monthly/legacy-null dues (a lane change),
  // the old gate skipped the sibling lookup entirely and fell through to
  // `monthly_rate`, minting a SECOND collectible base charge beside the
  // sibling's still-live invoice. The fix gates on the visit's own shape
  // (isSiblingCoverageEligibleVisit, billing-lane.js) instead, so the
  // lookup still runs — and the mint still refuses the double charge —
  // no matter what lane the customer is on today.
  test('a lane-changed customer (per_application → monthly) still runs the sibling lookup off the visit\'s own shape, not the current billing mode', async () => {
    mockDb.__svcRow = { ...SVC_ROW, cust_billing_mode: 'monthly_membership', cust_monthly_rate: 74.7 };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    // The lookup ran despite `cust_billing_mode` no longer being
    // 'per_application' — proving the gate reads the visit's shape, not
    // the mutable lane.
    expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalled();
    // Owner decision (round-8 P1, narrow + fail closed): a definitive
    // 'covered' verdict now refuses the mint OUTRIGHT with a 409, never
    // falls through to $0-plus-extras — the pre-fix regression instead fell
    // through to the $74.70 monthly rate and minted it, a real second
    // charge beside the sibling's invoice.
    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/combined trip invoice/i);
    expect(mockMint).not.toHaveBeenCalled();
  });

  test('a lane-changed customer with an unresolved sibling verdict (needs_review) still refuses instead of charging the monthly rate', async () => {
    mockDb.__svcRow = { ...SVC_ROW, cust_billing_mode: null, cust_monthly_rate: 74.7 };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.body.error).toMatch(/manual review/i);
    expect(mockMint).not.toHaveBeenCalled();
  });

  // Codex pre-push P1 (round 3): resolveScheduledServiceCharge's verdict is
  // read on a plain connection BEFORE mintScheduledServiceInvoiceWithDeposit
  // opens its locked transaction — a concurrent refund/restoration can
  // invalidate it before the invoice is actually created. The route must
  // pass a `recheckInTrx` that re-runs the SAME lookup (lockRows: true, so
  // it holds the matched row to commit) and refuses the mint if the status
  // changed.
  describe('recheckInTrx — the sibling verdict is re-proven inside the mint lock', () => {
    test('passes a recheckInTrx for a "none" verdict, which re-runs the lookup WITH lockRows: true', async () => {
      // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13):
      // SVC_ROW's own per_application shape now refuses the WHOLE mint
      // unconditionally (base or extras) — a monthly_membership lane with a
      // rate on file is what makes the mint (and so recheckInTrx) reachable
      // here; that lane has no equivalent gap (see prepaid-receipt-gate.test.js).
      mockDb.__svcRow = { ...SVC_ROW, cust_billing_mode: 'monthly_membership', cust_monthly_rate: 74.7 };
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      mockMint.mockImplementation(async ({ buildCreateParams }) => {
        buildCreateParams();
        throw new Error('stop-after-capture');
      });
      const { req, res, next } = makeReqRes({});
      await handler(req, res, next);

      const { recheckInTrx } = mockMint.mock.calls[0][0];
      expect(typeof recheckInTrx).toBe('function');
      findFirstApplicationInvoiceForEstimateService.mockClear();
      // Unchanged verdict ('none' again) — the recheck proceeds silently.
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      // A working query-builder stand-in (owner ruling — REFUSE AFTER A
      // VOID): the 'none' branch now also runs
      // combinedInvoiceVoidedWithoutLiveReplacement's own `invoices as i`
      // query, AWAITED DIRECTLY (thenable — mirrors knex's `.select()`), so
      // a bare `{}` trx is no longer sufficient — this resolves it to "no
      // invoice on the estimate" (empty array), preserving the exact 'none'
      // verdict the recheck expects.
      const fakeTrx = (_table) => {
        const q = {};
        ['join', 'where', 'whereNot', 'whereNull', 'whereNotIn', 'whereIn', 'orderBy', 'forUpdate', 'noWait', 'select'].forEach((m) => { q[m] = () => q; });
        q.first = async () => undefined;
        q.then = (resolve, reject) => Promise.resolve([]).then(resolve, reject);
        q.catch = (reject) => Promise.resolve([]).catch(reject);
        return q;
      };
      await expect(recheckInTrx(fakeTrx)).resolves.toBeUndefined();
      expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalledWith(
        expect.objectContaining({ id: 'svc-lawn' }), fakeTrx, { lockRows: true, noWait: true },
      );
    });

    test('refuses the mint when a concurrent refund flips "none" to a live sibling match ("covered") under the lock', async () => {
      // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13):
      // a monthly_membership lane with a rate is what makes the mint
      // reachable now for this unpriced-visit shape.
      mockDb.__svcRow = { ...SVC_ROW, cust_billing_mode: 'monthly_membership', cust_monthly_rate: 74.7 };
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      mockMint.mockImplementation(async ({ buildCreateParams }) => {
        buildCreateParams();
        throw new Error('stop-after-capture');
      });
      const { req, res, next } = makeReqRes({});
      await handler(req, res, next);
      const { recheckInTrx } = mockMint.mock.calls[0][0];

      // A sibling invoice was restored between the pre-lock read and the
      // locked recheck — the verdict is now 'covered'.
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-restored', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
        liveBeside: null,
      });
      await expect(recheckInTrx({})).rejects.toMatchObject({
        status: 409, code: 'SIBLING_COVERAGE_CHANGED',
      });
    });

    // Owner decision (round-8 P1, narrow + fail closed): a definitive
    // 'covered' verdict now refuses the mint OUTRIGHT — no zero-base-plus-
    // extras path exists any more for Charge Now to mint AROUND coverage.
    // The mint (and any recheckInTrx) is never reached at all, even with an
    // operator-added checkout extra — this replaces the old "covered
    // resolves the base to 0, extras make it chargeable, recheck catches a
    // concurrent refund" scenario, which no longer occurs because 'covered'
    // never gets that far pre-lock.
    test('a definitive "covered" verdict refuses the ENTIRE mint before the lock — no extras-only path around it', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
        liveBeside: null,
      });
      const { req, res, next } = makeReqRes({
        extraLineItems: [{ description: 'Extra treatment', quantity: 1, unit_price: 40, amount: 40 }],
      });
      await handler(req, res, next);

      expect(res.status).toHaveBeenCalledWith(409);
      expect(res.body.error).toMatch(/combined trip invoice/i);
      expect(mockMint).not.toHaveBeenCalled();
    });

    // Owner ruling — REFUSE AFTER A VOID: the priced row is never refused
    // pre-lock — isSiblingCoverageEligibleVisit still requires !hasOwnPrice
    // (or a confirmed priced covered member) to refuse here, and that gate
    // is untouched. Completing or charging an ordinary priced row proceeds
    // exactly as it always did.
    //
    // recheckInTrx ITSELF is no longer null for this shape (#5237 review r2
    // P1, siblingCoverageRecheckInTrx): its own pre-lock stamp gate used to
    // decide "maybe a covered member" from svc's OWN captured
    // first_application_invoice_id column, and a priced sibling stamped
    // AFTER this route's read (reconcileRecentUnstampedAccepts /
    // stampGroupRevalidated, in the window between this read and the mint
    // lock) made that stale snapshot return null — no in-lock recheck ran
    // at all, and a genuine covered member could still double-mint. The
    // outer gate is now price-blind; every dedicated
    // siblingCoverageRecheckInTrx test below covers its actual behavior.
    test('the sibling lookup never runs pre-lock for a priced row (unaffected by this fix) — recheckInTrx is still passed to the mint', async () => {
      mockDb.__svcRow = { ...SVC_ROW, estimated_price: 150 };
      mockMint.mockImplementation(async ({ buildCreateParams }) => {
        buildCreateParams();
        throw new Error('stop-after-capture');
      });
      const { req, res, next } = makeReqRes({});
      await handler(req, res, next);

      expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
      expect(typeof mockMint.mock.calls[0][0].recheckInTrx).toBe('function');
    });
  });

  // Codex round-9 P1: a legacy invoice can already sit on THIS visit's own
  // scheduled_service_id from before the sibling-coverage lookup existed
  // (e.g. an operator-added extras-only invoice). The pre-fix route
  // returned that invoice via the "reuse existing" branch WITHOUT ever
  // asking whether a sibling invoice actually covers the trip — completion
  // then found the sibling's own live invoice and never reconciled the
  // stale one. The sibling verdict must be checked BEFORE any existing
  // invoice is even looked up, so a 'covered'/'needs_review' verdict
  // refuses instead of handing back the stale invoice.
  describe('own-invoice reuse never bypasses the sibling verdict (codex round-9 P1)', () => {
    test('a "covered" sibling verdict refuses even though this visit already has its OWN attached invoice', async () => {
      mockDb.__existingInvoiceRow = {
        id: 'inv-legacy', status: 'sent', total: 40, token: 'tok-legacy',
        scheduled_service_id: 'svc-lawn', payer_id: null,
      };
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
        liveBeside: null,
      });
      const { req, res, next } = makeReqRes({});
      await handler(req, res, next);

      expect(res.status).toHaveBeenCalledWith(409);
      expect(res.body.error).toMatch(/combined trip invoice/i);
      // Never the stale reuse response for the legacy invoice.
      expect(res.body).not.toMatchObject({ reused: true, invoiceId: 'inv-legacy' });
      expect(mockMint).not.toHaveBeenCalled();
    });

    test('a "needs_review" sibling verdict also refuses instead of reusing this visit\'s own existing invoice', async () => {
      mockDb.__existingInvoiceRow = {
        id: 'inv-legacy', status: 'sent', total: 40, token: 'tok-legacy',
        scheduled_service_id: 'svc-lawn', payer_id: null,
      };
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
        liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      });
      const { req, res, next } = makeReqRes({});
      await handler(req, res, next);

      expect(res.status).toHaveBeenCalledWith(409);
      expect(res.body.error).toMatch(/manual review/i);
      expect(res.body).not.toMatchObject({ reused: true, invoiceId: 'inv-legacy' });
      expect(mockMint).not.toHaveBeenCalled();
    });

    // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13,
    // codex pre-push P1): this used to prove a 'none' verdict reuses a
    // legacy own-invoice normally. For SVC_ROW's own per_application shape,
    // the per_application_fee_at_completion refusal now fires unconditionally
    // — BEFORE this route's existing-invoice reuse block is ever reached —
    // the same "refuse the whole mint" posture round-8 P1 already applies
    // to a covered sibling visit. An existing invoice on this exact shape's
    // row is not trustworthy enough to hand back as-is either: it could be
    // the same kind of stale extras-only invoice this whole ruling exists
    // to stop creating.
    test('a "none" verdict now refuses even with an existing invoice already on this visit\'s own row', async () => {
      mockDb.__existingInvoiceRow = {
        id: 'inv-legacy', status: 'sent', total: 97.2, token: 'tok-legacy',
        scheduled_service_id: 'svc-lawn', payer_id: null,
      };
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const { req, res, next } = makeReqRes({});
      await handler(req, res, next);

      expect(res.status).toHaveBeenCalledWith(409);
      expect(res.body.error).toMatch(/bills its application fee at completion/i);
      expect(res.body).not.toMatchObject({ reused: true, invoiceId: 'inv-legacy' });
      expect(mockMint).not.toHaveBeenCalled();
    });

    // The lane this ruling does NOT touch: a monthly_membership visit's own
    // existing invoice is still reused normally, exactly as round-9 P1
    // always intended for a genuine 'none' verdict.
    test('a "none" verdict still reuses an existing invoice normally for a monthly_membership visit', async () => {
      mockDb.__svcRow = { ...SVC_ROW, cust_billing_mode: 'monthly_membership', cust_monthly_rate: 74.7 };
      mockDb.__existingInvoiceRow = {
        id: 'inv-legacy', status: 'sent', total: 74.7, token: 'tok-legacy',
        scheduled_service_id: 'svc-lawn', payer_id: null,
      };
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const { req, res, next } = makeReqRes({});
      await handler(req, res, next);

      expect(res.status).not.toHaveBeenCalledWith(409);
      expect(res.body).toMatchObject({ success: true, reused: true, invoiceId: 'inv-legacy' });
      expect(mockMint).not.toHaveBeenCalled();
    });
  });
});

// Owner ruling — REFUSE AFTER A VOID: the PRICED reserved row is NEVER
// refused by Charge Now, in EITHER charging order. Whether the unpriced
// sibling was charged first (correctly refused — see the tests above) or
// the priced row is charged first (before the sibling has been touched at
// all), the priced row's own mint always proceeds and bills the combined
// amount once — the office handles the rest by hand. This replaces the
// round-10 "priced-row guard" (removed; the owner ruling makes it
// redundant — the unpriced sibling's own refusal is now order-independent).
describe('POST /:id/invoice — the PRICED reserved row is never refused (owner ruling, REFUSE AFTER A VOID)', () => {
  const PRICED_SVC_ROW = { ...SVC_ROW, estimated_price: 153.6 };

  test('mints normally even with a voided combined invoice AND a live sibling invoice on file', async () => {
    mockDb.__svcRow = PRICED_SVC_ROW;
    mockDb.__invoiceRows = [RECOGNIZED_VOIDED_INVOICE];
    mockMint.mockImplementation(async ({ buildCreateParams }) => {
      buildCreateParams();
      throw new Error('stop-after-capture');
    });
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(res.status).not.toHaveBeenCalledWith(409);
    expect(mockMint).toHaveBeenCalledTimes(1);
    expect(next).toHaveBeenCalledTimes(1);
    // The priced row's own mint never even asks the sibling-coverage
    // question — isSiblingCoverageEligibleVisit requires !hasOwnPrice.
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  test('mints normally with no voided invoice on file (the ordinary case)', async () => {
    mockDb.__svcRow = PRICED_SVC_ROW;
    mockDb.__invoiceRows = [];
    mockMint.mockImplementation(async ({ buildCreateParams }) => {
      buildCreateParams();
      throw new Error('stop-after-capture');
    });
    const { req, res, next } = makeReqRes({});
    await handler(req, res, next);

    expect(res.status).not.toHaveBeenCalledWith(409);
    expect(mockMint).toHaveBeenCalledTimes(1);
  });
});

// resolveScheduledServiceCharge — priced-covered-member widening (Codex r21
// P1 on PR #5021, deferred to this follow-up). Pre-fix, a NON-ANCHOR row
// staff priced AFTER its trip's combined invoice already existed made
// isSiblingCoverageEligibleVisit's `!hasOwnPrice` gate false, so this
// resolver skipped the sibling lookup entirely and minted a SECOND charge
// beside the sibling's live invoice. Driven directly (not through the HTTP
// handler — its own "existing invoice on this row" reuse query is a
// SEPARATE concern from this resolver, and would otherwise collide with
// mockDb's crude single-row 'invoices' stand-in used below for the
// priced-covered-member anchor-identity check).
describe('resolveScheduledServiceCharge — priced-covered-member widening (Codex r21 P1, PR #5021 follow-up)', () => {
  const { resolveScheduledServiceCharge } = adminScheduleRouter._test;
  const callResolver = (svc) => resolveScheduledServiceCharge({
    estimatedPrice: svc.estimated_price, isCallback: svc.is_callback, monthlyRate: svc.cust_monthly_rate,
    billingMode: svc.cust_billing_mode, serviceType: svc.service_type, svc, dbConn: mockDb,
  });

  test('a PRICED non-anchor sibling stamped to a DIFFERENT row\'s PAID combined invoice refuses (was a silent second mint pre-fix)', async () => {
    const svc = { ...SVC_ROW, estimated_price: 65, first_application_invoice_id: 'inv-1' };
    mockDb.__existingInvoiceRow = { scheduled_service_id: 'svc-pest' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'paid', total: 153.6 },
      liveBeside: null,
    });
    await expect(callResolver(svc)).resolves.toEqual({
      refused: true, reason: 'sibling_invoice_covered',
      message: expect.stringMatching(/combined trip invoice/i),
    });
  });

  test('...and a still-OPEN (sent) combined invoice refuses the same way', async () => {
    const svc = { ...SVC_ROW, estimated_price: 65, first_application_invoice_id: 'inv-1' };
    mockDb.__existingInvoiceRow = { scheduled_service_id: 'svc-pest' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    await expect(callResolver(svc)).resolves.toEqual({
      refused: true, reason: 'sibling_invoice_covered',
      message: expect.stringMatching(/combined trip invoice/i),
    });
  });

  test('...and a VOID combined invoice with no live recognized replacement refuses with sibling_invoice_needs_review', async () => {
    const svc = { ...SVC_ROW, estimated_price: 65, first_application_invoice_id: 'inv-void' };
    mockDb.__existingInvoiceRow = { scheduled_service_id: 'svc-pest' };
    // No live/refunded match via the ordinary (void-excluding) lookup —
    // combinedInvoiceVoidedWithoutLiveReplacement's own candidate query is
    // what finds the void row.
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    mockDb.__invoiceRows = [RECOGNIZED_VOIDED_INVOICE];
    await expect(callResolver(svc)).resolves.toEqual({
      refused: true, reason: 'sibling_invoice_needs_review',
      message: expect.stringMatching(/manual review/i),
    });
  });

  test('the PRICED ANCHOR row — stamped to ITS OWN invoice — never refuses, mints the ordinary priced amount unchanged', async () => {
    const svc = { ...SVC_ROW, id: 'svc-pest', estimated_price: 153.6, first_application_invoice_id: 'inv-1' };
    mockDb.__existingInvoiceRow = { scheduled_service_id: 'svc-pest' };
    await expect(callResolver(svc)).resolves.toBe(153.6);
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  test('an UNSTAMPED priced row never refuses, mints the ordinary priced amount unchanged', async () => {
    const svc = { ...SVC_ROW, estimated_price: 65 };
    await expect(callResolver(svc)).resolves.toBe(65);
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // #5237 review r2 P2: a priced covered member whose OWN base-application
  // invoice is REFUNDED — the combined invoice is STILL LIVE, so
  // isPricedCoveredMemberVisit's "split off by hand" check
  // (liveBaseApplicationInvoiceVisitIdsOn, LIVE-only) still says covered —
  // must refuse with needs_review, the SAME verdict completion reaches by
  // checking this visit's own refund first (completionTerminalInvoiceLookup),
  // never the plain 'sibling_invoice_covered' "collect on the combined
  // invoice" copy — that invoice is fine; THIS visit's own money is what's
  // in question.
  test('a priced covered member with its OWN refunded base-application invoice (combined still live) → needs_review, matching completion', async () => {
    const svc = { ...SVC_ROW, estimated_price: 65, first_application_invoice_id: 'inv-1' };
    mockDb.__existingInvoiceRow = { scheduled_service_id: 'svc-pest' }; // anchor identity
    mockDb.__ownRefundInvoiceRow = { id: 'inv-own-refund', invoice_number: 'WPC-TEST-0077', status: 'refunded' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    await expect(callResolver(svc)).resolves.toEqual({
      refused: true, reason: 'sibling_invoice_needs_review',
      message: expect.stringMatching(/manual review/i),
    });
    // The own-refund short-circuit never even asks the sibling lookup.
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });
});

// siblingCoverageRecheckInTrx — same priced-covered-member widening, but for
// the in-transaction recheck the mint runs right before committing. A
// priced row with NO stamp at all stays null synchronously (no DB call
// spent ruling it out); a priced STAMPED row returns a closure whose OWN
// under-lock anchor-identity check decides whether to actually re-run the
// coverage verdict — an anchor's own stamp is a permanent no-op, a
// non-anchor member's re-proves coverage exactly like the unpriced path
// always has.
describe('siblingCoverageRecheckInTrx — priced-covered-member widening (Codex r21 P1, PR #5021 follow-up)', () => {
  const { siblingCoverageRecheckInTrx } = adminScheduleRouter._test;
  // `stampedInvoiceId`/`anchorId` model the row's state UNDER THE LOCK —
  // 'scheduled_services' backs isPricedCoveredMemberVisit's own
  // readFirstApplicationStamp fallback read (a NARROW `{id}` shape forces
  // this path — see the closure's own comment), 'invoices' backs its
  // anchor-identity read. Deliberately independent of whatever svc's OWN
  // pre-lock object carries, since #5237 review r2 P1 is exactly about the
  // closure never trusting that stale snapshot.
  const fakeTrx = ({ stampedInvoiceId = null, anchorId = null } = {}) => (table) => {
    if (table === 'scheduled_services') return { where: () => ({ first: async () => ({ first_application_invoice_id: stampedInvoiceId }) }) };
    if (table === 'invoices') {
      // Two DISTINCT queries share this table: isPricedCoveredMemberVisit's
      // own plain `.where({id}).first('scheduled_service_id')` anchor-
      // identity read (below), and its "split off by hand" check
      // (liveBaseApplicationInvoiceVisitIdsOn) which always starts with
      // `.whereIn` instead — never a plain `.where` first. Fixture never
      // needs a split-off member in these tests, so that chain just
      // resolves empty.
      const q = {};
      q.where = jest.fn(() => ({ first: async () => (anchorId ? { scheduled_service_id: anchorId } : null) }));
      q.whereIn = jest.fn(() => q);
      q.whereNotIn = jest.fn(() => q);
      q.whereNot = jest.fn(() => q);
      q.modify = jest.fn((fn) => { fn(q); return q; });
      q.select = jest.fn(async () => []);
      return q;
    }
    throw new Error(`unexpected table: ${table}`);
  };

  // #5237 review r2 P1: the outer sync gate used to predict "maybe a
  // covered member" off svc's OWN captured first_application_invoice_id
  // column — stale the moment a stamp lands between the route's read and
  // this mint transaction's row lock. It is now price-blind: EVERY
  // estimate-linked, non-callback, non-always-free visit gets the closure,
  // stamped or not, priced or not — only the closure's own in-lock re-read
  // may decide.
  test('ALWAYS returns a recheck closure for a priced, estimate-linked visit — even with NO stamp on svc\'s own pre-lock row', () => {
    const svc = { ...SVC_ROW, estimated_price: 65 };
    expect(typeof siblingCoverageRecheckInTrx(svc)).toBe('function');
  });

  test('...and that closure is a no-op when the row is STILL genuinely unstamped under the lock', async () => {
    const svc = { ...SVC_ROW, estimated_price: 65 };
    const recheckInTrx = siblingCoverageRecheckInTrx(svc);
    await expect(recheckInTrx(fakeTrx({ stampedInvoiceId: null }))).resolves.toBeUndefined();
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // The exact race Codex r2 P1 caught: reconcileRecentUnstampedAccepts /
  // stampGroupRevalidated commits a stamp in the window between this
  // route's pre-lock read (svc, captured with NO stamp) and the mint
  // transaction's own row lock. Without this fix, the outer gate above
  // would have returned null from svc's stale snapshot and no in-lock
  // recheck would ever run — a second invoice mints beside the now-covered
  // sibling's live combined invoice.
  test('a stamp added AFTER svc was read (between the route\'s read and the mint lock) → the in-lock recheck refuses', async () => {
    const svc = { ...SVC_ROW, estimated_price: 65 }; // svc as read BEFORE the stamp existed
    const recheckInTrx = siblingCoverageRecheckInTrx(svc);
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    await expect(recheckInTrx(fakeTrx({ stampedInvoiceId: 'inv-1', anchorId: 'svc-pest' })))
      .rejects.toMatchObject({ code: 'SIBLING_COVERAGE_CHANGED' });
  });

  test('the ANCHOR\'s own priced closure is a permanent no-op — never throws, never even runs the coverage recheck', async () => {
    const svc = { ...SVC_ROW, id: 'svc-pest', estimated_price: 153.6 };
    const recheckInTrx = siblingCoverageRecheckInTrx(svc);
    await expect(recheckInTrx(fakeTrx({ stampedInvoiceId: 'inv-1', anchorId: 'svc-pest' }))).resolves.toBeUndefined();
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });
});

// mintOrReuseScheduledServiceInvoice backs the Mark-prepaid / prepaid-receipt
// mint (generatePrepaidReceiptForService). It never throws to its caller —
// it must translate resolveScheduledServiceCharge's structured refusal into
// the SAME { invoice: null, reason } shape it already reports every other
// refusal in, so the reason surfaces through receipt.reason on the modal
// instead of a bare 0 quietly minting an extras-only invoice.
describe('mintOrReuseScheduledServiceInvoice — sibling-lookup refusal', () => {
  const { mintOrReuseScheduledServiceInvoice } = adminScheduleRouter._test;
  const SVC = { ...SVC_ROW };

  test('a lookup failure refuses to mint with a structured reason, not a $0 invoice', async () => {
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
    const result = await mintOrReuseScheduledServiceInvoice(SVC);
    expect(result).toEqual({ invoice: null, reason: 'sibling_lookup_failed' });
    expect(mockMint).not.toHaveBeenCalled();
  });

  test('a needs_review verdict refuses to mint with a structured reason', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: null,
      liveBeside: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
    const result = await mintOrReuseScheduledServiceInvoice(SVC);
    expect(result).toEqual({ invoice: null, reason: 'sibling_invoice_needs_review' });
    expect(mockMint).not.toHaveBeenCalled();
  });

  // Round-8 P1 (owner decision — narrow + fail closed): a definitive
  // 'covered' verdict is ALSO a flat refusal now — MarkPrepaidModal's
  // RECEIPT_REASON_TEXT has copy for this exact reason.
  test('a definitive "covered" verdict refuses to mint with a structured reason, never a $0 "nothing chargeable"', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    const result = await mintOrReuseScheduledServiceInvoice(SVC);
    expect(result).toEqual({ invoice: null, reason: 'sibling_invoice_covered' });
    expect(mockMint).not.toHaveBeenCalled();
  });

  // Owner ruling — REFUSE AFTER A VOID: the same voided-combined scenario,
  // through the Mark-prepaid mint path — the unpriced sibling's own
  // recognized combined invoice being voided (with no live recognized
  // replacement) must refuse here too, never mint the acceptance fee on
  // top of a trip whose combined amount the reserved row still bills once.
  test('a voided combined invoice with no live recognized replacement refuses to mint with a structured reason', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    mockDb.__invoiceRows = [RECOGNIZED_VOIDED_INVOICE];
    const result = await mintOrReuseScheduledServiceInvoice(SVC);
    expect(result).toEqual({ invoice: null, reason: 'sibling_invoice_needs_review' });
    expect(mockMint).not.toHaveBeenCalled();
  });

  // Owner ruling — REFUSE AFTER A VOID: the PRICED reserved row is never
  // refused here either, even with the SAME voided invoice on file — its
  // own mint never asks the sibling-coverage question at all
  // (isSiblingCoverageEligibleVisit requires !hasOwnPrice).
  test('a priced row mints normally even with a voided combined invoice on file', async () => {
    mockDb.__invoiceRows = [RECOGNIZED_VOIDED_INVOICE];
    mockMint.mockImplementation(async () => ({ invoice: { id: 'inv-priced' }, reused: false }));
    const result = await mintOrReuseScheduledServiceInvoice({ ...SVC, estimated_price: 153.6 });
    expect(result).toEqual({ invoice: { id: 'inv-priced' }, reused: false });
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // Owner ruling — REMOVE THE CHARGE NOW FEE FALLBACK: a 'none' verdict on
  // SVC's own per_application shape resolves to 0 now (no fee fallback) and
  // returns 'no_chargeable_amount' before ever reaching the mint — proven
  // separately below. Mint (and so recheckInTrx) is still reachable through
  // this same sibling-eligible shape for a customer whose OTHER precedence
  // resolves a positive amount — a monthly_membership customer with an
  // unpriced, estimate-linked visit still falls through to monthlyRate
  // (completionInvoiceAmount's own unaffected precedence) — so this proves
  // the wiring is intact, not that the fee still mints.
  test('a "none" verdict mints and passes a recheckInTrx that re-proves coverage under the lock', async () => {
    const svcMonthly = { ...SVC, cust_billing_mode: 'monthly_membership' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    mockMint.mockImplementation(async ({ buildCreateParams }) => {
      buildCreateParams();
      return { invoice: { id: 'inv-new' }, reused: false };
    });
    const result = await mintOrReuseScheduledServiceInvoice(svcMonthly);
    expect(result).toEqual({ invoice: { id: 'inv-new' }, reused: false });
    const { recheckInTrx } = mockMint.mock.calls[0][0];
    expect(typeof recheckInTrx).toBe('function');

    findFirstApplicationInvoiceForEstimateService.mockClear();
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-restored', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    await expect(recheckInTrx({})).rejects.toMatchObject({ code: 'SIBLING_COVERAGE_CHANGED' });
    expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalledWith(svcMonthly, {}, { lockRows: true, noWait: true });
  });

  // Owner ruling — REMOVE THE CHARGE NOW FEE FALLBACK, then REFUSE
  // EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13, codex pre-push P1): the
  // exact regression this ruling fixes, through the mark-prepaid mint path —
  // an unpriced, estimate-linked, per_application visit with a genuine
  // 'none' sibling verdict (nothing covers it) used to mint the customer's
  // established per_application_fee here. It now reports the structured
  // per_application_fee_at_completion refusal (mark-prepaid's own
  // RECEIPT_REASON_TEXT has copy for it), never mints.
  test('a "none" verdict on an unpriced per_application visit with no other price refuses — completion bills the fee, never mints', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const result = await mintOrReuseScheduledServiceInvoice(SVC);
    expect(result).toEqual({ invoice: null, reason: 'per_application_fee_at_completion' });
    expect(mockMint).not.toHaveBeenCalled();
  });

  // Codex round-9 P1 (the same fix as the Charge Now route above): a legacy
  // invoice already on svc's own scheduled_service_id must not be reused
  // when the sibling verdict is anything but 'none'.
  test('a "covered" sibling verdict refuses to mint even though svc already has its OWN existing invoice', async () => {
    mockDb.__existingInvoiceRow = { id: 'inv-legacy', status: 'sent', total: 40, scheduled_service_id: 'svc-lawn' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    const result = await mintOrReuseScheduledServiceInvoice(SVC);
    expect(result).toEqual({ invoice: null, reason: 'sibling_invoice_covered' });
    expect(mockMint).not.toHaveBeenCalled();
  });

  // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13):
  // SVC's own per_application shape now refuses even with an existing
  // invoice already on the row (same "refuse the whole mint" posture as the
  // Charge Now route's own equivalent test) — not trustworthy enough to
  // hand back as-is, since it could be the stale kind of extras-only
  // invoice this ruling exists to stop creating.
  test('a "none" verdict now refuses even with an existing invoice already on svc\'s own row', async () => {
    mockDb.__existingInvoiceRow = { id: 'inv-legacy', status: 'sent', total: 97.2, scheduled_service_id: 'svc-lawn' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const result = await mintOrReuseScheduledServiceInvoice(SVC);
    expect(result).toEqual({ invoice: null, reason: 'per_application_fee_at_completion' });
    expect(mockMint).not.toHaveBeenCalled();
  });

  // The lane this ruling does NOT touch: a monthly_membership visit's
  // existing invoice is still reused normally for a genuine 'none' verdict.
  test('a "none" verdict still reuses an existing invoice normally for a monthly_membership visit', async () => {
    const svcMonthly = { ...SVC, cust_billing_mode: 'monthly_membership' };
    mockDb.__existingInvoiceRow = { id: 'inv-legacy', status: 'sent', total: 74.7, scheduled_service_id: 'svc-lawn' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const result = await mintOrReuseScheduledServiceInvoice(svcMonthly);
    expect(result).toEqual({ invoice: mockDb.__existingInvoiceRow, reused: true });
    expect(mockMint).not.toHaveBeenCalled();
  });
});

// Codex r5 P2 on #5237: the 'covered' copy follows the combined invoice's
// collection state (collectionStateForCoveredInvoice) — "collect on that
// invoice" only when it is collectible from this customer.
describe('siblingCoverageRefusal — covered copy follows the combined invoice state', () => {
  const { siblingCoverageRefusal } = require('../routes/admin-schedule')._test;
  const base = { id: 'inv-1', invoice_number: 'WPC-1', total: 153.6, amount_paid: 0 };
  const msg = (invoice, hasOwnPrice = true) => siblingCoverageRefusal({ status: 'covered', invoice }, { hasOwnPrice }).message;

  test.each([
    ['paid', { status: 'paid' }, /already paid — do not collect again/],
    ['prepaid', { status: 'prepaid' }, /already paid — do not collect again/],
    ['processing', { status: 'processing' }, /still processing — do not collect again/],
    ['payer-billed', { status: 'sent', payer_id: 'payer-1' }, /third-party payer — do not collect from the customer/],
    ['open (sent)', { status: 'sent' }, /collect on that invoice/],
  ])('%s combined invoice', (_label, fields, expected) => {
    const message = msg({ ...base, ...fields });
    expect(message).toMatch(/combined trip invoice/);
    expect(message).toMatch(expected);
    if (fields.status !== 'sent' || fields.payer_id) expect(message).not.toMatch(/collect on that invoice/);
  });

  test('a settled invoice never suggests setting a price on an unpriced visit', () => {
    expect(msg({ ...base, status: 'paid' }, false)).not.toMatch(/set a price/);
  });

  test('the refusal reason code is unchanged', () => {
    expect(siblingCoverageRefusal({ status: 'covered', invoice: { ...base, status: 'paid' } }).reason).toBe('sibling_invoice_covered');
  });
});
