// getCounty / getCounties: the county whose nitrogen rules apply to a customer. The eleven cities the function always mapped keep
// their county; the other service-area cities come from the repo's address tables (config/address-county.js); Longboat Key, which
// lies in two counties, gets both (the stricter of the two applies). Synthetic customers; real Postgres for the blackout effect.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const applicationLimits = require('../services/application-limits');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const MANATEE = 'manatee_county';
const SARASOTA = 'sarasota_county';
const CHARLOTTE = 'charlotte_county';

// city -> counties, with the source of each county (see the PR notes): Wikipedia article for the city, and the repo table row.
const ADDED = [
  ['Punta Gorda', [CHARLOTTE]],
  ['Port Charlotte', [CHARLOTTE]],
  ['Anna Maria', [MANATEE]],
  ['Holmes Beach', [MANATEE]],
  ['Bradenton Beach', [MANATEE]],
  ['Myakka City', [MANATEE]],
  ['Siesta Key', [SARASOTA]],
  ['Longboat Key', [SARASOTA, MANATEE]],
];

describe('getCounties (no database)', () => {
  test.each([
    ['Bradenton', MANATEE], ['Lakewood Ranch', MANATEE], ['Parrish', MANATEE], ['Palmetto', MANATEE], ['Ellenton', MANATEE],
    ['Sarasota', SARASOTA], ['Venice', SARASOTA], ['Nokomis', SARASOTA], ['Osprey', SARASOTA], ['North Port', SARASOTA], ['Englewood', SARASOTA],
  ])('the always-mapped city %s keeps %s, even with a ZIP the service-area map shares', (city, county) => {
    expect(applicationLimits.getCounties({ city, zip: '34243' })).toEqual([county]);
    expect(applicationLimits.getCounty({ city })).toBe(county);
  });

  test.each(ADDED)('%s', (city, counties) => {
    expect(applicationLimits.getCounties({ city })).toEqual(counties);
    expect(applicationLimits.getCounty({ city: city.toUpperCase() })).toBe(counties[0]);
  });

  test('Longboat Key is both counties whatever the ZIP says; a shared ZIP with an unknown city is both too', () => {
    expect(applicationLimits.getCounties({ city: 'Longboat Key', zip: '34228' })).toEqual([SARASOTA, MANATEE]);
    expect(applicationLimits.getCounties({ city: 'Longboat Key', zip: '34202' })).toEqual([SARASOTA, MANATEE]);
    expect(applicationLimits.getCounties({ city: 'University Park', zip: '34243' })).toEqual([SARASOTA, MANATEE]);
  });

  test('a ZIP decides when the city is not on a list; nothing found is no county, as before', () => {
    expect(applicationLimits.getCounties({ city: '', zip: '34216' })).toEqual([MANATEE]);
    expect(applicationLimits.getCounties({ city: 'Somewhere', zip: '33950-1234' })).toEqual([CHARLOTTE]);
    expect(applicationLimits.getCounties({ city: 'Tampa', zip: '33602' })).toEqual([]);
    expect(applicationLimits.getCounty({ city: 'Tampa', zip: '33602' })).toBe('all');
    expect(applicationLimits.getCounty(null)).toBe('all');
    expect(applicationLimits.getCounty({})).toBe('all');
  });
});

describeDb('the county nitrogen blackout, through checkLimits', () => {
  let owned;
  let knex;
  let fertilizer;

  async function clone(table) {
    await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
    const columns = await knex(table).columnInfo();
    if (String(columns.id?.defaultValue || '').includes('nextval(')) {
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
    }
  }
  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['products_catalog', 'product_aliases', 'lawn_protocol_products', 'product_limits', 'property_application_history']) await clone(table);
    [fertilizer] = await knex('products_catalog').insert({ name: 'Fixture 16-4-8 Fertilizer', category: 'fertilizer', active: true }).returning('*');
    // The rows the compliance seed (20260401000020) writes: June 1 to September 30, a hard block, one per county.
    await knex('product_limits').insert([SARASOTA, MANATEE].map((jurisdiction) => ({
      match_type: 'nitrogen', limit_type: 'seasonal_blackout', limit_value: 0, limit_unit: 'applications', season_start: '2026-06-01', season_end: '2026-09-30',
      jurisdiction, severity: 'hard_block', description: `${jurisdiction} blackout`,
    })));
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  async function judge(city, date, zip = '34201') {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ city, zip });
    return applicationLimits.checkLimits(f.customerId, fertilizer.id, new Date(`${date}T16:00:00Z`), knex, {});
  }
  const blackouts = (result) => result.blocks.filter((block) => block.type === 'seasonal_blackout').map((block) => block.message);

  test('a mapped city of each county is blocked in July and not in October (the baseline)', async () => {
    expect(blackouts(await judge('Bradenton', '2026-07-15'))).toEqual([expect.stringContaining('manatee county restricts nitrogen 06/01 — 09/30')]);
    expect(blackouts(await judge('Venice', '2026-07-15'))).toEqual([expect.stringContaining('sarasota county restricts nitrogen 06/01 — 09/30')]);
    expect(blackouts(await judge('Bradenton', '2026-10-15'))).toEqual([]);
  });

  test.each([
    ['Anna Maria', 'manatee', '34216'], ['Holmes Beach', 'manatee', '34217'], ['Bradenton Beach', 'manatee', '34217'],
    ['Myakka City', 'manatee', '34251'], ['Siesta Key', 'sarasota', '34242'],
  ])('%s is blocked from June 1 to September 30 like the mapped city of its county, and not in October', async (city, county, zip) => {
    expect(blackouts(await judge(city, '2026-07-15', zip))).toEqual([expect.stringContaining(`${county} county restricts nitrogen`)]);
    expect(blackouts(await judge(city, '2026-06-01', zip))).toHaveLength(1);
    expect(blackouts(await judge(city, '2026-09-30', zip))).toHaveLength(1);
    expect(blackouts(await judge(city, '2026-10-01', zip))).toEqual([]);
    expect(blackouts(await judge(city, '2026-05-31', zip))).toEqual([]);
  });

  test('a product with no nitrogen is not held by the blackout in an added city', async () => {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ city: 'Anna Maria', zip: '34216' });
    const [herbicide] = await knex('products_catalog').insert({ name: 'Fixture herbicide', category: 'herbicide', active: true }).returning('*');
    expect(blackouts(await applicationLimits.checkLimits(f.customerId, herbicide.id, new Date('2026-07-15T16:00:00Z'), knex, {}))).toEqual([]);
  });

  test('Longboat Key gets both counties blackouts', async () => {
    const found = blackouts(await judge('Longboat Key', '2026-07-15', '34228'));
    expect(found).toHaveLength(2);
    expect(found.join(' ')).toMatch(/manatee county/);
    expect(found.join(' ')).toMatch(/sarasota county/);
    expect(blackouts(await judge('Longboat Key', '2026-10-15', '34228'))).toEqual([]);
  });

  test('Punta Gorda and Port Charlotte resolve to Charlotte County, which has no blackout row in product_limits: nothing is blocked, as before', async () => {
    expect(blackouts(await judge('Punta Gorda', '2026-07-15', '33950'))).toEqual([]);
    expect(blackouts(await judge('Port Charlotte', '2026-07-15', '33948'))).toEqual([]);
  });

  test('a city on no list (Tampa) is still judged by no county', async () => {
    expect(blackouts(await judge('Tampa', '2026-07-15', '33602'))).toEqual([]);
  });
});
