/**
 * Sibling-coverage schedule verdict — a per-application accept that combines
 * two recurring programs into ONE same-day slot invoices the RESERVED
 * program's row for the combined total and leaves the PROMOTED program's row
 * deliberately unpriced (estimate-converter.js reservedAcceptPerVisitSplit).
 * closeout-status.js reads this shape as `sibling_first_application`.
 *
 * Prod 2026-09-26: a per-application Silver customer accepted lawn
 * ($56.40/app) + quarterly pest ($97.20/app) into ONE reserved slot. The
 * pest row's invoice ($153.60) covered the trip; the lawn row was left
 * unpriced on purpose. The schedule sheet showed the lawn visit's price as
 * $74.70 (the annual/12 equivalent of monthlyRate — meaningless here) and
 * warned "nothing will bill", both wrong. These pin siblingCoverageForSchedule
 * reusing the SAME sibling-invoice lookup completion uses, so the sheet can
 * never contradict it.
 *
 * Owner decision (narrow + fail closed, after 8 Codex rounds): the server
 * computes ONE canonical verdict — { state, invoiceId, invoiceNumber,
 * amountDue, reason } — built ONLY from siblingInvoiceCoverageVerdict plus
 * invoice-helpers' own collectibility checks (invoiceWithdrawnFromCustomer,
 * payer ownership, credit-applied netting, terminal statuses). Every client
 * surface renders this verdict and nothing else.
 */

jest.mock('../services/estimate-first-application-invoice', () => ({
  // Codex pre-push P0 (round 10): billing-lane.js's
  // pricedRowFirstApplicationInvoiceVoided reuses the REAL, pure
  // isAutoGeneratedPayPerApplicationInvoice (no DB, no side effects) to
  // recognize a voided combined invoice's notes — only the DB-backed
  // lookup itself is mocked below.
  ...jest.requireActual('../services/estimate-first-application-invoice'),
  findFirstApplicationInvoiceForEstimateService: jest.fn(),
}));

const { findFirstApplicationInvoiceForEstimateService } = require('../services/estimate-first-application-invoice');
const {
  siblingCoverageForSchedule, siblingInvoiceCoverageVerdict, coveringSiblingInvoice, pricedSiblingCoverageVerdict,
} = require('../services/billing-lane');

// Minimal knex-like stand-in: distinguishes the two 'scheduled_services'
// queries the function issues by their `where` shape — a lookup by id
// (the invoice's owning visit) vs. the same-day/estimate members scan.
// `unrecognizedSiblingInvoice` (codex pre-push P0, round 9) backs
// sameTripSiblingHasUnrecognizedLiveInvoice's own `invoices`-table query
// (the fail-closed guard for a same-trip sibling's invoice the notes-based
// lookup can't recognize) — every call site that doesn't pass it defaults
// to "no such invoice", keeping every EXISTING test's verdict unchanged.
// `voidedFirstApplicationInvoiceOnRow` (codex pre-push P0, round 10) backs
// pricedRowFirstApplicationInvoiceVoided's own `.whereIn(status, [...])`
// query (the PRICED-row counterpart) — a THIRD independently controllable
// shape on this same 'invoices' table, distinguished from the joined shape
// by whether `.join` was ever called on this query instance. `invoiceQueryCalls`
// (optional, out param) collects each `.where*` call made against the
// `invoices` query so a test can assert the query is correctly SCOPED
// (same estimate + same trip, excluding svc's own row) without a real
// database.
function fakeDbConn({
  byId = {}, members = [], unrecognizedSiblingInvoice = false, voidedFirstApplicationInvoiceOnRow = null, invoiceQueryCalls = null,
} = {}) {
  return (table) => {
    if (table === 'scheduled_services') {
      return {
        where(cond) {
          if (cond && cond.id !== undefined) {
            return { first: async () => byId[cond.id] || null };
          }
          return {
            whereNull: () => ({
              select: async () => members,
            }),
          };
        },
      };
    }
    if (table === 'invoices') {
      const q = { _joined: false };
      const record = (method) => (...args) => {
        if (method === 'join') q._joined = true;
        invoiceQueryCalls?.push([method, ...args]);
        return q;
      };
      q.join = record('join');
      q.where = record('where');
      q.whereNot = record('whereNot');
      q.whereNull = record('whereNull');
      q.whereNotIn = record('whereNotIn');
      q.whereIn = record('whereIn');
      q.orderBy = record('orderBy');
      q.forUpdate = record('forUpdate');
      q.noWait = record('noWait');
      q.first = async () => {
        if (q._joined) return unrecognizedSiblingInvoice ? { id: 'unrecognized-inv' } : undefined;
        return voidedFirstApplicationInvoiceOnRow;
      };
      return q;
    }
    throw new Error(`unexpected table: ${table}`);
  };
}

const PEST_ROW = {
  id: 'svc-pest',
  service_type: 'Quarterly Pest Control',
  estimated_price: 153.6,
  recurring_template_overrides: { anchored_split_per_visit: 97.2 },
};
const LAWN_ROW = {
  id: 'svc-lawn',
  service_type: 'Every 6 Weeks Lawn Care',
  estimated_price: null,
  recurring_template_overrides: { anchored_split_per_visit: 56.4 },
};

const LAWN_SVC = {
  id: 'svc-lawn',
  customer_id: 'cust-1',
  source_estimate_id: 'est-1',
  scheduled_date: '2026-09-27',
};

afterEach(() => {
  jest.clearAllMocks();
});

describe('siblingCoverageForSchedule', () => {
  test('reads the reserved sibling invoice as covering the unpriced promoted visit, with a reconciled breakdown', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1',
        scheduled_service_id: 'svc-pest',
        invoice_number: 'WPC-TEST-0001',
        status: 'sent',
        total: 153.6,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW],
    });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });

    expect(coverage).toEqual({
      state: 'collect_on_combined_invoice',
      invoiceId: 'inv-1',
      invoiceNumber: 'WPC-TEST-0001',
      amountDue: 153.6,
      reason: null,
    });
    expect(prediction).toMatchObject({
      kind: 'covered_sibling_invoice',
      amount: null,
      invoiceId: 'inv-1',
      invoiceNumber: 'WPC-TEST-0001',
      siblingServiceType: 'Quarterly Pest Control',
    });
    expect(prediction.breakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ serviceType: 'Quarterly Pest Control', amount: 97.2 }),
        expect.objectContaining({ serviceType: 'Every 6 Weeks Lawn Care', amount: 56.4 }),
      ]),
    );
    expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalledWith(LAWN_SVC, dbConn);
  });

  // Codex round-9 P2: the invoice ALSO carries a one-time setup fee line
  // and sales tax — `total` (262.35 = $99 setup + $153.60 applications +
  // $9.75 tax) folds in both, so comparing the anchored per-visit splits
  // (which never included either) against the raw total rejected a
  // genuinely correct breakdown outright. Reconciling against the
  // invoice's own line items — excluding the setup fee line, and tax was
  // never a line item to begin with — must still find the match.
  test('reconciles the breakdown against the application-line subtotal, excluding setup fee and tax', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1',
        scheduled_service_id: 'svc-pest',
        invoice_number: 'WPC-TEST-0002',
        status: 'sent',
        total: 262.35,
        line_items: [
          { description: 'WaveGuard Membership — one-time setup fee', amount: 99 },
          { description: 'Quarterly Pest Control', amount: 97.2 },
          { description: 'Every 6 Weeks Lawn Care', amount: 56.4 },
        ],
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW],
    });

    const { prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });

    expect(prediction.kind).toBe('covered_sibling_invoice');
    expect(prediction.breakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ serviceType: 'Quarterly Pest Control', amount: 97.2 }),
        expect.objectContaining({ serviceType: 'Every 6 Weeks Lawn Care', amount: 56.4 }),
      ]),
    );
  });

  // A stringified line_items JSON column (as Postgres can return it) must
  // parse the same way — never silently fall back to the (mismatching)
  // raw total for a real row shape.
  test('reconciles against a STRINGIFIED line_items column the same way', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1',
        scheduled_service_id: 'svc-pest',
        invoice_number: 'WPC-TEST-0003',
        status: 'sent',
        total: 262.35,
        line_items: JSON.stringify([
          { description: 'WaveGuard Membership — one-time setup fee', amount: 99 },
          { description: 'Quarterly Pest Control', amount: 97.2 },
          { description: 'Every 6 Weeks Lawn Care', amount: 56.4 },
        ]),
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW],
    });

    const { prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(prediction.breakdown).toBeDefined();
  });

  // Codex round-7 P1 (mechanism retained, verdict now server-side): the raw
  // invoice status alone told a consumer THAT a sibling invoice exists,
  // never whether it still needs collecting. `amountDue` (total minus
  // credit_applied — invoiceAmountDue, invoice-helpers.js) lets the state
  // machine tell staff exactly what's still owed on THAT invoice.
  test('amountDue nets any account credit already applied to the sibling invoice', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'overdue', total: 153.6, credit_applied: 50,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
    });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toMatchObject({ state: 'collect_on_combined_invoice', amountDue: 103.6 });
  });

  // Round-8 P1: a credit-applied invoice fully covered (amountDue <= 0) is
  // settled — nothing left to collect — even though the raw status is still
  // an ordinarily-collectible one like 'sent'.
  test('a fully credit-covered sibling invoice (amountDue <= 0) reads settled, not collect', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'sent', total: 153.6, credit_applied: 200,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'credit_applied' });
  });

  // Round-8 P1: a payer-owned or withdrawn-from-customer sibling invoice is
  // not collectible from THIS customer at all — the payment paths reject
  // those explicitly (invoiceWithdrawnFromCustomer, payer ownership,
  // invoice-helpers.js) — so it reads settled, never "collect on that
  // invoice," even while the invoice itself is still draft/sent.
  test('a payer-owned sibling invoice reads settled, never collectible from the homeowner', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'sent', total: 153.6, payer_id: 'payer-1',
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'payer_billed' });
  });

  test('a sibling invoice withdrawn from the customer (payer_billed: stamp) reads settled', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'sent', total: 153.6, scheduled_send_error: 'payer_billed:payer-1',
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'withdrawn_from_customer' });
  });

  // A paid/prepaid/processing sibling invoice is settled — money already
  // collected or in flight — regardless of amountDue's raw value. A
  // technician collects nothing from any of the three either way, but
  // 'processing' keeps its OWN reason (codex round-9 P2) — see the test
  // right below.
  test('a paid sibling invoice reads settled', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'paid', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'invoice_settled' });
  });

  // Codex round-9 P2: a covering sibling invoice that is only 'processing'
  // (money in flight, e.g. a pending ACH debit) still reads `state:
  // 'settled'` — a technician collects nothing from it either way — but
  // its `reason` must stay 'invoice_processing', distinct from a genuinely
  // paid/prepaid 'invoice_settled'. Lumping the two together let the
  // schedule sheet's CompletionPanel preview an immediate review request
  // for a visit whose completion path (complete-scheduled-service.js
  // invoiceBlocksReview) actually holds the ask until the sibling invoice
  // is literally 'paid'/'prepaid'.
  test('a processing sibling invoice reads settled with its own distinct reason', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'processing', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'invoice_processing' });
  });

  test('omits the breakdown when the anchored splits do not reconcile to the invoice total', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'sent', total: 200,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW], // sums to 153.60, not 200
    });

    const { prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(prediction.kind).toBe('covered_sibling_invoice');
    expect(prediction.breakdown).toBeUndefined();
  });

  // Mirrors the completion predicate exactly: findFirstApplicationInvoiceForEstimateService
  // itself scopes the match to the SAME scheduled_date as the visit passed in,
  // so an unpriced visit whose only source-estimate invoice belongs to a
  // DIFFERENT day's sibling correctly reads as "no match" — never covered.
  test('is not covered when the shared predicate finds no match (different-date sibling)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
  });

  // Codex pre-push P0 (round 9): after the combined acceptance invoice on
  // the RESERVED sibling (svc-pest) is voided, Charge Now can recreate a
  // plain replacement invoice on it — one with no acceptance-flow notes,
  // so findFirstApplicationInvoiceForEstimateService's own notes-based
  // match reports 'none' for it. Without the fail-closed guard, the
  // unpriced PROMOTED sibling (LAWN_SVC) would read 'none' too and mint
  // its own per-application fee ON TOP of the reserved row's invoice,
  // which already billed the combined total — a real double charge. The
  // guard (sameTripSiblingHasUnrecognizedLiveInvoice) must catch this and
  // surface 'review' instead, so Charge Now refuses with its 409 and the
  // schedule sheet shows the review state — never a silent mint.
  test('surfaces review — never a false "none" — when a same-trip sibling carries a live invoice the lookup cannot recognize', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const dbConn = fakeDbConn({ unrecognizedSiblingInvoice: true });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({
      state: 'review', invoiceId: null, invoiceNumber: null, amountDue: null, reason: 'sibling_unrecognized_invoice',
    });
    expect(prediction).toMatchObject({ kind: 'sibling_needs_review', amount: null, invoiceId: null, invoiceNumber: null });
  });

  // Scope proof: the guard's OWN query must only ever ask about the SAME
  // estimate + SAME trip (customer + source_estimate_id + scheduled_date),
  // excluding svc's own row and any recurring child — never a sibling's
  // unrelated invoice from a different estimate or a different day. This
  // inspects the query calls directly (no real database) so the scoping
  // can't silently drift into a broader, false-positive-prone match.
  test('the unrecognized-sibling guard query is scoped to the same estimate + same trip only', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const invoiceQueryCalls = [];
    const dbConn = fakeDbConn({ unrecognizedSiblingInvoice: false, invoiceQueryCalls });

    await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });

    const whereCalls = invoiceQueryCalls.filter(([method]) => method === 'where' || method === 'whereNot');
    expect(whereCalls).toEqual(expect.arrayContaining([
      ['where', 'scheduled_services.customer_id', LAWN_SVC.customer_id],
      ['where', 'scheduled_services.source_estimate_id', LAWN_SVC.source_estimate_id],
      ['where', 'scheduled_services.scheduled_date', LAWN_SVC.scheduled_date],
      ['whereNot', 'scheduled_services.id', LAWN_SVC.id],
    ]));
    expect(invoiceQueryCalls.some(([method, ...args]) => method === 'whereNull' && args[0] === 'scheduled_services.recurring_parent_id')).toBe(true);
    expect(invoiceQueryCalls.some(([method, ...args]) => method === 'whereNotIn' && args[0] === 'invoices.status')).toBe(true);
  });

  // Codex round 5 P2 (mechanism retained): a refunded/terminal match is NOT
  // collapsed to 'none' — resolveScheduledServiceCharge (the mint-side
  // resolver sharing this same lookup) always refuses this exact shape with
  // a 409, so leaving the naive positive prediction in place offered a
  // Charge button that could never succeed. A 'review' verdict tells staff
  // to go resolve it instead.
  test('surfaces a review verdict for a refunded sibling invoice — never a false "covered" or a stale positive amount', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'refunded', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'review', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: null, reason: 'terminal_invoice' });
    expect(prediction).toEqual({
      kind: 'sibling_needs_review',
      amount: null,
      conflictStampedPrice: false,
      invoiceId: 'inv-1',
      invoiceNumber: 'WPC-TEST-0001',
    });
  });

  // Round-8 P2: this visit's OWN attached first-application invoice sitting
  // in a terminal state (refunded) also reads 'review' — the raw lookup
  // (siblingInvoiceCoverageVerdict) surfaces a terminal match regardless of
  // WHOSE row it sits on, before its own-visit exclusion, so no special case
  // is needed here for "own invoice, not a sibling's."
  test('surfaces a review verdict for THIS visit\'s own refunded attached invoice (not a sibling\'s)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, invoice_number: 'WPC-TEST-0001', status: 'refunded', total: 56.4 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage.state).toBe('review');
    expect(prediction.kind).toBe('sibling_needs_review');
  });

  // Codex round 5 P2: the canceled-acceptance-invoice-with-setup-fee shape
  // (siblingInvoiceCoverageVerdict's `canceledSetupFee`) is also review with
  // NO invoice at all — must still surface the review verdict, not 'none',
  // and not throw on the missing invoice.
  test('surfaces a review verdict for a canceled acceptance invoice with no live replacement (no invoice on the verdict)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: null,
      liveBeside: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'review', invoiceId: null, invoiceNumber: null, amountDue: null, reason: 'canceled_setup_fee' });
    expect(prediction).toEqual({
      kind: 'sibling_needs_review',
      amount: null,
      conflictStampedPrice: false,
      invoiceId: null,
      invoiceNumber: null,
    });
  });

  test('never covers a visit against its OWN live (non-terminal) invoice (not a sibling)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, invoice_number: 'WPC-TEST-0001', status: 'sent', total: 56.4 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
  });

  test('fails toward "none" (never a false "covered") when there is no source estimate', async () => {
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: { ...LAWN_SVC, source_estimate_id: null }, dbConn: fakeDbConn() });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // Codex round 5 P2 (mechanism retained): a lookup FAILURE is treated
  // exactly like needs_review/'review', not collapsed to 'none' —
  // resolveScheduledServiceCharge refuses to mint for it too, so the naive
  // positive prediction must not survive untouched here either.
  test('surfaces a review verdict (never "none") when the shared lookup throws', async () => {
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn: fakeDbConn() });
    expect(coverage).toEqual({ state: 'review', invoiceId: null, invoiceNumber: null, amountDue: null, reason: 'lookup_failed' });
    expect(prediction).toEqual({
      kind: 'sibling_needs_review',
      amount: null,
      conflictStampedPrice: false,
      invoiceId: null,
      invoiceNumber: null,
    });
  });
});

// Codex pre-push P0 (x2): a MINT decision (resolveScheduledServiceCharge,
// admin-schedule.js) must tell "definitely no relevant sibling invoice"
// apart from "a lookup failure" and "a terminal/refunded match" — both of
// which completion's own mint refuses to remint over. siblingCoverageForSchedule's
// display-safe wrapper (coveringSiblingInvoice) collapses all three
// non-covered cases to null on purpose (advisory, never toward a false
// "covered"); the verdict function underneath must NOT collapse them the
// same way, so a write caller can refuse instead of bill.
describe('siblingInvoiceCoverageVerdict', () => {
  test('covered — a live sibling invoice', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'covered',
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
  });

  // A working dbConn is required from here on (codex pre-push P0, round
  // 9): a null-invoice verdict now also runs the fail-closed
  // sameTripSiblingHasUnrecognizedLiveInvoice guard, so `{}` is no longer
  // a valid stand-in for the `!inv` branch specifically — fakeDbConn()'s
  // default (no unrecognized invoice) preserves this exact 'none' verdict.
  test('none — no match at all', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, fakeDbConn())).toEqual({ status: 'none' });
  });

  test('none — a match naming this visit\'s OWN row (not a sibling)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, status: 'sent', total: 56.4 },
      liveBeside: null,
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({ status: 'none' });
  });

  test('needs_review — a terminal/refunded match, carrying any live replacement as liveBeside', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'needs_review',
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
  });

  // Codex round-2 P0: the shared lookup deliberately returns a refunded
  // match ahead of any live replacement REGARDLESS of whose row it sits
  // on (no reliable refund-event clock), with the live replacement riding
  // along as `liveBeside`. The own-visit check ("just my own row, not a
  // sibling") must NOT be evaluated before the terminal-status check — an
  // own-visit REFUNDED match discarded as "none" would also discard a
  // live SIBLING invoice riding beside it, letting a write caller mint
  // the acceptance fee for a trip that sibling's live invoice already
  // covers.
  test('needs_review — a REFUNDED match naming this visit\'s OWN row, with a live SIBLING invoice riding as liveBeside', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, status: 'refunded', total: 56.4 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'needs_review',
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, status: 'refunded', total: 56.4 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
  });

  test('error — the shared lookup throws', async () => {
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({ status: 'error' });
  });

  // Codex round-6 P1 (pre-push): `noWait` rides through to the shared
  // lookup ONLY when the caller passes it (the schedule mint's own recheck,
  // which already holds the estimate.deposit.ledger lock and must fail
  // fast rather than block into a deadlock against
  // withInvoiceDepositSettlement's invoice-row-then-ledger-lock order). A
  // NOWAIT lock-busy failure is just another lookup failure here.
  test('passes lockRows/noWait through to the shared lookup exactly as given', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const trx = {};
    await siblingInvoiceCoverageVerdict(LAWN_SVC, trx, { lockRows: true, noWait: true });
    expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalledWith(
      LAWN_SVC, trx, { lockRows: true, noWait: true },
    );
  });

  test('a NOWAIT lock-busy failure reads as a plain lookup error, not a crash', async () => {
    const busy = new Error('could not obtain lock on row');
    busy.code = '55P03';
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(busy);
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {}, { lockRows: true, noWait: true }))
      .toEqual({ status: 'error' });
  });

  // Codex pre-push P0 (round 2): the lookup's null-invoice return is NOT
  // always "no relevant match" — it also carries canceledSetupFee when a
  // canceled acceptance invoice included the one-time setup fee with no
  // live replacement. Losing that here would let a write caller mint only
  // the per-visit/per-application charge and silently drop the fee
  // completion itself parks for manual billing instead.
  test('needs_review — a canceled acceptance invoice carrying the setup fee, with no live replacement', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: null,
      liveBeside: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'needs_review',
      invoice: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
  });

  test('none — a null invoice with no canceledSetupFee either', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, fakeDbConn())).toEqual({ status: 'none' });
  });

  test('coveringSiblingInvoice (the display-safe wrapper) still collapses needs_review/error to null', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: null,
    });
    expect(await coveringSiblingInvoice(LAWN_SVC, {})).toBeNull();
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
    expect(await coveringSiblingInvoice(LAWN_SVC, {})).toBeNull();
  });

  // Codex pre-push P0 (round 9) — the fail-closed guard itself: a null
  // invoice from the shared lookup is 'needs_review' (never 'none') when a
  // same-trip sibling carries a live invoice the lookup can't recognize
  // (e.g. a Charge Now remint on the reserved sibling after its original
  // combined invoice was voided). Scoped to unpriced/estimate-linked svc
  // shapes only — the reserved (priced) row itself never reaches this
  // function at all (isSiblingCoverageEligibleVisit gates every caller).
  describe('the fail-closed unrecognized-live-sibling-invoice guard', () => {
    test('needs_review with reason sibling_unrecognized_invoice when a same-trip sibling has a live unrecognized invoice', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const dbConn = fakeDbConn({ unrecognizedSiblingInvoice: true });
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn)).toEqual({
        status: 'needs_review', invoice: null, reason: 'sibling_unrecognized_invoice',
      });
    });

    // canceledSetupFee still wins (checked first) — this fix never
    // reclassifies that existing, already fail-closed verdict shape.
    test('canceledSetupFee still takes precedence over the new guard', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: null, liveBeside: null,
        canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
      });
      const dbConn = fakeDbConn({ unrecognizedSiblingInvoice: true });
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn)).toEqual({
        status: 'needs_review', invoice: null, canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
      });
    });

    // A recognized 'covered' verdict is untouched — the guard only ever
    // runs inside the `!inv` branch, never re-litigating an already-live
    // recognized match.
    test('never overrides an already-recognized "covered" verdict', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
        liveBeside: null,
      });
      const dbConn = fakeDbConn({ unrecognizedSiblingInvoice: true });
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn)).toEqual({
        status: 'covered', invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      });
    });

    // A query failure inside the guard fails CLOSED — the same way any
    // other lookup failure does — never silently as "no live invoice".
    test('a guard-query failure reads as a plain lookup error, not a silent "none"', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const brokenDbConn = () => { throw new Error('connection lost'); };
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, brokenDbConn)).toEqual({ status: 'error' });
    });

    // Owner ruling: "use the in-transaction recheck (lockRows) path too" —
    // the guard's own query takes the SAME forUpdate/noWait it's given,
    // so a concurrent void+remint between the pre-lock check and the
    // locked recheck is caught the same way.
    test('lockRows/noWait ride through to the guard\'s own query', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const invoiceQueryCalls = [];
      const dbConn = fakeDbConn({ unrecognizedSiblingInvoice: true, invoiceQueryCalls });
      const verdict = await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn, { lockRows: true, noWait: true });
      expect(verdict).toEqual({ status: 'needs_review', invoice: null, reason: 'sibling_unrecognized_invoice' });
      expect(invoiceQueryCalls.some(([method]) => method === 'forUpdate')).toBe(true);
      expect(invoiceQueryCalls.some(([method]) => method === 'noWait')).toBe(true);
    });

    // Without lockRows, the guard's query must NOT take a row lock — a
    // plain read-only schedule-sheet prediction never holds rows.
    test('no forUpdate/noWait on the guard\'s query when lockRows is not requested', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const invoiceQueryCalls = [];
      const dbConn = fakeDbConn({ unrecognizedSiblingInvoice: true, invoiceQueryCalls });
      await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn);
      expect(invoiceQueryCalls.some(([method]) => method === 'forUpdate')).toBe(false);
    });
  });
});

// Codex pre-push P0 (round 10, owner ruling — symmetric, minimal, narrow +
// fail closed): the OPPOSITE direction from siblingInvoiceCoverageVerdict's
// own fail-closed guard. A PRICED "reserved" row (svc-pest here, mirroring
// the sibling-coverage fixtures above) is otherwise entirely exempt from
// any sibling-coverage question — right for the ordinary case, but blind
// to the one narrow sequence where its own recognized first-application
// invoice was voided while its unpriced sibling (svc-lawn) was separately
// charged in the meantime.
describe('pricedSiblingCoverageVerdict', () => {
  const PEST_SVC = {
    id: 'svc-pest', customer_id: 'cust-1', source_estimate_id: 'est-1', scheduled_date: '2026-09-27', estimated_price: 153.6,
  };
  const RECOGNIZED_VOIDED_INVOICE = {
    id: 'inv-void', status: 'void', title: 'First application',
    notes: 'Auto-generated from accepted estimate #est-1 — customer selected pay per application — first application.',
  };

  test('needs_review with reason sibling_already_invoiced_after_void when BOTH hold', async () => {
    const dbConn = fakeDbConn({ voidedFirstApplicationInvoiceOnRow: RECOGNIZED_VOIDED_INVOICE, unrecognizedSiblingInvoice: true });
    expect(await pricedSiblingCoverageVerdict(PEST_SVC, dbConn)).toEqual({
      status: 'needs_review', reason: 'sibling_already_invoiced_after_void',
    });
  });

  test('none — no voided first-application invoice on this row at all (ordinary priced visit)', async () => {
    const dbConn = fakeDbConn({ voidedFirstApplicationInvoiceOnRow: null, unrecognizedSiblingInvoice: true });
    expect(await pricedSiblingCoverageVerdict(PEST_SVC, dbConn)).toEqual({ status: 'none' });
  });

  test('none — the invoice was voided but the sibling has no live invoice either', async () => {
    const dbConn = fakeDbConn({ voidedFirstApplicationInvoiceOnRow: RECOGNIZED_VOIDED_INVOICE, unrecognizedSiblingInvoice: false });
    expect(await pricedSiblingCoverageVerdict(PEST_SVC, dbConn)).toEqual({ status: 'none' });
  });

  // A terminal invoice on this row that does NOT carry the recognized
  // acceptance-flow notes (an ordinary voided/refunded office invoice) must
  // never trip the guard — no false positive from voiding an unrelated
  // invoice.
  test('none — a voided invoice exists on this row but is not a recognized first-application invoice', async () => {
    const dbConn = fakeDbConn({
      voidedFirstApplicationInvoiceOnRow: { id: 'inv-other', status: 'void', title: 'Ad hoc charge', notes: 'Unrelated' },
      unrecognizedSiblingInvoice: true,
    });
    expect(await pricedSiblingCoverageVerdict(PEST_SVC, dbConn)).toEqual({ status: 'none' });
  });

  test('error — the voided-invoice query fails', async () => {
    const brokenDbConn = () => { throw new Error('connection lost'); };
    expect(await pricedSiblingCoverageVerdict(PEST_SVC, brokenDbConn)).toEqual({ status: 'error' });
  });

  test('error — the sibling-live query fails after a recognized voided invoice is found', async () => {
    const dbConn = (table) => {
      if (table !== 'invoices') throw new Error(`unexpected table: ${table}`);
      const q = { _joined: false };
      q.where = () => q; q.whereNot = () => q; q.whereNull = () => q; q.whereNotIn = () => q;
      q.whereIn = () => q; q.orderBy = () => q; q.forUpdate = () => q; q.noWait = () => q;
      q.join = () => { q._joined = true; return q; };
      q.first = async () => {
        if (q._joined) throw new Error('sibling query connection lost');
        return RECOGNIZED_VOIDED_INVOICE;
      };
      return q;
    };
    expect(await pricedSiblingCoverageVerdict(PEST_SVC, dbConn)).toEqual({ status: 'error' });
  });

  // Owner ruling: "use the in-transaction recheck (lockRows) path too" —
  // rides through to BOTH sub-queries (the voided-invoice check and the
  // sibling-live check).
  test('lockRows/noWait ride through to both underlying queries', async () => {
    const invoiceQueryCalls = [];
    const dbConn = fakeDbConn({
      voidedFirstApplicationInvoiceOnRow: RECOGNIZED_VOIDED_INVOICE, unrecognizedSiblingInvoice: true, invoiceQueryCalls,
    });
    const verdict = await pricedSiblingCoverageVerdict(PEST_SVC, dbConn, { lockRows: true, noWait: true });
    expect(verdict).toEqual({ status: 'needs_review', reason: 'sibling_already_invoiced_after_void' });
    const forUpdateCalls = invoiceQueryCalls.filter(([method]) => method === 'forUpdate');
    const noWaitCalls = invoiceQueryCalls.filter(([method]) => method === 'noWait');
    expect(forUpdateCalls.length).toBeGreaterThanOrEqual(2);
    expect(noWaitCalls.length).toBeGreaterThanOrEqual(2);
  });
});

describe('siblingCoverageForSchedule — the PRICED-row branch (codex pre-push P0, round 10)', () => {
  const PEST_SVC = {
    id: 'svc-pest', customer_id: 'cust-1', source_estimate_id: 'est-1', scheduled_date: '2026-09-27', estimated_price: 153.6,
  };
  const RECOGNIZED_VOIDED_INVOICE = {
    id: 'inv-void', status: 'void', title: 'First application',
    notes: 'Auto-generated from accepted estimate #est-1 — customer selected pay per application — first application.',
  };

  test('surfaces a review verdict with reason sibling_already_invoiced_after_void for a priced row whose invoice was voided after its sibling was charged', async () => {
    const dbConn = fakeDbConn({ voidedFirstApplicationInvoiceOnRow: RECOGNIZED_VOIDED_INVOICE, unrecognizedSiblingInvoice: true });
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PEST_SVC, dbConn });
    expect(coverage).toEqual({
      state: 'review', invoiceId: null, invoiceNumber: null, amountDue: null, reason: 'sibling_already_invoiced_after_void',
    });
    expect(prediction).toMatchObject({ kind: 'sibling_needs_review', amount: null, invoiceId: null, invoiceNumber: null });
  });

  // A normal priced visit (no voided combined invoice at all) reads exactly
  // as before this fix — 'none', never pushed into review.
  test('a normal priced visit with no voided combined invoice reads none, unchanged', async () => {
    const dbConn = fakeDbConn({ voidedFirstApplicationInvoiceOnRow: null, unrecognizedSiblingInvoice: true });
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PEST_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
  });

  // A priced visit whose invoice was voided but whose sibling was NEVER
  // separately charged also reads 'none' — nothing to double-bill.
  test('a priced visit whose sibling has no live invoice reads none, unchanged', async () => {
    const dbConn = fakeDbConn({ voidedFirstApplicationInvoiceOnRow: RECOGNIZED_VOIDED_INVOICE, unrecognizedSiblingInvoice: false });
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PEST_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
  });

  test('a query failure surfaces review with reason lookup_failed, never a false none', async () => {
    const brokenDbConn = () => { throw new Error('connection lost'); };
    const { coverage } = await siblingCoverageForSchedule({ svc: PEST_SVC, dbConn: brokenDbConn });
    expect(coverage.state).toBe('review');
    expect(coverage.reason).toBe('lookup_failed');
  });

  // An UNPRICED visit's own verdict path is completely untouched by this
  // branch — isPricedSiblingCoverageEligibleVisit requires hasOwnPrice, so
  // a voided-first-application fixture (only pricedSiblingCoverageVerdict's
  // OWN `.whereIn` query ever reads it) never even gets asked.
  test('an unpriced visit never enters the priced branch at all — the voided-invoice fixture is irrelevant to it', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const dbConn = fakeDbConn({ voidedFirstApplicationInvoiceOnRow: RECOGNIZED_VOIDED_INVOICE, unrecognizedSiblingInvoice: false });
    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage.state).toBe('none');
  });
});
