/**
 * Sibling-coverage schedule verdict — a per-application accept that combines
 * two recurring programs into ONE same-day slot invoices the RESERVED
 * program's row for the combined total and leaves the PROMOTED program's row
 * deliberately unpriced (estimate-converter.js reservedAcceptPerVisitSplit).
 * closeout-status.js reads this shape as `sibling_first_application`.
 *
 * Prod 2026-09-26: a per-application Silver customer accepted lawn
 * ($56.40/app) + quarterly pest ($97.20/app) into ONE reserved slot. The
 * pest row's invoice ($153.60) covered the trip; the lawn row was left
 * unpriced on purpose. The schedule sheet showed the lawn visit's price as
 * $74.70 (the annual/12 equivalent of monthlyRate — meaningless here) and
 * warned "nothing will bill", both wrong. These pin siblingCoverageForSchedule
 * reusing the SAME sibling-invoice lookup completion uses, so the sheet can
 * never contradict it.
 *
 * Owner decision (narrow + fail closed, after 8 Codex rounds, then REFUSE
 * AFTER A VOID replacing the round-9/round-10 guards with one rule): the
 * server computes ONE canonical verdict — { state, invoiceId, invoiceNumber,
 * amountDue, reason } — built ONLY from siblingInvoiceCoverageVerdict plus
 * invoice-helpers' own collectibility checks (invoiceWithdrawnFromCustomer,
 * payer ownership, credit-applied netting, terminal statuses). Every client
 * surface renders this verdict and nothing else. The PRICED reserved row is
 * never refused — completing or charging it bills the combined amount once,
 * which is correct; only the UNPRICED sibling's own verdict changed.
 */

jest.mock('../services/estimate-first-application-invoice', () => ({
  // combinedInvoiceVoidedWithoutLiveReplacement (billing-lane.js) reuses the
  // REAL, pure isAutoGeneratedPayPerApplicationInvoice (no DB, no side
  // effects) to recognize a voided combined invoice's notes — only the
  // DB-backed lookup itself is mocked below.
  ...jest.requireActual('../services/estimate-first-application-invoice'),
  findFirstApplicationInvoiceForEstimateService: jest.fn(),
}));

const { findFirstApplicationInvoiceForEstimateService } = require('../services/estimate-first-application-invoice');
const {
  siblingCoverageForSchedule, siblingInvoiceCoverageVerdict, combinedInvoiceVoidedWithoutLiveReplacement,
  perApplicationCompletionVoidHold,
} = require('../services/billing-lane');

// Minimal knex-like stand-in. 'scheduled_services' distinguishes the two
// queries sameTripFirstApplicationBreakdown issues by their `where` shape —
// a lookup by id (the invoice's owning visit) vs. the same-day/estimate
// members scan. 'invoices as i' backs combinedInvoiceVoidedWithoutLiveReplacement's
// own query (owner ruling — REFUSE AFTER A VOID): unlike a `.first()`-based
// lookup, this one is awaited DIRECTLY (mirrors the real knex `.select()`
// thenable — `await query` resolves to the row array), so the fake must be
// "thenable" (`.then`) rather than exposing a separate terminal method.
// `invoiceRows` (default `[]`, i.e. nothing on file) is the full candidate
// set that query would return; every call site that doesn't pass it keeps
// every EXISTING verdict unchanged. `invoiceQueryCalls` (optional, out
// param) collects each chain call made against the `invoices` query so a
// test can assert the query is correctly SCOPED without a real database.
// `invoiceById` (plain `invoices` table, distinct from the `invoices as i`
// alias below) backs isPricedCoveredMemberVisit's own anchor-identity read
// (`.where({id}).first('scheduled_service_id')`) — the priced-covered-member
// widening gate, never the sibling-invoice lookup itself. `ownRefundRow`
// (default none) backs pricedCoveredMemberOwnRefundHold's own
// completionTerminalInvoiceLookup read (its ONLY `.whereIn('status', ...)`
// call on this table — the discriminator from the anchor-identity read
// above); `splitOffRows` (default `[]`) backs isPricedCoveredMemberVisit's
// OWN "split off by hand" check (liveBaseApplicationInvoiceVisitIdsOn),
// which always starts with `.whereIn` too but ends in `.select(...)`, never
// `.first(...)` — told apart by which terminal method the real call chain
// actually reaches.
function fakeDbConn({
  byId = {}, members = [], invoiceRows = [], invoiceQueryCalls = null, invoiceById = {},
  ownRefundRow = null, splitOffRows = [],
} = {}) {
  return (table) => {
    if (table === 'scheduled_services') {
      return {
        where(cond) {
          if (cond && cond.id !== undefined) {
            return { first: async () => byId[cond.id] || null };
          }
          return {
            whereNull: () => ({
              select: async () => members,
            }),
          };
        },
      };
    }
    if (table === 'invoices') {
      const q = {};
      let usedWhereIn = false;
      let firstWhereCond;
      // Three real call chains share this table: isPricedCoveredMemberVisit's
      // plain `.where({id}).first(...)` anchor-identity read (no
      // .whereIn); pricedCoveredMemberOwnRefundHold's
      // `.where(fn).whereIn('status', ...)....first(...)` own-refund read;
      // and isPricedCoveredMemberVisit's OWN split-off check
      // (`.whereIn(...).whereNotIn(...).modify(...).select(...)`, never
      // `.first()` at all). `.first()` tells the first two apart by
      // whether `.whereIn` was ever called on this chain.
      q.where = (cond) => { if (firstWhereCond === undefined) firstWhereCond = cond; return q; };
      q.whereIn = () => { usedWhereIn = true; return q; };
      q.whereNotIn = () => q;
      q.whereNot = () => q;
      q.orderBy = () => q;
      q.modify = (fn) => { fn(q); return q; };
      q.select = async () => splitOffRows;
      q.first = async () => (usedWhereIn ? ownRefundRow : (invoiceById[firstWhereCond?.id] || null));
      return q;
    }
    if (table === 'invoices as i') {
      const q = {};
      const record = (method) => (...args) => { invoiceQueryCalls?.push([method, ...args]); return q; };
      q.join = record('join');
      q.where = record('where');
      q.whereNot = record('whereNot');
      q.whereNull = record('whereNull');
      q.whereNotIn = record('whereNotIn');
      q.whereIn = record('whereIn');
      q.orderBy = record('orderBy');
      q.forUpdate = record('forUpdate');
      q.noWait = record('noWait');
      q.select = record('select');
      q.then = (resolve, reject) => Promise.resolve(invoiceRows).then(resolve, reject);
      q.catch = (reject) => Promise.resolve(invoiceRows).catch(reject);
      return q;
    }
    throw new Error(`unexpected table: ${table}`);
  };
}

const PEST_ROW = {
  id: 'svc-pest',
  service_type: 'Quarterly Pest Control',
  estimated_price: 153.6,
  recurring_template_overrides: { anchored_split_per_visit: 97.2 },
};
const LAWN_ROW = {
  id: 'svc-lawn',
  service_type: 'Every 6 Weeks Lawn Care',
  estimated_price: null,
  recurring_template_overrides: { anchored_split_per_visit: 56.4 },
};

const LAWN_SVC = {
  id: 'svc-lawn',
  customer_id: 'cust-1',
  source_estimate_id: 'est-1',
  scheduled_date: '2026-09-27',
};

// The recognized notes isAutoGeneratedPayPerApplicationInvoice checks for.
const RECOGNIZED_VOIDED_INVOICE = {
  id: 'inv-void', invoice_number: 'WPC-TEST-0099', status: 'void', title: 'First application',
  created_at: '2026-09-01T00:00:00Z',
  notes: 'Auto-generated from accepted estimate #est-1 — customer selected pay per application — first application.',
};

afterEach(() => {
  jest.clearAllMocks();
});

describe('siblingCoverageForSchedule', () => {
  test('reads the reserved sibling invoice as covering the unpriced promoted visit, with a reconciled breakdown', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1',
        scheduled_service_id: 'svc-pest',
        invoice_number: 'WPC-TEST-0001',
        status: 'sent',
        total: 153.6,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW],
    });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });

    expect(coverage).toEqual({
      state: 'collect_on_combined_invoice',
      invoiceId: 'inv-1',
      invoiceNumber: 'WPC-TEST-0001',
      amountDue: 153.6,
      reason: null,
    });
    expect(prediction).toMatchObject({
      kind: 'covered_sibling_invoice',
      amount: null,
      invoiceId: 'inv-1',
      invoiceNumber: 'WPC-TEST-0001',
      siblingServiceType: 'Quarterly Pest Control',
    });
    expect(prediction.breakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ serviceType: 'Quarterly Pest Control', amount: 97.2 }),
        expect.objectContaining({ serviceType: 'Every 6 Weeks Lawn Care', amount: 56.4 }),
      ]),
    );
    expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalledWith(LAWN_SVC, dbConn);
  });

  // Codex round-9 P2: the invoice ALSO carries a one-time setup fee line
  // and sales tax — `total` (262.35 = $99 setup + $153.60 applications +
  // $9.75 tax) folds in both, so comparing the anchored per-visit splits
  // (which never included either) against the raw total rejected a
  // genuinely correct breakdown outright. Reconciling against the
  // invoice's own line items — excluding the setup fee line, and tax was
  // never a line item to begin with — must still find the match.
  test('reconciles the breakdown against the application-line subtotal, excluding setup fee and tax', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1',
        scheduled_service_id: 'svc-pest',
        invoice_number: 'WPC-TEST-0002',
        status: 'sent',
        total: 262.35,
        line_items: [
          { description: 'WaveGuard Membership — one-time setup fee', amount: 99 },
          { description: 'Quarterly Pest Control', amount: 97.2 },
          { description: 'Every 6 Weeks Lawn Care', amount: 56.4 },
        ],
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW],
    });

    const { prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });

    expect(prediction.kind).toBe('covered_sibling_invoice');
    expect(prediction.breakdown).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ serviceType: 'Quarterly Pest Control', amount: 97.2 }),
        expect.objectContaining({ serviceType: 'Every 6 Weeks Lawn Care', amount: 56.4 }),
      ]),
    );
  });

  // A stringified line_items JSON column (as Postgres can return it) must
  // parse the same way — never silently fall back to the (mismatching)
  // raw total for a real row shape.
  test('reconciles against a STRINGIFIED line_items column the same way', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1',
        scheduled_service_id: 'svc-pest',
        invoice_number: 'WPC-TEST-0003',
        status: 'sent',
        total: 262.35,
        line_items: JSON.stringify([
          { description: 'WaveGuard Membership — one-time setup fee', amount: 99 },
          { description: 'Quarterly Pest Control', amount: 97.2 },
          { description: 'Every 6 Weeks Lawn Care', amount: 56.4 },
        ]),
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW],
    });

    const { prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(prediction.breakdown).toBeDefined();
  });

  // Codex round-7 P1 (mechanism retained, verdict now server-side): the raw
  // invoice status alone told a consumer THAT a sibling invoice exists,
  // never whether it still needs collecting. `amountDue` (total minus
  // credit_applied — invoiceAmountDue, invoice-helpers.js) lets the state
  // machine tell staff exactly what's still owed on THAT invoice.
  test('amountDue nets any account credit already applied to the sibling invoice', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'overdue', total: 153.6, credit_applied: 50,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
    });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toMatchObject({ state: 'collect_on_combined_invoice', amountDue: 103.6 });
  });

  // Round-8 P1: a credit-applied invoice fully covered (amountDue <= 0) is
  // settled — nothing left to collect — even though the raw status is still
  // an ordinarily-collectible one like 'sent'.
  test('a fully credit-covered sibling invoice (amountDue <= 0) reads settled, not collect', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'sent', total: 153.6, credit_applied: 200,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'credit_applied' });
  });

  // Round-8 P1: a payer-owned or withdrawn-from-customer sibling invoice is
  // not collectible from THIS customer at all — the payment paths reject
  // those explicitly (invoiceWithdrawnFromCustomer, payer ownership,
  // invoice-helpers.js) — so it reads settled, never "collect on that
  // invoice," even while the invoice itself is still draft/sent.
  test('a payer-owned sibling invoice reads settled, never collectible from the homeowner', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'sent', total: 153.6, payer_id: 'payer-1',
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'payer_billed' });
  });

  test('a sibling invoice withdrawn from the customer (payer_billed: stamp) reads settled', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001',
        status: 'sent', total: 153.6, scheduled_send_error: 'payer_billed:payer-1',
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'withdrawn_from_customer' });
  });

  // A paid/prepaid/processing sibling invoice is settled — money already
  // collected or in flight — regardless of amountDue's raw value. A
  // technician collects nothing from any of the three either way, but
  // 'processing' keeps its OWN reason (codex round-9 P2) — see the test
  // right below.
  test('a paid sibling invoice reads settled', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'paid', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'invoice_settled' });
  });

  // Codex round-9 P2: a covering sibling invoice that is only 'processing'
  // (money in flight, e.g. a pending ACH debit) still reads `state:
  // 'settled'` — a technician collects nothing from it either way — but
  // its `reason` must stay 'invoice_processing', distinct from a genuinely
  // paid/prepaid 'invoice_settled'. Lumping the two together let the
  // schedule sheet's CompletionPanel preview an immediate review request
  // for a visit whose completion path (complete-scheduled-service.js
  // invoiceBlocksReview) actually holds the ask until the sibling invoice
  // is literally 'paid'/'prepaid'.
  test('a processing sibling invoice reads settled with its own distinct reason', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'processing', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'invoice_processing' });
  });

  test('omits the breakdown when the anchored splits do not reconcile to the invoice total', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: {
        id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'sent', total: 200,
      },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } },
      members: [PEST_ROW, LAWN_ROW], // sums to 153.60, not 200
    });

    const { prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(prediction.kind).toBe('covered_sibling_invoice');
    expect(prediction.breakdown).toBeUndefined();
  });

  // Mirrors the completion predicate exactly: findFirstApplicationInvoiceForEstimateService
  // itself scopes the match to the SAME scheduled_date as the visit passed in,
  // so an unpriced visit whose only source-estimate invoice belongs to a
  // DIFFERENT day's sibling correctly reads as "no match" — never covered.
  test('is not covered when the shared predicate finds no match (different-date sibling)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
  });

  // Owner ruling — REFUSE AFTER A VOID: after the estimate's recognized
  // combined invoice on the RESERVED sibling (svc-pest) is voided,
  // findFirstApplicationInvoiceForEstimateService's own query can't see it
  // at all (excludes 'void' entirely) and reports 'none' — indistinguishable
  // from "nothing was ever minted." Without the fix, the unpriced PROMOTED
  // sibling (LAWN_SVC) would read 'none' too and mint its own
  // per-application fee ON TOP of the combined invoice the reserved row
  // will still (correctly) bill. combinedInvoiceVoidedWithoutLiveReplacement
  // must catch this and surface 'review' (reason 'combined_invoice_voided')
  // instead, so Charge Now refuses with its 409 and the schedule sheet
  // shows the review state — never a silent mint.
  test('surfaces review with reason combined_invoice_voided — never a false "none" — when the estimate\'s recognized invoice is voided', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE] });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({
      state: 'review', invoiceId: 'inv-void', invoiceNumber: 'WPC-TEST-0099', amountDue: null, reason: 'combined_invoice_voided',
    });
    expect(prediction).toMatchObject({ kind: 'sibling_needs_review', amount: null, invoiceId: 'inv-void', invoiceNumber: 'WPC-TEST-0099' });
  });

  // Scope proof: the guard's OWN query must only ever ask about the SAME
  // estimate + SAME trip + customer (never a different estimate or a
  // different day). This inspects the query calls directly (no real
  // database) so the scoping can't silently drift into a broader,
  // false-positive-prone match.
  test('the combined-invoice-voided query is scoped to the same estimate + same trip + customer only', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const invoiceQueryCalls = [];
    const dbConn = fakeDbConn({ invoiceRows: [], invoiceQueryCalls });

    await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });

    const whereCalls = invoiceQueryCalls.filter(([method]) => method === 'where');
    expect(whereCalls).toEqual(expect.arrayContaining([
      ['where', 'i.customer_id', LAWN_SVC.customer_id],
      ['where', 'first_visit.source_estimate_id', LAWN_SVC.source_estimate_id],
      ['where', 'first_visit.scheduled_date', LAWN_SVC.scheduled_date],
    ]));
    expect(invoiceQueryCalls.some(([method]) => method === 'join')).toBe(true);
  });

  // Codex round 5 P2 (mechanism retained): a refunded/terminal match is NOT
  // collapsed to 'none' — resolveScheduledServiceCharge (the mint-side
  // resolver sharing this same lookup) always refuses this exact shape with
  // a 409, so leaving the naive positive prediction in place offered a
  // Charge button that could never succeed. A 'review' verdict tells staff
  // to go resolve it instead.
  test('surfaces a review verdict for a refunded sibling invoice — never a false "covered" or a stale positive amount', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'refunded', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ byId: { 'svc-pest': { id: 'svc-pest', service_type: 'Quarterly Pest Control' } } });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'review', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: null, reason: 'terminal_invoice' });
    expect(prediction).toEqual({
      kind: 'sibling_needs_review',
      amount: null,
      conflictStampedPrice: false,
      invoiceId: 'inv-1',
      invoiceNumber: 'WPC-TEST-0001',
    });
  });

  // Round-8 P2: this visit's OWN attached first-application invoice sitting
  // in a terminal state (refunded) also reads 'review' — the raw lookup
  // (siblingInvoiceCoverageVerdict) surfaces a terminal match regardless of
  // WHOSE row it sits on, before its own-visit exclusion, so no special case
  // is needed here for "own invoice, not a sibling's."
  test('surfaces a review verdict for THIS visit\'s own refunded attached invoice (not a sibling\'s)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, invoice_number: 'WPC-TEST-0001', status: 'refunded', total: 56.4 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage.state).toBe('review');
    expect(prediction.kind).toBe('sibling_needs_review');
  });

  // Codex round 5 P2: the canceled-acceptance-invoice-with-setup-fee shape
  // (siblingInvoiceCoverageVerdict's `canceledSetupFee`) is also review with
  // NO invoice at all — must still surface the review verdict, not 'none',
  // and not throw on the missing invoice.
  test('surfaces a review verdict for a canceled acceptance invoice with no live replacement (no invoice on the verdict)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: null,
      liveBeside: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'review', invoiceId: null, invoiceNumber: null, amountDue: null, reason: 'canceled_setup_fee' });
    expect(prediction).toEqual({
      kind: 'sibling_needs_review',
      amount: null,
      conflictStampedPrice: false,
      invoiceId: null,
      invoiceNumber: null,
    });
  });

  test('never covers a visit against its OWN live (non-terminal) invoice (not a sibling)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, invoice_number: 'WPC-TEST-0001', status: 'sent', total: 56.4 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn();

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
  });

  test('fails toward "none" (never a false "covered") when there is no source estimate', async () => {
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: { ...LAWN_SVC, source_estimate_id: null }, dbConn: fakeDbConn() });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // Codex round 5 P2 (mechanism retained): a lookup FAILURE is treated
  // exactly like needs_review/'review', not collapsed to 'none' —
  // resolveScheduledServiceCharge refuses to mint for it too, so the naive
  // positive prediction must not survive untouched here either.
  test('surfaces a review verdict (never "none") when the shared lookup throws', async () => {
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: LAWN_SVC, dbConn: fakeDbConn() });
    expect(coverage).toEqual({ state: 'review', invoiceId: null, invoiceNumber: null, amountDue: null, reason: 'lookup_failed' });
    expect(prediction).toEqual({
      kind: 'sibling_needs_review',
      amount: null,
      conflictStampedPrice: false,
      invoiceId: null,
      invoiceNumber: null,
    });
  });

  // Owner ruling — REFUSE AFTER A VOID: the priced reserved row is NEVER
  // pushed into review by this function — completing or charging it bills
  // the combined amount once, which is correct. Only the UNPRICED sibling's
  // own verdict changes when the combined invoice is voided.
  test('a PRICED visit never enters this prediction at all, even with a voided combined invoice on file', async () => {
    const PEST_SVC = { ...LAWN_SVC, id: 'svc-pest', estimated_price: 153.6 };
    const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE] });
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PEST_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // Priced-covered-member widening (Codex r21 P1 on PR #5021, deferred to
  // this follow-up): a NON-ANCHOR row staff priced AFTER its trip's combined
  // invoice already existed is stamped to a DIFFERENT row's invoice
  // (invoice.scheduled_service_id !== svc.id) — still covered, the SAME
  // verdict the unpriced path already reached. Distinguishes this row from
  // the "PRICED visit never enters" test above, which is the UNSTAMPED case.
  test('a PRICED non-anchor sibling stamped to a DIFFERENT row\'s PAID invoice still reads settled', async () => {
    const PRICED_LAWN_SVC = { ...LAWN_SVC, estimated_price: 56.4, first_application_invoice_id: 'inv-1' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'paid', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ invoiceById: { 'inv-1': { scheduled_service_id: 'svc-pest' } } });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PRICED_LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'settled', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 0, reason: 'invoice_settled' });
    expect(prediction.kind).toBe('covered_sibling_invoice');
  });

  test('a PRICED non-anchor sibling stamped to a DIFFERENT row\'s OPEN invoice still reads collect_on_combined_invoice', async () => {
    const PRICED_LAWN_SVC = { ...LAWN_SVC, estimated_price: 56.4, first_application_invoice_id: 'inv-1' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({ invoiceById: { 'inv-1': { scheduled_service_id: 'svc-pest' } } });

    const { coverage } = await siblingCoverageForSchedule({ svc: PRICED_LAWN_SVC, dbConn });
    expect(coverage).toEqual({ state: 'collect_on_combined_invoice', invoiceId: 'inv-1', invoiceNumber: 'WPC-TEST-0001', amountDue: 153.6, reason: null });
  });

  // The ANCHOR itself, even when stamped (to its OWN invoice), never enters
  // this prediction — completing/charging it bills the combined amount
  // once, which is correct (same rule as the unstamped priced case above;
  // this pins the STAMPED-but-still-the-anchor shape specifically).
  test('a PRICED ANCHOR row — stamped to ITS OWN invoice — never enters this prediction, unchanged', async () => {
    const PEST_SVC = { ...LAWN_SVC, id: 'svc-pest', estimated_price: 153.6, first_application_invoice_id: 'inv-1' };
    const dbConn = fakeDbConn({ invoiceById: { 'inv-1': { scheduled_service_id: 'svc-pest' } } });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PEST_SVC, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // #5237 review r2 P2: a priced covered member whose OWN base-application
  // invoice is REFUNDED — the combined invoice is STILL LIVE, so
  // isPricedCoveredMemberVisit's "split off by hand" check (LIVE-only)
  // still says covered — must surface `review`, the SAME verdict
  // completion reaches by checking this visit's own refund FIRST
  // (completionTerminalInvoiceLookup), never `collect_on_combined_invoice`
  // — that invoice is fine; THIS visit's own money is what's in question.
  test('a PRICED non-anchor sibling with its OWN refunded base-application invoice (combined still live) → review, matching completion', async () => {
    const PRICED_LAWN_SVC = { ...LAWN_SVC, estimated_price: 56.4, first_application_invoice_id: 'inv-1' };
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', invoice_number: 'WPC-TEST-0001', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    const dbConn = fakeDbConn({
      invoiceById: { 'inv-1': { scheduled_service_id: 'svc-pest' } },
      ownRefundRow: { id: 'inv-own-refund', invoice_number: 'WPC-TEST-0077', status: 'refunded' },
    });

    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PRICED_LAWN_SVC, dbConn });
    expect(coverage.state).toBe('review');
    expect(prediction.kind).toBe('sibling_needs_review');
    // The own-refund short-circuit never even asks the sibling lookup.
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // Codex r4 P2 on #5237: the day/week feeds call this per visit, so a
  // priced row whose feed read carries a NULL stamp spends no member-check
  // query at all (read-only prediction; charge paths re-read under a lock).
  test('a PRICED row whose feed read carries a NULL stamp spends no member-check query', async () => {
    const PRICED_UNSTAMPED = { ...LAWN_SVC, estimated_price: 56.4, first_application_invoice_id: null };
    const dbConn = jest.fn(() => { throw new Error('no query expected'); });
    const { coverage, prediction } = await siblingCoverageForSchedule({ svc: PRICED_UNSTAMPED, dbConn });
    expect(coverage.state).toBe('none');
    expect(prediction).toBeNull();
    expect(dbConn).not.toHaveBeenCalled();
  });

  test('...nor does a priced CALLBACK row, even stamped (shape fails before any read)', async () => {
    const PRICED_CALLBACK = { ...LAWN_SVC, estimated_price: 56.4, first_application_invoice_id: 'inv-1', is_callback: true };
    const dbConn = jest.fn(() => { throw new Error('no query expected'); });
    const { coverage } = await siblingCoverageForSchedule({ svc: PRICED_CALLBACK, dbConn });
    expect(coverage.state).toBe('none');
    expect(dbConn).not.toHaveBeenCalled();
  });
});

// Codex pre-push P0 (x2): a MINT decision (resolveScheduledServiceCharge,
// admin-schedule.js) must tell "definitely no relevant sibling invoice"
// apart from "a lookup failure" and "a terminal/refunded match" — both of
// which completion's own mint refuses to remint over. The verdict function
// must NOT collapse those non-covered cases to null (Codex r13 P2 removed
// the display-safe wrapper that did, so no caller can mistake an
// unresolved invoice for an absent one); a write caller refuses instead of
// bills.
describe('siblingInvoiceCoverageVerdict', () => {
  test('covered — a live sibling invoice', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      liveBeside: null,
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'covered',
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
  });

  // A working dbConn is required from here on: a null-invoice verdict now
  // also runs the fail-closed combinedInvoiceVoidedWithoutLiveReplacement
  // check, so `{}` is no longer a valid stand-in for the `!inv` branch
  // specifically — fakeDbConn()'s default (no invoice rows on file)
  // preserves this exact 'none' verdict.
  test('none — no match at all', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, fakeDbConn())).toEqual({ status: 'none' });
  });

  test('none — a match naming this visit\'s OWN row (not a sibling)', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, status: 'sent', total: 56.4 },
      liveBeside: null,
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({ status: 'none' });
  });

  test('needs_review — a terminal/refunded match, carrying any live replacement as liveBeside', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'needs_review',
      invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
  });

  // Codex round-2 P0: the shared lookup deliberately returns a refunded
  // match ahead of any live replacement REGARDLESS of whose row it sits
  // on (no reliable refund-event clock), with the live replacement riding
  // along as `liveBeside`. The own-visit check ("just my own row, not a
  // sibling") must NOT be evaluated before the terminal-status check — an
  // own-visit REFUNDED match discarded as "none" would also discard a
  // live SIBLING invoice riding beside it, letting a write caller mint
  // the acceptance fee for a trip that sibling's live invoice already
  // covers.
  test('needs_review — a REFUNDED match naming this visit\'s OWN row, with a live SIBLING invoice riding as liveBeside', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, status: 'refunded', total: 56.4 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'needs_review',
      invoice: { id: 'inv-1', scheduled_service_id: LAWN_SVC.id, status: 'refunded', total: 56.4 },
      liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
    });
  });

  test('error — the shared lookup throws', async () => {
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({ status: 'error' });
  });

  // Codex round-6 P1 (pre-push): `noWait` rides through to the shared
  // lookup ONLY when the caller passes it (the schedule mint's own recheck,
  // which already holds the estimate.deposit.ledger lock and must fail
  // fast rather than block into a deadlock against
  // withInvoiceDepositSettlement's invoice-row-then-ledger-lock order). A
  // NOWAIT lock-busy failure is just another lookup failure here.
  test('passes lockRows/noWait through to the shared lookup exactly as given', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    const trx = {};
    await siblingInvoiceCoverageVerdict(LAWN_SVC, trx, { lockRows: true, noWait: true });
    expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalledWith(
      LAWN_SVC, trx, { lockRows: true, noWait: true },
    );
  });

  test('a NOWAIT lock-busy failure reads as a plain lookup error, not a crash', async () => {
    const busy = new Error('could not obtain lock on row');
    busy.code = '55P03';
    findFirstApplicationInvoiceForEstimateService.mockRejectedValue(busy);
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {}, { lockRows: true, noWait: true }))
      .toEqual({ status: 'error' });
  });

  // Codex pre-push P0 (round 2): the lookup's null-invoice return is NOT
  // always "no relevant match" — it also carries canceledSetupFee when a
  // canceled acceptance invoice included the one-time setup fee with no
  // live replacement. Losing that here would let a write caller mint only
  // the per-visit/per-application charge and silently drop the fee
  // completion itself parks for manual billing instead.
  test('needs_review — a canceled acceptance invoice carrying the setup fee, with no live replacement', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
      invoice: null,
      liveBeside: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, {})).toEqual({
      status: 'needs_review',
      invoice: null,
      canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
    });
  });

  test('none — a null invoice with no canceledSetupFee either', async () => {
    findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
    expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, fakeDbConn())).toEqual({ status: 'none' });
  });

  // Owner ruling — REFUSE AFTER A VOID: the null-invoice branch's
  // combinedInvoiceVoidedWithoutLiveReplacement integration.
  describe('the REFUSE AFTER A VOID guard', () => {
    test('needs_review with reason combined_invoice_voided when the estimate\'s recognized invoice is voided with no live replacement', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE] });
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn)).toEqual({
        status: 'needs_review', invoice: RECOGNIZED_VOIDED_INVOICE, reason: 'combined_invoice_voided',
      });
    });

    // canceledSetupFee still wins (checked first) — this fix never
    // reclassifies that existing, already fail-closed verdict shape.
    test('canceledSetupFee still takes precedence over the new guard', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: null, liveBeside: null,
        canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
      });
      const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE] });
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn)).toEqual({
        status: 'needs_review', invoice: null, canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
      });
    });

    // A recognized 'covered' verdict is untouched — the guard only ever
    // runs inside the `!inv` branch, never re-litigating an already-live
    // recognized match.
    test('never overrides an already-recognized "covered" verdict', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
        liveBeside: null,
      });
      const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE] });
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn)).toEqual({
        status: 'covered', invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      });
    });

    // A query failure inside the guard fails CLOSED — the same way any
    // other lookup failure does — never silently as "no voided invoice".
    test('a guard-query failure reads as a plain lookup error, not a silent "none"', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const brokenDbConn = () => { throw new Error('connection lost'); };
      expect(await siblingInvoiceCoverageVerdict(LAWN_SVC, brokenDbConn)).toEqual({ status: 'error' });
    });

    // Owner ruling: "this must hold through the in-transaction locked
    // recheck as well" — the guard's own query takes the SAME
    // forUpdate/noWait it's given, so a concurrent void+remint between the
    // pre-lock check and the locked recheck is caught the same way.
    test('lockRows/noWait ride through to the guard\'s own query', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const invoiceQueryCalls = [];
      const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE], invoiceQueryCalls });
      const verdict = await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn, { lockRows: true, noWait: true });
      expect(verdict).toEqual({ status: 'needs_review', invoice: RECOGNIZED_VOIDED_INVOICE, reason: 'combined_invoice_voided' });
      expect(invoiceQueryCalls.some(([method]) => method === 'forUpdate')).toBe(true);
      expect(invoiceQueryCalls.some(([method]) => method === 'noWait')).toBe(true);
    });

    // Without lockRows, the guard's query must NOT take a row lock — a
    // plain read-only schedule-sheet prediction never holds rows.
    test('no forUpdate/noWait on the guard\'s query when lockRows is not requested', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const invoiceQueryCalls = [];
      const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE], invoiceQueryCalls });
      await siblingInvoiceCoverageVerdict(LAWN_SVC, dbConn);
      expect(invoiceQueryCalls.some(([method]) => method === 'forUpdate')).toBe(false);
    });
  });
});

// Direct unit coverage of the predicate itself (owner ruling — REFUSE AFTER
// A VOID, replacing sameTripSiblingHasUnrecognizedLiveInvoice /
// isPricedSiblingCoverageEligibleVisit / pricedSiblingCoverageVerdict with
// ONE rule). "billing-lane.js:1004" finding: the recognized terminal
// invoice must be found by filtering EVERY candidate row BEFORE any
// limit/order truncation — never by ordering/limiting first and checking
// recognition after, which could let an unrelated newer invoice on the
// same estimate mask an older recognized invoice that had actually died.
describe('combinedInvoiceVoidedWithoutLiveReplacement', () => {
  test('returns the recognized terminal invoice when it is void with no live recognized replacement', async () => {
    const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE] });
    expect(await combinedInvoiceVoidedWithoutLiveReplacement(LAWN_SVC, dbConn)).toEqual(RECOGNIZED_VOIDED_INVOICE);
  });

  test('returns null when no invoice exists on the estimate at all', async () => {
    const dbConn = fakeDbConn({ invoiceRows: [] });
    expect(await combinedInvoiceVoidedWithoutLiveReplacement(LAWN_SVC, dbConn)).toBeNull();
  });

  test('returns null when a live recognized invoice replaces the voided one', async () => {
    const liveReplacement = {
      ...RECOGNIZED_VOIDED_INVOICE, id: 'inv-live', status: 'sent', created_at: '2026-09-10T00:00:00Z',
    };
    const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE, liveReplacement] });
    expect(await combinedInvoiceVoidedWithoutLiveReplacement(LAWN_SVC, dbConn)).toBeNull();
  });

  // Codex pre-push P1 ("billing-lane.js:1004" finding): a NEWER, unrelated
  // (unrecognized) invoice on the same estimate must never mask an OLDER
  // recognized invoice that actually died — filtering to the recognized
  // set happens BEFORE any ordering/limiting, so this still finds it.
  test('finds the recognized terminal invoice even when a newer UNRELATED invoice exists on the same estimate', async () => {
    const newerUnrelated = {
      id: 'inv-unrelated', invoice_number: 'WPC-TEST-0100', status: 'sent', title: 'Ad hoc extra',
      notes: 'Not an acceptance invoice', created_at: '2026-09-15T00:00:00Z',
    };
    const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE, newerUnrelated] });
    expect(await combinedInvoiceVoidedWithoutLiveReplacement(LAWN_SVC, dbConn)).toEqual(RECOGNIZED_VOIDED_INVOICE);
  });

  // A recognized CANCELED invoice with no setup-fee line is ALSO invisible
  // to findFirstApplicationInvoiceForEstimateService's own canceledSetupFee
  // check (it only parks when a setup fee line exists) — this predicate
  // must still detect it as a died combined invoice.
  test('detects a recognized CANCELED (not just void) invoice with no live replacement', async () => {
    const canceled = { ...RECOGNIZED_VOIDED_INVOICE, id: 'inv-canceled', status: 'canceled' };
    const dbConn = fakeDbConn({ invoiceRows: [canceled] });
    expect(await combinedInvoiceVoidedWithoutLiveReplacement(LAWN_SVC, dbConn)).toEqual(canceled);
  });

  // Multiple terminal recognized invoices (a rare double-void history) —
  // pick the newest, deterministically, AFTER filtering to the recognized
  // set (never before).
  test('picks the newest recognized terminal invoice when more than one exists', async () => {
    const older = { ...RECOGNIZED_VOIDED_INVOICE, id: 'inv-old', created_at: '2026-08-01T00:00:00Z' };
    const newer = { ...RECOGNIZED_VOIDED_INVOICE, id: 'inv-new', created_at: '2026-09-20T00:00:00Z' };
    const dbConn = fakeDbConn({ invoiceRows: [older, newer] });
    const result = await combinedInvoiceVoidedWithoutLiveReplacement(LAWN_SVC, dbConn);
    expect(result.id).toBe('inv-new');
  });

  test('missing estimate/customer/date shape reads as null, never a query attempt', async () => {
    const brokenDbConn = () => { throw new Error('should not be called'); };
    expect(await combinedInvoiceVoidedWithoutLiveReplacement({ id: 'svc-x' }, brokenDbConn)).toBeNull();
  });
});

// perApplicationCompletionVoidHold — the completion-side (and closeout-
// status.js / annual-prepay-renewals.js projection) counterpart of the
// Charge Now REFUSE AFTER A VOID guard above: same combinedInvoiceVoidedWithoutLiveReplacement,
// gated by the SAME isSiblingCoverageEligibleVisit shape. Priced-covered-
// member widening (Codex r21 P1 on PR #5021, deferred to this follow-up):
// a NON-ANCHOR row staff priced after its trip's combined invoice died
// still needs the hold; the ANCHOR's own priced mint never does.
describe('perApplicationCompletionVoidHold — priced-covered-member widening (r21 P1, #5021 follow-up)', () => {
  test('a PRICED non-anchor sibling, combined invoice voided with no live replacement → the hold fires (was a silent pass-through pre-fix)', async () => {
    const PRICED_LAWN_SVC = { ...LAWN_SVC, estimated_price: 56.4, first_application_invoice_id: 'inv-void' };
    const dbConn = fakeDbConn({
      invoiceRows: [RECOGNIZED_VOIDED_INVOICE],
      invoiceById: { 'inv-void': { scheduled_service_id: 'svc-pest' } },
    });
    const hold = await perApplicationCompletionVoidHold({
      isCallback: false, serviceType: PRICED_LAWN_SVC.service_type, svc: PRICED_LAWN_SVC, dbConn,
    });
    expect(hold).toEqual(RECOGNIZED_VOIDED_INVOICE);
  });

  test('the PRICED ANCHOR row (stamped to its OWN invoice) never holds, even with that same invoice voided', async () => {
    const PEST_SVC = { ...LAWN_SVC, id: 'svc-pest', estimated_price: 153.6, first_application_invoice_id: 'inv-void' };
    const dbConn = fakeDbConn({
      invoiceRows: [RECOGNIZED_VOIDED_INVOICE],
      invoiceById: { 'inv-void': { scheduled_service_id: 'svc-pest' } },
    });
    const hold = await perApplicationCompletionVoidHold({
      isCallback: false, serviceType: PEST_SVC.service_type, svc: PEST_SVC, dbConn,
    });
    expect(hold).toBeNull();
  });

  test('an UNSTAMPED priced row never holds — unchanged (no DB call spent deciding isPricedCoveredMember beyond the fast no-stamp path)', async () => {
    const PEST_SVC = { ...LAWN_SVC, id: 'svc-pest', estimated_price: 153.6 };
    const dbConn = fakeDbConn({ invoiceRows: [RECOGNIZED_VOIDED_INVOICE] });
    const hold = await perApplicationCompletionVoidHold({
      isCallback: false, serviceType: PEST_SVC.service_type, svc: PEST_SVC, dbConn,
    });
    expect(hold).toBeNull();
  });

  test('a PRICED non-anchor sibling with a LIVE replacement on the anchor never holds (correctly "covered", not void)', async () => {
    const PRICED_LAWN_SVC = { ...LAWN_SVC, estimated_price: 56.4, first_application_invoice_id: 'inv-void' };
    const replacement = { ...RECOGNIZED_VOIDED_INVOICE, id: 'inv-live', status: 'sent', scheduled_service_id: 'svc-pest' };
    const dbConn = fakeDbConn({
      invoiceRows: [RECOGNIZED_VOIDED_INVOICE, replacement],
      invoiceById: { 'inv-void': { scheduled_service_id: 'svc-pest' } },
    });
    const hold = await perApplicationCompletionVoidHold({
      isCallback: false, serviceType: PRICED_LAWN_SVC.service_type, svc: PRICED_LAWN_SVC, dbConn,
    });
    expect(hold).toBeNull();
  });
});
