const {
  itemizeFirstApplication,
  findFirstApplicationInvoiceForEstimateService,
  isAutoGeneratedPayPerApplicationInvoice,
  invoiceBillsBaseApplication,
  invoiceContainsSetupFeeLine,
  invoiceHasPositiveSetupFeeLine,
  classifyAcceptedEstimateInvoiceCoverage,
} = require('../services/estimate-first-application-invoice');

function makeItemizeKnex(first, members) {
  let queryNumber = 0;
  return jest.fn(() => {
    const rows = queryNumber++ === 0 ? [first] : members;
    const chain = {
      where: jest.fn(() => chain),
      whereNull: jest.fn(() => chain),
      orderBy: jest.fn(() => chain),
      first: jest.fn(async () => rows[0]),
      then: (resolve, reject) => Promise.resolve(rows).then(resolve, reject),
    };
    return chain;
  });
}

describe('itemizeFirstApplication — frozen acceptance ownership', () => {
  const originalGate = process.env.GATE_VISIT_CLOSEOUT;

  afterEach(() => {
    if (originalGate === undefined) delete process.env.GATE_VISIT_CLOSEOUT;
    else process.env.GATE_VISIT_CLOSEOUT = originalGate;
  });

  test('itemizes a gross first-application line across the exact pest and lawn parents', async () => {
    process.env.GATE_VISIT_CLOSEOUT = 'true';
    const members = [
      { id: 'lawn-parent', service_id: 'lawn-catalog', service_type: 'Lawn Care' },
      { id: 'pest-parent', service_id: 'pest-catalog', service_type: 'Quarterly Pest Control' },
    ];
    const line = { description: 'First service application', quantity: 1, unit_price: 220 };
    const result = await itemizeFirstApplication({
      estimateId: 'estimate-1', customerId: 'customer-1', scheduledServiceId: 'pest-parent',
      rowAmounts: [
        { service: 'pest_control', name: 'Quarterly Pest Control', amount: 120 },
        { service: 'lawn_care', name: 'Lawn Care', amount: 100 },
      ],
      line,
    }, makeItemizeKnex({ ...members[1], customer_id: 'customer-1', source_estimate_id: 'estimate-1' }, members));

    expect(result).toEqual([
      { description: 'Lawn Care', quantity: 1, unit_price: 100, amount: 100,
        client_id: 'scheduled_lawn-parent_primary', accepted_service_type: 'Lawn Care',
        accepted_service_id: 'lawn-catalog' },
      { description: 'Quarterly Pest Control', quantity: 1, unit_price: 120, amount: 120,
        client_id: 'scheduled_pest-parent_primary', accepted_service_type: 'Quarterly Pest Control',
        accepted_service_id: 'pest-catalog' },
    ]);
    expect(result.reduce((sum, item) => sum + item.amount, 0)).toBe(line.unit_price);
  });

  test('keeps the historical aggregate when the frozen row amounts do not reproduce its gross total', async () => {
    process.env.GATE_VISIT_CLOSEOUT = 'true';
    const members = [
      { id: 'lawn-parent', service_id: 'lawn-catalog', service_type: 'Lawn Care' },
      { id: 'pest-parent', service_id: 'pest-catalog', service_type: 'Quarterly Pest Control' },
    ];
    const line = { description: 'First service application', quantity: 1, unit_price: 200 };
    const result = await itemizeFirstApplication({
      estimateId: 'estimate-1', customerId: 'customer-1', scheduledServiceId: 'pest-parent',
      // These are the pre-discount gross rows. A separate negative invoice
      // line may reduce the net, but this aggregate cannot safely own them.
      rowAmounts: [
        { service: 'pest_control', name: 'Quarterly Pest Control', amount: 120 },
        { service: 'lawn_care', name: 'Lawn Care', amount: 100 },
      ],
      line,
    }, makeItemizeKnex({ ...members[1], customer_id: 'customer-1', source_estimate_id: 'estimate-1' }, members));

    expect(result).toEqual([line]);
  });

  test('restores exact plan-credit slices before itemizing and leaves the separate discount intact', async () => {
    process.env.GATE_VISIT_CLOSEOUT = 'true';
    const members = [
      { id: 'lawn-parent', service_id: 'lawn-catalog', service_type: 'Lawn Care' },
      { id: 'pest-parent', service_id: 'pest-catalog', service_type: 'Quarterly Pest Control' },
    ];
    const line = { description: 'First service application', quantity: 1, unit_price: 240 };
    const result = await itemizeFirstApplication({
      estimateId: 'estimate-1', customerId: 'customer-1', scheduledServiceId: 'pest-parent',
      rowAmounts: [
        { service: 'pest_control', name: 'Quarterly Pest Control', amount: 110 },
        { service: 'lawn_care', name: 'Lawn Care', amount: 112 },
      ],
      rowDiscounts: [10, 8],
      line,
    }, makeItemizeKnex({ ...members[1], customer_id: 'customer-1', source_estimate_id: 'estimate-1' }, members));

    expect(result.map(({ client_id, accepted_service_id, amount }) => ({ client_id, accepted_service_id, amount }))).toEqual([
      { client_id: 'scheduled_lawn-parent_primary', accepted_service_id: 'lawn-catalog', amount: 120 },
      { client_id: 'scheduled_pest-parent_primary', accepted_service_id: 'pest-catalog', amount: 120 },
    ]);
    expect(result.reduce((sum, item) => sum + item.amount, 0) - 18).toBe(222);
  });
});

describe('invoiceContainsSetupFeeLine — billed-fee evidence', () => {
  test('a positive one-time setup-fee line counts; waived language never does (Codex P0 r13)', () => {
    expect(invoiceContainsSetupFeeLine({
      line_items: JSON.stringify([{ description: 'WaveGuard Membership — one-time setup fee', amount: 99 }]),
    })).toBe(true);
    expect(invoiceContainsSetupFeeLine({
      line_items: JSON.stringify([{ description: '12 months prepaid (setup fee waived)', amount: 340 }]),
    })).toBe(false);
    expect(invoiceContainsSetupFeeLine({
      line_items: JSON.stringify([{ description: 'WaveGuard Membership — one-time setup fee', amount: 0 }]),
    })).toBe(false);
  });

  test('the notes fallback rejects waived language too', () => {
    expect(invoiceContainsSetupFeeLine({ line_items: null, notes: '$99 setup fee plus first application' })).toBe(true);
    expect(invoiceContainsSetupFeeLine({ line_items: null, notes: '12 months prepaid — setup fee waived' })).toBe(false);
  });

  test.each([null, [], 'not-json', '{}', '[]'])(
    'notes can require fee review but cannot prove a billed fee with %j lines', (lineItems) => {
      const invoice = { line_items: lineItems, notes: '$99 setup fee plus first application' };
      expect(invoiceContainsSetupFeeLine(invoice)).toBe(true);
      expect(invoiceHasPositiveSetupFeeLine(invoice)).toBe(false);
    },
  );

  test.each([
    [{ description: 'Setup fee', unit_price: 49.5, quantity: 2 }, true],
    [{ description: 'Setup fee', amount: 0, unit_price: 99 }, false],
    [{ description: 'Setup fee', amount: -99 }, false],
    [{ description: 'Setup fee waived', amount: 99 }, false],
    [{ description: 'Setup fee', amount: 'unreadable' }, false],
    [{ description: 'First application', amount: 99 }, false],
    [null, false],
  ])('parsed charges take precedence over fee notes: %j', (line, expected) => {
    for (const lineItems of [[line], JSON.stringify([line])]) {
      const invoice = { line_items: lineItems, notes: '$99 setup fee plus first application' };
      expect(invoiceContainsSetupFeeLine(invoice)).toBe(expected);
      expect(invoiceHasPositiveSetupFeeLine(invoice)).toBe(expected);
    }
  });
});

describe('invoiceBillsBaseApplication — base-application billing evidence', () => {
  test('the base-application identity: client_id `_primary` or the exact first-application description', () => {
    expect(invoiceBillsBaseApplication({
      line_items: JSON.stringify([{ client_id: 'scheduled_ss-1_primary', description: 'Quarterly Pest Control', unit_price: 88, quantity: 1 }]),
    })).toBe(true);
    expect(invoiceBillsBaseApplication({
      line_items: JSON.stringify([{ description: 'First service application', unit_price: 88, quantity: 1 }]),
    })).toBe(true);
    expect(invoiceBillsBaseApplication({
      line_items: JSON.stringify([{ description: 'WaveGuard Membership — one-time setup fee', amount: 99 }]),
    })).toBe(false);
  });

  test('add-on/product lines are NOT the application (Codex P0, rounds 6–11)', () => {
    expect(invoiceBillsBaseApplication({
      line_items: JSON.stringify([{ client_id: 'scheduled_ss-1_addon_2', description: 'Wasp nest removal', amount: 45 }]),
    })).toBe(false);
    expect(invoiceBillsBaseApplication({
      line_items: JSON.stringify([{ description: 'Advion gel bait (product)', amount: 20 }]),
    })).toBe(false);
  });

  test('credits/discounts/adjustments beside the setup fee are NOT application coverage', () => {
    // InvoiceService.create appends "Deposit credit (paid at acceptance)"
    // adjustment lines to setup-only invoices.
    expect(invoiceBillsBaseApplication({
      line_items: JSON.stringify([
        { description: 'WaveGuard Membership — one-time setup fee', amount: 99 },
        { description: 'Deposit credit (paid at acceptance)', amount: -49 },
      ]),
    })).toBe(false);
  });

  test('non-positive lines never count, even with the base identity', () => {
    expect(invoiceBillsBaseApplication({
      line_items: JSON.stringify([{ client_id: 'scheduled_ss-1_primary', description: 'Refunded application', amount: -88 }]),
    })).toBe(false);
  });

  test('unreadable rows FAIL CLOSED — they prove nothing', () => {
    expect(invoiceBillsBaseApplication({ line_items: null, notes: 'visit charge' })).toBe(false);
    expect(invoiceBillsBaseApplication({ line_items: 'not-json', notes: '$99 setup fee only' })).toBe(false);
    expect(invoiceBillsBaseApplication({ line_items: JSON.stringify([]) })).toBe(false);
  });
});

describe('classifyAcceptedEstimateInvoiceCoverage — coverage scope', () => {
  test('setup-fee coverage is estimate-wide while application coverage follows the visit date', () => {
    expect(classifyAcceptedEstimateInvoiceCoverage({
      service_date: '2026-06-08',
      line_items: [{ description: 'WaveGuard Membership — one-time setup fee', amount: 99 }],
    }, '2026-07-10')).toEqual({
      hasSetupFee: true,
      setupFeeOnly: true,
      matchesApplicationDate: false,
    });

    expect(classifyAcceptedEstimateInvoiceCoverage({
      scheduled_date: '2026-06-08T14:00:00.000Z',
      line_items: [{ client_id: 'scheduled_ss-1_primary', amount: 88 }],
    }, '2026-06-08')).toEqual({
      hasSetupFee: false,
      setupFeeOnly: false,
      matchesApplicationDate: true,
    });
  });

  test('missing and unreadable evidence fails closed as a possible application-date match', () => {
    expect(classifyAcceptedEstimateInvoiceCoverage({ line_items: 'not-json' }, '2026-06-08')).toEqual({
      hasSetupFee: false,
      setupFeeOnly: false,
      matchesApplicationDate: true,
    });
    expect(classifyAcceptedEstimateInvoiceCoverage({
      service_date: '2026-06-09', line_items: 'not-json',
    }, '2026-06-08').matchesApplicationDate).toBe(false);
  });
});

function makeKnex(rows = []) {
  const calls = [];
  const chain = {
    join: jest.fn((...args) => {
      calls.push(['join', ...args]);
      return chain;
    }),
    where: jest.fn((...args) => {
      calls.push(['where', ...args]);
      return chain;
    }),
    whereNot: jest.fn((...args) => {
      calls.push(['whereNot', ...args]);
      return chain;
    }),
    orderBy: jest.fn((...args) => {
      calls.push(['orderBy', ...args]);
      return chain;
    }),
    select: jest.fn(async (...args) => {
      calls.push(['select', ...args]);
      return rows;
    }),
  };
  const knex = jest.fn((table) => {
    calls.push(['table', table]);
    return chain;
  });
  knex.calls = calls;
  return knex;
}

describe('estimate first-application invoice lookup', () => {
  test('classifies only auto-generated pay-per-application first-application invoices', () => {
    expect(isAutoGeneratedPayPerApplicationInvoice({
      title: 'WaveGuard Membership Setup + First Application',
      notes: 'Auto-generated from accepted estimate #est-1. Customer selected pay per application - $99 setup fee plus first application.',
    })).toBe(true);

    expect(isAutoGeneratedPayPerApplicationInvoice({
      title: 'WaveGuard Bronze - Annual Prepay (12 months)',
      notes: 'Auto-generated from accepted estimate #est-1. Customer selected "Pay the year upfront" - $99 setup fee waived.',
    })).toBe(false);

    expect(isAutoGeneratedPayPerApplicationInvoice({
      title: 'First Service Application',
      notes: 'Created manually by office.',
    })).toBe(false);

    expect(isAutoGeneratedPayPerApplicationInvoice({
      title: 'WaveGuard Membership Setup',
      notes: 'Auto-generated from accepted estimate #est-1. Customer selected pay per application - $99 setup fee only.',
    })).toBe(false);
  });

  test('finds sibling first-application invoice for same estimate date', async () => {
    const annualInvoice = {
      id: 'annual-invoice',
      title: 'WaveGuard Bronze - Annual Prepay (12 months)',
      notes: 'Auto-generated from accepted estimate #est-1. Customer selected "Pay the year upfront" - $99 setup fee waived.',
    };
    const firstApplicationInvoice = {
      id: 'first-app-invoice',
      title: 'WaveGuard Membership Setup + First Application',
      notes: 'Auto-generated from accepted estimate #est-1. Customer selected pay per application - $99 setup fee plus first application.',
    };
    const knex = makeKnex([annualInvoice, firstApplicationInvoice]);

    const result = await findFirstApplicationInvoiceForEstimateService({
      customer_id: 'customer-1',
      source_estimate_id: 'est-1',
      scheduled_date: '2026-06-08',
    }, knex);

    expect(result).toEqual({ invoice: firstApplicationInvoice, liveBeside: null });
    expect(knex.calls).toContainEqual(['table', 'invoices as i']);
    expect(knex.calls).toContainEqual(['join', 'scheduled_services as first_visit', 'i.scheduled_service_id', 'first_visit.id']);
    expect(knex.calls).toContainEqual(['where', 'i.customer_id', 'customer-1']);
    expect(knex.calls).toContainEqual(['where', 'first_visit.source_estimate_id', 'est-1']);
    expect(knex.calls).toContainEqual(['where', 'first_visit.scheduled_date', '2026-06-08']);
    expect(knex.calls).toContainEqual(['whereNot', 'i.status', 'void']);
  });

  test('a REFUNDED sibling first-application invoice still suppresses (status quo — own-visit terminal handling lives in admin-dispatch)', async () => {
    const refunded = {
      id: 'inv-sib', status: 'refunded', scheduled_service_id: 'sibling-visit',
      title: 'WaveGuard Membership Setup + First Application',
      notes: 'Auto-generated from accepted estimate #est-1. Customer selected pay per application - $99 setup fee plus first application.',
    };
    const knex = makeKnex([refunded]);
    const found = await findFirstApplicationInvoiceForEstimateService(
      { customer_id: 'customer-1', source_estimate_id: 'est-1', scheduled_date: '2026-06-08' },
      knex,
    );
    expect(found).toEqual({ invoice: refunded, liveBeside: null });
    // Only void is filtered here — deliberately NOT the terminal vocabulary.
    expect(knex.calls).toContainEqual(['whereNot', 'i.status', 'void']);
    expect(knex.calls.some((c) => c[0] === 'whereNotIn')).toBe(false);
  });

  test('does not query when the service is not linked to an estimate date', async () => {
    const knex = makeKnex();

    await expect(findFirstApplicationInvoiceForEstimateService({
      customer_id: 'customer-1',
      scheduled_date: '2026-06-08',
    }, knex)).resolves.toEqual({ invoice: null, liveBeside: null });

    expect(knex).not.toHaveBeenCalled();
  });
});
