// Lawn protocol v13: Dylox 6.2 G is at most 2 applications per lawn per calendar year (migration 20261009173000, after the frozen
// 20261009172000 wrote 3), through the real migrations on PostgreSQL (cloned schema). Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned: after 172000 then 173000 the count limit reads 2 with the Waves rule description and the staged rows carry annualMaxApps 2;
// the 7 day and 9.07 lb rows and minIntervalDays are as 172000 wrote them; a hand-edited 3 (other description), a stricter hand-edited
// value and a retired row are left; no count row at all gets one inserted at 2; a second up changes nothing; with no catalog row nothing
// is written; down puts back 3 and the label description only where the rows still read as written; 172000's own down after this one
// removes everything, and run while this write is in place it leaves the 2 and deletes nothing it did not write.
const { createLawnHistoryDb } = require('./helpers/lawn-history-db');
const first = require('../models/migrations/20261009172000_lawn_v13_dylox_label_limits');
const migration = require('../models/migrations/20261009173000_lawn_v13_dylox_two_a_year');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');

const DYLOX = first.DYLOX;
const SL = 'Dylox 420 SL T&O Insecticide';
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_dx_a', 'fixture_dx_b'];
const OCT = 'oct_v13_spreader_fall';
const DYLOX_GATES = { trigger: 'grubs_or_mole_crickets', postAppIrrigation: true, spreaderVisitOnly: true };
const CATALOG_TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products',
  'lawn_protocol_audit_log', 'lawn_protocol_service_completions', 'product_limits', 'lawn_protocol_product_actuals', 'service_products'];

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 Dylox 6.2 G two a year migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of CATALOG_TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [table, constraint, suffix] of [
      ['product_limits', 'fixture_limits_product', ''], ['product_aliases', 'fixture_aliases_product', ''],
      ['service_products', 'fixture_sp_product', ' ON DELETE SET NULL'], ['lawn_protocol_products', 'fixture_lpp_product', ''],
    ]) {
      await knex.raw(`ALTER TABLE ??.?? ADD CONSTRAINT ${constraint} FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)${suffix}`, [owned.schema, table, owned.schema]);
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const limits = (name) => knex('product_limits').whereIn('product_id', knex('products_catalog').where({ name }).select('id')).orderBy('id');
  const byType = async (name, type) => (await limits(name)).filter((row) => row.limit_type === type);
  const rows = (name, version = V13) => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'p.product_name': name, 'l.version': version }).orderBy(['l.protocol_key', 'p.id']).select('p.*', 'l.protocol_key');
  const ours = () => knex('lawn_protocol_audit_log').whereIn('action', [first.ACTION, first.CATALOG_ACTION, migration.ACTION, migration.CATALOG_ACTION]);
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  async function snapshot() {
    return clean([
      await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']), await knex('products_catalog').orderBy('name'),
      await knex('product_limits').orderBy('id'), await knex('lawn_protocol_audit_log').orderBy('id'),
    ]);
  }

  // The catalog (Dylox 6.2 G, Dylox 420 SL with its own limits, a decoy product) and two staged v13 protocols with the
  // Dylox 6.2 G row in the October window as migration 20261005120000 leaves it, plus an older protocol version.
  async function reset({ dylox = true } = {}) {
    for (const table of ['service_products', 'lawn_protocol_product_actuals', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    const [sl] = await knex('products_catalog').insert({ name: SL, category: 'insecticide', formulation: 'liquid', active: true }).returning('*');
    const [other] = await knex('products_catalog').insert({ name: 'Fixture Other', category: 'insecticide', active: true }).returning('*');
    ids.sl = sl.id; ids.other = other.id;
    await knex('product_limits').insert({ product_id: sl.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 5, limit_unit: 'applications', severity: 'warning' });
    if (dylox) {
      const [dx] = await knex('products_catalog').insert({ name: DYLOX, category: 'insecticide', formulation: 'granular', active_ingredient: 'trichlorfon 6.2%', rate_unit: 'lb', active: true }).returning('*');
      ids.dx = dx.id;
    }
    for (const key of KEYS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' });
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 10, window_key: OCT, title: OCT, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert([
        ...(dylox ? [{ lawn_protocol_window_id: window.id, product_id: ids.dx, product_name: DYLOX, role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'label_rate', default_in_plan: false, sort_order: 3, gates: JSON.stringify(DYLOX_GATES) }] : []),
        { lawn_protocol_window_id: window.id, product_id: ids.sl, product_name: SL, role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'fl_oz', default_in_plan: false, sort_order: 4, gates: JSON.stringify({ trigger: 'mole_cricket_adults' }) },
        { lawn_protocol_window_id: window.id, product_id: ids.other, product_name: 'Fixture Other', role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'lb', default_in_plan: false, sort_order: 5, gates: JSON.stringify({ trigger: 'fixture' }) },
      ]);
    }
    if (dylox) {
      // An older protocol version's row: not a v13 row, so it is left alone.
      const [old] = await knex('lawn_protocols').where({ protocol_key: KEYS[0], version: '2026.06' });
      const [oldWindow] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: old.id, month: 10, window_key: OCT, title: OCT, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: oldWindow.id, product_id: ids.dx, product_name: DYLOX, role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'lb', default_in_plan: false, sort_order: 3, gates: JSON.stringify(DYLOX_GATES) });
    }
  }


  const countRows = () => byType(DYLOX, 'annual_max_apps');
  const numbers = async () => (await countRows()).map((row) => [Number(row.limit_value), row.description]);

  describe('after 172000 then 173000', () => {
    beforeEach(async () => { await reset(); await first.up(knex); });

    test('the count limit is 2 with the Waves rule description; the interval and amount rows and the interval gate are as 172000 wrote them', async () => {
      const before = clean(await limits(DYLOX));
      await migration.up(knex);
      expect(await numbers()).toEqual([[2, migration.LIMIT.description]]);
      expect(migration.LIMIT.description).toMatch(/Waves rule/);
      expect(migration.LIMIT.description).toMatch(/432-1308/);
      const [interval] = await byType(DYLOX, 'min_interval_days');
      const [amount] = await byType(DYLOX, 'annual_max_rate');
      expect([Number(interval.limit_value), interval.severity, Number(amount.limit_value), amount.match_value]).toEqual([7, 'hard_block', 9.07, 'trichlorfon']);
      expect((await countRows())[0]).toMatchObject({ severity: 'hard_block', limit_unit: 'applications', match_type: 'product' });
      expect(JSON.parse(before)).toHaveLength(3);
      for (const row of await rows(DYLOX)) expect(row.gates).toEqual({ ...DYLOX_GATES, annualMaxApps: 2, minIntervalDays: 7 });
    });

    test('Dylox 420 SL, the decoy and the older protocol version are not touched', async () => {
      const state = { sl: clean(await limits(SL)), slRows: clean(await rows(SL)), other: clean(await rows('Fixture Other')), old: clean(await rows(DYLOX, '2026.06')) };
      await migration.up(knex);
      expect({ sl: clean(await limits(SL)), slRows: clean(await rows(SL)), other: clean(await rows('Fixture Other')), old: clean(await rows(DYLOX, '2026.06')) }).toEqual(state);
    });

    test('one audit row per protocol and one for the limit; a second up changes nothing', async () => {
      await migration.up(knex);
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.ACTION })).toHaveLength(KEYS.length);
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION })).toHaveLength(1);
      const state = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(state);
    });

    test('down puts back 3 and the label description, the gates at 3, and removes its audit rows', async () => {
      const state = await snapshot();
      await migration.up(knex);
      await migration.down(knex);
      expect(await snapshot()).toBe(state);
      expect(await numbers()).toEqual([[3, first.LIMITS[0].description]]);
    });

    test('down leaves a hand-edited limit and a gate somebody changed since', async () => {
      await migration.up(knex);
      const [count] = await countRows();
      await knex('product_limits').where({ id: count.id }).update({ limit_value: 1 });
      const [row] = await rows(DYLOX);
      await knex('lawn_protocol_products').where({ id: row.id }).update({ gates: JSON.stringify({ ...DYLOX_GATES, annualMaxApps: 1, minIntervalDays: 7 }) });
      await migration.down(knex);
      expect(Number((await countRows())[0].limit_value)).toBe(1);
      const after = await rows(DYLOX);
      expect(after[0].gates.annualMaxApps).toBe(1);
      expect(after[1].gates.annualMaxApps).toBe(3);
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION })).toHaveLength(0);
    });

    test("172000's down after this down removes everything it wrote", async () => {
      await migration.up(knex);
      await migration.down(knex);
      await first.down(knex);
      expect(await limits(DYLOX)).toHaveLength(0);
      for (const row of await rows(DYLOX)) expect(row.gates).toEqual(DYLOX_GATES);
      expect(await ours()).toHaveLength(0);
    });

    test("172000's down while this write is in place leaves the 2 and the gate at 2, removes its other rows, and restores nothing wrong", async () => {
      await migration.up(knex);
      await first.down(knex);
      expect(await numbers()).toEqual([[2, migration.LIMIT.description]]);
      expect(await byType(DYLOX, 'min_interval_days')).toHaveLength(0);
      expect(await byType(DYLOX, 'annual_max_rate')).toHaveLength(0);
      for (const row of await rows(DYLOX)) expect(row.gates).toEqual({ ...DYLOX_GATES, annualMaxApps: 2 });
      // This down still cleans up what it wrote.
      await migration.down(knex);
      expect(await numbers()).toEqual([[3, first.LIMITS[0].description]]);
    });
  });

  describe('rows that are not exactly what 172000 wrote', () => {
    beforeEach(async () => { await reset(); await first.up(knex); });

    test('a hand-edited 3 with another description is left, as are its gates when they are not 3', async () => {
      const [count] = await countRows();
      await knex('product_limits').where({ id: count.id }).update({ description: 'owner edit' });
      const [a, b] = await rows(DYLOX);
      await knex('lawn_protocol_products').where({ id: a.id }).update({ gates: JSON.stringify({ ...DYLOX_GATES, annualMaxApps: 4, minIntervalDays: 7 }) });
      await knex('lawn_protocol_products').where({ id: b.id }).update({ gates: JSON.stringify({ ...DYLOX_GATES, annualMaxApps: 3, minIntervalDays: 7, retired: true }) });
      await migration.up(knex);
      expect(await numbers()).toEqual([[3, 'owner edit']]);
      const [c, d] = await rows(DYLOX);
      expect(c.gates.annualMaxApps).toBe(4);
      expect(d.gates).toEqual({ ...DYLOX_GATES, annualMaxApps: 3, minIntervalDays: 7, retired: true });
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION })).toHaveLength(0);
    });

    test('a stricter hand-edited value is left', async () => {
      const [count] = await countRows();
      await knex('product_limits').where({ id: count.id }).update({ limit_value: 1 });
      await migration.up(knex);
      expect(Number((await countRows())[0].limit_value)).toBe(1);
    });

    test('a product with no count row at all gets one at 2, and down deletes it while unchanged', async () => {
      await knex('product_limits').where({ product_id: ids.dx, limit_type: 'annual_max_apps' }).del();
      await migration.up(knex);
      expect(await numbers()).toEqual([[2, migration.LIMIT.description]]);
      expect((await countRows())[0]).toMatchObject({ product_id: ids.dx, match_type: 'product', limit_unit: 'applications', severity: 'hard_block' });
      await migration.down(knex);
      expect(await countRows()).toHaveLength(0);
    });

    test('an inserted row somebody edited is not deleted by down', async () => {
      await knex('product_limits').where({ product_id: ids.dx, limit_type: 'annual_max_apps' }).del();
      await migration.up(knex);
      const [count] = await countRows();
      await knex('product_limits').where({ id: count.id }).update({ limit_value: 1 });
      await migration.down(knex);
      expect(Number((await countRows())[0].limit_value)).toBe(1);
    });
  });

  test('with no Dylox 6.2 G catalog row nothing is written', async () => {
    await reset({ dylox: false });
    const state = await snapshot();
    await migration.up(knex);
    expect(await snapshot()).toBe(state);
    await migration.down(knex);
    expect(await snapshot()).toBe(state);
  });
});
