const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { loadLawnCompletionContext } = require('../services/lawn-completion-defaults');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { getProtocolWindowContext } = require('../services/lawn-protocol-operating-layer');
const { recordLawnProtocolCompletion } = require('../services/lawn-protocol-completion');
const { recordServiceProductNutrients, nutrientTreatedSqft } = require('../services/nutrient-ledger');
const { etDateString, addETDays, parseETDateTime } = require('../utils/datetime-et');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
describeDb('appointment completion defaults through PostgreSQL', () => {
  let owned;
  let knex;
  let protocol;
  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals']) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    [protocol] = await knex('lawn_protocols').insert({ protocol_key: 'fixture_lawn', version: 'fixture1', name: 'Fixture protocol', status: 'active', grass_track: 'st_augustine', region: 'swfl' }).returning('*');
    await knex('lawn_protocol_windows').insert([6, 9].map(month => ({ lawn_protocol_id: protocol.id, month, window_key: `fixture_${month}`, title: `Fixture ${month}`, visit_type: 'fixture' })));
    const [product] = await knex('products_catalog').insert({ name: 'High Mn Combo', category: 'micronutrient', default_rate_per_1000: 3, rate_unit: 'fl oz', label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'fl oz', active: true }).returning('*');
    const window = await knex('lawn_protocol_windows').where({ lawn_protocol_id: protocol.id, month: 6 }).first();
    await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: product.id, product_name: product.name, role: 'micronutrient', application_mode: 'broadcast', default_in_plan: true, rate_per_1000: 3, rate_unit: 'fl oz' });
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
    await knex('municipality_ordinances').insert({ jurisdiction_name: 'Fixture September', jurisdiction_type: 'city', city: 'Fixture City', active: true, restricted_start_month: 9, restricted_start_day: 1, restricted_end_month: 9, restricted_end_day: 30, restricted_nitrogen: true, source_url: 'https://example.invalid/fixture', source_name: 'Synthetic test', source_checked_at: '2026-01-01' });
  });
  afterAll(async () => { if (owned) await owned.dispose(); });

  function joined(visit, f) { return { ...visit, ...Object.fromEntries(['address_line1', 'address_line2', 'city', 'state', 'zip'].map(key => [key, f.property[key]])) }; }
  async function plannedVisit(changes = {}) {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
    await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, grass_type: 'st_augustine', track_key: 'st_augustine', lawn_sqft: 4000 });
    const visit = await f.visit(0, { scheduled_date: '2026-09-07', lawn_protocol_key: protocol.protocol_key, lawn_protocol_version: protocol.version, lawn_protocol_window_key: 'fixture_6', ...changes });
    return { f, visit };
  }

  test('previous progress excludes other properties, future visits and unconfirmed attempts; current draft supplies planning context only', async () => {
    const f = await fixture(knex);
    const old = await f.assessment(await f.visit(-20));
    const previous = await f.assessment(await f.visit(-10));
    await f.assessment(await f.visit(2));
    await f.assessment(await f.visit(-3), { confirmed_by_tech: false });
    const [second] = await knex('customer_properties').insert({ customer_id: f.customerId }).returning('*');
    await f.assessment(await f.visit(-2, { property_id: second.id }));
    const visit = await f.visit(0);
    const draft = await f.assessment(visit, { confirmed_by_tech: false, stress_flags: { drought_stress: true } });
    const result = await loadLawnCompletionContext(joined(visit, f), knex);
    expect(result.history.rows.map(row => row.id)).toEqual([old.id, previous.id]);
    expect(result.history.current).toBeNull();
    expect(result.history.previous.id).toBe(previous.id);
    expect(result.latestAssessment.id).toBe(draft.id);
    expect(result.propertyMatchesProfile).toBe(true);
    expect(result.history.rows[0]).not.toHaveProperty('technician_notes');
  });

  test('installed record-linked assessment wins over the newer retake for current progress', async () => {
    const f = await fixture(knex);
    const prior = await f.assessment(await f.visit(-10));
    const visit = await f.visit(0);
    const record = await f.record(visit);
    const installed = await f.assessment(null, { service_record_id: record.id, property_id: f.property.id, turf_density: 50 });
    await f.assessment(visit, { turf_density: 99 });
    const result = await loadLawnCompletionContext(joined(visit, f), knex);
    expect(result.history.rows.map(row => row.id)).toEqual([prior.id, installed.id]);
    expect(result.history.current.id).toBe(installed.id);
    expect(result.history.current.date).toBe(etDateString());
  });

  test('a confirmed property stamp survives a second property while an ambiguous unfinished visit cannot prefill', async () => {
    const f = await fixture(knex);
    const visit = await f.visit(0, { property_id: null, service_address_line1: f.property.address_line1, service_address_city: f.property.city, service_address_zip: f.property.zip });
    const installed = await f.assessment(visit, { property_id: f.property.id });
    await knex('customer_properties').insert({ customer_id: f.customerId });
    const result = await loadLawnCompletionContext(joined(visit, f), knex);
    expect(result.propertyMatchesProfile).toBe(true);
    expect(result.history.current.id).toBe(installed.id);
    const unfinished = await f.visit(0, { property_id: null });
    expect((await loadLawnCompletionContext(joined(unfinished, f), knex)).propertyMatchesProfile).toBe(false);
  });

  test('an explicit second property gets its own history and no primary turf area', async () => {
    const f = await fixture(knex);
    const [second] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '200 Fixture Street', city: f.property.city, zip: f.property.zip }).returning('*');
    const previous = await f.assessment(await f.visit(-10, { property_id: second.id }));
    const visit = await f.visit(0, { property_id: second.id });
    const result = await loadLawnCompletionContext(joined(visit, f), knex);
    expect(result.history.previous.id).toBe(previous.id);
    expect(result.propertyMatchesProfile).toBe(false);
  });

  test('an empty reset does not fall back to a pre-reset previous assessment', async () => {
    const f = await fixture(knex);
    await f.assessment(await f.visit(-10));
    await knex('lawn_baseline_resets').insert({ customer_id: f.customerId, property_id: f.property.id, reset_by: 'fixture', reason: 'Fixture', created_at: parseETDateTime(`${etDateString(addETDays(new Date(), -5))}T12:00:00`) });
    const result = await loadLawnCompletionContext(joined(await f.visit(0), f), knex);
    expect(result.history.rows).toEqual([]);
    expect(result.latestAssessment).toBeNull();
  });

  test('rescheduling preserves the assigned window in the canonical planner, and area edits are visit-only', async () => {
    const { f, visit } = await plannedVisit();
    const options = { db: knex, completionDefaultsEnabled: true, includeCompletionDefaults: true };
    const plan = await buildPlanForService(visit.id, options);
    expect(plan.propertyGate.month).toBe('Jun');
    expect(plan.protocol.structured.window.key).toBe('fixture_6');
    expect(plan.propertyGate.activeOrdinanceWindows[0].jurisdictionName).toBe('Fixture September');
    expect(plan.completionDefaults.lawnSqft).toBe(4000);
    expect(plan.completionDefaults.items[0].mix.amount).toBe(12);
    const edited = await buildPlanForService(visit.id, { ...options, lawnSqft: 2500 });
    expect(edited.completionDefaults.lawnSqft).toBe(2500);
    expect(edited.completionDefaults.items[0].mix.amount).toBe(7.5);
    expect((await buildPlanForService(visit.id, { ...options, lawnSqft: null })).completionDefaults.lawnSqft).toBeNull();
    expect(Number((await knex('customer_turf_profiles').where({ customer_id: f.customerId }).first()).lawn_sqft)).toBe(4000);
    const legacy = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: false });
    expect(legacy.propertyGate.month).toBe('Sep');
    expect(legacy).not.toHaveProperty('completionDefaults');
  });

  test.each([{ lawn_protocol_version: 'missing' }, { lawn_protocol_window_key: 'missing' }])('unresolved appointment assignment stays unavailable: %j', async (changes) => {
    const { visit } = await plannedVisit(changes);
    const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, includeCompletionDefaults: true });
    expect(plan.completionDefaults.items).toEqual([]);
    expect(plan.propertyGate.blocks.map(row => row.code)).toContain('lawn_protocol_unresolved');
  });

  test('unknown grass cannot inherit St. Augustine defaults', async () => {
    const { f, visit } = await plannedVisit();
    await knex('customer_turf_profiles').where({ customer_id: f.customerId }).update({ grass_type: null, track_key: null });
    const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, includeCompletionDefaults: true });
    expect(plan.propertyGate.trackKey).toBeNull();
    expect(plan.completionDefaults.items).toEqual([]);
  });

  test('assigned protocol lookup executes the exact version query without falling through', async () => {
    const result = await getProtocolWindowContext(knex, { protocolKey: protocol.protocol_key, protocolVersion: protocol.version, windowKey: 'fixture_6', strict: true });
    expect(result.protocol.id).toBe(protocol.id);
    expect(result.window.month).toBe(6);
    expect(await getProtocolWindowContext(knex, { protocolKey: protocol.protocol_key, protocolVersion: 'missing', strict: true })).toBeNull();
  });

  test('publishing a new version preserves the upcoming visit assigned to the archived version', async () => {
    const { visit } = await plannedVisit();
    let published;
    try {
      await knex('lawn_protocols').where({ id: protocol.id }).update({ status: 'archived' });
      [published] = await knex('lawn_protocols').insert({ protocol_key: protocol.protocol_key, version: 'fixture2', name: 'Fixture replacement', status: 'active', grass_track: 'st_augustine', region: 'swfl' }).returning('*');
      const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, includeCompletionDefaults: true });
      expect(plan.protocol.structured).toMatchObject({ id: protocol.id, version: 'fixture1', status: 'archived' });
      expect(plan.completionDefaults.items[0].mix.amount).toBe(12);
      expect(plan.propertyGate.blocks.map(row => row.code)).not.toContain('lawn_protocol_unresolved');
    } finally {
      if (published) await knex('lawn_protocols').where({ id: published.id }).delete();
      await knex('lawn_protocols').where({ id: protocol.id }).update({ status: 'active' });
    }
  });

  test.each(['rate', 'product', 'missing-rate'])('archived %s drift withholds current-recipe suggestions while retaining the assignment', async drift => {
    const { visit } = await plannedVisit();
    const original = await knex('lawn_protocol_products').first();
    let replacement;
    try {
      await knex('lawn_protocols').where({ id: protocol.id }).update({ status: 'archived' });
      if (drift === 'product') {
        [replacement] = await knex('products_catalog').insert({ name: 'Archived fixture product', category: 'micronutrient', active: true }).returning('*');
      }
      await knex('lawn_protocol_products').where({ id: original.id }).update(drift === 'product'
        ? { product_id: replacement.id } : { rate_per_1000: drift === 'rate' ? 2 : null });
      const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, includeCompletionDefaults: true });
      expect(plan.protocol.structured).toMatchObject({ id: protocol.id, version: 'fixture1', status: 'archived' });
      expect(plan.propertyGate.blocks.map(row => row.code)).toContain('lawn_archived_recipe_unavailable');
      expect(plan.mixCalculator.items).toEqual([]);
      expect(plan.completionDefaults.items).toEqual([]);
      expect(plan.protocol.base).toEqual([]);
      expect(plan.completionDefaults.message).toContain('assigned archived recipe');
    } finally {
      await knex('lawn_protocol_products').where({ id: original.id }).update({ product_id: original.product_id, rate_per_1000: original.rate_per_1000 });
      if (replacement) await knex('products_catalog').where({ id: replacement.id }).delete();
      await knex('lawn_protocols').where({ id: protocol.id }).update({ status: 'active' });
    }
  });

  test('the canonical planner reads formulation for weighed spray concentrates', async () => {
    const { visit } = await plannedVisit();
    try {
      await knex('products_catalog').where({ name: 'High Mn Combo' }).update({ formulation: 'WDG', rate_unit: 'oz' });
      const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, includeCompletionDefaults: true });
      expect(plan.completionDefaults.items[0]).toMatchObject({ applicationMethod: 'broadcast_spray', product: { formulation: 'WDG' } });
    } finally {
      await knex('products_catalog').where({ name: 'High Mn Combo' }).update({ formulation: null, rate_unit: 'fl oz' });
    }
  });

  test.each([2500, null])('the visit area %p persists consistently through the planner and existing protocol/nutrient writers', async lawnSqft => {
    const { f, visit } = await plannedVisit();
    const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, lawnSqft });
    const record = await f.record(visit);
    const completion = await recordLawnProtocolCompletion(knex, {
      service: visit, serviceRecord: record, plan, completionInput: { treatedSqft: lawnSqft },
    });
    expect(plan.propertyGate.lawnSqft).toBe(lawnSqft);
    expect(plan.propertyGate.profileLawnSqft).toBe(4000);
    expect(completion.treated_sqft).toBe(lawnSqft);
    expect(completion.total_carrier_gal === null ? null : Number(completion.total_carrier_gal)).toBe(lawnSqft === null ? null : 2.5);
    const profile = await knex('customer_turf_profiles').where({ customer_id: f.customerId }).first();
    const [product] = await knex('products_catalog').insert({ name: 'Fixture nitrogen', category: 'fertilizer', analysis_n: 20 }).returning('*');
    const [actual] = await knex('service_products').insert({ service_record_id: record.id, product_id: product.id, product_name: product.name, total_amount: 5, amount_unit: 'lb' }).returning('*');
    const nutrient = await recordServiceProductNutrients(knex, { customerId: f.customerId, turfProfile: { ...profile, lawn_sqft: lawnSqft }, serviceRecord: record, serviceProduct: actual, product });
    expect(nutrient?.lawn_sqft || null).toBe(lawnSqft);
    if (lawnSqft) expect(Number(nutrient.n_applied_per_1000)).toBe(0.4);
    expect(Number((await knex('customer_turf_profiles').where({ id: profile.id }).first()).lawn_sqft)).toBe(4000);
  });

  test('each product nutrient entry uses its treated area while the protocol retains the visit area', async () => {
    const { f, visit } = await plannedVisit();
    const lawnSqft = 2500;
    const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, lawnSqft });
    const record = await f.record(visit);
    const completion = await recordLawnProtocolCompletion(knex, { service: visit, serviceRecord: record, plan, completionInput: { treatedSqft: lawnSqft } });
    expect(completion.treated_sqft).toBe(2500);
    const profile = await knex('customer_turf_profiles').where({ customer_id: f.customerId }).first();
    const [product] = await knex('products_catalog').insert({ name: 'Fixture partial fertilizer', category: 'fertilizer', analysis_n: 20, analysis_p: 5, analysis_k: 10 }).returning('*');
    for (const area of [1000, 2500, 1000.4]) {
      const [actual] = await knex('service_products').insert({ service_record_id: record.id, product_id: product.id, product_name: product.name, total_amount: 5, amount_unit: 'lb', area_value: area, area_unit: 'sqft' }).returning('*');
      const nutrient = await recordServiceProductNutrients(knex, {
        customerId: f.customerId, turfProfile: { ...profile, lawn_sqft: nutrientTreatedSqft(actual.area_value, actual.area_unit, lawnSqft) },
        serviceRecord: record, serviceProduct: actual, product,
      });
      expect(Number(actual.area_value)).toBe(area);
      expect(Number(nutrient.lawn_sqft)).toBe(Math.round(area));
      expect(Number(nutrient.n_applied_per_1000)).toBe(Math.round(area) === 1000 ? 1 : 0.4);
      expect(Number(nutrient.p_applied_per_1000)).toBe(Math.round(area) === 1000 ? 0.25 : 0.1);
      expect(Number(nutrient.k_applied_per_1000)).toBe(Math.round(area) === 1000 ? 0.5 : 0.2);
    }
    expect(Number((await knex('customer_turf_profiles').where({ id: profile.id }).first()).lawn_sqft)).toBe(4000);
  });

  describe('GATE_LAWN_ACTUALS_LEDGER', () => {
    afterEach(() => { delete process.env.GATE_LAWN_ACTUALS_LEDGER; });

    test('a one-time lawn visit records the frozen property and unattributed per-product actuals, idempotently', async () => {
      process.env.GATE_LAWN_ACTUALS_LEDGER = 'true';
      const f = await fixture(knex);
      const visit = await f.visit(0, { scheduled_date: '2026-09-07', service_type: 'Lawn one-time fertilization' });
      const record = await f.record(visit);
      let plan = null;
      try { plan = await buildPlanForService(visit.id, { db: knex }); } catch { plan = null; }
      const { lawnPlanAttributesVisit } = require('../services/lawn-completion-defaults');
      expect(plan === null || lawnPlanAttributesVisit(plan)).toBe(false);
      const [product] = await knex('products_catalog').insert({ name: 'Fixture one-time iron', category: 'micronutrient', rate_unit: 'fl oz', active: true }).returning('*');
      const [applied] = await knex('service_products').insert({
        service_record_id: record.id, product_id: product.id, product_name: product.name, application_rate: 3, rate_unit: 'fl oz',
        total_amount: 4.5, amount_unit: 'fl oz', application_method: 'spot_spray', application_area: 'Front yard', area_value: 1500, area_unit: 'sqft',
      }).returning('*');
      const args = {
        service: visit, serviceRecord: record, plan: null, serviceProducts: [applied],
        completionInput: { treatedSqft: null, incompleteVisit: true, skippedProducts: [
          { productId: product.id, productName: 'Fixture removed default' },
          // A product retired while the form was open: name kept, uuid FK NULL, no 500.
          { productId: '00000000-0000-4000-8000-00000000dead', productName: 'Fixture retired default' },
        ] },
      };
      const completion = await recordLawnProtocolCompletion(knex, args);
      expect(completion).toMatchObject({ property_id: visit.property_id, customer_id: f.customerId, protocol_key: null, window_key: null, treated_sqft: null, total_carrier_gal: null });
      expect(completion.metadata).toMatchObject({ attribution: 'none', treatedSqftSource: 'missing', incompleteVisit: true });
      const actuals = () => knex('lawn_protocol_product_actuals').where({ lawn_protocol_service_completion_id: completion.id }).orderBy('status').orderBy('product_name');
      const first = await actuals();
      expect(first.map(row => row.status)).toEqual(['applied', 'skipped', 'skipped']);
      expect(first[0]).toMatchObject({ service_product_id: applied.id, protocol_product_id: null });
      expect(first[0].metadata).toMatchObject({ areaValue: 1500, areaUnit: 'sqft', applicationArea: 'Front yard', applicationMethod: 'spot_spray' });
      expect(first[1]).toMatchObject({ product_name: 'Fixture removed default', product_id: product.id });
      expect(first[1].metadata).toEqual({ source: 'tech_closeout', reasonSupplied: false, substitution: null, unresolvedProductId: null });
      expect(first[2]).toMatchObject({ product_name: 'Fixture retired default', product_id: null });
      expect(first[2].metadata).toMatchObject({ unresolvedProductId: '00000000-0000-4000-8000-00000000dead' });
      // A retry re-runs the same writer: one completion row, the same three actual rows.
      const again = await recordLawnProtocolCompletion(knex, args);
      expect(again.id).toBe(completion.id);
      expect((await actuals()).length).toBe(3);
      expect(await knex('lawn_protocol_service_completions').where({ service_record_id: record.id }).count('id as count').first()).toMatchObject({ count: '1' });
    });

    test('gate off leaves a one-time lawn visit unrecorded while a member visit records attribution plus the property', async () => {
      const f = await fixture(knex);
      const oneTime = await f.visit(0, { scheduled_date: '2026-09-07' });
      expect(await recordLawnProtocolCompletion(knex, { service: oneTime, serviceRecord: await f.record(oneTime), plan: null, serviceProducts: [], completionInput: {} })).toBeNull();
      process.env.GATE_LAWN_ACTUALS_LEDGER = 'true';
      const { f: member, visit } = await plannedVisit();
      const plan = await buildPlanForService(visit.id, { db: knex, completionDefaultsEnabled: true, lawnSqft: 2500 });
      const completion = await recordLawnProtocolCompletion(knex, { service: visit, serviceRecord: await member.record(visit), plan, completionInput: { treatedSqft: 2500 } });
      expect(completion).toMatchObject({ property_id: visit.property_id, protocol_key: 'fixture_lawn', window_key: 'fixture_6', treated_sqft: 2500 });
      expect(completion.metadata).toMatchObject({ attribution: 'protocol', treatedSqftSource: 'visit' });
    });
  });
});
