// Lawn v13 final pass: the new limit entries of config/lawn-v13-count-caps.js evaluated by the real application-limits service on
// PostgreSQL (cloned schema), with no change to application-limits.js: Blindside yearly amount, Velista yearly amount, Artavia yearly
// amount, Dylox count of 3, Certainty 28 day interval. All gate-on only (GATE_LAWN_V13). Synthetic data only; self-skips without
// DATABASE_URL.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const caps = require('../config/lawn-v13-count-caps');
const applicationLimits = require('../services/application-limits');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const BLINDSIDE = 'Blindside Herbicide';
const CERTAINTY = 'Certainty Turf Herbicide';
const DYLOX = 'Dylox 6.2 G Granular Insecticide';
const VELISTA = 'Velista';
const ARTAVIA = 'Artavia 2 SC (Azoxy)';
const DAY = new Date('2026-05-12T16:00:00Z');

describeDb('v13 final pass limits through PostgreSQL', () => {
  const saved = process.env.GATE_LAWN_V13;
  let owned;
  let knex;
  const catalog = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['products_catalog', 'product_aliases', 'product_limits', 'property_application_history', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products']) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [name, unit, rate] of [[BLINDSIDE, 'oz', 0.149], [CERTAINTY, 'oz', 0.028], [DYLOX, 'lb', 3], [VELISTA, 'oz', 0.5], [ARTAVIA, 'fl oz', 0.38]]) {
      const [row] = await knex('products_catalog').insert({
        name, category: name === CERTAINTY || name === BLINDSIDE ? 'herbicide' : 'fungicide', default_rate_per_1000: rate, rate_unit: unit, label_verified_at: new Date(),
        inventory_on_hand: 1000, inventory_unit: unit, active: true,
      }).returning('*');
      catalog[name] = row;
    }
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });
  beforeEach(async () => {
    process.env.GATE_LAWN_V13 = 'true';
    caps.resetV13CapIdentity();
    await knex('property_application_history').del();
    await knex('lawn_protocol_products').del();
  });
  afterEach(() => { if (saved === undefined) delete process.env.GATE_LAWN_V13; else process.env.GATE_LAWN_V13 = saved; });

  // `rows`: [date, rate, unit] (rate null = unreadable).
  async function history(name, rows) {
    const { customerId } = await fixture(knex);
    for (const [date, rate, unit] of rows) {
      await knex('property_application_history').insert({ customer_id: customerId, product_id: catalog[name].id, application_date: date, application_rate: rate, rate_unit: unit });
    }
    return customerId;
  }
  const check = (customerId, name, opts = {}) => applicationLimits.checkLimits(customerId, catalog[name].id, DAY, knex, opts);
  const amountBlock = (result) => result.blocks.filter((b) => b.type === 'annual_max_rate');
  const dates = (count) => ['2026-01-05', '2026-01-26', '2026-02-16', '2026-03-09', '2026-03-30', '2026-04-20', '2026-04-27', '2026-05-04', '2026-05-08'].slice(0, count);

  describe('Blindside: 0.23 oz per 1,000 sq ft a year (label EPA 279-3411), one pass a year at the program rate of 0.149 oz', () => {
    test('a prior 0.149 oz pass blocks a second 0.149 oz pass (the yearly amount), and so does a second pass at 0.23 oz', async () => {
      const customerId = await history(BLINDSIDE, [['2026-01-05', 0.149, 'oz']]);
      const second = await check(customerId, BLINDSIDE, { proposed: { ratePer1000: 0.149, unit: 'oz' } });
      expect(second.allowed).toBe(false);
      // Blocked twice: by the count of 1 (effectiveCap) and by the amount.
      expect(second.blocks.map((b) => b.type).sort()).toEqual(['annual_max_apps', 'annual_max_rate']);
      expect(amountBlock(second)[0].message).toMatch(/total 64.8% of the yearly label amount \(0\.23 oz per 1,000 sq ft\).*brings it to 129.6% — THIS APPLICATION WOULD EXCEED IT/);
      const over = await check(customerId, BLINDSIDE, { proposed: { ratePer1000: 0.23, unit: 'oz' } });
      expect(over.allowed).toBe(false);
      expect(amountBlock(over)[0].message).toMatch(/THIS APPLICATION WOULD EXCEED IT/);
    });

    test('with no earlier pass, one pass at 0.149 oz and one at the label maximum 0.23 oz are both allowed', async () => {
      const customerId = await history(BLINDSIDE, []);
      expect((await check(customerId, BLINDSIDE, { proposed: { ratePer1000: 0.149, unit: 'oz' } })).allowed).toBe(true);
      expect((await check(customerId, BLINDSIDE, { proposed: { ratePer1000: 0.23, unit: 'oz' } })).allowed).toBe(true);
    });

    test('one pass at the label maximum (0.23 oz) fills the year', async () => {
      const customerId = await history(BLINDSIDE, [['2026-01-05', 0.23, 'oz']]);
      const result = await check(customerId, BLINDSIDE);
      expect(result.allowed).toBe(false);
      expect(amountBlock(result)[0].message).toMatch(/LIMIT REACHED/);
    });

    test('an earlier pass whose rate cannot be read counts as the whole year (0.23 oz)', async () => {
      const customerId = await history(BLINDSIDE, [['2026-01-05', null, null]]);
      const result = await check(customerId, BLINDSIDE, { proposed: { ratePer1000: 0.149, unit: 'oz' } });
      expect(result.allowed).toBe(false);
      expect(amountBlock(result)[0].message).toMatch(/total 100% of the yearly label amount.*1 earlier application sized at the standard rate/);
    });

    test('a proposal with no dose counts the staged row\'s 0.149 oz (64.8%); with no staged rate it counts the fixed 0.23 (100%)', async () => {
      const customerId = await history(BLINDSIDE, []);
      const fixed = await check(customerId, BLINDSIDE, { proposal: true });
      expect(fixed.allowed).toBe(true);
      expect(fixed.warnings.map((w) => w.message)).toContain('Blindside Herbicide: 0/1 this year — this would be the LAST allowed.');
      expect(fixed.warnings.find((w) => w.type === 'annual_max_rate').message).toMatch(/this application brings it to 100%/);
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: 'fixture_fp_limits', version: '2026.10-v13', name: 'Fixture', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 12, window_key: 'dec_fixture', title: 'dec', visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: catalog[BLINDSIDE].id, product_name: BLINDSIDE, role: 'post_emergent_spot', application_mode: 'spot', rate_per_1000: 0.149, rate_unit: 'oz', default_in_plan: false });
      try {
        const staged = await check(customerId, BLINDSIDE, { proposal: true });
        expect(staged.allowed).toBe(true);
        // 0.149 of 0.23 is 64.8%: below the warning threshold, so the fixed 0.23 (100%) is not what was counted.
        expect(staged.warnings.some((w) => w.type === 'annual_max_rate')).toBe(false);
      } finally {
        await knex('lawn_protocol_products').del();
        await knex('lawn_protocol_windows').del();
        await knex('lawn_protocols').del();
      }
    });

    test('the count of 1 blocks a second pass even when the amount would fit (a small earlier pass)', async () => {
      const customerId = await history(BLINDSIDE, [['2026-01-05', 0.05, 'oz']]);
      const result = await check(customerId, BLINDSIDE, { proposed: { ratePer1000: 0.05, unit: 'oz' } });
      expect(result.allowed).toBe(false);
      expect(result.blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
      expect(result.blocks[0].message).toMatch(/1/);
    });

    test('the count limit row the app reads says 1 for Blindside and still 2 for Certainty', async () => {
      const count = async (name) => (await caps.applyV13CountCaps(knex, { id: catalog[name].id, name }, [], catalog[name].id)).find((l) => l.limit_type === 'annual_max_apps').limit_value;
      expect(await count(BLINDSIDE)).toBe(1);
      expect(await count(CERTAINTY)).toBe(2);
    });
  });

  describe('Velista: 2.2 oz per 1,000 sq ft a year (label EPA 100-1534)', () => {
    test('three passes at 0.5 oz leave room for 0.5 and not for 0.8', async () => {
      const customerId = await history(VELISTA, dates(3).map((d) => [d, 0.5, 'oz']));
      expect((await check(customerId, VELISTA, { proposed: { ratePer1000: 0.5, unit: 'oz' } })).allowed).toBe(true);
      const over = await check(customerId, VELISTA, { proposed: { ratePer1000: 0.8, unit: 'oz' } });
      expect(over.allowed).toBe(false);
      expect(amountBlock(over)[0].message).toMatch(/total 68\.2% of the yearly label amount \(2\.2 oz per 1,000 sq ft\).*THIS APPLICATION WOULD EXCEED IT/);
    });

    test('an unreadable earlier pass counts as 0.7 oz (the label\'s single-application maximum): four of them fill the year, three plus a proposal without a dose exceed it', async () => {
      const four = await history(VELISTA, dates(4).map((d) => [d, null, null]));
      expect(amountBlock(await check(four, VELISTA))[0].message).toMatch(/LIMIT REACHED/);
      const three = await history(VELISTA, dates(3).map((d) => [d, null, null]));
      expect((await check(three, VELISTA)).allowed).toBe(true);
      expect((await check(three, VELISTA, { proposal: true })).allowed).toBe(false);
    });

    test('no count row exists for Velista: a seventh pass at 0.1 oz is not blocked by a count', async () => {
      const customerId = await history(VELISTA, dates(7).map((d) => [d, 0.1, 'oz']));
      const result = await check(customerId, VELISTA, { proposed: { ratePer1000: 0.1, unit: 'oz' } });
      expect(result.allowed).toBe(true);
      expect(result.blocks.map((b) => b.type)).not.toContain('annual_max_apps');
    });
  });

  describe('Artavia: 7.1 fl oz per 1,000 sq ft a year (label: 9.6 quarts per acre)', () => {
    test('eight passes at 0.77 fl oz leave room for a ninth; nine do not', async () => {
      const eight = await history(ARTAVIA, dates(8).map((d) => [d, 0.77, 'fl oz']));
      expect((await check(eight, ARTAVIA, { proposed: { ratePer1000: 0.77, unit: 'fl oz' } })).allowed).toBe(true);
      const nine = await history(ARTAVIA, dates(9).map((d) => [d, 0.77, 'fl oz']));
      const result = await check(nine, ARTAVIA, { proposed: { ratePer1000: 0.77, unit: 'fl oz' } });
      expect(result.allowed).toBe(false);
      expect(amountBlock(result)[0].message).toMatch(/yearly label amount \(7\.1 fl oz per 1,000 sq ft\)/);
    });

    test('a large patch pass at the catalog 0.38 fl oz counts as 0.38, and an unreadable pass counts as 0.77', async () => {
      const half = await history(ARTAVIA, dates(9).map((d) => [d, 0.38, 'fl oz']));
      expect((await check(half, ARTAVIA)).allowed).toBe(true);
      // Nine unreadable passes count 9 x 0.77 = 6.93 (97.6%, a warning); a tenth fills the year.
      const nine = await history(ARTAVIA, dates(9).map((d) => [d, null, null]));
      const warned = await check(nine, ARTAVIA);
      expect(warned.allowed).toBe(true);
      expect(warned.warnings.map((w) => w.message).join(' ')).toMatch(/total 97\.6%/);
      const ten = await history(ARTAVIA, [...dates(9), '2026-05-10'].map((d) => [d, null, null]));
      expect(amountBlock(await check(ten, ARTAVIA))[0].message).toMatch(/LIMIT REACHED/);
    });
  });

  describe('Dylox 6.2 G: 3 applications a calendar year (label)', () => {
    test('two prior applications allow a third (the last), three block a fourth', async () => {
      const two = await history(DYLOX, [['2026-03-01', 3, 'lb'], ['2026-04-01', 3, 'lb']]);
      const third = await check(two, DYLOX);
      expect(third.allowed).toBe(true);
      expect(third.warnings.map((w) => w.message).join(' ')).toMatch(/this would be the LAST allowed/);
      const three = await history(DYLOX, [['2026-02-01', 3, 'lb'], ['2026-03-01', 3, 'lb'], ['2026-04-01', 3, 'lb']]);
      const fourth = await check(three, DYLOX);
      expect(fourth.allowed).toBe(false);
      expect(fourth.blocks[0].message).toMatch(/3\/3 applications this year — LIMIT REACHED/);
    });

    test('last year\'s applications do not count', async () => {
      const customerId = await history(DYLOX, [['2025-03-01', 3, 'lb'], ['2025-04-01', 3, 'lb'], ['2025-05-01', 3, 'lb']]);
      expect((await check(customerId, DYLOX)).allowed).toBe(true);
    });
  });

  describe('Certainty: 28 days between applications (label: a sequential application 4 or more weeks after the first)', () => {
    test('20 days after the last pass is blocked, 28 days is allowed; the count of 2 is unchanged', async () => {
      const soon = await history(CERTAINTY, [['2026-04-22', 0.028, 'oz']]);
      const blocked = await check(soon, CERTAINTY);
      expect(blocked.allowed).toBe(false);
      expect(blocked.blocks.map((b) => b.type)).toEqual(['min_interval_days']);
      expect(blocked.blocks[0].message).toMatch(/only 20 days since last app \(min 28\)/);
      const ok = await history(CERTAINTY, [['2026-04-14', 0.028, 'oz']]);
      expect((await check(ok, CERTAINTY)).allowed).toBe(true);
      const two = await history(CERTAINTY, [['2026-01-05', 0.028, 'oz'], ['2026-02-16', 0.028, 'oz']]);
      expect((await check(two, CERTAINTY)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
    });

    test('the gap spans the new year (a December pass holds a January pass 21 days later)', async () => {
      const customerId = await history(CERTAINTY, [['2025-12-30', 0.028, 'oz']]);
      const result = await applicationLimits.checkLimits(customerId, catalog[CERTAINTY].id, new Date('2026-01-20T16:00:00Z'), knex, {});
      expect(result.blocks.map((b) => b.type)).toEqual(['min_interval_days']);
      expect(result.blocks[0].message).toMatch(/only 21 days since last app \(min 28\)/);
    });
  });

  test('gate off: none of the new limits applies', async () => {
    const blindside = await history(BLINDSIDE, [['2026-01-05', 0.23, 'oz']]);
    const velista = await history(VELISTA, dates(4).map((d) => [d, null, null]));
    const dylox = await history(DYLOX, [['2026-02-01', 3, 'lb'], ['2026-03-01', 3, 'lb'], ['2026-04-01', 3, 'lb']]);
    const certainty = await history(CERTAINTY, [['2026-05-10', 0.028, 'oz']]);
    delete process.env.GATE_LAWN_V13;
    for (const [customerId, name] of [[blindside, BLINDSIDE], [velista, VELISTA], [dylox, DYLOX], [certainty, CERTAINTY]]) {
      const result = await check(customerId, name);
      expect({ name, blocks: result.blocks }).toEqual({ name, blocks: [] });
    }
  });

  describe('the closeout audit (auditHardCountLimits) reads the same entries', () => {
    const audit = (customerId, name) => applicationLimits.auditHardCountLimits(customerId, catalog[name].id, '2026-05-12', knex, {});

    test('Velista over its yearly amount, Blindside over its yearly amount, Dylox at its count, Certainty inside its gap', async () => {
      const velista = await history(VELISTA, dates(4).map((d) => [d, 0.7, 'oz']));
      expect((await audit(velista, VELISTA)).map((v) => v.type)).toEqual(['annual_max_rate']);
      const blindside = await history(BLINDSIDE, [['2026-01-05', 0.23, 'oz']]);
      expect((await audit(blindside, BLINDSIDE)).map((v) => v.type).sort()).toEqual(['annual_max_apps', 'annual_max_rate']);
      const dylox = await history(DYLOX, [['2026-02-01', 3, 'lb'], ['2026-03-01', 3, 'lb'], ['2026-04-01', 3, 'lb']]);
      expect((await audit(dylox, DYLOX)).map((v) => v.type)).toEqual(['annual_max_apps']);
      const certainty = await history(CERTAINTY, [['2026-05-01', 0.028, 'oz']]);
      expect((await audit(certainty, CERTAINTY)).map((v) => v.type)).toEqual(['min_interval_days']);
    });

    test('inside every limit nothing is flagged', async () => {
      const velista = await history(VELISTA, dates(3).map((d) => [d, 0.5, 'oz']));
      expect(await audit(velista, VELISTA)).toEqual([]);
      const artavia = await history(ARTAVIA, dates(5).map((d) => [d, 0.77, 'fl oz']));
      expect(await audit(artavia, ARTAVIA)).toEqual([]);
    });
  });

  describe('identity: the new entries resolve by the exact catalog name, else an alias', () => {
    test('the id map holds the five products of this fixture, and an alias finds a renamed product', async () => {
      const ids = await caps.capIdMap(knex);
      expect([...ids.values()].map((entry) => entry.name).sort()).toEqual([BLINDSIDE, CERTAINTY, DYLOX, VELISTA, ARTAVIA].sort());
      await knex('products_catalog').where({ id: catalog[VELISTA].id }).update({ name: 'Velista renamed away' });
      await knex('product_aliases').insert({ product_id: catalog[VELISTA].id, alias_name: VELISTA });
      try {
        caps.resetV13CapIdentity();
        expect((await caps.v13CapEntryFor(knex, catalog[VELISTA].id, 'Velista renamed away')).name).toBe(VELISTA);
      } finally {
        await knex('product_aliases').del();
        await knex('products_catalog').where({ id: catalog[VELISTA].id }).update({ name: VELISTA });
        caps.resetV13CapIdentity();
      }
    });

    test('a catalog rename with no alias keeps the limit: the staged protocol row holds the product id (Dylox, Velista, Artavia carry no annualMaxApps)', async () => {
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: 'fixture_fp_rename', version: '2026.10-v13', name: 'Fixture', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 6, window_key: 'jun_fixture', title: 'jun', visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      for (const name of [DYLOX, VELISTA, ARTAVIA]) {
        await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: catalog[name].id, product_name: name, role: 'spot', application_mode: 'spot', default_in_plan: false });
        await knex('products_catalog').where({ id: catalog[name].id }).update({ name: `${name} (renamed)` });
      }
      try {
        caps.resetV13CapIdentity();
        for (const name of [DYLOX, VELISTA, ARTAVIA]) {
          expect((await caps.v13CapEntryFor(knex, catalog[name].id, `${name} (renamed)`)).name).toBe(name);
        }
        const three = await history(DYLOX, [['2026-02-01', 3, 'lb'], ['2026-03-01', 3, 'lb'], ['2026-04-01', 3, 'lb']]);
        expect((await check(three, DYLOX)).allowed).toBe(false);
      } finally {
        await knex('lawn_protocol_products').del();
        await knex('lawn_protocol_windows').del();
        await knex('lawn_protocols').del();
        for (const name of [DYLOX, VELISTA, ARTAVIA]) await knex('products_catalog').where({ id: catalog[name].id }).update({ name });
        caps.resetV13CapIdentity();
      }
    });
  });
});
