// Lawn v13 yearly count caps for Arena, Celsius, Certainty and Blindside
// (migration 20261007170000, owner 2026-10-06): insert-only, by explicit product id,
// and enforced per property through the real plan engine. Own cloned schema; synthetic data only.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261007170000_lawn_v13_count_caps');
const wording = require('../models/migrations/20261007171000_lawn_v13_count_caps_wording');
const restore = require('../models/migrations/20261007172000_lawn_v13_celsius_cap_v13_only');
const { DIMENSION } = require('../models/migrations/20261006150000_lawn_v13_april_9x_branch');
const { submittedProductLimitFindings } = require('../services/complete-scheduled-service');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION } = require('../services/lawn-program');
const v13Recipe = require('../config/lawn-protocol-v13.json');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const NAMES = migration.CAPS.map((cap) => cap.name);
const [ARENA, CELSIUS, CERTAINTY, BLINDSIDE] = NAMES;
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY'];

describe('the recipe text (no database)', () => {
  test('every track states the Arena, Celsius + Certainty and Blindside counts', () => {
    for (const track of Object.values(v13Recipe)) {
      expect(track.notes.join('\n')).toContain('Arena: up to 2 applications per lawn per year (app-enforced); never treat the same area twice (tech rule; label 0.4 lb clothianidin per acre per year)');
      const safety = track.safety_rules.join('\n');
      expect(safety).toContain('Celsius, Certainty and Blindside: up to 2 applications per lawn per year each');
      expect(safety).not.toMatch(/per spot/);
    }
  });

  test('the migration writes 2 for each of the four products, by exact catalog name', () => {
    expect(NAMES).toEqual(['Arena 50 WDG', 'Celsius WG', 'Certainty Turf Herbicide', 'Blindside Herbicide']);
    expect(migration.CAPS.map((cap) => cap.limit_value)).toEqual([2, 2, 2, 2]);
  });
});

describeDb('v13 count caps through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  const catalog = {};

  async function clone(table) {
    await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
    const columns = await knex(table).columnInfo();
    if (String(columns.id?.defaultValue || '').includes('nextval(')) {
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
    }
  }
  const product = async (name, fields = {}) => {
    const [row] = await knex('products_catalog').insert({
      name, category: 'herbicide', default_rate_per_1000: 0.1, rate_unit: 'oz', label_verified_at: new Date(),
      inventory_on_hand: 1000, inventory_unit: 'oz', active: true, ...fields,
    }).returning('*');
    catalog[name] = row;
    return row;
  };
  const limitsOf = (name, type = 'annual_max_apps') => knex('product_limits').where({ product_id: catalog[name].id, limit_type: type }).orderBy('id');
  const allLimits = () => knex('product_limits').orderBy('id');

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'lawn_protocol_audit_log', 'product_limits', 'property_application_history']) {
      await clone(table);
    }
    await product('Tetrino Insecticide', { category: 'insecticide', default_rate_per_1000: 0.367, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    await product(ARENA, { category: 'insecticide', default_rate_per_1000: 0.29 });
    await product(CELSIUS, { default_rate_per_1000: 0.085 });
    await product(CERTAINTY, { default_rate_per_1000: 0.028 });
    await product(BLINDSIDE);
    const surfactant = await product('LESCO 90/10 Nonionic Surfactant', { category: 'adjuvant', default_rate_per_1000: 0.25, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    const [staged] = await knex('lawn_protocols').insert({ protocol_key: 'fixture_v13_count_caps', version: LAWN_V13_VERSION, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
    const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: staged.id, month: 5, window_key: 'may_v13', title: 'may_v13', visit_type: 'fixture' }).returning('*');
    await knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: window.id, product_id: catalog['Tetrino Insecticide'].id, product_name: 'Tetrino Insecticide', role: 'insecticide', application_mode: 'broadcast',
      default_in_plan: true, rate_per_1000: 0.367, rate_unit: 'fl oz', gates: JSON.stringify({}),
    });
    for (const [row, rate, unit, gates] of [[catalog[ARENA], null, 'label_rate', { trigger: 'chinch' }], [catalog[CELSIUS], 0.085, 'oz', {}], [surfactant, null, 'label_rate', { concentration: '0.25% v/v' }]]) {
      await knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: window.id, product_id: row.id, product_name: row.name, role: 'post_emergent_spot', application_mode: 'spot',
        default_in_plan: false, rate_per_1000: rate, rate_unit: unit, carrier_gal_per_1000: 4, gates: JSON.stringify(gates),
      });
    }
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  describe('the migration', () => {
    beforeEach(async () => {
      await knex('product_limits').del(); await knex('product_aliases').del();
      jest.spyOn(console, 'log').mockImplementation(() => {});
    });
    afterEach(() => jest.restoreAllMocks());

    test('inserts one hard-block product row of 2 per product, nothing else', async () => {
      await migration.up(knex);
      const rows = await allLimits();
      expect(rows).toHaveLength(4);
      for (const name of NAMES) {
        const [row] = await limitsOf(name);
        expect(row).toMatchObject({ match_type: 'product', limit_type: 'annual_max_apps', limit_unit: 'applications', severity: 'hard_block' });
        expect(Number(row.limit_value)).toBe(2);
        expect(row.description).toContain(name);
      }
      expect((await limitsOf(ARENA))[0].description).toMatch(/never the same area twice/);
      // The frozen 170000 text; the wording migration below rewrites it.
    });

    test('a product that already has an annual_max_apps row keeps it exactly (value, unit, severity, description); the other products are still added', async () => {
      const [celsius] = await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 3, limit_unit: 'applications', severity: 'hard_block', description: 'Celsius WG: max 3 applications per year per property.' }).returning('*');
      const [certainty] = await knex('product_limits').insert({ product_id: catalog[CERTAINTY].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 5, limit_unit: 'apps', severity: 'warning', description: 'admin row' }).returning('*');
      await migration.up(knex);
      expect(await limitsOf(CELSIUS)).toEqual([celsius]);
      expect(await limitsOf(CERTAINTY)).toEqual([certainty]);
      expect(await limitsOf(ARENA)).toHaveLength(1);
      expect(await limitsOf(BLINDSIDE)).toHaveLength(1);
      expect(await allLimits()).toHaveLength(4);
    });

    test('other limit types on the product do not count: Celsius with only an interval row still gets its count cap', async () => {
      await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'min_interval_days', limit_value: 60, limit_unit: 'days', severity: 'warning', description: 'interval' });
      await migration.up(knex);
      expect(await limitsOf(CELSIUS)).toHaveLength(1);
      expect(await limitsOf(CELSIUS, 'min_interval_days')).toHaveLength(1);
    });

    test('a product missing from the catalog is skipped without an error; an exact alias resolves', async () => {
      await knex('products_catalog').where({ id: catalog[BLINDSIDE].id }).update({ name: 'Blindside renamed away' });
      await knex('products_catalog').where({ id: catalog[ARENA].id }).update({ name: 'Arena renamed away' });
      await knex('product_aliases').insert({ product_id: catalog[ARENA].id, alias_name: ARENA });
      try {
        await expect(migration.up(knex)).resolves.toBeUndefined();
        expect(console.log.mock.calls.flat().join('\n')).toMatch(/no catalog row or alias for Blindside Herbicide/);
      } finally {
        await knex('products_catalog').where({ id: catalog[BLINDSIDE].id }).update({ name: BLINDSIDE });
        await knex('products_catalog').where({ id: catalog[ARENA].id }).update({ name: ARENA });
      }
      expect(await limitsOf(ARENA)).toHaveLength(1);
      expect(await limitsOf(BLINDSIDE)).toHaveLength(0);
      expect(await allLimits()).toHaveLength(3);
    });

    test('a second up writes nothing', async () => {
      await migration.up(knex);
      const before = await allLimits();
      await migration.up(knex);
      expect(await allLimits()).toEqual(before);
    });

    test('down removes only the rows it wrote; admin rows, a row edited since and rows of other types stay; up again restores', async () => {
      const [admin] = await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 3, limit_unit: 'applications', severity: 'hard_block', description: 'Celsius WG: max 3 applications per year per property.' }).returning('*');
      const [interval] = await knex('product_limits').insert({ product_id: catalog[ARENA].id, match_type: 'product', limit_type: 'min_interval_days', limit_value: 14, limit_unit: 'days', severity: 'warning', description: 'interval' }).returning('*');
      await migration.up(knex);
      // Someone raised Blindside to 3 and Certainty to a warning after the deploy: both stay.
      await knex('product_limits').where({ product_id: catalog[BLINDSIDE].id, limit_type: 'annual_max_apps' }).update({ limit_value: 3 });
      await knex('product_limits').where({ product_id: catalog[CERTAINTY].id, limit_type: 'annual_max_apps' }).update({ severity: 'warning' });
      await migration.down(knex);
      const left = await allLimits();
      expect(left.map((r) => r.id).sort()).toEqual([admin.id, interval.id, ...(await limitsOf(BLINDSIDE)).map((r) => r.id), ...(await limitsOf(CERTAINTY)).map((r) => r.id)].sort());
      expect(await limitsOf(CELSIUS)).toEqual([admin]);
      expect(await limitsOf(ARENA)).toHaveLength(0);
      // Restore the two edited rows to what up wrote and take the full round trip.
      await knex('product_limits').where({ product_id: catalog[BLINDSIDE].id }).del();
      await knex('product_limits').where({ product_id: catalog[CERTAINTY].id }).del();
      await migration.up(knex);
      expect(await allLimits()).toHaveLength(5);
      await migration.down(knex);
      expect((await allLimits()).map((r) => r.id).sort()).toEqual([admin.id, interval.id].sort());
    });

    describe('the Celsius seed row (3 -> 2, owner 2026-10-06)', () => {
      const { CELSIUS_SEED, CELSIUS_LOWERED } = migration;
      const seed = (changes = {}) => knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...CELSIUS_SEED, ...changes }).returning('*').then(([row]) => row);
      const fields = (row) => ({ product_id: row.product_id, match_type: row.match_type, limit_type: row.limit_type, limit_value: Number(row.limit_value), limit_unit: row.limit_unit, severity: row.severity, description: row.description });

      test('the row that still equals the seed is lowered to 2 in place (same id, same unit and severity); no second Celsius row is added', async () => {
        const before = await seed();
        await migration.up(knex);
        const rows = await limitsOf(CELSIUS);
        expect(rows).toHaveLength(1);
        expect(rows[0].id).toBe(before.id);
        expect(fields(rows[0])).toEqual({ ...fields(before), limit_value: 2, description: CELSIUS_LOWERED.description });
        expect(await allLimits()).toHaveLength(4);
      });

      test.each([
        ['another value', { limit_value: 4 }],
        ['an edited description', { description: 'Celsius WG: max 3 applications per year. Admin note.' }],
        ['a softer severity', { severity: 'warning' }],
        ['another unit', { limit_unit: 'apps' }],
      ])('an admin-edited row (%s) is left exactly as it is and logged', async (_label, changes) => {
        const before = await seed(changes);
        await migration.up(knex);
        expect(await limitsOf(CELSIUS)).toEqual([before]);
        expect(console.log.mock.calls.flat().join('\n')).toMatch(/Celsius WG already has annual_max_apps/);
      });

      test('a second up changes nothing more', async () => {
        await seed();
        await migration.up(knex);
        const once = await allLimits();
        await migration.up(knex);
        expect(await allLimits()).toEqual(once);
      });

      test('down restores 3 and the seed description while the row still holds the lowered values; up again lowers it', async () => {
        const before = await seed();
        await migration.up(knex);
        await migration.down(knex);
        const [restored] = await limitsOf(CELSIUS);
        expect(restored.id).toBe(before.id);
        expect(fields(restored)).toEqual(fields(before));
        expect(await allLimits()).toHaveLength(1);
        await migration.up(knex);
        expect(Number((await limitsOf(CELSIUS))[0].limit_value)).toBe(2);
      });

      test('down leaves the row alone once someone edited it after the deploy (value or description)', async () => {
        await seed();
        await migration.up(knex);
        await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 1 });
        await migration.down(knex);
        expect(Number((await limitsOf(CELSIUS))[0].limit_value)).toBe(1);
        expect((await limitsOf(CELSIUS))[0].description).toBe(CELSIUS_LOWERED.description);

        await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 2, description: 'admin rewrote this' });
        await migration.down(knex);
        expect((await limitsOf(CELSIUS))[0]).toMatchObject({ description: 'admin rewrote this' });
        expect(Number((await limitsOf(CELSIUS))[0].limit_value)).toBe(2);
      });

      test('a Celsius row this inserted (no seed row) is deleted by down, never "restored" to 3', async () => {
        await migration.up(knex);
        expect(await limitsOf(CELSIUS)).toHaveLength(1);
        await migration.down(knex);
        expect(await limitsOf(CELSIUS)).toHaveLength(0);
      });
    });
  });

  describe('the property-wide wording (20261007171000)', () => {
    beforeEach(async () => {
      await knex('product_limits').del(); await knex('product_aliases').del();
      jest.spyOn(console, 'log').mockImplementation(() => {});
    });
    afterEach(() => jest.restoreAllMocks());
    const descriptions = async () => Object.fromEntries((await allLimits()).map((r) => [NAMES.find((n) => catalog[n].id === r.product_id), r.description]));
    const fieldsOf = (r) => ({ id: r.id, product_id: r.product_id, match_type: r.match_type, limit_type: r.limit_type, limit_value: Number(r.limit_value), limit_unit: r.limit_unit, severity: r.severity });

    test('rewrites only the descriptions: every row now says per lawn per year, none says per spot; Arena keeps the tech rule', async () => {
      await migration.up(knex);
      const before = (await allLimits()).map(fieldsOf);
      await wording.up(knex);
      expect((await allLimits()).map(fieldsOf)).toEqual(before);
      const after = await descriptions();
      for (const name of NAMES) {
        expect(after[name]).toMatch(/max 2 applications per lawn per year/);
        expect(after[name]).not.toMatch(/per spot|passes/);
      }
      expect(after[ARENA]).toMatch(/Never treat the same area twice \(tech rule, not enforced by the app\)/);
      expect(after[ARENA]).toMatch(/0\.4 lb clothianidin per acre per year/);
    });

    test('the lowered Celsius seed row gets the property-wide text too; a second up changes nothing; down restores the 170000 text', async () => {
      await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...migration.CELSIUS_SEED });
      await migration.up(knex);
      const lowered = await allLimits();
      await wording.up(knex);
      const once = await allLimits();
      expect(once.find((r) => r.product_id === catalog[CELSIUS].id).description).toBe('Celsius WG: max 2 applications per lawn per year (owner 2026-10-06; lowered from 3).');
      await wording.up(knex);
      expect(await allLimits()).toEqual(once);
      await wording.down(knex);
      expect((await allLimits()).map((r) => [r.id, r.description])).toEqual(lowered.map((r) => [r.id, r.description]));
    });

    test('an admin-edited row, or one with another value, is left alone; down touches only rows still holding the new text', async () => {
      await migration.up(knex);
      await knex('product_limits').where({ product_id: catalog[CERTAINTY].id }).update({ description: 'admin wrote this' });
      await knex('product_limits').where({ product_id: catalog[BLINDSIDE].id }).update({ limit_value: 3 });
      const before = await allLimits();
      await wording.up(knex);
      const after = await allLimits();
      for (const name of [CERTAINTY, BLINDSIDE]) {
        expect(after.find((r) => r.product_id === catalog[name].id)).toEqual(before.find((r) => r.product_id === catalog[name].id));
      }
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ description: 'admin rewrote Celsius' });
      await wording.down(knex);
      expect((await limitsOf(CELSIUS))[0].description).toBe('admin rewrote Celsius');
      expect((await limitsOf(ARENA))[0].description).toBe(migration.CAPS[0].description);
    });

    test('a row an admin owns (not one of the 170000 texts) is never rewritten', async () => {
      const [admin] = await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 2, limit_unit: 'applications', severity: 'hard_block', description: 'Celsius WG: max 2 passes per spot per year (admin).' }).returning('*');
      await wording.up(knex);
      expect(await limitsOf(CELSIUS)).toEqual([admin]);
    });
  });

  describe('the Celsius cap of 2 lives behind the v13 gate (20261007172000)', () => {
    const applicationLimits = require('../services/application-limits');
    const { effectiveCountCap } = require('../config/lawn-v13-count-caps');
    const celsiusRows = () => limitsOf(CELSIUS);
    const audits = () => knex('lawn_protocol_audit_log').where({ action: 'v13_celsius_cap_restore' });
    beforeEach(async () => {
      await knex('product_limits').del(); await knex('product_aliases').del(); await knex('lawn_protocol_audit_log').del();
      jest.spyOn(console, 'log').mockImplementation(() => {});
    });
    afterEach(() => jest.restoreAllMocks());

    test('the Celsius row goes back to the exact compliance-seed values and description; the other three caps are untouched; each restore is audited', async () => {
      const [seeded] = await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...migration.CELSIUS_SEED }).returning('*');
      await migration.up(knex); await wording.up(knex);
      const others = (await allLimits()).filter((r) => r.product_id !== catalog[CELSIUS].id);
      expect(Number((await celsiusRows())[0].limit_value)).toBe(2);
      await restore.up(knex);
      const [row] = await celsiusRows();
      expect(row.id).toBe(seeded.id);
      expect({ match_type: row.match_type, limit_type: row.limit_type, limit_value: Number(row.limit_value), limit_unit: row.limit_unit, severity: row.severity, description: row.description }).toEqual(migration.CELSIUS_SEED);
      expect((await allLimits()).filter((r) => r.product_id !== catalog[CELSIUS].id)).toEqual(others);
      const logged = await audits();
      expect(logged).toHaveLength(1);
      expect(typeof logged[0].before_snapshot === 'string' ? JSON.parse(logged[0].before_snapshot) : logged[0].before_snapshot).toMatchObject({ limitId: seeded.id, limit_value: 2 });
      await restore.up(knex); // idempotent
      expect(await audits()).toHaveLength(1);
    });

    test('a Celsius row 170000 inserted (no seed existed) is restored to the seed values too', async () => {
      await migration.up(knex); await wording.up(knex);
      await restore.up(knex);
      expect(Number((await celsiusRows())[0].limit_value)).toBe(3);
      expect((await celsiusRows())[0].description).toBe(migration.CELSIUS_SEED.description);
    });

    test('an admin-edited Celsius row is never touched; down re-applies the 2 only to a row still equal to the seed, then spends its audit row', async () => {
      await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...migration.CELSIUS_SEED });
      await migration.up(knex); await wording.up(knex);
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 1 });
      await restore.up(knex);
      expect(Number((await celsiusRows())[0].limit_value)).toBe(1);
      expect(await audits()).toHaveLength(0);
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 2 });
      await restore.up(knex);
      expect(Number((await celsiusRows())[0].limit_value)).toBe(3);
      // Edited after the restore: down leaves it.
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 4 });
      await restore.down(knex);
      expect(Number((await celsiusRows())[0].limit_value)).toBe(4);
      expect(await audits()).toHaveLength(0);
      // Untouched since: down puts back the 2 and the 171000 text.
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 2, description: 'Celsius WG: max 2 applications per lawn per year (owner 2026-10-06; lowered from 3).' });
      await restore.up(knex);
      await restore.down(knex);
      expect(Number((await celsiusRows())[0].limit_value)).toBe(2);
      expect((await celsiusRows())[0].description).toBe('Celsius WG: max 2 applications per lawn per year (owner 2026-10-06; lowered from 3).');
    });

    test('the override lowers Celsius only, only while the gate is on, and never raises a value', () => {
      expect(effectiveCountCap('Celsius WG', 3, true)).toBe(2);
      expect(effectiveCountCap('Celsius WG', 3, false)).toBe(3);
      expect(effectiveCountCap('Celsius WG', 1, true)).toBe(1);
      expect(effectiveCountCap('Arena 50 WDG', 3, true)).toBe(3);
      expect(effectiveCountCap('Celsius WG', null, true)).toBeNull();
    });

    describe('with the stored row at the legacy 3', () => {
      async function history(dates) {
        const f = await fixture(knex);
        for (const date of dates) await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[CELSIUS].id, application_date: date, application_rate: 0.085, rate_unit: 'oz' });
        return f;
      }
      beforeEach(async () => {
        await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...migration.CELSIUS_SEED });
        await migration.up(knex); await wording.up(knex); await restore.up(knex);
      });
      const check = (customerId, gate) => {
        if (gate) process.env.GATE_LAWN_V13 = 'true'; else delete process.env.GATE_LAWN_V13;
        return applicationLimits.checkLimits(customerId, catalog[CELSIUS].id, new Date('2026-06-10T16:00:00Z'), knex, {});
      };

      test('gate off (the pre-visit brief reads checkLimits): the 3rd Celsius application is allowed, the 4th is blocked', async () => {
        const two = await history(['2026-02-02', '2026-03-16']);
        expect((await check(two.customerId, false)).blocks).toEqual([]);
        const three = await history(['2026-02-02', '2026-03-16', '2026-04-20']);
        expect((await check(three.customerId, false)).blocks.map((b) => b.max)).toEqual([3]);
      });

      test('gate on: the 3rd application is blocked at 2 (the stored 3 is lowered by the v13 override)', async () => {
        const two = await history(['2026-02-02', '2026-03-16']);
        const blocks = (await check(two.customerId, true)).blocks;
        expect(blocks).toEqual([expect.objectContaining({ type: 'annual_max_apps', current: 2, max: 2 })]);
      });

      test('the closeout finds it at the 3rd and not at the 2nd, gate on', async () => {
        process.env.GATE_LAWN_V13 = 'true';
        const f = await fixture(knex);
        const visit = await f.visit(0, { scheduled_date: '2026-06-10', service_type: 'Every 6 Weeks Lawn Care Service' });
        const record = async (date) => {
          const [past] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: visit.property_id, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
          const [rec] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: past.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
          await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[CELSIUS].id, application_date: date, application_rate: 0.085, rate_unit: 'oz', service_record_id: rec.id });
        };
        await record('2026-02-02');
        expect(await submittedProductLimitFindings({ svc: visit, productIds: [catalog[CELSIUS].id], serviceDate: '2026-06-10', database: knex })).toEqual([]);
        await record('2026-03-16');
        expect(await submittedProductLimitFindings({ svc: visit, productIds: [catalog[CELSIUS].id], serviceDate: '2026-06-10', database: knex }))
          .toEqual([expect.objectContaining({ code: 'application_limit_exceeded', limitType: 'annual_max_apps', current: 2, max: 2 })]);
        // Gate off: no v13 closeout flag at all.
        delete process.env.GATE_LAWN_V13;
        expect(await submittedProductLimitFindings({ svc: visit, productIds: [catalog[CELSIUS].id], serviceDate: '2026-06-10', database: knex })).toEqual([]);
      });
    });
  });

  describe('the closeout audit covers the whole cap year and both sides of a minimum interval', () => {
    let both;
    beforeAll(async () => {
      both = await product(DIMENSION, { category: 'fertilizer', active_ingredient: 'Dithiopyr' });
      await knex('product_limits').insert([
        { product_id: both.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 3, limit_unit: 'applications', severity: 'hard_block', description: 'fixture' },
        { product_id: both.id, match_type: 'product', limit_type: 'min_interval_days', limit_value: 60, limit_unit: 'days', severity: 'hard_block', description: 'fixture' },
      ]);
    });
    beforeEach(() => { process.env.GATE_LAWN_V13 = 'true'; });
    const applied = (customerId, date, extra = {}) => knex('property_application_history').insert({ customer_id: customerId, product_id: both.id, application_date: date, application_rate: 1, rate_unit: 'lb', ...extra });
    const findings = async (f, date) => {
      const visit = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: f.property.id, scheduled_date: date, service_type: 'Every 6 Weeks Lawn Care Service' }).returning('*').then(([row]) => row);
      return submittedProductLimitFindings({ svc: visit, productIds: [both.id], serviceDate: date, database: knex });
    };

    test('a backdated June closeout with January and October already recorded is flagged (the 3rd of the year, and the later ones count)', async () => {
      const cel = await fixture(knex);
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).del();
      await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...migration.CELSIUS_SEED });
      await knex('property_application_history').insert([
        { customer_id: cel.customerId, product_id: catalog[CELSIUS].id, application_date: '2026-01-10', application_rate: 0.085, rate_unit: 'oz' },
        { customer_id: cel.customerId, product_id: catalog[CELSIUS].id, application_date: '2026-10-05', application_rate: 0.085, rate_unit: 'oz' },
      ]);
      const visit = await knex('scheduled_services').insert({ customer_id: cel.customerId, property_id: cel.property.id, scheduled_date: '2026-06-10', service_type: 'Every 6 Weeks Lawn Care Service' }).returning('*').then(([row]) => row);
      const out = await submittedProductLimitFindings({ svc: visit, productIds: [catalog[CELSIUS].id], serviceDate: '2026-06-10', database: knex });
      expect(out).toEqual([expect.objectContaining({ code: 'application_limit_exceeded', limitType: 'annual_max_apps', current: 2, max: 2 })]);
      // Another calendar year does not count.
      expect(await submittedProductLimitFindings({ svc: visit, productIds: [catalog[CELSIUS].id], serviceDate: '2027-06-10', database: knex })).toEqual([]);
    });

    test('a backdated closeout is judged on BOTH sides of a minimum interval: an application 25 days AFTER it flags; one 61 days after does not', async () => {
      const f = await fixture(knex);
      await applied(f.customerId, '2026-07-05');
      expect(await findings(f, '2026-06-10')).toEqual([expect.objectContaining({ limitType: 'min_interval_days', current: 25, max: 60 })]);
      const g = await fixture(knex);
      await applied(g.customerId, '2026-08-10');
      expect(await findings(g, '2026-06-10')).toEqual([]);
      const h = await fixture(knex);
      await applied(h.customerId, '2025-12-20'); // across the new year, on the earlier side
      expect(await findings(h, '2026-02-08')).toEqual([expect.objectContaining({ limitType: 'min_interval_days', current: 50 })]);
    });

    test('a product over BOTH of its limits (Dimension 0.21%: 3 a year and 60 days) is reported once per limit', async () => {
      const f = await fixture(knex);
      for (const date of ['2026-01-05', '2026-04-20', '2026-06-01']) await applied(f.customerId, date);
      const out = await findings(f, '2026-06-20');
      expect(out.map((o) => [o.code, o.limitType, o.current, o.max])).toEqual([
        ['application_limit_exceeded', 'annual_max_apps', 3, 3],
        ['application_limit_exceeded', 'min_interval_days', 19, 60],
      ]);
    });
  });

  describe('the limits read across the new year (the minimum interval) and by property', () => {
    const applicationLimits = require('../services/application-limits');
    let hard;
    beforeAll(async () => {
      hard = await product('Cross-year interval fixture');
      await knex('product_limits').insert([
        { product_id: hard.id, match_type: 'product', limit_type: 'min_interval_days', limit_value: 60, limit_unit: 'days', severity: 'hard_block', description: 'fixture' },
        { product_id: hard.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 2, limit_unit: 'applications', severity: 'hard_block', description: 'fixture' },
      ]);
    });
    const applied = (customerId, date, extra = {}) => knex('property_application_history').insert({ customer_id: customerId, product_id: hard.id, application_date: date, application_rate: 1, rate_unit: 'oz', ...extra });
    const check = (customerId, date, opts = {}) => applicationLimits.checkLimits(customerId, hard.id, new Date(`${date}T16:00:00Z`), knex, opts);
    const types = (result) => result.blocks.map((b) => b.type);

    test('a December application and a February proposal 50 days later: the 60-day interval blocks; 60 days later it does not', async () => {
      const { customerId } = await fixture(knex);
      await applied(customerId, '2025-12-20');
      const fifty = await check(customerId, '2026-02-08');
      expect(types(fifty)).toEqual(['min_interval_days']);
      expect(fifty.blocks[0]).toMatchObject({ current: 50, max: 60 });
      expect(types(await check(customerId, '2026-02-18'))).toEqual([]);
      expect(types(await check(customerId, '2026-02-19'))).toEqual([]);
      expect(types(await check(customerId, '2026-02-17'))).toEqual(['min_interval_days']);
    });

    test('the yearly count keeps the calendar year: two 2025 applications do not count in February 2026, two 2026 ones do', async () => {
      const { customerId } = await fixture(knex);
      await applied(customerId, '2025-01-05');
      await applied(customerId, '2025-04-10');
      expect(types(await check(customerId, '2026-02-12'))).toEqual([]);
      const other = await fixture(knex);
      await applied(other.customerId, '2026-01-02');
      await applied(other.customerId, '2026-03-10');
      expect(types(await check(other.customerId, '2026-06-01'))).toEqual(['annual_max_apps']);
    });

    test('property scope and the visit\'s own row: another property blocks neither count nor interval; the same property does; a re-plan leaves its own ledger row out', async () => {
      const { customerId, property } = await fixture(knex);
      const [other] = await knex('customer_properties').insert({ customer_id: customerId, address_line1: '200 Fixture Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      const [past] = await knex('scheduled_services').insert({ customer_id: customerId, property_id: other.id, scheduled_date: '2026-01-20', service_type: 'Lawn fixture' }).returning('*');
      const [record] = await knex('service_records').insert({ customer_id: customerId, scheduled_service_id: past.id, service_date: '2026-01-20', service_type: 'Lawn fixture' }).returning('*');
      await applied(customerId, '2026-01-20', { service_record_id: record.id });
      expect(types(await check(customerId, '2026-02-12', { propertyId: property.id }))).toEqual([]);
      expect(types(await check(customerId, '2026-02-12', { propertyId: other.id }))).toEqual(['min_interval_days']);
      expect(types(await check(customerId, '2026-02-12', { propertyId: other.id, excludeScheduledServiceId: past.id }))).toEqual([]);
    });

    test('the closeout flag applies the same reading: a December visit then a February closeout 50 days later is flagged', async () => {
      process.env.GATE_LAWN_V13 = 'true';
      const f = await fixture(knex);
      const visit = await f.visit(0, { scheduled_date: '2026-02-08', service_type: 'Every 6 Weeks Lawn Care Service' });
      const [past] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: visit.property_id, scheduled_date: '2025-12-20', service_type: 'Lawn fixture' }).returning('*');
      const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: past.id, service_date: '2025-12-20', service_type: 'Lawn fixture' }).returning('*');
      await applied(f.customerId, '2025-12-20', { service_record_id: record.id });
      const flagged = await submittedProductLimitFindings({ svc: visit, productIds: [hard.id], serviceDate: '2026-02-08', database: knex });
      expect(flagged).toEqual([expect.objectContaining({ code: 'application_limit_exceeded', limitType: 'min_interval_days', current: 50, max: 60 })]);
      expect(await submittedProductLimitFindings({ svc: visit, productIds: [hard.id], serviceDate: '2026-02-18', database: knex })).toEqual([]);
    });
  });

  describe('the closeout flag against real history (submittedProductLimitFindings)', () => {
    beforeAll(async () => { await knex('product_limits').del(); await migration.up(knex); });
    beforeEach(() => { process.env.GATE_LAWN_V13 = 'true'; });

    async function setup(name, dates) {
      const f = await fixture(knex);
      const visitA = await f.visit(0, { scheduled_date: '2026-05-12', service_type: 'Every 6 Weeks Lawn Care Service' });
      const [propertyB] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '200 Fixture Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      const [visitB] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: propertyB.id, scheduled_date: '2026-05-12', service_type: 'Every 6 Weeks Lawn Care Service' }).returning('*');
      for (const date of dates) {
        const [past] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: visitA.property_id, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
        const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: past.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
        await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[name].id, application_date: date, application_rate: 0.085, rate_unit: 'oz', service_record_id: record.id });
      }
      return { visitA, visitB };
    }
    const check = (visit, ...names) => submittedProductLimitFindings({ svc: visit, productIds: names.map((n) => catalog[n].id), serviceDate: '2026-05-12', database: knex });

    test.each([CELSIUS, CERTAINTY, BLINDSIDE, ARENA])('%s: a 3rd application in the year at the same property is flagged; at another property it is not', async (name) => {
      const { visitA, visitB } = await setup(name, ['2026-02-02', '2026-03-16']);
      expect(await check(visitA, name)).toEqual([expect.objectContaining({ code: 'application_limit_exceeded', productId: catalog[name].id, productName: name, limitType: 'annual_max_apps', current: 2, max: 2 })]);
      expect(await check(visitB, name)).toEqual([]);
    });

    test('an unreadable history (a SQL error inside a transaction) is an unavailable finding, never a throw; the savepoint keeps the transaction usable', async () => {
      const { visitA } = await setup(CELSIUS, ['2026-02-02']);
      const limitsModule = require('../services/application-limits');
      const spy = jest.spyOn(limitsModule, 'auditHardCountLimits').mockImplementation(async (customerId, productId, date, k) => k.raw('SELECT * FROM table_that_does_not_exist'));
      const trx = await knex.transaction();
      try {
        const found = await submittedProductLimitFindings({ svc: visitA, productIds: [catalog[CELSIUS].id], serviceDate: '2026-05-12', database: trx });
        expect(found).toEqual([expect.objectContaining({ code: 'application_limit_check_unavailable', productId: catalog[CELSIUS].id })]);
        await expect(trx.raw('SELECT 1 AS ok')).resolves.toBeTruthy();
      } finally { spy.mockRestore(); await trx.rollback(); }
      expect(await check(visitA, CELSIUS)).toEqual([]);
    });

    test('the 2nd application is not flagged, and a default product with no limit row is unaffected beside a capped one', async () => {
      const { visitA } = await setup(CELSIUS, ['2026-02-02']);
      expect(await check(visitA, CELSIUS)).toEqual([]);
      const capped = await setup(CELSIUS, ['2026-02-02', '2026-03-16']);
      const flagged = await check(capped.visitA, 'Tetrino Insecticide', CELSIUS);
      expect(flagged).toEqual([expect.objectContaining({ productName: CELSIUS })]);
      expect(await check(capped.visitA, 'Tetrino Insecticide')).toEqual([]);
    });

    test('the visit\'s own ledger rows never count against it (a retry)', async () => {
      const f = await fixture(knex);
      const visit = await f.visit(0, { scheduled_date: '2026-05-12', service_type: 'Every 6 Weeks Lawn Care Service' });
      const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: visit.id, service_date: '2026-05-12', service_type: 'Lawn fixture' }).returning('*');
      for (const date of ['2026-02-02', '2026-05-12']) {
        await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[CELSIUS].id, application_date: date, application_rate: 0.085, rate_unit: 'oz', service_record_id: date === '2026-05-12' ? record.id : null });
      }
      expect(await check(visit, CELSIUS)).toEqual([]);
    });
  });

  describe('through the plan: the count is the treated property\'s', () => {
    beforeAll(async () => { await knex('product_limits').del(); await migration.up(knex); });

    async function twoProperties(name, dates) {
      const f = await fixture(knex);
      await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
      await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, grass_type: 'bermuda', track_key: 'bermuda', lawn_sqft: 10000 });
      const visitA = await f.visit(0, { scheduled_date: '2026-05-12' });
      const [propertyB] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '200 Fixture Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      const [visitB] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: propertyB.id, scheduled_date: '2026-05-12', service_type: 'Lawn fixture' }).returning('*');
      for (const date of dates) {
        const [past] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: visitA.property_id, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
        const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: past.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
        await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[name].id, application_date: date, application_rate: 0.085, rate_unit: 'oz', service_record_id: record.id });
      }
      return { visitA, visitB };
    }
    const plan = (visit, name) => {
      process.env.GATE_LAWN_V13 = 'true';
      return buildPlanForService(visit.id, { db: knex, selectedConditionalProductNames: [name] });
    };
    const limitBlocks = (result) => result.propertyGate.blocks.filter((b) => b.code === 'lawn_v13_annual_limit');

    test.each([CELSIUS, ARENA])('%s: a third application in the year at the same property is blocked; one at another property is not', async (name) => {
      const { visitA, visitB } = await twoProperties(name, ['2026-02-02', '2026-03-16']);
      const resultA = await plan(visitA, name);
      expect(limitBlocks(resultA)).toHaveLength(1);
      expect(limitBlocks(resultA)[0]).toMatchObject({ productName: name });
      expect(limitBlocks(resultA)[0].message).toMatch(/2\/2 applications this year — LIMIT REACHED/);
      expect(resultA.status).toBe('blocked');
      const resultB = await plan(visitB, name);
      expect(limitBlocks(resultB)).toEqual([]);
    });

    test('Celsius with the stored row at the legacy 3 (after 20261007172000): the plan still blocks the 3rd application under v13 (override 2) and the 2nd is allowed', async () => {
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 3 });
      try {
        const two = await twoProperties(CELSIUS, ['2026-02-02', '2026-03-16']);
        expect(limitBlocks(await plan(two.visitA, CELSIUS))).toHaveLength(1);
        expect(limitBlocks(await plan(two.visitB, CELSIUS))).toEqual([]);
        const one = await twoProperties(CELSIUS, ['2026-02-02']);
        expect(limitBlocks(await plan(one.visitA, CELSIUS))).toEqual([]);
      } finally {
        await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 2 });
      }
    });

    test('the second application in the year is still allowed', async () => {
      const { visitA } = await twoProperties(CELSIUS, ['2026-02-02']);
      const result = await plan(visitA, CELSIUS);
      expect(limitBlocks(result)).toEqual([]);
    });
  });
});
