// Lawn protocol v13 field rules round 9 (20261007159000) on PostgreSQL (cloned schema): the
// fertilizer safety gate on N-carrying spreader rows, and the SOP markdown that prints the one shared
// block for an N window and nothing for a hose window. Synthetic data only.
const { randomUUID } = require('crypto');
const { createLawnHistoryDb } = require('./helpers/lawn-history-db');
const adminProtocols = require('../routes/admin-protocols');
const migration = require('../models/migrations/20261007159000_lawn_v13_field_rules_round9');
const { FERTILIZER_SAFETY_RULES } = require('../services/lawn-fertilizer-safety');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const V13 = '2026.10-v13';
const TABLES = ['lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates', 'lawn_protocol_audit_log', 'scheduled_services', 'lawn_protocol_service_completions'];

describeDb('v13 fertilizer safety through PostgreSQL', () => {
  let owned;
  let knex;
  const rows = {};
  const protocols = {};

  const gatesOf = async (id) => (await knex('lawn_protocol_products').where({ id }).first('gates')).gates;
  const sop = async (protocol, windowKey) => {
    const payload = await adminProtocols._internals.loadWindowSopPayload(knex, protocol.id, windowKey);
    return adminProtocols._internals.renderWindowSopMarkdown(payload);
  };

  async function stage(track) {
    const [protocol] = await knex('lawn_protocols').insert({ protocol_key: `fixture_round9_${track}`, version: V13, name: track, status: 'staged', grass_track: track, region: 'swfl' }).returning('*');
    const window = (month, key) => knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: key, title: key, visit_type: 'x' }).returning('*').then((r) => r[0]);
    const row = (win, name, gates) => knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: win.id, product_name: name, role: 'x', application_mode: 'broadcast', default_in_plan: true, gates: JSON.stringify(gates),
    }).returning('*').then((r) => r[0]);
    const feb = await window(2, 'feb_v13_spreader_green_up');
    const jun = await window(6, 'jun_v13_hose_blackout');
    protocols[track] = protocol;
    rows[track] = {
      f24: await row(feb, 'LESCO 24-0-11', { targetN: '0.75 lb N/1000', blackoutSensitive: true }),
      nutra: await row(jun, 'Nutra-TECH', { requiresZeroNP: true }),
    };
  }

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES.filter((t) => !['scheduled_services'].includes(t))) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    await stage('bermuda');
    await stage('zoysia');
  });
  afterAll(async () => { if (owned) await owned.dispose(); });

  test('up gates the N-carrying spreader rows only, and a second up changes nothing', async () => {
    await migration.up(knex);
    await migration.up(knex);
    for (const track of ['bermuda', 'zoysia']) {
      expect(await gatesOf(rows[track].f24.id)).toEqual({ targetN: '0.75 lb N/1000', blackoutSensitive: true, fertilizerSafety: true });
      expect(await gatesOf(rows[track].nutra.id)).toEqual({ requiresZeroNP: true });
    }
    expect(await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules_r9' })).toHaveLength(2);
  });

  test('the SOP markdown prints the shared block for the N window and nothing for the hose window', async () => {
    const feb = await sop(protocols.bermuda, 'feb_v13_spreader_green_up');
    expect(feb).toContain('## Fertilizer Safety');
    for (const rule of FERTILIZER_SAFETY_RULES) expect(feb).toContain(`- ${rule}`);
    const jun = await sop(protocols.bermuda, 'jun_v13_hose_blackout');
    expect(jun).not.toContain('Fertilizer Safety');
    expect(jun).not.toContain('deflector');
  });

  test('down takes the gate back from an unreferenced protocol and leaves a referenced one alone', async () => {
    // The zoysia protocol is referenced by a completion.
    await knex('lawn_protocol_service_completions').insert({ service_record_id: randomUUID(), lawn_protocol_id: protocols.zoysia.id, protocol_key: protocols.zoysia.protocol_key, protocol_version: V13 });
    await migration.down(knex);
    expect(await gatesOf(rows.bermuda.f24.id)).toEqual({ targetN: '0.75 lb N/1000', blackoutSensitive: true });
    expect(await gatesOf(rows.zoysia.f24.id)).toEqual({ targetN: '0.75 lb N/1000', blackoutSensitive: true, fertilizerSafety: true });
    expect(await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules_r9' })).toHaveLength(1);
  });
});
