// Lawn bermuda removal (GATE_LAWN_BERMUDA_REMOVAL) through the real plan engine,
// the real staged-row migration and PostgreSQL (cloned schema, synthetic data).
//
// Pins: gate off is the old plan; St. Augustine and Zoysia lawns that asked for
// the step (staff switch or accepted estimate) get Recognition, Fusilade II and
// the surfactant as spot lines on the April and June visits; Bermuda, Bahia,
// other months and lawns that did not ask never do; Fusilade II is never planned
// or selectable without Recognition; the 2-a-year and 42-day limits block; the
// migration is safe to run up, down, up.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION } = require('../services/lawn-program');
const rowsMigration = require('../models/migrations/20261006190100_lawn_bermuda_removal_rows');
const auditMigration = require('../models/migrations/20261006190200_lawn_bermuda_removal_audit');
const { bermudaPairViolation } = require('../services/lawn-bermuda-removal');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_BERMUDA_REMOVAL', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY'];
const TRACKS = [
  ['swfl_st_augustine_10_10', 'st_augustine'],
  ['swfl_zoysia_10_10', 'zoysia'],
  ['swfl_bermuda_10_10', 'bermuda'],
  ['swfl_bahia_10_10', 'bahia'],
];
const REC = 'Recognition Post Emergent Herbicide';
const FUS = 'Fusilade II Post Emergent Liquid Herbicide';
const NIS = 'LESCO 90/10 Nonionic Surfactant';

function setGates({ v13 = true, removal = true } = {}) {
  for (const [name, on] of [['GATE_LAWN_V13', v13], ['GATE_LAWN_BERMUDA_REMOVAL', removal]]) {
    if (on) process.env[name] = 'true'; else delete process.env[name];
  }
  delete process.env.GATE_LAWN_COMPLETION_DEFAULTS;
  delete process.env.GATE_LAWN_PROPERTY_HISTORY;
}

describeDb('lawn bermuda removal through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  let rec;
  let fus;
  let nis;

  async function cloneTables(tables) {
    for (const table of tables) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
  }

  const product = async (name, changes = {}) => (await knex('products_catalog').insert({
    name, category: 'herbicide', default_rate_per_1000: 0.03, rate_unit: 'oz', label_verified_at: new Date(),
    inventory_on_hand: 1000, inventory_unit: 'oz', active: true, ...changes,
  }).returning('*'))[0];

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    await cloneTables(['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'product_limits', 'property_application_history',
      'estimates', 'lawn_protocol_audit_log']);
    rec = await product(REC);
    fus = await product(FUS, { default_rate_per_1000: 0.55, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    nis = await product(NIS, { category: 'adjuvant', default_rate_per_1000: 0.25, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    for (const [key, track] of TRACKS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: `Old ${track}`, status: 'active', grass_track: track, region: 'swfl' });
      const [staged] = await knex('lawn_protocols').insert({
        protocol_key: key, version: LAWN_V13_VERSION, name: `v13 ${track}`, status: 'staged', grass_track: track, region: 'swfl', effective_from: '2000-01-01',
      }).returning('*');
      for (const [month, windowKey] of [[4, 'apr_v13_spreader_feeding'], [5, 'may_v13_tetrino_hose'], [6, 'jun_v13_hose_blackout']]) {
        await knex('lawn_protocol_windows').insert({ lawn_protocol_id: staged.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture' });
      }
    }
    // The real migration writes the rows and the limits into the fixture protocols.
    await rowsMigration.up(knex);
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  });
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  async function lawn({ grass = 'st_augustine', date = '2026-04-14', bermuda = false, acceptedEstimate = false, cultivar = 'Floratam' } = {}) {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
    await knex('customer_turf_profiles').insert({
      customer_id: f.customerId, active: true, grass_type: grass, track_key: grass, cultivar, lawn_sqft: 10000, bermuda_removal: bermuda,
    });
    if (acceptedEstimate) {
      await knex('estimates').insert({
        customer_id: f.customerId, status: 'accepted',
        estimate_data: JSON.stringify({ engineRequest: { options: { bermudaSuppression: true } } }),
      });
    }
    const visit = await f.visit(0, { scheduled_date: date });
    return { ...f, visit, customerId: f.customerId };
  }
  const plan = (visit, options = {}) => buildPlanForService(visit.id, { db: knex, ...options });
  const names = (items) => items.map((item) => item.product?.name).filter(Boolean);
  const optionNames = (result) => names([...result.mixCalculator.items, ...result.mixCalculator.conditionalOptions]);
  const codes = (result) => result.propertyGate.blocks.map((b) => b.code);
  const strip = (result) => JSON.parse(JSON.stringify({ ...result, generatedAt: null }));
  const history = (customerId, product, dates) => knex('property_application_history').insert(
    dates.map((application_date) => ({ customer_id: customerId, product_id: product.id, application_date })),
  );

  describe('who gets the step', () => {
    test.each([['st_augustine', '2026-04-14'], ['st_augustine', '2026-06-16'], ['zoysia', '2026-04-14'], ['zoysia', '2026-06-16']])(
      '%s on %s: the staff switch adds the three spot lines, never an amount', async (grass, date) => {
        setGates();
        const f = await lawn({ grass, date, bermuda: true });
        const result = await plan(f.visit);
        expect(result.bermudaRemoval).toMatchObject({ active: true, source: 'staff' });
        expect(result.bermudaRemoval.mix).toContain('Recognition 0.03 oz + Fusilade II 0.55 fl oz');
        const lines = result.mixCalculator.conditionalOptions.filter((item) => [REC, FUS, NIS].includes(item.product?.name));
        expect(lines.map((item) => item.product.name).sort()).toEqual([FUS, NIS, REC].sort());
        for (const line of lines) {
          expect(line.spot).toMatchObject({ note: expect.stringContaining('enter the area') });
          expect(line.mix).toBeNull();
        }
        expect(lines.find((item) => item.product.name === REC).spot.reference).toBe('Label rate 0.03 oz per 1,000 sq ft');
        expect(lines.find((item) => item.product.name === FUS).spot.reference).toBe('Label rate 0.55 fl oz per 1,000 sq ft');
      });

    test('the field rules ride the rows as gate notes (June adds the morning and 85 F rule)', async () => {
      setGates();
      const june = await plan((await lawn({ date: '2026-06-16', bermuda: true })).visit, { selectedConditionalProductIds: [rec.id, fus.id] });
      const note = (name) => june.mixCalculator.items.find((item) => item.product?.name === name).gateNotes.map((n) => n.text).join(' | ');
      expect(note(REC)).toContain('actively growing');
      expect(note(REC)).toContain('temperature under 85');
      expect(note(REC)).toContain('No rain or irrigation for 3 hours');
      expect(note(REC)).toContain('Do not mow for 2 days before or after');
      expect(note(REC)).toContain('Skip the Celsius weed spot in the bermuda area');
      expect(note(FUS)).toContain('only together with Recognition');
      const april = await plan((await lawn({ date: '2026-04-14', bermuda: true })).visit, { selectedConditionalProductIds: [rec.id] });
      expect(april.mixCalculator.items.find((item) => item.product?.name === REC).gateNotes.map((n) => n.text).join(' | ')).not.toContain('under 85');
    });

    test('an accepted estimate that carries the add-on turns it on with no staff switch', async () => {
      setGates();
      const result = await plan((await lawn({ acceptedEstimate: true })).visit);
      expect(result.bermudaRemoval).toMatchObject({ active: true, source: 'estimate' });
      expect(optionNames(result)).toEqual(expect.arrayContaining([REC, FUS, NIS]));
    });

    test('an estimate counts only while the CURRENT profile grass is St. Augustine: a reclassified Zoysia lawn needs the staff switch', async () => {
      setGates();
      const f = await lawn({ grass: 'zoysia', acceptedEstimate: true });
      const viaEstimate = await plan(f.visit);
      expect(viaEstimate.bermudaRemoval).toBeUndefined();
      expect(optionNames(viaEstimate)).not.toContain(REC);
      await knex('customer_turf_profiles').where({ customer_id: f.customerId }).update({ bermuda_removal: true });
      const viaSwitch = await plan(f.visit);
      expect(viaSwitch.bermudaRemoval).toMatchObject({ active: true, source: 'staff' });
      expect(optionNames(viaSwitch)).toEqual(expect.arrayContaining([REC, FUS, NIS]));
    });

    test('a lawn that did not ask never gets it, and neither does a draft or archived estimate', async () => {
      setGates();
      const plain = await lawn({});
      await knex('estimates').insert({ customer_id: plain.customerId, status: 'draft', estimate_data: JSON.stringify({ engineRequest: { options: { bermudaSuppression: true } } }) });
      await knex('estimates').insert({ customer_id: plain.customerId, status: 'accepted', archived_at: new Date(), estimate_data: JSON.stringify({ engineRequest: { options: { bermudaSuppression: true } } }) });
      const result = await plan(plain.visit);
      expect(result.bermudaRemoval).toBeUndefined();
      expect(optionNames(result)).not.toEqual(expect.arrayContaining([REC]));
      expect(optionNames(result)).not.toContain(FUS);
    });

    test.each(['bermuda', 'bahia'])('%s never gets it, even with the switch on and the estimate flag set', async (grass) => {
      setGates();
      const f = await lawn({ grass, bermuda: true, acceptedEstimate: true });
      const result = await plan(f.visit, { selectedConditionalProductIds: [rec.id, fus.id, nis.id] });
      expect(result.bermudaRemoval).toBeUndefined();
      expect(optionNames(result)).not.toContain(REC);
      expect(optionNames(result)).not.toContain(FUS);
    });

    test('other months carry no step (May)', async () => {
      setGates();
      const result = await plan((await lawn({ date: '2026-05-12', bermuda: true })).visit);
      expect(result.bermudaRemoval).toBeUndefined();
      expect(optionNames(result)).not.toContain(REC);
    });

    test('gate off: a flagged lawn plans exactly as the same lawn unflagged (byte-identical)', async () => {
      setGates({ removal: false });
      const f = await lawn({ bermuda: true, acceptedEstimate: true });
      const flagged = strip(await plan(f.visit));
      await knex('customer_turf_profiles').where({ customer_id: f.customerId }).update({ bermuda_removal: false });
      await knex('estimates').where({ customer_id: f.customerId }).del();
      const plain = strip(await plan(f.visit));
      expect(flagged).toEqual(plain);
      expect(JSON.stringify(flagged)).not.toContain(REC);
      expect(flagged.bermudaRemoval).toBeUndefined();
    });
  });

  describe('Recognition, Fusilade II and the surfactant are one selection', () => {
    const stepNames = (result) => names(result.mixCalculator.items).filter((name) => [REC, FUS, NIS].includes(name));

    test.each([['fus'], ['rec'], ['nis']])('selecting only %s selects all three, with no block', async (which) => {
      setGates();
      const id = { fus, rec, nis }[which].id;
      const result = await plan((await lawn({ bermuda: true })).visit, { selectedConditionalProductIds: [id] });
      expect(stepNames(result).sort()).toEqual([FUS, NIS, REC].sort());
      expect(codes(result)).not.toContain('lawn_bermuda_step_unavailable');
    });

    test('nothing selected: the three are options, none is selected', async () => {
      setGates();
      const result = await plan((await lawn({ bermuda: true })).visit);
      expect(stepNames(result)).toEqual([]);
      expect(optionNames(result)).toEqual(expect.arrayContaining([REC, FUS, NIS]));
    });

    test('Recognition blocked by the 42-day interval: all three leave the plan, with the reason', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-16', bermuda: true });
      await history(f.customerId, rec, ['2026-06-01']);
      const result = await plan(f.visit, { selectedConditionalProductIds: [rec.id] });
      expect(codes(result)).toEqual(expect.arrayContaining(['lawn_v13_annual_limit', 'lawn_bermuda_step_unavailable']));
      for (const name of [REC, FUS, NIS]) expect(optionNames(result)).not.toContain(name);
      expect(result.status).toBe('blocked');
    });

    test('Fusilade II limited on its own: Recognition and the surfactant leave too', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-16', bermuda: true });
      await history(f.customerId, fus, ['2026-06-01']);
      const result = await plan(f.visit);
      for (const name of [REC, FUS, NIS]) expect(optionNames(result)).not.toContain(name);
      expect(codes(result)).toContain('lawn_bermuda_step_unavailable');
    });

    test('limited with nobody selecting anything: the options are gone too', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-16', bermuda: true });
      await history(f.customerId, rec, ['2026-06-01']);
      const result = await plan(f.visit);
      for (const name of [REC, FUS, NIS]) expect(optionNames(result)).not.toContain(name);
    });

    test.each([[REC], [FUS], [NIS]])('%s inactive in the catalog: none of the three is planned', async (name) => {
      setGates();
      await knex('products_catalog').where({ name }).update({ active: false });
      try {
        const result = await plan((await lawn({ bermuda: true })).visit, { selectedConditionalProductIds: [rec.id, fus.id] });
        for (const step of [REC, FUS, NIS]) expect(optionNames(result)).not.toContain(step);
        expect(codes(result)).toContain('lawn_bermuda_step_unavailable');
      } finally {
        await knex('products_catalog').where({ name }).update({ active: true });
      }
    });
  });

  describe('St. Augustine cultivar policy', () => {
    const stepOptions = (result) => optionNames(result).filter((name) => [REC, FUS, NIS].includes(name));

    test.each(['ProVista', 'Captiva', 'seville', 'Seville dwarf'])('%s never gets the step, and the plan says why', async (cultivar) => {
      setGates();
      const f = await lawn({ bermuda: true, acceptedEstimate: true, cultivar });
      const result = await plan(f.visit, { selectedConditionalProductIds: [rec.id, fus.id, nis.id] });
      expect(stepOptions(result)).toEqual([]);
      expect(result.bermudaRemoval).toBeUndefined();
      expect(result.propertyGate.warnings.map((w) => w.code)).toContain('lawn_bermuda_cultivar_excluded');
    });

    test.each(['Floratam', 'Palmetto', 'Raleigh', 'SunClipse'])('%s gets the step with no test-patch note', async (cultivar) => {
      setGates();
      const result = await plan((await lawn({ bermuda: true, cultivar })).visit, { selectedConditionalProductIds: [rec.id] });
      expect(stepOptions(result).sort()).toEqual([FUS, NIS, REC].sort());
      expect(JSON.stringify(result)).not.toMatch(/Test patch first/);
    });

    test.each(['CitraBlue', null, '', 'mystery sod'])('cultivar %p gets the step with a hard test-patch note on each of the three lines', async (cultivar) => {
      setGates();
      const result = await plan((await lawn({ bermuda: true, cultivar })).visit, { selectedConditionalProductIds: [rec.id] });
      const lines = result.mixCalculator.items.filter((item) => [REC, FUS, NIS].includes(item.product?.name));
      expect(lines).toHaveLength(3);
      for (const line of lines) {
        const note = line.gateNotes.find((n) => n.key === 'testPatchFirst');
        expect(note).toMatchObject({ severity: 'required' });
        expect(note.text).toMatch(/3 x 3 ft patch.*3 to 4 weeks/);
      }
      expect(result.propertyGate.warnings.filter((w) => w.code === 'lawn_v13_product_gate' && /Test patch first/.test(w.message))).toHaveLength(3);
    });

    test('Zoysia has no cultivar rule: even ProVista on file gets the step with no note', async () => {
      setGates();
      const result = await plan((await lawn({ grass: 'zoysia', bermuda: true, cultivar: 'ProVista' })).visit, { selectedConditionalProductIds: [rec.id] });
      expect(stepOptions(result).sort()).toEqual([FUS, NIS, REC].sort());
      expect(JSON.stringify(result)).not.toMatch(/Test patch first/);
    });
  });

  describe('limits: 2 sprays a year, 42 days apart', () => {
    test('the migration wrote the hard-block rows for both products and the label warning for Recognition', async () => {
      const rows = await knex('product_limits').whereIn('product_id', [rec.id, fus.id]).select('product_id', 'limit_type', 'limit_value', 'severity');
      const pick = (id) => rows.filter((row) => row.product_id === id).map((row) => `${row.limit_type}:${Number(row.limit_value)}:${row.severity}`).sort();
      expect(pick(rec.id)).toEqual(['annual_max_apps:2:hard_block', 'annual_max_rate:0.1437:warning', 'min_interval_days:42:hard_block']);
      expect(pick(fus.id)).toEqual(['annual_max_apps:2:hard_block', 'min_interval_days:42:hard_block']);
    });

    test('a second spray 41 days after the first is blocked; 42 days after is allowed', async () => {
      setGates();
      const early = await lawn({ date: '2026-06-10', bermuda: true });
      await history(early.customerId, rec, ['2026-04-30']);
      const blocked = await plan(early.visit, { selectedConditionalProductIds: [rec.id, fus.id] });
      expect(blocked.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit').message).toMatch(/only 41 days since last app \(min 42\)/);
      expect(codes(blocked)).toContain('lawn_bermuda_step_unavailable');
      for (const name of [REC, FUS, NIS]) expect(optionNames(blocked)).not.toContain(name);
      const ok = await lawn({ date: '2026-06-11', bermuda: true });
      await history(ok.customerId, rec, ['2026-04-30']);
      const allowed = await plan(ok.visit, { selectedConditionalProductIds: [rec.id, fus.id] });
      expect(codes(allowed)).not.toContain('lawn_v13_annual_limit');
      expect(names(allowed.mixCalculator.items)).toEqual(expect.arrayContaining([REC, FUS]));
    });

    test('a third spray in the calendar year is blocked, and waits for next year', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await history(f.customerId, rec, ['2026-03-01', '2026-04-20']);
      const third = await plan(f.visit, { selectedConditionalProductIds: [rec.id] });
      const block = third.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit');
      expect(block.message).toMatch(/2\/2 applications this year — LIMIT REACHED/);
      expect(optionNames(third)).not.toContain(FUS);
      // The count is per calendar year: the same two sprays do not count next year.
      const nextYear = await lawn({ date: '2027-04-13', bermuda: true });
      await history(nextYear.customerId, rec, ['2026-03-01', '2026-04-20']);
      const fresh = await plan(nextYear.visit, { selectedConditionalProductIds: [rec.id] });
      expect(codes(fresh)).not.toContain('lawn_v13_annual_limit');
    });
  });

  describe('the staged-row migration', () => {
    const count = async () => ({
      rows: Number((await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'").count('* as n').first()).n),
      limits: Number((await knex('product_limits').whereIn('product_id', [rec.id, fus.id]).count('* as n').first()).n),
    });

    test('12 rows (2 grasses x 2 windows x 3 products) and 5 limits; the other grasses get none', async () => {
      expect(await count()).toEqual({ rows: 12, limits: 5 });
      const onOtherGrasses = await knex('lawn_protocol_products as p')
        .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
        .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
        .whereRaw("p.gates->>'bermudaRemoval' = 'true'").whereIn('l.grass_track', ['bermuda', 'bahia']).count('* as n').first();
      expect(Number(onOtherGrasses.n)).toBe(0);
      const mayRows = await knex('lawn_protocol_products as p')
        .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
        .whereRaw("p.gates->>'bermudaRemoval' = 'true'").where('w.window_key', 'may_v13_tetrino_hose').count('* as n').first();
      expect(Number(mayRows.n)).toBe(0);
    });

    test('every row is a spot row that is not in the plan by default, with a catalog link', async () => {
      const rows = await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'");
      expect(rows.every((row) => row.application_mode === 'spot' && row.default_in_plan === false && row.product_id)).toBe(true);
    });

    test('up twice is a no-op; down removes exactly the 12 rows and 5 limits; up again restores them', async () => {
      await rowsMigration.up(knex);
      expect(await count()).toEqual({ rows: 12, limits: 5 });
      await rowsMigration.down(knex);
      expect(await count()).toEqual({ rows: 0, limits: 0 });
      await rowsMigration.up(knex);
      expect(await count()).toEqual({ rows: 12, limits: 5 });
    });

    test('a row a completion actual references survives down (documented no-op for it)', async () => {
      const row = await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'").first();
      await knex('lawn_protocol_product_actuals').insert({ protocol_product_id: row.id, lawn_protocol_service_completion_id: require('crypto').randomUUID(), product_name: row.product_name });
      const hasActual = await knex('lawn_protocol_product_actuals').where({ protocol_product_id: row.id }).first();
      expect(hasActual).toBeTruthy();
      await rowsMigration.down(knex);
      const left = Number((await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'").count('* as n').first()).n);
      expect(left).toBe(1);
      await knex('lawn_protocol_product_actuals').where({ protocol_product_id: row.id }).del();
      await rowsMigration.down(knex);
      await rowsMigration.up(knex);
      expect(await count()).toEqual({ rows: 12, limits: 5 });
    });
  });

  describe('completion: Recognition and Fusilade II are recorded together', () => {
    const submitted = (...items) => items.map((item) => ({ productId: item.id }));

    test('one without the other is refused with a clear message; the surfactant is optional', async () => {
      setGates();
      expect(await bermudaPairViolation(knex, submitted(rec))).toMatch(/Recognition goes on with Fusilade II/);
      expect(await bermudaPairViolation(knex, submitted(fus))).toMatch(/Fusilade II is never applied without Recognition/);
      expect(await bermudaPairViolation(knex, submitted(fus, nis))).toMatch(/without Recognition/);
      expect(await bermudaPairViolation(knex, submitted(rec, fus))).toBeNull();
      expect(await bermudaPairViolation(knex, submitted(rec, fus, nis))).toBeNull();
    });

    test('other products, no products and gate off are never refused', async () => {
      setGates();
      expect(await bermudaPairViolation(knex, submitted(nis))).toBeNull();
      expect(await bermudaPairViolation(knex, [])).toBeNull();
      expect(await bermudaPairViolation(knex, undefined)).toBeNull();
      expect(await bermudaPairViolation(knex, [{ productId: null }])).toBeNull();
      setGates({ removal: false });
      expect(await bermudaPairViolation(knex, submitted(rec))).toBeNull();
      expect(await bermudaPairViolation(knex, submitted(fus))).toBeNull();
    });
  });

  describe('the audit migration (20261006190200)', () => {
    const entries = () => knex('lawn_protocol_audit_log').where({ action: 'seed_v13_bermuda_removal' });

    test('one entry per affected protocol with a snapshot of the rows added; up twice is a no-op; down removes them; up restores', async () => {
      await auditMigration.down(knex);
      await auditMigration.up(knex);
      let rows = await entries();
      expect(rows).toHaveLength(2);
      for (const row of rows) {
        expect(row).toMatchObject({ actor_name: 'migration 20261006190100', entity_type: 'protocol' });
        const snapshot = typeof row.after_snapshot === 'string' ? JSON.parse(row.after_snapshot) : row.after_snapshot;
        expect(['swfl_st_augustine_10_10', 'swfl_zoysia_10_10']).toContain(snapshot.protocol_key);
        expect(snapshot.added_products).toHaveLength(6);
        expect(snapshot.added_products.map((p) => p.window_key).sort()).toEqual([
          ...Array(3).fill('apr_v13_spreader_feeding'), ...Array(3).fill('jun_v13_hose_blackout')].sort());
        expect(snapshot.added_products.every((p) => p.application_mode === 'spot')).toBe(true);
      }
      await auditMigration.up(knex);
      expect(await entries()).toHaveLength(2);
      await auditMigration.down(knex);
      expect(await entries()).toHaveLength(0);
      await auditMigration.up(knex);
      rows = await entries();
      expect(rows).toHaveLength(2);
    });

    test('down leaves every other audit entry alone', async () => {
      await knex('lawn_protocol_audit_log').insert({
        lawn_protocol_id: (await knex('lawn_protocols').first('id')).id, actor_name: 'someone else', entity_type: 'protocol',
        entity_id: (await knex('lawn_protocols').first('id')).id, action: 'seed_v13',
      });
      await auditMigration.down(knex);
      expect(Number((await knex('lawn_protocol_audit_log').where({ action: 'seed_v13' }).count('* as n').first()).n)).toBe(1);
      await auditMigration.up(knex);
    });
  });
});
