// Lawn protocol v13: three empty chemical groups are filled and the November LESCO 24-0-11 rows get the active large patch nitrogen
// key (migration 20261009175000), through the real migration on PostgreSQL (cloned schema). Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned: Gravex frac_group '3', Dylox 6.2 G irac_group '1B' and the Dimension MOP row (resolved by alias) hrac_group '3' are filled only
// where empty (null or ''); a value somebody wrote stays; Dylox 420 SL (moa_group only) and the decoy are untouched; every non-retired
// November 24-0-11 row gets gates.activeLargePatchTargetN once, targetN unchanged, a retired row and another month are left; a second up
// changes nothing; a missing catalog row skips its group; down restores exactly and never touches a value it did not write.
const { createLawnHistoryDb } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009175000_lawn_v13_groups_and_large_patch_n');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');

const DYLOX = staged.NAMES.DYL;
const SL = 'Dylox 420 SL T&O Insecticide';
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_gn_a', 'fixture_gn_b'];
const NOV = 'nov_v13_spreader_feeding';
const FEB = 'feb_v13_spreader_green_up';
const F24 = staged.NAMES.F24;
const GRAVEX = 'Gravex 20 EW';
const DIMENSION_MOP = 'LESCO Dimension 0.21% 18-0-10 50% PolyPlus OPTI45 MOP Pre-Emergent Plus Fertilizer';
const NOV_GATES = { targetN: '0.75 lb N/1000', fertilizerSafety: true, blackoutSensitive: true };
const FERT_TARGET = '0.75 lb N/1000';
const CATALOG_TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products',
  'lawn_protocol_audit_log', 'lawn_protocol_service_completions', 'product_limits', 'lawn_protocol_product_actuals', 'service_products'];

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 empty chemical groups and November large patch nitrogen migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of CATALOG_TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [table, constraint, suffix] of [
      ['product_limits', 'fixture_limits_product', ''], ['product_aliases', 'fixture_aliases_product', ''],
      ['service_products', 'fixture_sp_product', ' ON DELETE SET NULL'], ['lawn_protocol_products', 'fixture_lpp_product', ''],
    ]) {
      await knex.raw(`ALTER TABLE ??.?? ADD CONSTRAINT ${constraint} FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)${suffix}`, [owned.schema, table, owned.schema]);
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });


  const group = async (name, column) => (await knex('products_catalog').where({ name }).first(column))[column];
  const novRows = () => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'w.window_key': NOV, 'p.product_name': F24, 'l.version': V13 }).orderBy(['l.protocol_key', 'p.id']).select('p.*', 'l.protocol_key');
  const ours = () => knex('lawn_protocol_audit_log').whereIn('action', [migration.ACTION, migration.CATALOG_ACTION]);
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  async function snapshot() {
    return clean([await knex('lawn_protocol_products').orderBy('id'), await knex('products_catalog').orderBy('name'), await knex('lawn_protocol_audit_log').orderBy('id')]);
  }

  // The catalog as production holds it (the three groups empty; Dylox 420 SL carries moa_group only) and two staged v13 protocols with a
  // November and a February 24-0-11 row.
  async function reset({ gravex = true } = {}) {
    for (const table of ['service_products', 'lawn_protocol_product_actuals', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    const insert = async (row) => (await knex('products_catalog').insert({ active: true, ...row }).returning('*'))[0];
    if (gravex) ids.gravex = (await insert({ name: GRAVEX, category: 'fungicide' })).id;
    ids.dylox = (await insert({ name: DYLOX, category: 'insecticide', active_ingredient: 'trichlorfon 6.2%' })).id;
    ids.sl = (await insert({ name: SL, category: 'insecticide', moa_group: 'Group 1B' })).id;
    ids.dimension = (await insert({ name: 'Dimension MOP catalog row', category: 'fertilizer' })).id;
    await knex('product_aliases').insert({ product_id: ids.dimension, alias_name: DIMENSION_MOP });
    ids.fert = (await insert({ name: F24, category: 'fertilizer' })).id;
    for (const key of KEYS) {
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      for (const [windowKey, month] of [[NOV, 11], [FEB, 2]]) {
        const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
        await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: ids.fert, product_name: F24, role: 'nutrition', application_mode: 'broadcast', rate_unit: 'lb_n', default_in_plan: true, sort_order: 1, gates: JSON.stringify(windowKey === NOV ? NOV_GATES : { targetN: FERT_TARGET, blackoutSensitive: true }) });
      }
    }
  }

  describe('fresh path', () => {
    let before;
    beforeAll(async () => {
      await reset();
      before = { sl: clean(await knex('products_catalog').where({ name: SL })), fert: clean(await knex('products_catalog').where({ name: F24 })) };
      await migration.up(knex);
    });

    test('the three groups are filled in the typed column, bare code; the Dimension row is found by alias', async () => {
      expect(await group(GRAVEX, 'frac_group')).toBe('3');
      expect(await group(DYLOX, 'irac_group')).toBe('1B');
      expect(await knex('products_catalog').where({ id: ids.dimension }).first('hrac_group', 'frac_group', 'irac_group', 'moa_group')).toEqual({ hrac_group: '3', frac_group: null, irac_group: null, moa_group: null });
      // Only the typed column: no second moa_group, which productGroups would read as the same group twice.
      expect(await knex('products_catalog').where({ name: GRAVEX }).first('moa_group', 'irac_group', 'hrac_group')).toEqual({ moa_group: null, irac_group: null, hrac_group: null });
      expect(await knex('products_catalog').where({ name: DYLOX }).first('moa_group', 'frac_group', 'hrac_group')).toEqual({ moa_group: null, frac_group: null, hrac_group: null });
    });

    test('Dylox 420 SL and the fertilizer catalog row are not touched', async () => {
      expect(clean(await knex('products_catalog').where({ name: SL }))).toBe(before.sl);
      expect(clean(await knex('products_catalog').where({ name: F24 }))).toBe(before.fert);
      expect(await group(SL, 'moa_group')).toBe('Group 1B');
    });

    test('every November 24-0-11 row has the large patch key once, with targetN unchanged; February is left', async () => {
      const rows = await novRows();
      expect(rows).toHaveLength(KEYS.length);
      for (const row of rows) expect(row.gates).toEqual({ ...NOV_GATES, activeLargePatchTargetN: '0.5 lb N/1000' });
      const feb = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').where({ 'w.window_key': FEB }).select('p.gates');
      for (const row of feb) expect(row.gates).toEqual({ targetN: FERT_TARGET, blackoutSensitive: true });
    });

    test('one catalog audit row and one audit row per protocol; a second up changes nothing', async () => {
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION })).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.ACTION })).toHaveLength(KEYS.length);
      const state = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(state);
    });

    test('down restores the groups to empty and removes the key and the audit rows', async () => {
      await migration.down(knex);
      expect(await group(GRAVEX, 'frac_group')).toBeNull();
      expect(await group(DYLOX, 'irac_group')).toBeNull();
      expect(await knex('products_catalog').where({ id: ids.dimension }).first('hrac_group')).toEqual({ hrac_group: null });
      for (const row of await novRows()) expect(row.gates).toEqual(NOV_GATES);
      expect(await ours()).toHaveLength(0);
    });
  });

  describe('values that are not empty or not as written', () => {
    beforeEach(() => reset());

    test('a hand-written group stays; an empty string counts as empty and goes back to an empty string on down', async () => {
      await knex('products_catalog').where({ id: ids.gravex }).update({ frac_group: '7' });
      await knex('products_catalog').where({ id: ids.dylox }).update({ irac_group: '' });
      await migration.up(knex);
      expect(await group(GRAVEX, 'frac_group')).toBe('7');
      expect(await group(DYLOX, 'irac_group')).toBe('1B');
      await migration.down(knex);
      expect(await group(GRAVEX, 'frac_group')).toBe('7');
      expect(await group(DYLOX, 'irac_group')).toBe('');
    });

    test('down leaves a group and a key somebody changed since', async () => {
      await migration.up(knex);
      await knex('products_catalog').where({ id: ids.gravex }).update({ frac_group: '3 + 7' });
      const [row] = await novRows();
      await knex('lawn_protocol_products').where({ id: row.id }).update({ gates: JSON.stringify({ ...NOV_GATES, activeLargePatchTargetN: '0.4 lb N/1000' }) });
      await migration.down(knex);
      expect(await group(GRAVEX, 'frac_group')).toBe('3 + 7');
      expect(await group(DYLOX, 'irac_group')).toBeNull();
      const [edited, other] = await novRows();
      expect(edited.gates.activeLargePatchTargetN).toBe('0.4 lb N/1000');
      expect(other.gates).toEqual(NOV_GATES);
    });

    test('a key already present and a retired row are left', async () => {
      const [a, b] = await novRows();
      await knex('lawn_protocol_products').where({ id: a.id }).update({ gates: JSON.stringify({ ...NOV_GATES, activeLargePatchTargetN: '0.4 lb N/1000' }) });
      await knex('lawn_protocol_products').where({ id: b.id }).update({ gates: JSON.stringify({ ...NOV_GATES, retired: true }) });
      await migration.up(knex);
      const [c, d] = await novRows();
      expect(c.gates.activeLargePatchTargetN).toBe('0.4 lb N/1000');
      expect(d.gates).toEqual({ ...NOV_GATES, retired: true });
      await migration.down(knex);
      const [e, f] = await novRows();
      expect(e.gates.activeLargePatchTargetN).toBe('0.4 lb N/1000');
      expect(f.gates).toEqual({ ...NOV_GATES, retired: true });
    });
  });

  test('a catalog row that is missing skips only its own group', async () => {
    await reset({ gravex: false });
    await migration.up(knex);
    expect(await group(DYLOX, 'irac_group')).toBe('1B');
    expect(await knex('products_catalog').where({ id: ids.dimension }).first('hrac_group')).toEqual({ hrac_group: '3' });
    expect(await knex('products_catalog').where({ name: GRAVEX })).toHaveLength(0);
  });
});
