// Mix help of the lawn Fast Complete sheet (GATE_LAWN_MIX_HELP) through PostgreSQL: the staged-row read and the context block on real
// lawn_protocol_* rows, and gallons sprayed -> recorded spot area -> the places check (the per-place yearly amount) equal to the same
// visit entered by area. Own cloned schema; synthetic data only. Skips without DATABASE_URL (CI runs it against the migrated database).
const { randomUUID } = require('crypto');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009110000_lawn_trouble_areas');
const { etDateString, addETDays } = require('../utils/datetime-et');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
jest.setTimeout(60000);
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_SPOT_RULES', 'GATE_LAWN_TROUBLE_AREAS', 'GATE_LAWN_TREATMENT_GUIDE', 'GATE_LAWN_MIX_HELP'];
const ARENA = 'Arena 50 WDG';
const CELSIUS = 'Celsius WG';
const CERTAINTY = 'Certainty Turf Herbicide';
const NIS = 'Mix Help Surfactant';
const dayAgo = (n) => etDateString(addETDays(new Date(), -n));

describeDb('mix help through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  let areas;
  let help;
  let world;
  let protocol;
  const catalog = {};

  async function clone(table) {
    await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
    const columns = await knex(table).columnInfo();
    if (String(columns.id?.defaultValue || '').includes('nextval(')) {
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
    }
  }
  const gates = (on) => { for (const name of GATES) { if (on) process.env[name] = 'true'; else delete process.env[name]; } };
  const product = async (name, fields = {}) => {
    const [row] = await knex('products_catalog').insert({
      name, category: 'herbicide', default_rate_per_1000: 0.1, rate_unit: 'oz', label_verified_at: new Date(),
      inventory_on_hand: 1000, inventory_unit: 'oz', active: true, ...fields,
    }).returning('*');
    catalog[name] = row;
    return row;
  };
  let seq = 0;
  async function applied(name, { place = null, daysAgo = 5, rate = 0.1, unit = 'oz' } = {}) {
    seq += 1;
    await knex('property_application_history').insert({
      customer_id: world.customerId, property_id: world.property.id, product_id: catalog[name].id, application_date: dayAgo(daysAgo),
      application_rate: rate, rate_unit: unit, area_treated_sqft: 200, treated_place: place, notes: `row ${seq}`,
    });
  }
  const svcOf = async () => {
    const visit = await world.visit(0);
    return { id: visit.id, customer_id: world.customerId, property_id: world.property.id, scheduled_date: visit.scheduled_date, service_type: 'Lawn fixture' };
  };
  const loadPlan = async () => ({ plan: { protocol: { structured: { id: protocol.id } } } });

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions', 'service_products',
      'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'audit_log', 'product_limits', 'property_application_history']) {
      await clone(table);
    }
    for (const table of ['service_products', 'property_application_history']) {
      if (await knex.schema.hasColumn(table, 'treated_place')) await knex.schema.alterTable(table, (t) => t.dropColumn('treated_place'));
    }
    await knex.raw('DROP TABLE IF EXISTS lawn_trouble_areas');
    await migration.up(knex);
    await product(ARENA, { category: 'insecticide', default_rate_per_1000: 0.147, epa_reg_number: '59639-152' });
    await product(CELSIUS, { default_rate_per_1000: 0.085, epa_reg_number: '432-1507', mixing_order_category: 'dry_wg_wdg_wp_df' });
    await product(CERTAINTY, { epa_reg_number: '59639-226', mixing_order_category: 'liquid_flowable_sc' });
    await product(NIS, { category: 'adjuvant', mixing_order_category: 'adjuvant_last' });
    help = require('../services/lawn-mix-help');
    areas = require('../services/lawn-trouble-areas');
    world = await fixture(knex);
    // The staged rows as migration 20261005120000 states them: weed spots over 1 gal per 1,000, Arena over 4.
    [protocol] = await knex('lawn_protocols').insert({ protocol_key: `fixture_${randomUUID().slice(0, 6)}`, version: '2026.10-v13', name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
    const window = async (month) => (await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: `w_${month}_${randomUUID().slice(0, 6)}`, title: 'w', visit_type: 'fixture' }).returning('*'))[0];
    const may = await window(5);
    const oct = await window(10);
    const stage = (w, name, role, rate, unit, carrier, gates_ = {}) => knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: w.id, product_id: catalog[name].id, product_name: name, role, application_mode: 'spot', default_in_plan: false,
      rate_per_1000: rate, rate_unit: unit, carrier_gal_per_1000: carrier, gates: JSON.stringify(gates_),
    });
    for (const w of [may, oct]) {
      await stage(w, CELSIUS, 'post_emergent_spot', 0.085, 'oz', 1, { annualCounter: 'celsius_oz_per_1000' });
      await stage(w, CERTAINTY, 'post_emergent_spot', 0.028, 'oz', 1);
      await stage(w, NIS, 'adjuvant_spot', null, 'label_rate', 1, { concentration: '0.25% v/v' });
    }
    await stage(may, ARENA, 'insecticide_spot', 0.147, 'oz', 4);
    // A retired row never counts: a different carrier that would break the agreement if it were read.
    await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: oct.id, product_id: catalog[ARENA].id, product_name: ARENA, role: 'insecticide_spot', application_mode: 'spot', default_in_plan: false, rate_per_1000: 0.147, rate_unit: 'oz', carrier_gal_per_1000: 2, gates: JSON.stringify({ retired: true }) });
  }, 90000);
  afterAll(async () => { if (owned) await owned.dispose(); });
  beforeEach(async () => {
    require('../config/lawn-v13-count-caps').resetV13CapIdentity();
    gates(true);
    await knex('property_application_history').del();
    await knex('lawn_trouble_areas').del();
  });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  describe('the staged rows', () => {
    test('stagedRows reads a protocol\'s rows by product, retired rows left out', async () => {
      const rows = await help.stagedRows({ knex, protocolId: protocol.id, productIds: [catalog[ARENA].id, catalog[CELSIUS].id] });
      expect(rows.get(catalog[ARENA].id)).toHaveLength(1);
      expect(rows.get(catalog[CELSIUS].id)).toHaveLength(2);
      expect((await help.stagedRows({ knex, protocolId: protocol.id, productIds: [] })).size).toBe(0);
      expect((await help.stagedRows({ knex, protocolId: null, productIds: [catalog[ARENA].id] })).size).toBe(0);
    });

    test('the context block for the weed group and the chinch rung: Celsius + Certainty + surfactant in a 2 gallon tank, from the staged rows', async () => {
      const group = [CELSIUS, CERTAINTY, NIS].map((name) => catalog[name].id);
      const loaded = { plan: { protocol: { structured: { id: protocol.id } } }, items: [], addOns: group.map((id) => ({ product: { id } })) };
      const out = await help.contextBlock({ loaded, weed: { weedMix: { groupProductIds: group } }, chinch: { chinch: { rungIds: [catalog[ARENA].id] } }, month: 10, knex });
      const rows = out.mixHelp.rows;
      expect(rows[catalog[CELSIUS].id].perTank['2'].text).toBe('0.17 oz (4.82 g)');
      expect(rows[catalog[CERTAINTY].id].perTank['2'].text).toBe('0.06 oz (1.59 g)');
      expect(rows[catalog[NIS].id].perTank['2'].text).toBe('0.64 fl oz (18.9 mL)');
      expect(rows[catalog[ARENA].id]).toMatchObject({ carrierGalPer1000: 4 });
      expect(rows[catalog[ARENA].id].perTank['4'].text).toBe('0.15 oz (4.17 g)');
      expect(rows[catalog[CELSIUS].id].labelLines.map((line) => line.source)).toEqual(['Celsius WG label, Mixing Instructions', 'Celsius WG label, Precautions, item 3']);
      expect(out.mixHelp.weedOrder).toEqual([catalog[CELSIUS].id, catalog[CERTAINTY].id, catalog[NIS].id]);
    });

    test('gate off: the block is empty and the database is not touched', async () => {
      gates(false);
      const untouched = () => { throw new Error('the database was read'); };
      const out = await help.contextBlock({ loaded: { plan: { protocol: { structured: { id: protocol.id } } }, items: [], addOns: [{ product: { id: catalog[CELSIUS].id } }] }, month: 10, knex: untouched });
      expect(out).toEqual({});
    });
  });

  // The visit entered by AREA and the same visit entered by GALLONS must be judged the same by the places check: the per-place yearly
  // Arena amount (0.294 oz per 1,000 sq ft), where the quantity over the recorded area is the dose.
  describe('gallons -> recorded area -> the per-place limit equals the visit entered by area', () => {
    const arenaRow = (extra) => ({ productId: catalog[ARENA].id, name: ARENA, applicationMethod: 'spot_treatment', areaPlace: 'front', amountUnit: 'oz', ...extra });
    const byGallons = async (svc, row) => {
      const products = [row];
      const refusal = await help.withSprayedGallons({ knex, svc, products, loadPlan }, () => areas.preflightPlaces({ knex, svc, products }));
      return { refusal, row: products[0] };
    };

    test.each([
      ['a quantity that fits the remaining half of the yearly amount', 0.147, 4, 1000],
      ['the same quantity on a quarter of the area', 0.147, 1, 250],
      ['a large quantity on a small spot', 0.3, 4, 1000],
      ['the same large quantity spread over four times the area', 0.3, 16, 4000],
    ])('%s', async (_label, totalAmount, gallons, area) => {
      await applied(ARENA, { place: 'front', daysAgo: 100, rate: 0.147 });
      const svc = await svcOf();
      const typed = await areas.preflightPlaces({ knex, svc, products: [arenaRow({ totalAmount, areaValue: area, areaUnit: 'sqft' })] });
      const viaGallons = await byGallons(svc, arenaRow({ totalAmount, sprayedGallons: gallons }));
      expect(viaGallons.row).toMatchObject({ areaValue: area, areaUnit: 'sqft' });
      expect(viaGallons.refusal).toEqual(typed);
    });

    test('the two outcomes really differ with the area (the test can fail): the small spot is refused, the wide one fits', async () => {
      await applied(ARENA, { place: 'front', daysAgo: 100, rate: 0.147 });
      const svc = await svcOf();
      expect((await byGallons(svc, arenaRow({ totalAmount: 0.3, sprayedGallons: 4 }))).refusal).toMatchObject({ status: 400, payload: { code: 'lawn_place_limit', limitType: 'annual_max_rate' } });
      expect((await byGallons(svc, arenaRow({ totalAmount: 0.3, sprayedGallons: 16 }))).refusal).toBeNull();
    });

    // Celsius is judged over a rolling 365 days (not the calendar year): the gallons path must give the verdict a typed area gives.
    test.each([
      ['two passes at the front inside the rolling year: the front is refused', [300, 200], { status: 400, payload: { code: 'lawn_place_limit', limitType: 'annual_max_apps' } }],
      ['one of the two is older than 365 days: the front is open', [400, 200], null],
    ])('Celsius over the rolling year, %s', async (_label, daysAgo, expected) => {
      for (const days of daysAgo) await applied(CELSIUS, { place: 'front', daysAgo: days, rate: 0.085 });
      const svc = await svcOf();
      const row = (extra) => ({ productId: catalog[CELSIUS].id, name: CELSIUS, applicationMethod: 'spot_treatment', areaPlace: 'front', amountUnit: 'oz', totalAmount: 0.085, rate: 0.085, rateUnit: 'oz', ...extra });
      const typed = await areas.preflightPlaces({ knex, svc, products: [row({ areaValue: 1000, areaUnit: 'sqft' })] });
      const viaGallons = await byGallons(svc, row({ sprayedGallons: 1 }));
      expect(viaGallons.row).toMatchObject({ areaValue: 1000, areaUnit: 'sqft' });
      expect(viaGallons.refusal).toEqual(typed);
      if (expected) expect(typed).toMatchObject(expected); else expect(typed).toBeNull();
    });

    test('a product the staged rows give no carrier is refused (enter the area instead), and the gate off refuses the gallons', async () => {
      const svc = await svcOf();
      const noCarrier = (await byGallons(svc, { productId: catalog[NIS].id, name: NIS, applicationMethod: 'spot_treatment', areaPlace: 'front', sprayedGallons: 1 })).refusal;
      expect(noCarrier).toMatchObject({ status: 400, payload: { code: 'lawn_gallons_unavailable' } });
      gates(false);
      process.env.GATE_LAWN_V13 = 'true';
      process.env.GATE_LAWN_SPOT_RULES = 'true';
      const products = [arenaRow({ totalAmount: 0.147, areaValue: 700, areaUnit: 'sqft', sprayedGallons: 4 })];
      const next = jest.fn(async () => null);
      expect(await help.withSprayedGallons({ knex, svc, products, loadPlan }, next)).toMatchObject({ status: 400, payload: { code: 'lawn_gallons_unavailable' } });
      expect(next).not.toHaveBeenCalled();
      expect(products[0].areaValue).toBe(700);
    });
  });
});
