// GATE_LAWN_NOV_LARGE_PATCH_N (owner 2026-10-09) through the real plan engine and PostgreSQL (cloned schema): the v13 November
// 24-0-11 bag is sized for 0.5 lb N when the lawn has an ACTIVE mapped fungus area, and the one reduced target reaches the plan item,
// the completion defaults, the yearly-limit read and the note the technician sees. Synthetic data only. Skips without DATABASE_URL.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION } = require('../services/lawn-program');
const { etDateString, addETDays } = require('../utils/datetime-et');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
jest.setTimeout(60000);
const KEY = 'fixture_v13_lawn_nov';
const F24 = 'LESCO 24-0-11 with PolyPlus OPTI';
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY', 'GATE_LAWN_SPOT_RULES', 'GATE_LAWN_TREATMENT_GUIDE',
  'GATE_LAWN_TROUBLE_AREAS', 'GATE_LAWN_NOV_LARGE_PATCH_N'];
const NOTE = 'Active fungus mapped: nitrogen reduced to 0.5 lb N (2.1 lb per 1,000). Close the spreader over the patch and 6 ft around it.';
const day = etDateString(addETDays(new Date(), -1));

describeDb('November large patch nitrogen through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;

  async function clone(table) {
    await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
    const columns = await knex(table).columnInfo();
    if (String(columns.id?.defaultValue || '').includes('nextval(')) {
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
    }
  }
  const setGates = (on = GATES) => { for (const name of GATES) { if (on.includes(name)) process.env[name] = 'true'; else delete process.env[name]; } };

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'product_limits', 'property_application_history',
      'lawn_trouble_areas']) {
      await clone(table);
    }
    const [bag] = await knex('products_catalog').insert({
      name: F24, category: 'fertilizer', product_type: 'fertilizer', default_rate_per_1000: 4.2, rate_unit: 'lb', analysis_n: 24, analysis_p: 0, analysis_k: 11,
      label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'lb', active: true,
    }).returning('*');
    const [staged] = await knex('lawn_protocols').insert({ protocol_key: KEY, version: LAWN_V13_VERSION, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
    const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: staged.id, month: 11, window_key: 'nov_v13_spreader_feeding', title: 'November', visit_type: 'granular_production_plus_spots' }).returning('*');
    await knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: window.id, product_id: bag.id, product_name: F24, role: 'nutrition', application_mode: 'broadcast',
      default_in_plan: true, rate_per_1000: null, rate_unit: 'lb_n', gates: JSON.stringify({ targetN: '0.75 lb N/1000', blackoutSensitive: true }),
    });
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  }, 90000);
  afterAll(async () => { if (owned) await owned.dispose(); });
  beforeEach(async () => { setGates(); await knex('lawn_trouble_areas').del(); });
  afterEach(() => { for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; } });

  // A November visit at a fresh lawn, optionally with mapped areas ({ type, status }).
  async function novemberVisit(areas = []) {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
    await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, grass_type: 'bermuda', track_key: 'bermuda', lawn_sqft: 10000 });
    for (const [index, area] of areas.entries()) {
      await knex('lawn_trouble_areas').insert({
        customer_id: f.customerId, property_id: f.property.id, place: ['front', 'back', 'left_side', 'right_side'][index], type: area.type, status: area.status || 'active',
        source: 'tech_tap', first_seen_on: day, last_seen_on: day,
      });
    }
    return f.visit(0, { scheduled_date: '2026-11-10' });
  }
  const plan = (visit) => buildPlanForService(visit.id, { db: knex, includeCompletionDefaults: true });
  const bagOf = (list) => list.find((item) => item.product?.name === F24);
  const limitsSpy = () => jest.spyOn(require('../services/application-limits'), 'checkLimits');
  const limitedRate = (spy) => spy.mock.calls.find((call) => call[1] && call[4]?.proposed)?.[4].proposed.ratePer1000;

  test('active fungus, gate on: 2.083 lb per 1,000 (20.83 lb on 10,000 sq ft) in the plan item, the completion default and the limit read, with the note', async () => {
    const spy = limitsSpy();
    try {
      const result = await plan(await novemberVisit([{ type: 'fungus' }]));
      const item = bagOf(result.mixCalculator.items);
      expect(item.mix).toMatchObject({ rateSource: 'target_n_analysis', targetNPer1000: 0.5, amountUnit: 'lb' });
      expect(item.mix.ratePer1000).toBeCloseTo(2.0833, 3);
      expect(item.mix.amount).toBeCloseTo(20.833, 2);
      expect(item.gateNotes).toContainEqual({ key: 'activeFungusNitrogen', severity: 'note', text: NOTE });
      const defaulted = bagOf(result.completionDefaults.items);
      expect(defaulted.mix.ratePer1000).toBeCloseTo(2.0833, 3);
      expect(defaulted.mix.amount).toBeCloseTo(20.833, 2);
      expect(defaulted.gateNotes).toContainEqual(expect.objectContaining({ key: 'activeFungusNitrogen', text: NOTE }));
      expect(limitedRate(spy)).toBeCloseTo(2.0833, 3);
      // 2.083 lb x 24% = 0.5 lb N per 1,000.
      expect(item.mix.ratePer1000 * 0.24).toBeCloseTo(0.5, 3);
    } finally { spy.mockRestore(); }
  });

  test.each([
    ['no mapped area', []],
    ['take-all only', [{ type: 'take_all' }]],
    ['weeds and chinch only', [{ type: 'weeds' }, { type: 'chinch' }]],
    ['a CLEARED fungus area', [{ type: 'fungus', status: 'cleared' }]],
  ])('%s: the visit\'s 0.75 lb N (3.125 lb per 1,000), no note', async (_label, areas) => {
    const spy = limitsSpy();
    try {
      const result = await plan(await novemberVisit(areas));
      const item = bagOf(result.mixCalculator.items);
      expect(item.mix.ratePer1000).toBeCloseTo(3.125, 3);
      expect(item.mix.targetNPer1000).toBe(0.75);
      expect(JSON.stringify(item.gateNotes)).not.toContain('activeFungusNitrogen');
      expect(limitedRate(spy)).toBeCloseTo(3.125, 3);
    } finally { spy.mockRestore(); }
  });

  test('active fungus but the gate is off, or the trouble-areas gate is off: the old plan, no fungus note anywhere', async () => {
    const visit = await novemberVisit([{ type: 'fungus' }]);
    setGates(GATES.filter((name) => name !== 'GATE_LAWN_NOV_LARGE_PATCH_N'));
    const gateOff = await plan(visit);
    setGates(GATES.filter((name) => name !== 'GATE_LAWN_TROUBLE_AREAS'));
    const areasOff = await plan(visit);
    for (const result of [gateOff, areasOff]) {
      const item = bagOf(result.mixCalculator.items);
      expect(item.mix.ratePer1000).toBeCloseTo(3.125, 3);
      expect(JSON.stringify(result)).not.toContain('activeFungusNitrogen');
    }
  });

  test('a failed trouble-area read keeps the normal target and the plan still builds', async () => {
    const visit = await novemberVisit([{ type: 'fungus' }]);
    const areas = require('../services/lawn-trouble-areas');
    const spy = jest.spyOn(areas, 'loadActive').mockRejectedValue(Object.assign(new Error('db down'), { code: 'ECONNRESET' }));
    try {
      const result = await plan(visit);
      expect(bagOf(result.mixCalculator.items).mix.ratePer1000).toBeCloseTo(3.125, 3);
      expect(JSON.stringify(result)).not.toContain('activeFungusNitrogen');
    } finally { spy.mockRestore(); }
  });
});
