// Lawn protocol v13, Topchoice fire ant add-on: the guard migration (20261009102000, Codex round 2 on #6160), through the real
// migrations on PostgreSQL (cloned schema) and the real limit checker. Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned:
//   1. ownPass reaches every active Topchoice add-on row in the April and October windows, a row that was already there when
//      the first migration ran and a row staff edited before the follow-up included (only that key is added);
//   2. a hard limit with no match type is made an explicit product limit, so the closeout audit reads it too, without the
//      planner reporting the same violation twice;
//   3. the rollback truth table: a Topchoice row never loses ownPass while it stays, in any partial rollback; the rows
//      the first migration inserted leave only together with their gate; a pinned or staff-edited protocol stays whole.
const { isDeepStrictEqual } = require('node:util');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const first = require('../models/migrations/20261009100000_lawn_v13_fire_ant_granule');
const followup = require('../models/migrations/20261009101000_lawn_v13_fire_ant_granule_followup');
const guard = require('../models/migrations/20261009102000_lawn_v13_fire_ant_granule_guard');
const matrix = require('../models/migrations/20261007180000_lawn_v13_matrix_adds');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');
const limitChecker = require('../services/application-limits');

const GRANULE = first.GRANULE;
const ADVION = matrix.ADVION;
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_gd_a', 'fixture_gd_b'];
const [APR, OCT] = first.WINDOW_KEYS;
const JUL = 'jul_v13_inspect_spot';
const ADVION_GATES = { trigger: 'fire_ants_optional_add_on', optionalAddOn: true, officePrices: true };
const OWN_PASS_GATES = { ...ADVION_GATES, ownPass: true };
const SEED_NOTE = 'Seeded for lawn outline estimate packets from verified product/label source.';
const TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_audit_log',
  'lawn_protocol_service_completions', 'product_limits', 'lawn_protocol_product_actuals', 'service_products', 'property_application_history'];

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 Topchoice guard migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [table, constraint, suffix] of [
      ['product_limits', 'fixture_limits_product', ''], ['product_aliases', 'fixture_aliases_product', ''],
      ['service_products', 'fixture_sp_product', ' ON DELETE SET NULL'], ['lawn_protocol_products', 'fixture_lpp_product', ''],
    ]) {
      await knex.raw(`ALTER TABLE ??.?? ADD CONSTRAINT ${constraint} FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)${suffix}`, [owned.schema, table, owned.schema]);
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const ours = () => knex('lawn_protocol_audit_log').whereIn('action', [first.ACTION, first.CATALOG_ACTION, followup.ACTION, guard.ACTION_LIMITS, guard.ACTION_OWNPASS]);
  const limitsOf = (type) => knex('product_limits').where({ product_id: ids.top, ...(type ? { limit_type: type } : {}) }).orderBy(['limit_type', 'id']);
  // Every Topchoice row with its gates and protocol key (any window).
  const topRows = () => knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'p.product_name': GRANULE, 'l.version': V13 }).orderBy('p.id').select('p.id', 'p.gates', 'p.rate_per_1000', 'w.window_key', 'l.protocol_key');
  const byProtocol = async () => (await topRows()).reduce((acc, row) => ({ ...acc, [row.protocol_key]: [...(acc[row.protocol_key] || []), row] }), {});
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  async function snapshot() {
    return clean([
      await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']), await knex('lawn_protocol_windows').orderBy('id'),
      await knex('products_catalog').orderBy('name'), await knex('product_aliases').orderBy('alias_name'), await knex('product_limits').orderBy('id'),
      await knex('lawn_protocol_audit_log').orderBy('id'),
    ]);
  }
  // The invariant of finding 3: no Topchoice add-on row in the program lacks the gate.
  async function expectEveryRowCarriesOwnPass() {
    for (const row of await topRows()) expect({ id: row.id, ownPass: row.gates.ownPass }).toEqual({ id: row.id, ownPass: true });
  }

  async function reset({ preExisting = false, nullMatch = false } = {}) {
    for (const table of ['property_application_history', 'service_products', 'lawn_protocol_product_actuals', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products',
      'lawn_protocol_windows', 'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const [advion] = await knex('products_catalog').insert({ name: ADVION, category: 'insecticide', formulation: 'granular', epa_reg_number: '100-1481', rate_unit: 'lb', active: true }).returning('*');
    const [top] = await knex('products_catalog').insert({
      name: GRANULE, category: 'insecticide', product_type: 'pesticide', formulation: 'granular', epa_reg_number: '432-1217', restricted_use: false, default_rate_per_1000: 2,
      rate_unit: 'lb', irrigation_required: true, approved_for_service_report: true, label_source_note: SEED_NOTE, active: true,
    }).returning('*');
    ids.top = top.id;
    if (nullMatch) {
      // Hard limits of the right size that name no match type, as an admin or an older seed may have left them.
      await knex('product_limits').insert([
        { product_id: top.id, match_type: null, limit_type: 'annual_max_apps', limit_value: 1, limit_unit: 'applications', severity: 'hard_block', description: 'Null-match count.' },
        { product_id: top.id, match_type: null, limit_type: 'min_interval_days', limit_value: 365, limit_unit: 'days', severity: 'hard_block', description: 'Null-match interval.' },
      ]);
    }
    for (const key of KEYS) {
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      for (const [windowKey, month] of [[APR, 4], [OCT, 10], [JUL, 7]]) {
        const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
        if (windowKey !== JUL) {
          await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: advion.id, product_name: ADVION, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 0.0344, rate_unit: 'lb', default_in_plan: false, sort_order: 9, gates: JSON.stringify(ADVION_GATES) });
        }
        // A Topchoice row already in the window (the first migration then retires Advion and inserts nothing there).
        if (preExisting && key === KEYS[0] && windowKey === APR) {
          await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: top.id, product_name: GRANULE, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 2, rate_unit: 'lb', default_in_plan: false, sort_order: 20, gates: JSON.stringify(ADVION_GATES) });
        }
      }
    }
  }

  const upAll = async () => { await first.up(knex); await followup.up(knex); await guard.up(knex); };

  // ── 1. ownPass on every row ──────────────────────────────────────────────────
  describe('finding 1: ownPass on every Topchoice add-on row', () => {
    test('a Topchoice row that was already in a window (no insert by the first migration) gets ownPass; the inserted rows carry it from the follow-up', async () => {
      await reset({ preExisting: true });
      const [pre] = await topRows();
      await upAll();
      const rows = await topRows();
      expect(rows).toHaveLength(KEYS.length * 2 - 1 + 1);
      for (const row of rows) expect(row.gates).toEqual(OWN_PASS_GATES);
      expect(rows.find((row) => row.id === pre.id).gates).toEqual(OWN_PASS_GATES);
      const [log] = await knex('lawn_protocol_audit_log').where({ action: guard.ACTION_OWNPASS });
      expect(log.after_snapshot.added).toEqual([expect.objectContaining({ rowId: pre.id, gatesBefore: ADVION_GATES, gatesAfter: OWN_PASS_GATES })]);
    });

    test('the follow-up never saw the pre-existing row: only this migration wrote its gate (and the follow-up\'s list has no entry for it)', async () => {
      await reset({ preExisting: true });
      const [pre] = await topRows();
      await first.up(knex); await followup.up(knex);
      expect((await topRows()).find((row) => row.id === pre.id).gates).toEqual(ADVION_GATES);
      const [fu] = await knex('lawn_protocol_audit_log').where({ action: followup.ACTION });
      expect(fu.after_snapshot.rows.map((entry) => entry.rowId)).not.toContain(pre.id);
      await guard.up(knex);
      expect((await topRows()).find((row) => row.id === pre.id).gates).toEqual(OWN_PASS_GATES);
    });

    test('a row staff edited before the follow-up ran (so it was skipped) gets the key and keeps its edit', async () => {
      await reset();
      await first.up(knex);
      const [edited] = await topRows();
      await knex('lawn_protocol_products').where({ id: edited.id }).update({ rate_per_1000: 1.5, gates: JSON.stringify({ ...ADVION_GATES, officePrices: false }) });
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      try { await followup.up(knex); } finally { log.mockRestore(); }
      expect((await topRows()).find((row) => row.id === edited.id).gates).toEqual({ ...ADVION_GATES, officePrices: false });
      await guard.up(knex);
      const row = (await topRows()).find((r) => r.id === edited.id);
      expect(row.gates).toEqual({ ...ADVION_GATES, officePrices: false, ownPass: true });
      expect(Number(row.rate_per_1000)).toBe(1.5);
    });

    test('ownPass set to something other than true is left and logged; rows that are not the add-on, retired Advion rows, other windows and older versions are untouched', async () => {
      await reset();
      await first.up(knex);
      const [staffFalse, ...others] = await topRows();
      await knex('lawn_protocol_products').where({ id: staffFalse.id }).update({ gates: JSON.stringify({ ...ADVION_GATES, ownPass: false }) });
      // A Topchoice row in the July window, and one in April that is not an optional add-on.
      const julWindow = await knex('lawn_protocol_windows').where({ window_key: JUL }).first('id');
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: julWindow.id, product_id: ids.top, product_name: GRANULE, role: 'insecticide_optional_addon', application_mode: 'broadcast', default_in_plan: false, sort_order: 30, gates: JSON.stringify(ADVION_GATES) });
      const aprWindow = await knex('lawn_protocol_windows').where({ window_key: APR }).first('id');
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: aprWindow.id, product_id: ids.top, product_name: GRANULE, role: 'insecticide_spot', application_mode: 'spot', default_in_plan: false, sort_order: 31, gates: JSON.stringify({ trigger: 'fixture' }) });
      const advionBefore = clean(await knex('lawn_protocol_products').where({ product_name: ADVION }).orderBy('id'));
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      try {
        await guard.up(knex);
        expect(log).toHaveBeenCalledWith(expect.stringContaining(`the Topchoice row ${staffFalse.id} has ownPass set to false: left as it is`));
      } finally { log.mockRestore(); }
      const rows = await topRows();
      expect(rows.find((row) => row.id === staffFalse.id).gates).toEqual({ ...ADVION_GATES, ownPass: false });
      expect(rows.filter((row) => row.window_key === JUL).map((row) => row.gates)).toEqual([ADVION_GATES]);
      expect(rows.filter((row) => row.gates.trigger === 'fixture').map((row) => row.gates)).toEqual([{ trigger: 'fixture' }]);
      expect(clean(await knex('lawn_protocol_products').where({ product_name: ADVION }).orderBy('id'))).toBe(advionBefore);
      expect(others.length).toBeGreaterThan(0);
    });

    test('a second up changes nothing', async () => {
      await reset({ preExisting: true });
      await upAll();
      const before = await snapshot();
      await guard.up(knex);
      expect(await snapshot()).toBe(before);
    });

    test('nothing is written without a Topchoice row, or without a v13 protocol', async () => {
      await reset();
      await first.up(knex); await followup.up(knex);
      await knex('products_catalog').where({ id: ids.top }).update({ name: 'Renamed away' });
      let before = await snapshot();
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      try {
        await guard.up(knex);
        expect(log).toHaveBeenCalledWith(expect.stringContaining('not found in the catalog: nothing written'));
      } finally { log.mockRestore(); }
      expect(await snapshot()).toBe(before);
      await knex('products_catalog').where({ id: ids.top }).update({ name: GRANULE });
      await knex('lawn_protocols').update({ version: '2026.06' });
      before = await snapshot();
      await guard.up(knex);
      expect(await snapshot()).toBe(before);
    });
  });

  // ── 2. explicit product limits ───────────────────────────────────────────────
  describe('finding 2: count limits matched on the product', () => {
    beforeEach(async () => { await reset({ nullMatch: true }); });
    let customerId;
    const plan = (day) => limitChecker.checkLimits(customerId, ids.top, new Date(`${day}T16:00:00Z`), knex);
    const seedHistory = async (day) => {
      await knex('property_application_history').del();
      await knex('property_application_history').insert({ customer_id: customerId, product_id: ids.top, application_date: day, application_rate: 2, rate_unit: 'lb' });
    };
    beforeEach(async () => { customerId = (await fixture(knex)).customerId; });

    test('before: the first two migrations accept the null-match rows, and the closeout audit does not read them', async () => {
      await first.up(knex); await followup.up(knex);
      expect((await limitsOf()).map((row) => [row.limit_type, row.match_type])).toEqual([['annual_max_apps', null], ['min_interval_days', null]]);
      await seedHistory('2026-10-15');
      expect((await plan('2027-04-15')).blocks.map((b) => b.type)).toEqual(['min_interval_days']);
      expect(await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-04-15', knex)).toEqual([]);
    });

    test('after: both rows are product-matched hard limits (still two rows), the planner reports each violation once and the closeout audit sees them', async () => {
      await upAll();
      const rows = await limitsOf();
      expect(rows.map((row) => [row.limit_type, row.match_type, row.severity, Number(row.limit_value)])).toEqual([
        ['annual_max_apps', 'product', 'hard_block', 1], ['min_interval_days', 'product', 'hard_block', 365],
      ]);
      expect(rows.map((row) => row.description)).toEqual(['Null-match count.', 'Null-match interval.']);
      await seedHistory('2026-10-15');
      const april = await plan('2027-04-15');
      expect(april.allowed).toBe(false);
      expect(april.blocks.map((b) => b.type)).toEqual(['min_interval_days']);
      expect((await plan('2026-12-01')).blocks.map((b) => b.type).sort()).toEqual(['annual_max_apps', 'min_interval_days']);
      expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-04-15', knex)).map((v) => v.type)).toEqual(['min_interval_days']);
      expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2026-12-01', knex)).map((v) => v.type).sort()).toEqual(['annual_max_apps', 'min_interval_days']);
      expect(await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-10-15', knex)).toEqual([]);
    });

    test('an explicit product-matched row already there is left alone: no second row, no audit entry', async () => {
      await reset();
      await first.up(knex); await followup.up(knex);
      const before = clean(await limitsOf());
      await guard.up(knex);
      expect(clean(await limitsOf())).toBe(before);
      expect(await knex('lawn_protocol_audit_log').where({ action: guard.ACTION_LIMITS })).toEqual([]);
    });

    test('a row that is deleted or weakened after the follow-up is made explicit again (inserted, or tightened)', async () => {
      await reset();
      await first.up(knex); await followup.up(knex);
      await knex('product_limits').where({ product_id: ids.top, limit_type: 'min_interval_days' }).del();
      await knex('product_limits').where({ product_id: ids.top, limit_type: 'annual_max_apps' }).update({ limit_value: 3, severity: 'warning' });
      await guard.up(knex);
      expect((await limitsOf()).map((row) => [row.limit_type, row.match_type, row.severity, Number(row.limit_value)])).toEqual([
        ['annual_max_apps', 'product', 'hard_block', 1], ['min_interval_days', 'product', 'hard_block', 365],
      ]);
    });

    test('down never weakens a limit: the normalized and the inserted rows stay strict, and the audit row that records them stays', async () => {
      await upAll();
      const before = clean(await limitsOf());
      await guard.down(knex);
      expect(clean(await limitsOf())).toBe(before);
      expect((await limitsOf()).map((row) => [row.limit_type, row.match_type, row.severity, Number(row.limit_value)])).toEqual([
        ['annual_max_apps', 'product', 'hard_block', 1], ['min_interval_days', 'product', 'hard_block', 365],
      ]);
      expect(await knex('lawn_protocol_audit_log').where({ action: guard.ACTION_LIMITS })).toHaveLength(1);
      // Run again after its own down: nothing to write, nothing duplicated.
      await guard.up(knex);
      expect(clean(await limitsOf())).toBe(before);
      expect(await knex('lawn_protocol_audit_log').where({ action: guard.ACTION_LIMITS })).toHaveLength(1);
    });

    test('a limit the guard inserted stays through every down; a row it tightened back to the first migration\'s own write is that migration\'s to delete', async () => {
      await reset();
      await first.up(knex); await followup.up(knex);
      await knex('product_limits').where({ product_id: ids.top, limit_type: 'min_interval_days' }).del();
      await knex('product_limits').where({ product_id: ids.top, limit_type: 'annual_max_apps' }).update({ limit_value: 3, severity: 'warning' });
      await guard.up(knex);
      const strict = clean(await limitsOf());
      await guard.down(knex); await followup.down(knex); await first.down(knex);
      // The interval row the guard inserted stays. The count row is the first migration's own row (the guard only tightened it back to what
      // that migration wrote), so the first migration's down deletes it, exactly as it would have: nothing is weakened that the guard added.
      expect((await limitsOf()).map((row) => [row.limit_type, row.match_type, row.severity, Number(row.limit_value)])).toEqual([
        ['min_interval_days', 'product', 'hard_block', 365],
      ]);
      expect(strict).toBeTruthy();
    });

    test('a full in-order rollback with null-match limits: nothing throws, the rows go with their gate, and both limits stay product-matched hard blocks (the closeout audit still enforces them)', async () => {
      await upAll();
      await seedHistory('2026-10-15');
      await guard.down(knex); await followup.down(knex); await first.down(knex);
      expect(await topRows()).toEqual([]);
      expect((await limitsOf()).map((row) => [row.limit_type, row.match_type, row.severity, Number(row.limit_value)])).toEqual([
        ['annual_max_apps', 'product', 'hard_block', 1], ['min_interval_days', 'product', 'hard_block', 365],
      ]);
      expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-04-15', knex)).map((v) => v.type)).toEqual(['min_interval_days']);
      expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2026-12-01', knex)).map((v) => v.type).sort()).toEqual(['annual_max_apps', 'min_interval_days']);
    });

    test('null-match limits and a pinned protocol: after every partial rollback and the full one, the pinned protocol keeps its rows, and the planner and the closeout audit still enforce both limits', async () => {
      await upAll();
      await seedHistory('2026-10-15');
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      const expectEnforced = async () => {
        expect((await limitsOf()).map((row) => [row.limit_type, row.match_type])).toEqual([['annual_max_apps', 'product'], ['min_interval_days', 'product']]);
        expect((await plan('2027-04-15')).blocks.map((b) => b.type)).toEqual(['min_interval_days']);
        expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-04-15', knex)).map((v) => v.type)).toEqual(['min_interval_days']);
        expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2026-12-01', knex)).map((v) => v.type).sort()).toEqual(['annual_max_apps', 'min_interval_days']);
      };
      try {
        await guard.down(knex);
        await expectEnforced();
        await followup.down(knex);
        await expectEnforced();
        await first.down(knex);
        await expectEnforced();
        const rows = await byProtocol();
        expect(Object.keys(rows)).toEqual([KEYS[0]]);
        for (const row of rows[KEYS[0]]) expect(row.gates).toEqual(OWN_PASS_GATES);
      } finally {
        log.mockRestore();
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
    });

    test('null-match limits and a staff-edited Topchoice row: the same, the edited protocol stays whole and enforced', async () => {
      await upAll();
      await seedHistory('2026-10-15');
      const [row] = await topRows();
      await knex('lawn_protocol_products').where({ id: row.id }).update({ rate_per_1000: 1.5 });
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      try { await guard.down(knex); await followup.down(knex); await first.down(knex); } finally { log.mockRestore(); }
      expect(Object.keys(await byProtocol())).toEqual([row.protocol_key]);
      expect((await limitsOf()).map((r) => [r.limit_type, r.match_type])).toEqual([['annual_max_apps', 'product'], ['min_interval_days', 'product']]);
      expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-04-15', knex)).map((v) => v.type)).toEqual(['min_interval_days']);
    });

    test('without null-match limits the guard writes no limit work, so the first two migrations\' own limit rollback leaves the exact starting state', async () => {
      await reset();
      const before = await snapshot();
      await upAll();
      await guard.down(knex); await followup.down(knex); await first.down(knex);
      expect(await snapshot()).toBe(before);
    });
  });

  // ── 3. the rollback truth table ──────────────────────────────────────────────
  describe('finding 3: ownPass leaves a Topchoice row only with the row', () => {
    beforeEach(async () => { await reset(); });
    const quiet = async (fn) => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      try { await fn(); } finally { log.mockRestore(); }
    };

    test('after the guard is applied the follow-up\'s list is empty (its limit entry stays) and every inserted-row snapshot holds ownPass', async () => {
      await upAll();
      const [fu] = await knex('lawn_protocol_audit_log').where({ action: followup.ACTION });
      expect(fu.after_snapshot.rows).toEqual([]);
      expect(fu.after_snapshot.keptLive.rows).toHaveLength(KEYS.length * 2);
      expect(fu.after_snapshot.limits.inserted).toHaveLength(1);
      for (const log of await knex('lawn_protocol_audit_log').where({ action: first.ACTION })) {
        for (const made of log.after_snapshot.inserted) expect(made.owned.gates).toEqual(OWN_PASS_GATES);
      }
      const [own] = await knex('lawn_protocol_audit_log').where({ action: guard.ACTION_OWNPASS });
      expect(own.after_snapshot.rewritten).toHaveLength(KEYS.length * 2);
      expect(own.after_snapshot.neutralized).toHaveLength(1);
    });

    test('state 1 - guard down only: every Topchoice row keeps ownPass, the neutralized state stays', async () => {
      await upAll();
      await guard.down(knex);
      await expectEveryRowCarriesOwnPass();
      expect(await topRows()).toHaveLength(KEYS.length * 2);
      expect(await knex('lawn_protocol_audit_log').whereIn('action', [guard.ACTION_LIMITS, guard.ACTION_OWNPASS])).toEqual([]);
      const [fu] = await knex('lawn_protocol_audit_log').where({ action: followup.ACTION });
      expect(fu.after_snapshot.rows).toEqual([]);
    });

    test('state 2 - guard and follow-up down (the first stays): every row keeps ownPass, the 365-day interval is removed, nothing else of the follow-up remains', async () => {
      await upAll();
      await guard.down(knex);
      await followup.down(knex);
      await expectEveryRowCarriesOwnPass();
      expect(await limitsOf('min_interval_days')).toEqual([]);
      expect(await limitsOf('annual_max_apps')).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toEqual([]);
    });

    test('state 2b - the follow-up down alone while the guard is applied (knex migrate:down --name): ownPass stays on every row', async () => {
      await upAll();
      await followup.down(knex);
      await expectEveryRowCarriesOwnPass();
      expect(await limitsOf('min_interval_days')).toEqual([]);
      expect(await topRows()).toHaveLength(KEYS.length * 2);
    });

    test('state 3 - all three down in order: the rows go together with their gate, and every row, limit and audit row is back to before the first migration', async () => {
      const before = await snapshot();
      await upAll();
      await guard.down(knex); await followup.down(knex); await first.down(knex);
      expect(await topRows()).toEqual([]);
      expect(await snapshot()).toBe(before);
      expect(await ours()).toEqual([]);
    });

    test('state 3b - the first down alone while the follow-up and the guard are applied: the rows are deleted with their gate (never kept without it)', async () => {
      await upAll();
      await first.down(knex);
      expect(await topRows()).toEqual([]);
      for (const advion of await knex('lawn_protocol_products').where({ product_name: ADVION })) expect(advion.gates).toEqual(ADVION_GATES);
    });

    test('state 3c - up, full rollback, up, full rollback: the same end state both times', async () => {
      const before = await snapshot();
      await upAll(); await guard.down(knex); await followup.down(knex); await first.down(knex);
      await upAll(); await guard.down(knex); await followup.down(knex); await first.down(knex);
      expect(await snapshot()).toBe(before);
    });

    test('state 4 - a visit pinned to one protocol: through every partial and the full rollback, that protocol\'s rows keep ownPass; the other protocol goes with its gate', async () => {
      await upAll();
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
      try {
        await quiet(async () => {
          await guard.down(knex);
          await expectEveryRowCarriesOwnPass();
          await followup.down(knex);
          await expectEveryRowCarriesOwnPass();
          await first.down(knex);
        });
        const rows = await byProtocol();
        expect(Object.keys(rows)).toEqual([KEYS[0]]);
        for (const row of rows[KEYS[0]]) expect(row.gates).toEqual(OWN_PASS_GATES);
        expect(await limitsOf('min_interval_days')).toHaveLength(1);
        expect(await limitsOf('annual_max_apps')).toHaveLength(1);
        expect((await knex('products_catalog').where({ id: ids.top }).first()).restricted_use).toBe(true);
      } finally {
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
    });

    test.each([
      ['its rate', { rate_per_1000: 1.5 }],
      ['its order', { sort_order: 3 }],
      ['its mixing', { mixing: JSON.stringify({ note: 'staff' }) }],
    ])('state 5 - staff edited %s on an inserted row: that protocol stays whole with ownPass on both rows through the full rollback, the other goes with its gate', async (_label, edit) => {
      await upAll();
      const [row] = await topRows();
      await knex('lawn_protocol_products').where({ id: row.id }).update(edit);
      await quiet(async () => {
        await guard.down(knex); await followup.down(knex); await first.down(knex);
      });
      const rows = await byProtocol();
      expect(Object.keys(rows)).toEqual([row.protocol_key]);
      expect(rows[row.protocol_key]).toHaveLength(2);
      for (const kept of rows[row.protocol_key]) expect(kept.gates).toEqual(OWN_PASS_GATES);
      expect(await limitsOf('min_interval_days')).toHaveLength(1);
      await expectEveryRowCarriesOwnPass();
    });

    test('state 5b - staff edited a gate on an inserted row after the guard ran: that row and its protocol are kept (the gate stays in it)', async () => {
      await upAll();
      const [row] = await topRows();
      const edited = { ...OWN_PASS_GATES, extra: 'staff' };
      await knex('lawn_protocol_products').where({ id: row.id }).update({ gates: JSON.stringify(edited) });
      await quiet(async () => {
        await guard.down(knex); await followup.down(knex); await first.down(knex);
      });
      const rows = await byProtocol();
      expect(Object.keys(rows)).toEqual([row.protocol_key]);
      expect(rows[row.protocol_key].find((r) => r.id === row.id).gates).toEqual(edited);
      await expectEveryRowCarriesOwnPass();
    });

    test('state 5c - staff removed ownPass from a row after the guard ran: nothing re-adds it, and that row (no longer the snapshot) keeps its protocol whole', async () => {
      await upAll();
      const [row] = await topRows();
      await knex('lawn_protocol_products').where({ id: row.id }).update({ gates: JSON.stringify(ADVION_GATES) });
      await quiet(async () => {
        await guard.down(knex); await followup.down(knex); await first.down(knex);
      });
      const rows = await byProtocol();
      expect(Object.keys(rows)).toEqual([row.protocol_key]);
      expect(rows[row.protocol_key].find((r) => r.id === row.id).gates).toEqual(ADVION_GATES);
    });

    test('state 6 - an edited retired Advion row keeps its protocol whole, with ownPass on its Topchoice rows', async () => {
      await upAll();
      const advion = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
        .where({ 'p.product_name': ADVION }).orderBy('p.id').first('p.id', 'l.protocol_key');
      await knex('lawn_protocol_products').where({ id: advion.id }).update({ gates: JSON.stringify({ ...ADVION_GATES, retired: true, edited: true }) });
      await quiet(async () => {
        await guard.down(knex); await followup.down(knex); await first.down(knex);
      });
      const rows = await byProtocol();
      expect(Object.keys(rows)).toEqual([advion.protocol_key]);
      for (const kept of rows[advion.protocol_key]) expect(kept.gates).toEqual(OWN_PASS_GATES);
    });

    test('state 7 - a row the first migration did not insert keeps its gate through the full rollback (it is not the first migration\'s to delete)', async () => {
      await reset({ preExisting: true });
      const [pre] = await topRows();
      await upAll();
      await guard.down(knex); await followup.down(knex); await first.down(knex);
      const rows = await topRows();
      expect(rows.map((row) => row.id)).toEqual([pre.id]);
      expect(rows[0].gates).toEqual(OWN_PASS_GATES);
      // The Advion row beside it came back (un-retired).
      for (const advion of await knex('lawn_protocol_products').where({ product_name: ADVION })) expect(advion.gates).toEqual(ADVION_GATES);
    });

    test('the guard re-run after its own down writes nothing and leaves every Topchoice row with ownPass', async () => {
      await upAll();
      await guard.down(knex);
      const before = await snapshot();
      await guard.up(knex);
      expect(await snapshot()).toBe(before);
      await expectEveryRowCarriesOwnPass();
      expect(isDeepStrictEqual(await limitsOf('min_interval_days').then((r) => r.length), 1)).toBe(true);
    });
  });
});
