// Lawn v13 yearly count caps for Arena, Celsius, Certainty and Blindside
// (migration 20261007170000, owner 2026-10-06): insert-only, by explicit product id,
// and enforced per property through the real plan engine. Own cloned schema; synthetic data only.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261007170000_lawn_v13_count_caps');
const wording = require('../models/migrations/20261007171000_lawn_v13_count_caps_wording');
const { submittedProductLimitBlockPayload } = require('../services/complete-scheduled-service');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION } = require('../services/lawn-program');
const v13Recipe = require('../config/lawn-protocol-v13.json');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const NAMES = migration.CAPS.map((cap) => cap.name);
const [ARENA, CELSIUS, CERTAINTY, BLINDSIDE] = NAMES;
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY'];

describe('the recipe text (no database)', () => {
  test('every track states the Arena, Celsius + Certainty and Blindside counts', () => {
    for (const track of Object.values(v13Recipe)) {
      expect(track.notes.join('\n')).toContain('Arena: up to 2 applications per lawn per year (app-enforced); never treat the same area twice (tech rule; label 0.4 lb clothianidin per acre per year)');
      const safety = track.safety_rules.join('\n');
      expect(safety).toContain('Celsius, Certainty and Blindside: up to 2 applications per lawn per year each');
      expect(safety).not.toMatch(/per spot/);
    }
  });

  test('the migration writes 2 for each of the four products, by exact catalog name', () => {
    expect(NAMES).toEqual(['Arena 50 WDG', 'Celsius WG', 'Certainty Turf Herbicide', 'Blindside Herbicide']);
    expect(migration.CAPS.map((cap) => cap.limit_value)).toEqual([2, 2, 2, 2]);
  });
});

describeDb('v13 count caps through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  const catalog = {};

  async function clone(table) {
    await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
    const columns = await knex(table).columnInfo();
    if (String(columns.id?.defaultValue || '').includes('nextval(')) {
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
    }
  }
  const product = async (name, fields = {}) => {
    const [row] = await knex('products_catalog').insert({
      name, category: 'herbicide', default_rate_per_1000: 0.1, rate_unit: 'oz', label_verified_at: new Date(),
      inventory_on_hand: 1000, inventory_unit: 'oz', active: true, ...fields,
    }).returning('*');
    catalog[name] = row;
    return row;
  };
  const limitsOf = (name, type = 'annual_max_apps') => knex('product_limits').where({ product_id: catalog[name].id, limit_type: type }).orderBy('id');
  const allLimits = () => knex('product_limits').orderBy('id');

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'product_limits', 'property_application_history']) {
      await clone(table);
    }
    await product('Tetrino Insecticide', { category: 'insecticide', default_rate_per_1000: 0.367, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    await product(ARENA, { category: 'insecticide', default_rate_per_1000: 0.29 });
    await product(CELSIUS, { default_rate_per_1000: 0.085 });
    await product(CERTAINTY, { default_rate_per_1000: 0.028 });
    await product(BLINDSIDE);
    const surfactant = await product('LESCO 90/10 Nonionic Surfactant', { category: 'adjuvant', default_rate_per_1000: 0.25, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    const [staged] = await knex('lawn_protocols').insert({ protocol_key: 'fixture_v13_count_caps', version: LAWN_V13_VERSION, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
    const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: staged.id, month: 5, window_key: 'may_v13', title: 'may_v13', visit_type: 'fixture' }).returning('*');
    await knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: window.id, product_id: catalog['Tetrino Insecticide'].id, product_name: 'Tetrino Insecticide', role: 'insecticide', application_mode: 'broadcast',
      default_in_plan: true, rate_per_1000: 0.367, rate_unit: 'fl oz', gates: JSON.stringify({}),
    });
    for (const [row, rate, unit, gates] of [[catalog[ARENA], null, 'label_rate', { trigger: 'chinch' }], [catalog[CELSIUS], 0.085, 'oz', {}], [surfactant, null, 'label_rate', { concentration: '0.25% v/v' }]]) {
      await knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: window.id, product_id: row.id, product_name: row.name, role: 'post_emergent_spot', application_mode: 'spot',
        default_in_plan: false, rate_per_1000: rate, rate_unit: unit, carrier_gal_per_1000: 4, gates: JSON.stringify(gates),
      });
    }
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  describe('the migration', () => {
    beforeEach(async () => {
      await knex('product_limits').del(); await knex('product_aliases').del();
      jest.spyOn(console, 'log').mockImplementation(() => {});
    });
    afterEach(() => jest.restoreAllMocks());

    test('inserts one hard-block product row of 2 per product, nothing else', async () => {
      await migration.up(knex);
      const rows = await allLimits();
      expect(rows).toHaveLength(4);
      for (const name of NAMES) {
        const [row] = await limitsOf(name);
        expect(row).toMatchObject({ match_type: 'product', limit_type: 'annual_max_apps', limit_unit: 'applications', severity: 'hard_block' });
        expect(Number(row.limit_value)).toBe(2);
        expect(row.description).toContain(name);
      }
      expect((await limitsOf(ARENA))[0].description).toMatch(/never the same area twice/);
      // The frozen 170000 text; the wording migration below rewrites it.
    });

    test('a product that already has an annual_max_apps row keeps it exactly (value, unit, severity, description); the other products are still added', async () => {
      const [celsius] = await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 3, limit_unit: 'applications', severity: 'hard_block', description: 'Celsius WG: max 3 applications per year per property.' }).returning('*');
      const [certainty] = await knex('product_limits').insert({ product_id: catalog[CERTAINTY].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 5, limit_unit: 'apps', severity: 'warning', description: 'admin row' }).returning('*');
      await migration.up(knex);
      expect(await limitsOf(CELSIUS)).toEqual([celsius]);
      expect(await limitsOf(CERTAINTY)).toEqual([certainty]);
      expect(await limitsOf(ARENA)).toHaveLength(1);
      expect(await limitsOf(BLINDSIDE)).toHaveLength(1);
      expect(await allLimits()).toHaveLength(4);
    });

    test('other limit types on the product do not count: Celsius with only an interval row still gets its count cap', async () => {
      await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'min_interval_days', limit_value: 60, limit_unit: 'days', severity: 'warning', description: 'interval' });
      await migration.up(knex);
      expect(await limitsOf(CELSIUS)).toHaveLength(1);
      expect(await limitsOf(CELSIUS, 'min_interval_days')).toHaveLength(1);
    });

    test('a product missing from the catalog is skipped without an error; an exact alias resolves', async () => {
      await knex('products_catalog').where({ id: catalog[BLINDSIDE].id }).update({ name: 'Blindside renamed away' });
      await knex('products_catalog').where({ id: catalog[ARENA].id }).update({ name: 'Arena renamed away' });
      await knex('product_aliases').insert({ product_id: catalog[ARENA].id, alias_name: ARENA });
      try {
        await expect(migration.up(knex)).resolves.toBeUndefined();
        expect(console.log.mock.calls.flat().join('\n')).toMatch(/no catalog row or alias for Blindside Herbicide/);
      } finally {
        await knex('products_catalog').where({ id: catalog[BLINDSIDE].id }).update({ name: BLINDSIDE });
        await knex('products_catalog').where({ id: catalog[ARENA].id }).update({ name: ARENA });
      }
      expect(await limitsOf(ARENA)).toHaveLength(1);
      expect(await limitsOf(BLINDSIDE)).toHaveLength(0);
      expect(await allLimits()).toHaveLength(3);
    });

    test('a second up writes nothing', async () => {
      await migration.up(knex);
      const before = await allLimits();
      await migration.up(knex);
      expect(await allLimits()).toEqual(before);
    });

    test('down removes only the rows it wrote; admin rows, a row edited since and rows of other types stay; up again restores', async () => {
      const [admin] = await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 3, limit_unit: 'applications', severity: 'hard_block', description: 'Celsius WG: max 3 applications per year per property.' }).returning('*');
      const [interval] = await knex('product_limits').insert({ product_id: catalog[ARENA].id, match_type: 'product', limit_type: 'min_interval_days', limit_value: 14, limit_unit: 'days', severity: 'warning', description: 'interval' }).returning('*');
      await migration.up(knex);
      // Someone raised Blindside to 3 and Certainty to a warning after the deploy: both stay.
      await knex('product_limits').where({ product_id: catalog[BLINDSIDE].id, limit_type: 'annual_max_apps' }).update({ limit_value: 3 });
      await knex('product_limits').where({ product_id: catalog[CERTAINTY].id, limit_type: 'annual_max_apps' }).update({ severity: 'warning' });
      await migration.down(knex);
      const left = await allLimits();
      expect(left.map((r) => r.id).sort()).toEqual([admin.id, interval.id, ...(await limitsOf(BLINDSIDE)).map((r) => r.id), ...(await limitsOf(CERTAINTY)).map((r) => r.id)].sort());
      expect(await limitsOf(CELSIUS)).toEqual([admin]);
      expect(await limitsOf(ARENA)).toHaveLength(0);
      // Restore the two edited rows to what up wrote and take the full round trip.
      await knex('product_limits').where({ product_id: catalog[BLINDSIDE].id }).del();
      await knex('product_limits').where({ product_id: catalog[CERTAINTY].id }).del();
      await migration.up(knex);
      expect(await allLimits()).toHaveLength(5);
      await migration.down(knex);
      expect((await allLimits()).map((r) => r.id).sort()).toEqual([admin.id, interval.id].sort());
    });

    describe('the Celsius seed row (3 -> 2, owner 2026-10-06)', () => {
      const { CELSIUS_SEED, CELSIUS_LOWERED } = migration;
      const seed = (changes = {}) => knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...CELSIUS_SEED, ...changes }).returning('*').then(([row]) => row);
      const fields = (row) => ({ product_id: row.product_id, match_type: row.match_type, limit_type: row.limit_type, limit_value: Number(row.limit_value), limit_unit: row.limit_unit, severity: row.severity, description: row.description });

      test('the row that still equals the seed is lowered to 2 in place (same id, same unit and severity); no second Celsius row is added', async () => {
        const before = await seed();
        await migration.up(knex);
        const rows = await limitsOf(CELSIUS);
        expect(rows).toHaveLength(1);
        expect(rows[0].id).toBe(before.id);
        expect(fields(rows[0])).toEqual({ ...fields(before), limit_value: 2, description: CELSIUS_LOWERED.description });
        expect(await allLimits()).toHaveLength(4);
      });

      test.each([
        ['another value', { limit_value: 4 }],
        ['an edited description', { description: 'Celsius WG: max 3 applications per year. Admin note.' }],
        ['a softer severity', { severity: 'warning' }],
        ['another unit', { limit_unit: 'apps' }],
      ])('an admin-edited row (%s) is left exactly as it is and logged', async (_label, changes) => {
        const before = await seed(changes);
        await migration.up(knex);
        expect(await limitsOf(CELSIUS)).toEqual([before]);
        expect(console.log.mock.calls.flat().join('\n')).toMatch(/Celsius WG already has annual_max_apps/);
      });

      test('a second up changes nothing more', async () => {
        await seed();
        await migration.up(knex);
        const once = await allLimits();
        await migration.up(knex);
        expect(await allLimits()).toEqual(once);
      });

      test('down restores 3 and the seed description while the row still holds the lowered values; up again lowers it', async () => {
        const before = await seed();
        await migration.up(knex);
        await migration.down(knex);
        const [restored] = await limitsOf(CELSIUS);
        expect(restored.id).toBe(before.id);
        expect(fields(restored)).toEqual(fields(before));
        expect(await allLimits()).toHaveLength(1);
        await migration.up(knex);
        expect(Number((await limitsOf(CELSIUS))[0].limit_value)).toBe(2);
      });

      test('down leaves the row alone once someone edited it after the deploy (value or description)', async () => {
        await seed();
        await migration.up(knex);
        await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 1 });
        await migration.down(knex);
        expect(Number((await limitsOf(CELSIUS))[0].limit_value)).toBe(1);
        expect((await limitsOf(CELSIUS))[0].description).toBe(CELSIUS_LOWERED.description);

        await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ limit_value: 2, description: 'admin rewrote this' });
        await migration.down(knex);
        expect((await limitsOf(CELSIUS))[0]).toMatchObject({ description: 'admin rewrote this' });
        expect(Number((await limitsOf(CELSIUS))[0].limit_value)).toBe(2);
      });

      test('a Celsius row this inserted (no seed row) is deleted by down, never "restored" to 3', async () => {
        await migration.up(knex);
        expect(await limitsOf(CELSIUS)).toHaveLength(1);
        await migration.down(knex);
        expect(await limitsOf(CELSIUS)).toHaveLength(0);
      });
    });
  });

  describe('the property-wide wording (20261007171000)', () => {
    beforeEach(async () => {
      await knex('product_limits').del(); await knex('product_aliases').del();
      jest.spyOn(console, 'log').mockImplementation(() => {});
    });
    afterEach(() => jest.restoreAllMocks());
    const descriptions = async () => Object.fromEntries((await allLimits()).map((r) => [NAMES.find((n) => catalog[n].id === r.product_id), r.description]));
    const fieldsOf = (r) => ({ id: r.id, product_id: r.product_id, match_type: r.match_type, limit_type: r.limit_type, limit_value: Number(r.limit_value), limit_unit: r.limit_unit, severity: r.severity });

    test('rewrites only the descriptions: every row now says per lawn per year, none says per spot; Arena keeps the tech rule', async () => {
      await migration.up(knex);
      const before = (await allLimits()).map(fieldsOf);
      await wording.up(knex);
      expect((await allLimits()).map(fieldsOf)).toEqual(before);
      const after = await descriptions();
      for (const name of NAMES) {
        expect(after[name]).toMatch(/max 2 applications per lawn per year/);
        expect(after[name]).not.toMatch(/per spot|passes/);
      }
      expect(after[ARENA]).toMatch(/Never treat the same area twice \(tech rule, not enforced by the app\)/);
      expect(after[ARENA]).toMatch(/0\.4 lb clothianidin per acre per year/);
    });

    test('the lowered Celsius seed row gets the property-wide text too; a second up changes nothing; down restores the 170000 text', async () => {
      await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, ...migration.CELSIUS_SEED });
      await migration.up(knex);
      const lowered = await allLimits();
      await wording.up(knex);
      const once = await allLimits();
      expect(once.find((r) => r.product_id === catalog[CELSIUS].id).description).toBe('Celsius WG: max 2 applications per lawn per year (owner 2026-10-06; lowered from 3).');
      await wording.up(knex);
      expect(await allLimits()).toEqual(once);
      await wording.down(knex);
      expect((await allLimits()).map((r) => [r.id, r.description])).toEqual(lowered.map((r) => [r.id, r.description]));
    });

    test('an admin-edited row, or one with another value, is left alone; down touches only rows still holding the new text', async () => {
      await migration.up(knex);
      await knex('product_limits').where({ product_id: catalog[CERTAINTY].id }).update({ description: 'admin wrote this' });
      await knex('product_limits').where({ product_id: catalog[BLINDSIDE].id }).update({ limit_value: 3 });
      const before = await allLimits();
      await wording.up(knex);
      const after = await allLimits();
      for (const name of [CERTAINTY, BLINDSIDE]) {
        expect(after.find((r) => r.product_id === catalog[name].id)).toEqual(before.find((r) => r.product_id === catalog[name].id));
      }
      await knex('product_limits').where({ product_id: catalog[CELSIUS].id }).update({ description: 'admin rewrote Celsius' });
      await wording.down(knex);
      expect((await limitsOf(CELSIUS))[0].description).toBe('admin rewrote Celsius');
      expect((await limitsOf(ARENA))[0].description).toBe(migration.CAPS[0].description);
    });

    test('a row an admin owns (not one of the 170000 texts) is never rewritten', async () => {
      const [admin] = await knex('product_limits').insert({ product_id: catalog[CELSIUS].id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 2, limit_unit: 'applications', severity: 'hard_block', description: 'Celsius WG: max 2 passes per spot per year (admin).' }).returning('*');
      await wording.up(knex);
      expect(await limitsOf(CELSIUS)).toEqual([admin]);
    });
  });

  describe('the closeout check against real history (submittedProductLimitBlockPayload)', () => {
    beforeAll(async () => { await knex('product_limits').del(); await migration.up(knex); });
    beforeEach(() => { process.env.GATE_LAWN_V13 = 'true'; });

    async function setup(name, dates) {
      const f = await fixture(knex);
      const visitA = await f.visit(0, { scheduled_date: '2026-05-12', service_type: 'Every 6 Weeks Lawn Care Service' });
      const [propertyB] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '200 Fixture Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      const [visitB] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: propertyB.id, scheduled_date: '2026-05-12', service_type: 'Every 6 Weeks Lawn Care Service' }).returning('*');
      for (const date of dates) {
        const [past] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: visitA.property_id, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
        const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: past.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
        await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[name].id, application_date: date, application_rate: 0.085, rate_unit: 'oz', service_record_id: record.id });
      }
      return { visitA, visitB };
    }
    const check = (visit, ...names) => submittedProductLimitBlockPayload({ svc: visit, products: names.map((n) => ({ productId: catalog[n].id })), serviceDate: '2026-05-12', database: knex });

    test.each([CELSIUS, CERTAINTY, BLINDSIDE, ARENA])('%s: a 3rd application in the year at the same property is refused; at another property it is allowed', async (name) => {
      const { visitA, visitB } = await setup(name, ['2026-02-02', '2026-03-16']);
      expect(await check(visitA, name)).toMatchObject({ code: 'application_limit_reached', productId: catalog[name].id, productName: name, limitType: 'annual_max_apps', current: 2, max: 2 });
      expect(await check(visitB, name)).toBeNull();
    });

    test('the 2nd application is allowed, and a default product with no limit row is unaffected beside a capped one', async () => {
      const { visitA } = await setup(CELSIUS, ['2026-02-02']);
      expect(await check(visitA, CELSIUS)).toBeNull();
      const capped = await setup(CELSIUS, ['2026-02-02', '2026-03-16']);
      const refused = await check(capped.visitA, 'Tetrino Insecticide', CELSIUS);
      expect(refused).toMatchObject({ productName: CELSIUS });
      expect(await check(capped.visitA, 'Tetrino Insecticide')).toBeNull();
    });

    test('the visit\'s own ledger rows never count against it (a retry)', async () => {
      const f = await fixture(knex);
      const visit = await f.visit(0, { scheduled_date: '2026-05-12', service_type: 'Every 6 Weeks Lawn Care Service' });
      const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: visit.id, service_date: '2026-05-12', service_type: 'Lawn fixture' }).returning('*');
      for (const date of ['2026-02-02', '2026-05-12']) {
        await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[CELSIUS].id, application_date: date, application_rate: 0.085, rate_unit: 'oz', service_record_id: date === '2026-05-12' ? record.id : null });
      }
      expect(await check(visit, CELSIUS)).toBeNull();
    });
  });

  describe('through the plan: the count is the treated property\'s', () => {
    beforeAll(async () => { await knex('product_limits').del(); await migration.up(knex); });

    async function twoProperties(name, dates) {
      const f = await fixture(knex);
      await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
      await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, grass_type: 'bermuda', track_key: 'bermuda', lawn_sqft: 10000 });
      const visitA = await f.visit(0, { scheduled_date: '2026-05-12' });
      const [propertyB] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '200 Fixture Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      const [visitB] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: propertyB.id, scheduled_date: '2026-05-12', service_type: 'Lawn fixture' }).returning('*');
      for (const date of dates) {
        const [past] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: visitA.property_id, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
        const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: past.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
        await knex('property_application_history').insert({ customer_id: f.customerId, product_id: catalog[name].id, application_date: date, application_rate: 0.085, rate_unit: 'oz', service_record_id: record.id });
      }
      return { visitA, visitB };
    }
    const plan = (visit, name) => {
      process.env.GATE_LAWN_V13 = 'true';
      return buildPlanForService(visit.id, { db: knex, selectedConditionalProductNames: [name] });
    };
    const limitBlocks = (result) => result.propertyGate.blocks.filter((b) => b.code === 'lawn_v13_annual_limit');

    test.each([CELSIUS, ARENA])('%s: a third application in the year at the same property is blocked; one at another property is not', async (name) => {
      const { visitA, visitB } = await twoProperties(name, ['2026-02-02', '2026-03-16']);
      const resultA = await plan(visitA, name);
      expect(limitBlocks(resultA)).toHaveLength(1);
      expect(limitBlocks(resultA)[0]).toMatchObject({ productName: name });
      expect(limitBlocks(resultA)[0].message).toMatch(/2\/2 applications this year — LIMIT REACHED/);
      expect(resultA.status).toBe('blocked');
      const resultB = await plan(visitB, name);
      expect(limitBlocks(resultB)).toEqual([]);
    });

    test('the second application in the year is still allowed', async () => {
      const { visitA } = await twoProperties(CELSIUS, ['2026-02-02']);
      const result = await plan(visitA, CELSIUS);
      expect(limitBlocks(result)).toEqual([]);
    });
  });
});
