// 20261008132000, the rollback guard for the frozen December migrations 20261008130000 and 20261008131000 (Codex round 2 on #6137),
// through all three real migrations on PostgreSQL (cloned schema). Synthetic data only.
//
// The finding: the frozen down() counts only the protocols that have a December swap log and are referenced by a visit or a
// completion. A referenced protocol with no swap log (its December row already named the 10-0-22) left the count at zero, so
// the rollback cleared the analysis and watering fields the migration had filled on the still-used catalog row. The guard's
// down() runs first and, when any v13 protocol is referenced, neutralizes the frozen catalog audit row (the originals stay under
// keptLive); its up() puts a neutralized row back.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const engine = require('../services/waveguard-plan-engine');
const v13Recipe = require('../config/lawn-protocol-v13.json');
const frozen = require('../models/migrations/20261008130000_lawn_v13_december_potash');
const followup = require('../models/migrations/20261008131000_lawn_v13_december_potash_followup');
const guard = require('../models/migrations/20261008132000_lawn_v13_december_potash_rollback_guard');
const { neutralizeAuditRows } = require('../services/lawn-v13-rollback-guard');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');

const F24 = frozen.OLD_NAME;
const F10 = frozen.NEW_NAME;
const V13 = staged.V13_VERSION;
const DEC = frozen.DECEMBER_WINDOW;
// A is the Codex protocol: its December row already names the 10-0-22. B is swapped by the frozen up.
const A = 'fixture_guard_a';
const B = 'fixture_guard_b';
const TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products',
  'lawn_protocol_audit_log', 'lawn_protocol_service_completions', 'product_limits', 'service_products'];

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 December rollback guard through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    // LIKE copies no foreign keys; the frozen down reads them to know whether the product is referenced.
    await knex.raw('ALTER TABLE ??.product_limits ADD CONSTRAINT fixture_limits_product FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)', [owned.schema, owned.schema]);
    await knex.raw('ALTER TABLE ??.lawn_protocol_products ADD CONSTRAINT fixture_lpp_product FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)', [owned.schema, owned.schema]);
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const newRow = () => knex('products_catalog').where({ name: F10 }).first();
  const logs = (action) => knex('lawn_protocol_audit_log').where({ action });
  const decemberRow = async (key) => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'w.window_key': DEC, 'p.role': 'nutrition', 'l.protocol_key': key }).first('p.*');
  const allUp = async () => { await frozen.up(knex); await followup.up(knex); await guard.up(knex); };
  const allDown = async () => { await guard.down(knex); await followup.down(knex); await frozen.down(knex); };
  const FILLED = ['analysis_n', 'analysis_k', 'slow_release_n_pct', 'post_application_watering'];

  // A pre-existing 10-0-22 row with none of the fields the frozen migration fills; protocol A already uses it.
  async function reset({ existing = true, aUsesNew = true } = {}) {
    for (const table of ['service_products', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const [f24] = await knex('products_catalog').insert({ name: F24, category: 'fertilizer', formulation: 'granular', analysis_n: 24, analysis_p: 0, analysis_k: 11, default_rate_per_1000: 4.2, rate_unit: 'lb', active: true }).returning('*');
    ids.f24 = f24.id;
    ids.f10 = existing ? (await knex('products_catalog').insert({ name: F10, category: 'fertilizer', formulation: 'granular', active: true, needs_pricing: false }).returning('*'))[0].id : null;
    for (const key of [A, B]) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' });
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const [dec] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 12, window_key: DEC, title: DEC, visit_type: 'granular_production_plus_spots', production_mode: 'spreader_plus_spot_backpack' }).returning('*');
      const usesNew = existing && aUsesNew && key === A;
      await knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: dec.id, product_id: usesNew ? ids.f10 : f24.id, product_name: usesNew ? F10 : F24, role: 'nutrition', application_mode: 'broadcast',
        rate_unit: 'lb_n', default_in_plan: true, sort_order: 53, gates: JSON.stringify({ targetN: '0.45 lb N/1000' }),
      });
    }
  }
  const pin = async (key) => {
    const f = await fixture(knex);
    return f.visit(0, { lawn_protocol_key: key, lawn_protocol_version: V13 });
  };
  const unpin = (visit) => knex('scheduled_services').where({ id: visit.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
  const derive = async () => {
    const product = await newRow();
    const notes = v13Recipe.st_augustine.visits.find((v) => v.month === 'Dec').notes;
    return engine.calculateProductAmount({
      product, lawnSqft: 1000, areaFactor: 1, ...engine.parseVisitNutrientTargets(notes), ...engine.v13RateOptions({ ratePer1000: null, rateUnit: 'lb_n' }),
    });
  };

  test('the finding: without the guard, a rollback clears the fills while protocol A (no swap log) still uses the row', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset();
    await frozen.up(knex); await followup.up(knex);
    expect(Number((await newRow()).analysis_n)).toBe(10);
    const visit = await pin(A);
    try {
      await followup.down(knex); await frozen.down(knex);
      const row = await newRow();
      expect(FILLED.map((column) => row[column])).toEqual([null, null, null, null]);
    } finally { log.mockRestore(); await unpin(visit); }
  });

  test('the Codex scenario: a referenced protocol whose December row already names the 10-0-22 keeps the row and its fills through a rollback of all three, and the step still derives 4.5 lb', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset();
    await allUp();
    const before = await newRow();
    const visit = await pin(A);
    try {
      await allDown();
      const row = await newRow();
      expect(row).toBeDefined();
      expect(row.id).toBe(before.id);
      for (const column of FILLED) expect(row[column]).toEqual(before[column]);
      expect(await derive()).toMatchObject({ rateSource: 'target_n_analysis', ratePer1000: 4.5, amount: 4.5 });
      // A is untouched (it never had a swap); B, not referenced, went back to the 24-0-11.
      expect(await decemberRow(A)).toMatchObject({ product_name: F10, product_id: row.id });
      expect(await decemberRow(B)).toMatchObject({ product_name: F24, product_id: ids.f24 });
      // The frozen down consumed the catalog audit row (its originals are gone with it); A had no swap log and has none.
      expect(await logs(frozen.ACTION)).toHaveLength(0);
    } finally { log.mockRestore(); await unpin(visit); }
  });

  test('the same when the referenced protocol also has Arena and weed-season logs (the helpers that return "retained" and are not counted)', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset();
    const [art] = await knex('products_catalog').insert([{ name: staged.NAMES.ARE, category: 'insecticide', active: true }, { name: 'Blindside Herbicide', category: 'herbicide', active: true }]).returning('*');
    for (const key of [A, B]) {
      const [protocol] = await knex('lawn_protocols').where({ protocol_key: key, version: V13 });
      const [may] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 5, window_key: 'may_v13_tetrino_hose', title: 'may', visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert([
        { lawn_protocol_window_id: may.id, product_id: art.id, product_name: staged.NAMES.ARE, role: 'insecticide_spot', application_mode: 'spot', rate_unit: 'label_rate', carrier_gal_per_1000: 4, default_in_plan: false, gates: JSON.stringify({ trigger: 'chinch_20_to_25_per_sqft' }) },
        { lawn_protocol_window_id: may.id, product_id: (await knex('products_catalog').where({ name: 'Blindside Herbicide' }).first()).id, product_name: 'Blindside Herbicide', role: 'post_emergent_spot', application_mode: 'spot', rate_unit: 'label_rate', default_in_plan: false, gates: JSON.stringify({ trigger: 'celsius_annual_cap_reached' }) },
      ]);
    }
    await allUp();
    expect(await logs(frozen.ARENA_ACTION)).toHaveLength(2);
    expect(await logs(frozen.WEED_ACTION)).toHaveLength(2);
    const visit = await pin(A);
    try {
      await allDown();
      expect(Number((await newRow()).analysis_n)).toBe(10);
      // A keeps its Arena and weed-season state (retained); B, not referenced, went back to the staged state.
      const arenaRates = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
        .where({ 'p.product_name': staged.NAMES.ARE }).select('l.protocol_key', 'p.rate_per_1000', 'p.rate_unit');
      expect(arenaRates.map((r) => [r.protocol_key, r.rate_per_1000 == null ? null : Number(r.rate_per_1000), r.rate_unit]).sort()).toEqual([[A, 0.147, 'oz'], [B, null, 'label_rate']]);
    } finally { log.mockRestore(); await unpin(visit); }
  });

  test('a completion on protocol A guards the same way', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset();
    await allUp();
    const [protocol] = await knex('lawn_protocols').where({ protocol_key: A, version: V13 });
    await knex('lawn_protocol_service_completions').insert({ service_record_id: require('crypto').randomUUID(), lawn_protocol_id: protocol.id, protocol_key: A, protocol_version: V13 });
    try {
      await allDown();
      expect(Number((await newRow()).analysis_n)).toBe(10);
    } finally { log.mockRestore(); await knex('lawn_protocol_service_completions').del(); }
  });

  test('a protocol that becomes referenced AFTER the migrations ran is guarded too: the frozen down decides at rollback time', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset();
    await allUp();
    const visit = await pin(A); // pinned only now
    try {
      await allDown();
      expect(Number((await newRow()).analysis_n)).toBe(10);
    } finally { log.mockRestore(); await unpin(visit); }
  });

  test('an unreferenced clean rollback of all three removes everything: the fills and the logs', async () => {
    await reset();
    await allUp();
    expect(await logs(frozen.ACTION)).toHaveLength(1); // B's swap log (A already named the row)
    await allDown();
    const row = await newRow();
    expect(FILLED.map((column) => row[column])).toEqual([null, null, null, null]);
    expect([row.default_rate_per_1000, row.rate_unit]).toEqual([null, null]);
    expect(await knex('lawn_protocol_audit_log')).toEqual([]);
    expect(await decemberRow(B)).toMatchObject({ product_name: F24 });
  });

  test('a row the migration inserted is removed by a clean rollback of all three, and kept while any protocol is referenced', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset({ existing: false });
    await allUp();
    await allDown();
    expect(await newRow()).toBeUndefined();
    await reset({ existing: false });
    await allUp();
    const visit = await pin(B);
    try {
      await allDown();
      expect(await newRow()).toBeDefined();
    } finally { log.mockRestore(); await unpin(visit); }
  });

  test('a referenced protocol WITH a swap log (B) guards the catalog the same way; the unreferenced protocol (A, no swap log) is left as it was', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset();
    await allUp();
    const visit = await pin(B);
    try {
      await allDown();
      expect(Number((await newRow()).analysis_n)).toBe(10);
      expect(await decemberRow(B)).toMatchObject({ product_name: F10 }); // referenced: whole
      expect(await decemberRow(A)).toMatchObject({ product_name: F10 });
    } finally { log.mockRestore(); await unpin(visit); }
  });

  test('partial reference: the referenced protocol stays whole, the unreferenced one goes back to the staged state, and the catalog stays because a referenced protocol uses it', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset({ aUsesNew: false });
    await allUp();
    expect(await decemberRow(A)).toMatchObject({ product_name: F10 });
    const visit = await pin(A);
    try {
      await allDown();
      expect(await decemberRow(A)).toMatchObject({ product_name: F10 });
      expect(await decemberRow(B)).toMatchObject({ product_name: F24, product_id: ids.f24 });
      const row = await newRow();
      expect(Number(row.analysis_n)).toBe(10);
      expect(await derive()).toMatchObject({ rateSource: 'target_n_analysis', amount: 4.5 });
    } finally { log.mockRestore(); await unpin(visit); }
  });

  describe('the guard\'s own up and down', () => {
    const catalogLog = async () => (await logs(frozen.CATALOG_ACTION).first());

    test('nothing referenced: down rewrites nothing', async () => {
      await reset();
      await allUp();
      const before = JSON.stringify(await catalogLog());
      await guard.down(knex);
      expect(JSON.stringify(await catalogLog())).toBe(before);
    });

    test('referenced: down neutralizes the frozen catalog row only (originals under keptLive), a second down changes nothing, up puts the original back exactly', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await reset();
      await allUp();
      const original = (await catalogLog()).after_snapshot;
      const others = JSON.stringify(await knex('lawn_protocol_audit_log').whereNot({ action: frozen.CATALOG_ACTION }).orderBy('id'));
      const visit = await pin(A);
      try {
        await guard.down(knex);
        const neutral = (await catalogLog()).after_snapshot;
        expect(neutral).toMatchObject({ inserted: null, filled: [], keptLive: original });
        expect(JSON.stringify(await knex('lawn_protocol_audit_log').whereNot({ action: frozen.CATALOG_ACTION }).orderBy('id'))).toBe(others);
        await guard.down(knex);
        expect((await catalogLog()).after_snapshot).toEqual(neutral);
        await guard.up(knex);
        expect((await catalogLog()).after_snapshot).toEqual(original);
        await guard.up(knex); // nothing to restore
        expect((await catalogLog()).after_snapshot).toEqual(original);
      } finally { log.mockRestore(); await unpin(visit); }
    });

    test('rolled back ALONE while a protocol is referenced, then up again: the other two stay applied and a later rollback of all three, with nothing referenced, is a clean undo', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await reset();
      await allUp();
      const visit = await pin(A);
      try {
        await guard.down(knex);
        expect(await decemberRow(B)).toMatchObject({ product_name: F10 }); // the frozen files are still applied
        await guard.up(knex);
      } finally { log.mockRestore(); await unpin(visit); }
      await allDown();
      const row = await newRow();
      expect(FILLED.map((column) => row[column])).toEqual([null, null, null, null]);
      expect(await decemberRow(B)).toMatchObject({ product_name: F24 });
      expect(await knex('lawn_protocol_audit_log')).toEqual([]);
    });

    test('rolled back alone while referenced and NOT put back: the frozen files rolled back later, with nothing referenced, leave the fills as residue and lose nothing', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await reset();
      await allUp();
      const visit = await pin(A);
      try { await guard.down(knex); } finally { log.mockRestore(); await unpin(visit); }
      await followup.down(knex); await frozen.down(knex);
      const row = await newRow();
      expect(row).toBeDefined();
      expect(Number(row.analysis_n)).toBe(10); // residue on a row that existed before; never data loss
      expect(await decemberRow(B)).toMatchObject({ product_name: F24 });
    });

    test('neutralizeAuditRows on the frozen catalog row reads as nothing to revert to the frozen down, whatever the inserted/filled content was', async () => {
      await reset({ existing: false });
      await allUp();
      await neutralizeAuditRows(knex, guard.EMPTY_BY_ACTION);
      await frozen.down(knex);
      // The inserted row is not deleted by a down that was told nothing was inserted.
      expect(await newRow()).toBeDefined();
    });
  });

  test('up, down, up of all three leaves the same state', async () => {
    for (const options of [{ existing: true }, { existing: false }]) {
      await reset(options);
      await allUp();
      const state = async () => JSON.stringify([await newRow(), await decemberRow(A), await decemberRow(B), await knex('lawn_protocol_audit_log').orderBy('action').select('action', 'after_snapshot')],
        (key, value) => (['id', 'updated_at', 'created_at', 'productId', 'product_id', 'rowId', 'lawn_protocol_window_id', 'logId', 'before', 'after'].includes(key) && typeof value === 'string' ? undefined : value));
      const first = await state();
      await allDown();
      await allUp();
      expect(await state()).toBe(first);
    }
  });

  test('up, down (with a protocol referenced), up of all three: the guarded rollback leaves the catalog, and applying again is stable', async () => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    await reset();
    await allUp();
    const visit = await pin(A);
    try {
      await allDown();
      await allUp();
      const row = await newRow();
      expect(Number(row.analysis_n)).toBe(10);
      expect(Number(row.default_rate_per_1000)).toBe(4.5);
      expect(await derive()).toMatchObject({ rateSource: 'target_n_analysis', amount: 4.5 });
    } finally { log.mockRestore(); await unpin(visit); }
    await allDown();
    expect(await knex('lawn_protocol_audit_log')).toEqual([]);
  });
});
