// Lawn protocol v13 field rules through PostgreSQL (cloned schema): the migration
// 20261007150000 up and down on real rows, and the North Port hold through the real
// plan engine. Synthetic data only.
const { randomUUID } = require('crypto');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION } = require('../services/lawn-program');
const { heldProductBlocks } = require('../services/complete-scheduled-service');
const migration = require('../models/migrations/20261007150000_lawn_v13_field_rules');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const { NUTRA, ACELEPRYN, DISMISS } = migration.NAMES;
const DIMENSION = 'Dimension 2EW Dithiopyr 24% Pre-Emergent Liquid Herbicide';
const TABLES = ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
  'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
  'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
  'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'lawn_protocol_audit_log', 'product_limits',
  'property_application_history'];

describeDb('v13 field rules through PostgreSQL', () => {
  const savedGate = process.env.GATE_LAWN_V13;
  let owned;
  let knex;
  const protocols = {};
  const rows = {};

  async function window(protocol, month, key) {
    const [row] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: key, title: key, visit_type: 'fixture' }).returning('*');
    return row;
  }
  async function productRow(win, name, changes = {}) {
    const [catalog] = await knex('products_catalog').where({ name });
    const [row] = await knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: win.id, product_id: catalog?.id || null, product_name: name, role: 'fixture', application_mode: 'broadcast',
      default_in_plan: true, gates: JSON.stringify({}), sort_order: 1, ...changes,
    }).returning('*');
    return row;
  }
  const gatesOf = async (id) => (await knex('lawn_protocol_products').where({ id }).first('gates')).gates;

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [name, category, rate, unit] of [[NUTRA, 'micronutrient', 12, 'fl oz'], [DIMENSION, 'herbicide', 0.5, 'fl oz'], [ACELEPRYN, 'insecticide', 0.07, 'fl oz'], [DISMISS, 'herbicide', 0.1, 'fl oz']]) {
      await knex('products_catalog').insert({
        name, category, default_rate_per_1000: rate, rate_unit: unit, label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: unit, active: true,
      });
    }
    // Two staged v13 protocols (the migration visits every one) and one older protocol it must leave alone.
    for (const track of ['bermuda', 'zoysia']) {
      [protocols[track]] = await knex('lawn_protocols').insert({
        protocol_key: `fixture_field_rules_${track}`, version: LAWN_V13_VERSION, name: `Fixture ${track}`, status: 'staged', grass_track: track, region: 'swfl', effective_from: '2000-01-01',
      }).returning('*');
      const june = await window(protocols[track], 6, 'jun_v13_hose_blackout');
      const january = await window(protocols[track], 1, 'jan_v13_pre_m_hose');
      const july = await window(protocols[track], 7, 'jul_v13_inspect_spot');
      rows[track] = {
        nutraJune: await productRow(june, NUTRA, { rate_per_1000: 12, rate_unit: 'fl oz', carrier_gal_per_1000: 1 }),
        dimensionJune: await productRow(june, DIMENSION, { rate_per_1000: 0.5, rate_unit: 'fl oz', carrier_gal_per_1000: 1, sort_order: 2 }),
        nutraJanuary: await productRow(january, NUTRA, { rate_per_1000: 6, rate_unit: 'fl oz', carrier_gal_per_1000: 1 }),
        dismissJanuary: await productRow(january, DISMISS, { application_mode: 'spot', default_in_plan: false, gates: JSON.stringify({ novToMarOnly: true }), sort_order: 9 }),
        acelepryn: await productRow(july, ACELEPRYN, { application_mode: 'spot', default_in_plan: false, gates: JSON.stringify({ trigger: 'caterpillars' }) }),
        dismissJuly: await productRow(july, DISMISS, { application_mode: 'spot', default_in_plan: false, sort_order: 9 }),
      };
    }
    const [older] = await knex('lawn_protocols').insert({ protocol_key: 'fixture_field_rules_old', version: '2026.06', name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' }).returning('*');
    rows.older = await productRow(await window(older, 1, 'old_1'), DISMISS, { default_in_plan: false });
    // A completion actual that references one Dismiss row: that row must stay.
    await knex('lawn_protocol_product_actuals').insert({
      lawn_protocol_service_completion_id: randomUUID(), protocol_product_id: rows.bermuda.dismissJuly.id, product_name: DISMISS,
    });
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  });
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => { if (savedGate === undefined) delete process.env.GATE_LAWN_V13; else process.env.GATE_LAWN_V13 = savedGate; });

  const audits = () => knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules' });

  describe('up and down', () => {
    test('up gates the summer Nutra-TECH rows and Acelepryn, retires unreferenced Dismiss rows, leaves everything else', async () => {
      const before = { nutraJanuary: await gatesOf(rows.bermuda.nutraJanuary.id), dimension: await gatesOf(rows.bermuda.dimensionJune.id) };
      await migration.up(knex);
      for (const track of ['bermuda', 'zoysia']) {
        expect(await gatesOf(rows[track].nutraJune.id)).toEqual({ northPortProductWindow: true });
        expect(await gatesOf(rows[track].acelepryn.id)).toEqual({ trigger: 'caterpillars', delayWateringOrMowingHours: 24 });
        expect(await knex('lawn_protocol_products').where({ id: rows[track].dismissJanuary.id }).first()).toBeUndefined();
      }
      expect(await gatesOf(rows.bermuda.nutraJanuary.id)).toEqual(before.nutraJanuary);
      expect(await gatesOf(rows.bermuda.dimensionJune.id)).toEqual(before.dimension);
      // A Dismiss row an actual references stays; so does the older protocol's row.
      expect(await knex('lawn_protocol_products').where({ id: rows.bermuda.dismissJuly.id }).first()).toBeDefined();
      expect(await knex('lawn_protocol_products').where({ id: rows.zoysia.dismissJuly.id }).first()).toBeUndefined();
      expect(await knex('lawn_protocol_products').where({ id: rows.older.id }).first()).toBeDefined();
      expect(await audits()).toHaveLength(2);
    });

    test('a second up changes nothing and writes no second audit row', async () => {
      const count = async () => Number((await knex('lawn_protocol_products').count('* as n').first()).n);
      const before = await count();
      await migration.up(knex);
      expect(await count()).toBe(before);
      expect(await audits()).toHaveLength(2);
    });

    test('down takes back exactly what up wrote: a key that changed since stays, the deleted Dismiss rows return under their own ids', async () => {
      const saved = await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules' });
      const deleted = saved.flatMap((log) => log.before_snapshot.dismissRows);
      expect(deleted).toHaveLength(3);
      // The owner edited one key after the migration: down leaves that value alone.
      await knex('lawn_protocol_products').where({ id: rows.zoysia.nutraJune.id }).update({ gates: JSON.stringify({ northPortProductWindow: false }) });
      await migration.down(knex);
      expect(await gatesOf(rows.bermuda.nutraJune.id)).toEqual({});
      expect(await gatesOf(rows.zoysia.nutraJune.id)).toEqual({ northPortProductWindow: false });
      expect(await gatesOf(rows.bermuda.acelepryn.id)).toEqual({ trigger: 'caterpillars' });
      for (const row of [rows.bermuda.dismissJanuary, rows.zoysia.dismissJanuary, rows.zoysia.dismissJuly]) {
        const back = await knex('lawn_protocol_products').where({ id: row.id }).first();
        expect(back).toMatchObject({ id: row.id, product_name: DISMISS, lawn_protocol_window_id: row.lawn_protocol_window_id, application_mode: row.application_mode, default_in_plan: row.default_in_plan, sort_order: row.sort_order });
        expect(back.gates).toEqual(row.gates);
      }
      expect(await audits()).toHaveLength(0);
      await migration.down(knex);
      expect(await knex('lawn_protocol_products').where({ product_name: DISMISS })).toHaveLength(5);
    });
  });

  describe('the plan in June', () => {
    beforeAll(async () => { await migration.up(knex); });

    async function plannedJune(city) {
      const f = await fixture(knex);
      await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
      await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, grass_type: 'bermuda', track_key: 'bermuda', lawn_sqft: 10000 });
      const visit = await f.visit(0, { scheduled_date: '2026-06-10' });
      process.env.GATE_LAWN_V13 = 'true';
      return buildPlanForService(visit.id, { db: knex });
    }
    // Selected items are in the mix; a held item is not selected, so it lives in the protocol lists.
    const item = (plan, name) => [...plan.protocol.base, ...plan.protocol.conditional].find((i) => i.product?.name === name);

    test('North Port: Nutra-TECH is not selected, gets no amount and says why; the pre-emergent plans as usual', async () => {
      const plan = await plannedJune('North Port');
      const nutra = item(plan, NUTRA);
      expect(nutra).toMatchObject({ selected: false, selectionReason: 'north_port_product_window', mix: null });
      expect(nutra.unavailable.reason).toMatch(/North Port bans this product/);
      expect(nutra.gateNotes.map((n) => n.key)).toContain('northPortProductWindow');
      expect(plan.propertyGate.warnings.map((w) => w.code)).toContain('lawn_v13_north_port_product_window');
      expect(item(plan, DIMENSION)).toMatchObject({ selected: true, mix: expect.objectContaining({ amount: 5 }) });
      expect(plan.mixCalculator.items.map((i) => i.product.name)).not.toContain(NUTRA);
      // A visit that records it anyway is flagged like the nitrogen ban.
      expect(heldProductBlocks(plan, [{ productId: nutra.product.id }]).map((b) => b.code)).toEqual(['actual_north_port_product_window']);
      expect(heldProductBlocks(plan, [{ productId: item(plan, DIMENSION).product.id }])).toEqual([]);
    });

    test('another city: Nutra-TECH plans as before and nothing is held', async () => {
      const plan = await plannedJune('Sarasota');
      expect(item(plan, NUTRA)).toMatchObject({ selected: true, mix: expect.objectContaining({ amount: 120 }) });
      expect(plan.propertyGate.warnings.map((w) => w.code)).not.toContain('lawn_v13_north_port_product_window');
    });
  });
});
