// Lawn protocol v13: the Dylox 6.2 G label limits (migration 20261009172000, label EPA Reg. No. 432-1308: 3 applications
// to turf per calendar year, 7 days between, 24.5 lb active ingredient per acre a year = 9.07 lb product per 1,000 sq ft), through the real migration on PostgreSQL (cloned schema). Synthetic data only.
// Self-skips without DATABASE_URL.
//
// Pinned: three limits (3 a year, 7 days, 9.07 lb per 1,000 sq ft a year as the active ingredient amount row; hard blocks) are inserted, a weaker one is tightened and
// a stricter one is left; every active staged Dylox 6.2 G row gets gates.annualMaxApps 3 and gates.minIntervalDays 7 where the
// key is absent (a retired row, a row with its own value and every other product are left); Dylox 420 SL is not touched; a second
// up changes nothing; with no catalog row nothing is written; down restores exactly and never touches a value it did not write.
const { createLawnHistoryDb } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009172000_lawn_v13_dylox_label_limits');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');

const DYLOX = migration.DYLOX;
const SL = 'Dylox 420 SL T&O Insecticide';
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_dx_a', 'fixture_dx_b'];
const OCT = 'oct_v13_spreader_fall';
const DYLOX_GATES = { trigger: 'grubs_or_mole_crickets', postAppIrrigation: true, spreaderVisitOnly: true };
const CATALOG_TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products',
  'lawn_protocol_audit_log', 'lawn_protocol_service_completions', 'product_limits', 'lawn_protocol_product_actuals', 'service_products'];

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 Dylox 6.2 G label limits migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of CATALOG_TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [table, constraint, suffix] of [
      ['product_limits', 'fixture_limits_product', ''], ['product_aliases', 'fixture_aliases_product', ''],
      ['service_products', 'fixture_sp_product', ' ON DELETE SET NULL'], ['lawn_protocol_products', 'fixture_lpp_product', ''],
    ]) {
      await knex.raw(`ALTER TABLE ??.?? ADD CONSTRAINT ${constraint} FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)${suffix}`, [owned.schema, table, owned.schema]);
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const limits = (name) => knex('product_limits').whereIn('product_id', knex('products_catalog').where({ name }).select('id')).orderBy('id');
  const byType = async (name, type) => (await limits(name)).filter((row) => row.limit_type === type);
  const rows = (name, version = V13) => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'p.product_name': name, 'l.version': version }).orderBy(['l.protocol_key', 'p.id']).select('p.*', 'l.protocol_key');
  const ours = () => knex('lawn_protocol_audit_log').whereIn('action', [migration.ACTION, migration.CATALOG_ACTION]);
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  async function snapshot() {
    return clean([
      await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']), await knex('products_catalog').orderBy('name'),
      await knex('product_limits').orderBy('id'), await knex('lawn_protocol_audit_log').orderBy('id'),
    ]);
  }

  // The catalog (Dylox 6.2 G, Dylox 420 SL with its own limits, a decoy product) and two staged v13 protocols with the
  // Dylox 6.2 G row in the October window as migration 20261005120000 leaves it, plus an older protocol version.
  async function reset({ dylox = true } = {}) {
    for (const table of ['service_products', 'lawn_protocol_product_actuals', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    const [sl] = await knex('products_catalog').insert({ name: SL, category: 'insecticide', formulation: 'liquid', active: true }).returning('*');
    const [other] = await knex('products_catalog').insert({ name: 'Fixture Other', category: 'insecticide', active: true }).returning('*');
    ids.sl = sl.id; ids.other = other.id;
    await knex('product_limits').insert({ product_id: sl.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 5, limit_unit: 'applications', severity: 'warning' });
    if (dylox) {
      const [dx] = await knex('products_catalog').insert({ name: DYLOX, category: 'insecticide', formulation: 'granular', active_ingredient: 'trichlorfon 6.2%', rate_unit: 'lb', active: true }).returning('*');
      ids.dx = dx.id;
    }
    for (const key of KEYS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' });
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 10, window_key: OCT, title: OCT, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert([
        ...(dylox ? [{ lawn_protocol_window_id: window.id, product_id: ids.dx, product_name: DYLOX, role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'label_rate', default_in_plan: false, sort_order: 3, gates: JSON.stringify(DYLOX_GATES) }] : []),
        { lawn_protocol_window_id: window.id, product_id: ids.sl, product_name: SL, role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'fl_oz', default_in_plan: false, sort_order: 4, gates: JSON.stringify({ trigger: 'mole_cricket_adults' }) },
        { lawn_protocol_window_id: window.id, product_id: ids.other, product_name: 'Fixture Other', role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'lb', default_in_plan: false, sort_order: 5, gates: JSON.stringify({ trigger: 'fixture' }) },
      ]);
    }
    if (dylox) {
      // An older protocol version's row: not a v13 row, so it is left alone.
      const [old] = await knex('lawn_protocols').where({ protocol_key: KEYS[0], version: '2026.06' });
      const [oldWindow] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: old.id, month: 10, window_key: OCT, title: OCT, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: oldWindow.id, product_id: ids.dx, product_name: DYLOX, role: 'insect_curative', application_mode: 'broadcast', rate_unit: 'lb', default_in_plan: false, sort_order: 3, gates: JSON.stringify(DYLOX_GATES) });
    }
  }

  describe('fresh path', () => {
    let before;
    beforeAll(async () => {
      await reset();
      before = { sl: clean(await knex('products_catalog').where({ name: SL })), slLimits: clean(await limits(SL)), slRows: clean(await rows(SL)), other: clean(await rows('Fixture Other')), old: clean(await rows(DYLOX, '2026.06')) };
      await migration.up(knex);
    });

    test('three limits: 3 applications a year, 7 days between and 9.07 lb per 1,000 sq ft a year, hard blocks, label quoted', async () => {
      const found = await limits(DYLOX);
      expect(found).toHaveLength(3);
      const [count] = await byType(DYLOX, 'annual_max_apps');
      const [interval] = await byType(DYLOX, 'min_interval_days');
      expect(count).toMatchObject({ product_id: ids.dx, match_type: 'product', limit_unit: 'applications', severity: 'hard_block' });
      expect(Number(count.limit_value)).toBe(3);
      expect(interval).toMatchObject({ product_id: ids.dx, match_type: 'product', limit_unit: 'days', severity: 'hard_block' });
      expect(Number(interval.limit_value)).toBe(7);
      for (const row of found) expect(row.description).toMatch(/Dylox 6\.2 G label, EPA Reg\. No\. 432-1308/);
      expect(count.description).toMatch(/3 applications to turf per calendar year/);
      // The yearly amount: the stored shape application-limits sizes per 1,000 sq ft (the prodiamine caps use it).
      const [amount] = await byType(DYLOX, 'annual_max_rate');
      expect(amount).toMatchObject({ product_id: ids.dx, match_type: 'active_ingredient', match_value: 'trichlorfon', limit_unit: 'lb/1000sf/year', severity: 'hard_block' });
      expect(Number(amount.limit_value)).toBe(9.07);
      expect(amount.description).toMatch(/24\.5 lbs of active ingredient per acre per year for controlling mole crickets and grubs/);
    });

    test('every staged v13 Dylox 6.2 G row carries annualMaxApps 3 and minIntervalDays 7 beside its own gates', async () => {
      const found = await rows(DYLOX);
      expect(found).toHaveLength(KEYS.length);
      for (const row of found) expect(row.gates).toEqual({ ...DYLOX_GATES, annualMaxApps: 3, minIntervalDays: 7 });
    });

    test('Dylox 420 SL (limits, rows, catalog), the decoy product and the older protocol version are not touched', async () => {
      expect(clean(await knex('products_catalog').where({ name: SL }))).toBe(before.sl);
      expect(clean(await limits(SL))).toBe(before.slLimits);
      expect(clean(await rows(SL))).toBe(before.slRows);
      expect(clean(await rows('Fixture Other'))).toBe(before.other);
      expect(clean(await rows(DYLOX, '2026.06'))).toBe(before.old);
    });

    test('one audit row per protocol and one for the limits', async () => {
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.ACTION })).toHaveLength(KEYS.length);
      const [catalog] = await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION });
      expect(catalog.after_snapshot.limits.inserted).toHaveLength(3);
    });

    test('a second up changes nothing', async () => {
      const state = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(state);
    });

    test('down removes the limits, the gate keys and the audit rows, leaving the rows as they were', async () => {
      await migration.down(knex);
      expect(await limits(DYLOX)).toHaveLength(0);
      for (const row of await rows(DYLOX)) expect(row.gates).toEqual(DYLOX_GATES);
      expect(await ours()).toHaveLength(0);
      expect(clean(await limits(SL))).toBe(before.slLimits);
    });
  });

  describe('existing limits and gates', () => {
    beforeEach(() => reset());

    test('a stricter stored limit is left; a weaker one is tightened, and down puts the weaker one back', async () => {
      await knex('product_limits').insert([
        { product_id: ids.dx, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 2, limit_unit: 'applications', severity: 'hard_block' },
        // A plain product-level yearly amount row is another mechanism: it is left, and the ingredient row is still inserted.
        { product_id: ids.dx, match_type: 'product', limit_type: 'annual_max_rate', limit_value: 20, limit_unit: 'lb/1000sf/year', severity: 'warning' },
        { product_id: ids.dx, match_type: 'product', limit_type: 'min_interval_days', limit_value: 3, limit_unit: 'days', severity: 'warning', description: 'old' },
      ]);
      await migration.up(knex);
      const [count] = await byType(DYLOX, 'annual_max_apps');
      expect(await byType(DYLOX, 'annual_max_apps')).toHaveLength(1);
      expect(Number(count.limit_value)).toBe(2);
      const intervals = await byType(DYLOX, 'min_interval_days');
      expect(intervals).toHaveLength(1);
      expect(Number(intervals[0].limit_value)).toBe(7);
      expect(intervals[0].severity).toBe('hard_block');
      const amounts = await byType(DYLOX, 'annual_max_rate');
      expect(amounts.map((row) => [row.match_type, Number(row.limit_value)]).sort()).toEqual([['active_ingredient', 9.07], ['product', 20]]);
      await migration.down(knex);
      expect((await byType(DYLOX, 'annual_max_rate')).map((row) => [row.match_type, Number(row.limit_value)])).toEqual([['product', 20]]);
      const back = await byType(DYLOX, 'min_interval_days');
      expect(back).toHaveLength(1);
      expect([Number(back[0].limit_value), back[0].severity, back[0].description]).toEqual([3, 'warning', 'old']);
      expect(Number((await byType(DYLOX, 'annual_max_apps'))[0].limit_value)).toBe(2);
    });

    test('a looser stored ingredient amount row is tightened to 9.07 and down puts it back; a stricter one is left', async () => {
      await knex('product_limits').insert({ product_id: ids.dx, match_type: 'active_ingredient', match_value: 'trichlorfon', limit_type: 'annual_max_rate', limit_value: 12, limit_unit: 'lb/1000sf/year', severity: 'warning', description: 'loose' });
      await migration.up(knex);
      const [tight] = await byType(DYLOX, 'annual_max_rate');
      expect([Number(tight.limit_value), tight.severity]).toEqual([9.07, 'hard_block']);
      await migration.down(knex);
      const [back] = await byType(DYLOX, 'annual_max_rate');
      expect([Number(back.limit_value), back.severity, back.description]).toEqual([12, 'warning', 'loose']);
      await knex('product_limits').where({ id: back.id }).update({ limit_value: 8, severity: 'hard_block' });
      await migration.up(knex);
      expect((await byType(DYLOX, 'annual_max_rate')).map((row) => Number(row.limit_value))).toEqual([8]);
    });

    test('a key a row already carries and a retired row are left; down removes only what this wrote', async () => {
      const [first, second] = await rows(DYLOX);
      await knex('lawn_protocol_products').where({ id: first.id }).update({ gates: JSON.stringify({ ...DYLOX_GATES, annualMaxApps: 2 }) });
      await knex('lawn_protocol_products').where({ id: second.id }).update({ gates: JSON.stringify({ ...DYLOX_GATES, retired: true }) });
      await migration.up(knex);
      const [a, b] = await rows(DYLOX);
      expect(a.gates).toEqual({ ...DYLOX_GATES, annualMaxApps: 2, minIntervalDays: 7 });
      expect(b.gates).toEqual({ ...DYLOX_GATES, retired: true });
      await migration.down(knex);
      const [c, d] = await rows(DYLOX);
      expect(c.gates).toEqual({ ...DYLOX_GATES, annualMaxApps: 2 });
      expect(d.gates).toEqual({ ...DYLOX_GATES, retired: true });
    });

    test('down leaves a hand-edited limit and a hand-edited gate value alone', async () => {
      await migration.up(knex);
      const [count] = await byType(DYLOX, 'annual_max_apps');
      await knex('product_limits').where({ id: count.id }).update({ limit_value: 4 });
      const [amount] = await byType(DYLOX, 'annual_max_rate');
      await knex('product_limits').where({ id: amount.id }).update({ limit_value: 9.5 });
      const [row] = await rows(DYLOX);
      await knex('lawn_protocol_products').where({ id: row.id }).update({ gates: JSON.stringify({ ...DYLOX_GATES, annualMaxApps: 3, minIntervalDays: 10 }) });
      await migration.down(knex);
      expect(Number((await byType(DYLOX, 'annual_max_apps'))[0].limit_value)).toBe(4);
      expect(await byType(DYLOX, 'min_interval_days')).toHaveLength(0);
      expect(Number((await byType(DYLOX, 'annual_max_rate'))[0].limit_value)).toBe(9.5);
      const [after] = await rows(DYLOX);
      expect(after.gates).toEqual({ ...DYLOX_GATES, minIntervalDays: 10 });
      const [other] = (await rows(DYLOX)).slice(1);
      expect(other.gates).toEqual(DYLOX_GATES);
    });
  });

  test('with no Dylox 6.2 G catalog row nothing is written', async () => {
    await reset({ dylox: false });
    const state = await snapshot();
    await migration.up(knex);
    expect(await snapshot()).toBe(state);
    await migration.down(knex);
    expect(await snapshot()).toBe(state);
  });
});
