// 20261008131000 (the follow-up to the frozen December migration 20261008130000, Codex round 1 on #6137), through both
// real migrations on PostgreSQL (cloned schema). Synthetic data only.
//
//   1. A 10-0-22 catalog row that already existed gets its 4.5 lb catalog rate (only where empty and coherent).
//   2. The frozen down() keeps an inserted row whose workflow fields (active, needs_pricing, content_status,
//      customer_visibility) were changed, because the follow-up adds those four inserted values to the audit
//      snapshot the frozen down compares.
const { randomUUID } = require('crypto');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const frozen = require('../models/migrations/20261008130000_lawn_v13_december_potash');
const followup = require('../models/migrations/20261008131000_lawn_v13_december_potash_followup');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');

const F24 = frozen.OLD_NAME;
const F10 = frozen.NEW_NAME;
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_followup_a', 'fixture_followup_b'];
const DEC = frozen.DECEMBER_WINDOW;
const TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products',
  'lawn_protocol_audit_log', 'lawn_protocol_service_completions', 'product_limits', 'service_products'];

describe('the follow-up migration (no database)', () => {
  test('rateFill: the rate and unit are filled together, or one beside a matching other, never beside a conflicting one', () => {
    const fill = (rate, unit) => followup.rateFill({ default_rate_per_1000: rate, rate_unit: unit });
    expect(fill(null, null)).toEqual([{ column: 'default_rate_per_1000', after: 4.5 }, { column: 'rate_unit', after: 'lb' }]);
    expect(fill(null, '')).toHaveLength(2);
    expect(fill(null, 'lb')).toEqual([{ column: 'default_rate_per_1000', after: 4.5 }]);
    expect(fill('4.5000', null)).toEqual([{ column: 'rate_unit', after: 'lb' }]);
    expect(fill(null, 'oz')).toEqual([]); // 4.5 oz would be a wrong dose
    expect(fill(3, null)).toEqual([]);
    expect(fill('4.5000', 'lb')).toEqual([]);
    expect(fill(2, 'fl oz')).toEqual([]);
  });

  test('the four values it adds to the audit snapshot are the ones the frozen insert writes', () => {
    expect(followup.INSERT_DEFAULTS).toEqual({ active: true, needs_pricing: true, content_status: 'draft', customer_visibility: 'internal_only' });
  });
});

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 December follow-up migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    // LIKE copies no foreign keys; the frozen down reads them to know whether the product is referenced.
    await knex.raw('ALTER TABLE ??.product_limits ADD CONSTRAINT fixture_limits_product FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)', [owned.schema, owned.schema]);
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const newRow = () => knex('products_catalog').where({ name: F10 }).first();
  const decemberRows = () => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .where({ 'w.window_key': DEC, 'p.role': 'nutrition' }).select('p.*');
  const followupLogs = () => knex('lawn_protocol_audit_log').where({ action: followup.ACTION });
  const bothUp = async () => { await frozen.up(knex); await followup.up(knex); };
  const bothDown = async () => { await followup.down(knex); await frozen.down(knex); };

  async function reset(existing) {
    for (const table of ['service_products', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const [f24] = await knex('products_catalog').insert({ name: F24, category: 'fertilizer', formulation: 'granular', analysis_n: 24, analysis_p: 0, analysis_k: 11, default_rate_per_1000: 4.2, rate_unit: 'lb', active: true }).returning('*');
    ids.f24 = f24.id;
    if (existing) await knex('products_catalog').insert({ name: F10, category: 'fertilizer', formulation: 'granular', active: true, needs_pricing: false, ...existing });
    for (const key of KEYS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' });
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const [dec] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 12, window_key: DEC, title: DEC, visit_type: 'granular_production_plus_spots', production_mode: 'spreader_plus_spot_backpack' }).returning('*');
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: dec.id, product_id: f24.id, product_name: F24, role: 'nutrition', application_mode: 'broadcast', rate_unit: 'lb_n', default_in_plan: true, sort_order: 53, gates: JSON.stringify({ targetN: '0.5 lb N/1000' }) });
    }
  }

  describe('1. the catalog rate on a row that already existed', () => {
    test('a sparse row gets 4.5 lb after the frozen migration filled its other fields, with an audit row; the December rows link to it', async () => {
      await reset({});
      await frozen.up(knex);
      const before = await newRow();
      expect([before.default_rate_per_1000, before.rate_unit]).toEqual([null, null]);
      await followup.up(knex);
      const after = await newRow();
      expect(Number(after.default_rate_per_1000)).toBe(4.5);
      expect(after.rate_unit).toBe('lb');
      for (const dec of await decemberRows()) expect(dec).toMatchObject({ product_name: F10, product_id: after.id });
      const [log] = await followupLogs();
      expect(log.after_snapshot.filled.map((f) => [f.column, f.after]).sort()).toEqual([['default_rate_per_1000', 4.5], ['rate_unit', 'lb']]);
    });

    test('a second up changes nothing: no new audit row, the same values', async () => {
      await reset({});
      await bothUp();
      const state = async () => JSON.stringify([await newRow(), await followupLogs()]);
      const before = await state();
      await followup.up(knex);
      expect(await state()).toBe(before);
    });

    test('only empty, coherent fields are written: a rate in another unit, a different rate, or a complete row are left as they are', async () => {
      for (const [existing, expected] of [
        [{ default_rate_per_1000: 2, rate_unit: 'oz' }, [2, 'oz']],
        [{ default_rate_per_1000: 3 }, [3, null]],
        [{ rate_unit: 'oz' }, [null, 'oz']],
        [{ default_rate_per_1000: 4.5, rate_unit: 'lb' }, [4.5, 'lb']],
        [{ rate_unit: 'lb' }, [4.5, 'lb']],
        [{ default_rate_per_1000: 4.5 }, [4.5, 'lb']],
      ]) {
        await reset(existing);
        await bothUp();
        const row = await newRow();
        expect([row.default_rate_per_1000 == null ? null : Number(row.default_rate_per_1000), row.rate_unit]).toEqual(expected);
      }
    });

    test('a row the frozen migration inserted already has its rate: nothing is filled', async () => {
      await reset(null);
      await bothUp();
      const row = await newRow();
      expect([Number(row.default_rate_per_1000), row.rate_unit]).toEqual([4.5, 'lb']);
      const [log] = await followupLogs();
      expect(log.after_snapshot.filled).toEqual([]);
    });

    test('down clears a rate it wrote only while it still holds the written value', async () => {
      await reset({});
      await bothUp();
      await followup.down(knex);
      const cleared = await newRow();
      expect([cleared.default_rate_per_1000, cleared.rate_unit]).toEqual([null, null]);
      expect(await followupLogs()).toEqual([]);
      await followup.up(knex);
      await knex('products_catalog').where({ name: F10 }).update({ default_rate_per_1000: 5 });
      await followup.down(knex);
      const kept = await newRow();
      expect([Number(kept.default_rate_per_1000), kept.rate_unit]).toEqual([5, null]);
    });

    test('a pinned visit keeps the rate and the audit row (the December rows are still live)', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await reset({});
      await bothUp();
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
      try {
        await followup.down(knex);
        expect(Number((await newRow()).default_rate_per_1000)).toBe(4.5);
        expect(await followupLogs()).toHaveLength(1);
        expect(log).toHaveBeenCalledWith(expect.stringContaining(`references ${V13}`));
      } finally {
        log.mockRestore();
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
    });
  });

  describe('2. the frozen down keeps an inserted row whose workflow fields were changed', () => {
    const EDITS = [
      ['active', { active: false }],
      ['needs_pricing', { needs_pricing: false }],
      ['content_status', { content_status: 'approved_for_portal' }],
      ['customer_visibility', { customer_visibility: 'portal_only' }],
    ];

    test('without the follow-up the frozen down deletes such a row (the finding)', async () => {
      for (const [, edit] of EDITS) {
        await reset(null);
        await frozen.up(knex);
        await knex('products_catalog').where({ name: F10 }).update(edit);
        await frozen.down(knex);
        expect(await newRow()).toBeUndefined();
      }
    });

    test.each(EDITS)('with the follow-up, a rollback of both migrations keeps the row when %s was changed', async (_name, edit) => {
      await reset(null);
      await bothUp();
      await knex('products_catalog').where({ name: F10 }).update(edit);
      await bothDown();
      const kept = await newRow();
      expect(kept).toBeDefined();
      for (const [column, value] of Object.entries(edit)) expect(kept[column]).toBe(value);
      // The protocol rows are back on the 24-0-11 either way.
      for (const dec of await decemberRows()) expect(dec).toMatchObject({ product_name: F24, product_id: ids.f24 });
      expect(await knex('lawn_protocol_audit_log').whereIn('action', [frozen.CATALOG_ACTION, followup.ACTION])).toEqual([]);
    });

    test('an untouched inserted row is still removed by the rollback of both', async () => {
      await reset(null);
      await bothUp();
      await bothDown();
      expect(await newRow()).toBeUndefined();
      expect(await knex('lawn_protocol_audit_log')).toEqual([]);
    });

    test('the snapshot gains the four inserted values once; a second up and a follow-up down leave them (the guard must outlive it)', async () => {
      await reset(null);
      await frozen.up(knex);
      const snapshot = async () => (await knex('lawn_protocol_audit_log').where({ action: frozen.CATALOG_ACTION }).first()).after_snapshot.inserted;
      expect(await snapshot()).not.toHaveProperty('active');
      await followup.up(knex);
      expect(await snapshot()).toMatchObject(followup.INSERT_DEFAULTS);
      const once = JSON.stringify(await snapshot());
      await followup.up(knex);
      expect(JSON.stringify(await snapshot())).toBe(once);
      await followup.down(knex);
      expect(await snapshot()).toMatchObject(followup.INSERT_DEFAULTS);
    });

    test('a preview database that edited the row BEFORE the follow-up ran is protected too', async () => {
      await reset(null);
      await frozen.up(knex);
      await knex('products_catalog').where({ name: F10 }).update({ active: false });
      await followup.up(knex);
      await bothDown();
      expect(await newRow()).toMatchObject({ active: false });
    });

    test('a priced or referenced row is kept by the frozen guards as before', async () => {
      await reset(null);
      await bothUp();
      await knex('products_catalog').where({ name: F10 }).update({ best_price: 31.81 });
      await bothDown();
      expect(await newRow()).toBeDefined();
      await reset(null);
      await bothUp();
      await knex('product_limits').insert({ product_id: (await newRow()).id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 2, limit_unit: 'applications', severity: 'hard_block', description: randomUUID() });
      await bothDown();
      expect(await newRow()).toBeDefined();
    });
  });

  test('up, down, up of both migrations leaves the same state as the first up', async () => {
    for (const existing of [null, {}]) {
      await reset(existing);
      await bothUp();
      const state = async () => JSON.stringify([await newRow(), await decemberRows(), await knex('lawn_protocol_audit_log').whereIn('action', [frozen.CATALOG_ACTION, followup.ACTION]).orderBy('action')],
        (key, value) => (['updated_at', 'created_at', 'id', 'entity_id', 'rowId', 'lawn_protocol_window_id', 'lawn_protocol_id', 'productId', 'product_id', 'logId', 'before', 'after', 'sort_order'].includes(key) && typeof value === 'string' ? undefined : value));
      const first = await state();
      await bothDown();
      await bothUp();
      expect(await state()).toBe(first);
    }
  });
});
