// Lawn bermuda removal (GATE_LAWN_BERMUDA_REMOVAL) through the real plan engine,
// the real staged-row migration and PostgreSQL (cloned schema, synthetic data).
//
// Pins: gate off is the old plan; St. Augustine and Zoysia lawns that asked for
// the step (staff switch or accepted estimate) get Recognition, Fusilade II and
// the surfactant as spot lines on the April and June visits; Bermuda, Bahia,
// other months and lawns that did not ask never do; Fusilade II is never planned
// or selectable without Recognition; the 2-a-year and 42-day limits block; the
// migration is safe to run up, down, up.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION } = require('../services/lawn-program');
const rowsMigration = require('../models/migrations/20261006190100_lawn_bermuda_removal_rows');
const programMigration = require('../models/migrations/20261006190300_lawn_bermuda_removal_limit_program');
const auditMigration = require('../models/migrations/20261006190200_lawn_bermuda_removal_audit');
const { bermudaPairViolation, bermudaLimitViolation, enforceStepLimitsInTransaction } = require('../services/lawn-bermuda-removal');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_BERMUDA_REMOVAL', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY'];
const TRACKS = [
  ['swfl_st_augustine_10_10', 'st_augustine'],
  ['swfl_zoysia_10_10', 'zoysia'],
  ['swfl_bermuda_10_10', 'bermuda'],
  ['swfl_bahia_10_10', 'bahia'],
];
const REC = 'Recognition Post Emergent Herbicide';
const FUS = 'Fusilade II Post Emergent Liquid Herbicide';
const NIS = 'LESCO 90/10 Nonionic Surfactant';

function setGates({ v13 = true, removal = true } = {}) {
  for (const [name, on] of [['GATE_LAWN_V13', v13], ['GATE_LAWN_BERMUDA_REMOVAL', removal]]) {
    if (on) process.env[name] = 'true'; else delete process.env[name];
  }
  delete process.env.GATE_LAWN_COMPLETION_DEFAULTS;
  delete process.env.GATE_LAWN_PROPERTY_HISTORY;
}

describeDb('lawn bermuda removal through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  let rec;
  let fus;
  let nis;

  async function cloneTables(tables) {
    for (const table of tables) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
  }

  const product = async (name, changes = {}) => (await knex('products_catalog').insert({
    name, category: 'herbicide', default_rate_per_1000: 0.03, rate_unit: 'oz', label_verified_at: new Date(),
    inventory_on_hand: 1000, inventory_unit: 'oz', active: true, ...changes,
  }).returning('*'))[0];

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    await cloneTables(['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'product_limits', 'property_application_history',
      'estimates', 'lawn_protocol_audit_log']);
    rec = await product(REC);
    fus = await product(FUS, { default_rate_per_1000: 0.55, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    nis = await product(NIS, { category: 'adjuvant', default_rate_per_1000: 0.25, rate_unit: 'fl oz', inventory_unit: 'fl oz' });
    for (const [key, track] of TRACKS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: `Old ${track}`, status: 'active', grass_track: track, region: 'swfl' });
      const [staged] = await knex('lawn_protocols').insert({
        protocol_key: key, version: LAWN_V13_VERSION, name: `v13 ${track}`, status: 'staged', grass_track: track, region: 'swfl', effective_from: '2000-01-01',
      }).returning('*');
      for (const [month, windowKey] of [[4, 'apr_v13_spreader_feeding'], [5, 'may_v13_tetrino_hose'], [6, 'jun_v13_hose_blackout']]) {
        await knex('lawn_protocol_windows').insert({ lawn_protocol_id: staged.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture' });
      }
    }
    // The real migration writes the rows and the limits into the fixture protocols.
    await rowsMigration.up(knex);
    await programMigration.up(knex);
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  });
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  async function lawn({ grass = 'st_augustine', date = '2026-04-14', bermuda = false, acceptedEstimate = false, cultivar = 'Floratam' } = {}) {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
    await knex('customer_turf_profiles').insert({
      customer_id: f.customerId, active: true, grass_type: grass, track_key: grass, cultivar, lawn_sqft: 10000, bermuda_removal: bermuda,
    });
    if (acceptedEstimate) {
      await knex('estimates').insert({
        customer_id: f.customerId, status: 'accepted',
        estimate_data: JSON.stringify({ engineRequest: { options: { bermudaSuppression: true } } }),
      });
    }
    const visit = await f.visit(0, { scheduled_date: date });
    return { ...f, visit, customerId: f.customerId };
  }
  const plan = (visit, options = {}) => buildPlanForService(visit.id, { db: knex, ...options });
  const names = (items) => items.map((item) => item.product?.name).filter(Boolean);
  const optionNames = (result) => names([...result.mixCalculator.items, ...result.mixCalculator.conditionalOptions]);
  const codes = (result) => result.propertyGate.blocks.map((b) => b.code);
  const strip = (result) => JSON.parse(JSON.stringify({ ...result, generatedAt: null }));
  const history = (customerId, product, dates) => knex('property_application_history').insert(
    dates.map((application_date) => ({ customer_id: customerId, product_id: product.id, application_date })),
  );

  describe('who gets the step', () => {
    test.each([['st_augustine', '2026-04-14'], ['st_augustine', '2026-06-16'], ['zoysia', '2026-04-14'], ['zoysia', '2026-06-16']])(
      '%s on %s: the staff switch adds the three spot lines, never an amount', async (grass, date) => {
        setGates();
        const f = await lawn({ grass, date, bermuda: true });
        const result = await plan(f.visit);
        expect(result.bermudaRemoval).toMatchObject({ active: true, source: 'staff' });
        expect(result.bermudaRemoval.mix).toContain('Recognition 0.03 oz + Fusilade II 0.55 fl oz');
        const lines = result.mixCalculator.conditionalOptions.filter((item) => [REC, FUS, NIS].includes(item.product?.name));
        expect(lines.map((item) => item.product.name).sort()).toEqual([FUS, NIS, REC].sort());
        for (const line of lines) {
          expect(line.spot).toMatchObject({ note: expect.stringContaining('enter the area') });
          expect(line.mix).toBeNull();
        }
        expect(lines.find((item) => item.product.name === REC).spot.reference).toBe('Label rate 0.03 oz per 1,000 sq ft');
        expect(lines.find((item) => item.product.name === FUS).spot.reference).toBe('Label rate 0.55 fl oz per 1,000 sq ft');
      });

    test('the field rules ride the rows as gate notes (June adds the morning and 85 F rule)', async () => {
      setGates();
      const june = await plan((await lawn({ date: '2026-06-16', bermuda: true })).visit, { selectedConditionalProductIds: [rec.id, fus.id] });
      const note = (name) => june.mixCalculator.items.find((item) => item.product?.name === name).gateNotes.map((n) => n.text).join(' | ');
      expect(note(REC)).toContain('actively growing');
      expect(note(REC)).toContain('temperature under 85');
      expect(note(REC)).toContain('No rain or irrigation for 3 hours');
      expect(note(REC)).toContain('Do not mow for 2 days before or after');
      expect(note(REC)).toContain('Skip the Celsius weed spot in the bermuda area');
      expect(note(FUS)).toContain('only together with Recognition');
      const april = await plan((await lawn({ date: '2026-04-14', bermuda: true })).visit, { selectedConditionalProductIds: [rec.id] });
      expect(april.mixCalculator.items.find((item) => item.product?.name === REC).gateNotes.map((n) => n.text).join(' | ')).not.toContain('under 85');
    });

    test('an accepted estimate that carries the add-on turns it on with no staff switch', async () => {
      setGates();
      const result = await plan((await lawn({ acceptedEstimate: true })).visit);
      expect(result.bermudaRemoval).toMatchObject({ active: true, source: 'estimate' });
      expect(optionNames(result)).toEqual(expect.arrayContaining([REC, FUS, NIS]));
    });

    test('an estimate counts only while the CURRENT profile grass is St. Augustine: a reclassified Zoysia lawn needs the staff switch', async () => {
      setGates();
      const f = await lawn({ grass: 'zoysia', acceptedEstimate: true });
      const viaEstimate = await plan(f.visit);
      expect(viaEstimate.bermudaRemoval).toBeUndefined();
      expect(optionNames(viaEstimate)).not.toContain(REC);
      await knex('customer_turf_profiles').where({ customer_id: f.customerId }).update({ bermuda_removal: true });
      const viaSwitch = await plan(f.visit);
      expect(viaSwitch.bermudaRemoval).toMatchObject({ active: true, source: 'staff' });
      expect(optionNames(viaSwitch)).toEqual(expect.arrayContaining([REC, FUS, NIS]));
    });

    test('a lawn that did not ask never gets it, and neither does a draft or archived estimate', async () => {
      setGates();
      const plain = await lawn({});
      await knex('estimates').insert({ customer_id: plain.customerId, status: 'draft', estimate_data: JSON.stringify({ engineRequest: { options: { bermudaSuppression: true } } }) });
      await knex('estimates').insert({ customer_id: plain.customerId, status: 'accepted', archived_at: new Date(), estimate_data: JSON.stringify({ engineRequest: { options: { bermudaSuppression: true } } }) });
      const result = await plan(plain.visit);
      expect(result.bermudaRemoval).toBeUndefined();
      expect(optionNames(result)).not.toEqual(expect.arrayContaining([REC]));
      expect(optionNames(result)).not.toContain(FUS);
    });

    test.each(['bermuda', 'bahia'])('%s never gets it, even with the switch on and the estimate flag set', async (grass) => {
      setGates();
      const f = await lawn({ grass, bermuda: true, acceptedEstimate: true });
      const result = await plan(f.visit, { selectedConditionalProductIds: [rec.id, fus.id, nis.id] });
      expect(result.bermudaRemoval).toBeUndefined();
      expect(optionNames(result)).not.toContain(REC);
      expect(optionNames(result)).not.toContain(FUS);
    });

    test('other months carry no step (May)', async () => {
      setGates();
      const result = await plan((await lawn({ date: '2026-05-12', bermuda: true })).visit);
      expect(result.bermudaRemoval).toBeUndefined();
      expect(optionNames(result)).not.toContain(REC);
    });

    test('gate off: a flagged lawn plans exactly as the same lawn unflagged (byte-identical)', async () => {
      setGates({ removal: false });
      const f = await lawn({ bermuda: true, acceptedEstimate: true });
      const flagged = strip(await plan(f.visit));
      await knex('customer_turf_profiles').where({ customer_id: f.customerId }).update({ bermuda_removal: false });
      await knex('estimates').where({ customer_id: f.customerId }).del();
      const plain = strip(await plan(f.visit));
      expect(flagged).toEqual(plain);
      expect(JSON.stringify(flagged)).not.toContain(REC);
      expect(flagged.bermudaRemoval).toBeUndefined();
    });
  });

  describe('Recognition, Fusilade II and the surfactant are one selection', () => {
    const stepNames = (result) => names(result.mixCalculator.items).filter((name) => [REC, FUS, NIS].includes(name));

    test.each([['fus'], ['rec'], ['nis']])('selecting only %s selects all three, with no block', async (which) => {
      setGates();
      const id = { fus, rec, nis }[which].id;
      const result = await plan((await lawn({ bermuda: true })).visit, { selectedConditionalProductIds: [id] });
      expect(stepNames(result).sort()).toEqual([FUS, NIS, REC].sort());
      expect(codes(result)).not.toContain('lawn_bermuda_step_unavailable');
    });

    test('nothing selected: the three are options, none is selected', async () => {
      setGates();
      const result = await plan((await lawn({ bermuda: true })).visit);
      expect(stepNames(result)).toEqual([]);
      expect(optionNames(result)).toEqual(expect.arrayContaining([REC, FUS, NIS]));
    });

    // Unselected and unusable: the three lines leave with a WARNING, never a block, and the
    // visit's own products, quantities and status are untouched.
    test('limited by the step\'s own sprays, nothing selected: the three lines leave with a warning, the visit is not blocked', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-16', bermuda: true });
      await history(f.customerId, rec, ['2026-06-01']);
      const result = await plan(f.visit);
      for (const name of [REC, FUS, NIS]) expect(optionNames(result)).not.toContain(name);
      expect(result.propertyGate.warnings.map((w) => w.code)).toContain('lawn_bermuda_step_unavailable');
      expect(codes(result)).not.toContain('lawn_bermuda_step_unavailable');
      expect(codes(result)).not.toContain('lawn_v13_annual_limit');
      expect(result.status).not.toBe('blocked');
    });

    test('a capped member with the group selected: the plan\'s mixing order has no bermuda products and is the base visit\'s order', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-16', bermuda: true });
      const clean = await plan(f.visit, { selectedConditionalProductIds: [rec.id] });
      await history(f.customerId, rec, ['2026-06-01']);
      const capped = await plan(f.visit, { selectedConditionalProductIds: [rec.id] });
      expect(capped.mixCalculator.items.filter((item) => item.bermudaStep).every((item) => item.unavailable)).toBe(true);
      expect(JSON.stringify(capped.mixingOrder)).not.toMatch(/Recognition|Fusilade|Surfactant/);
      const noStep = await plan((await lawn({ date: '2026-06-16' })).visit);
      expect(capped.mixingOrder).toEqual(noStep.mixingOrder);
      expect(clean.mixingOrder.length).toBeGreaterThanOrEqual(capped.mixingOrder.length);
    });

    test('the April base visit stays computable beside an unavailable optional step', async () => {
      setGates();
      const f = await lawn({ date: '2026-04-14', bermuda: true });
      const clean = await plan(f.visit);
      await history(f.customerId, rec, ['2026-03-20']);
      const limited = await plan(f.visit);
      expect(limited.propertyGate.warnings.map((w) => w.code)).toContain('lawn_bermuda_step_unavailable');
      // Same blocks, same planned products and amounts as the visit without the limit.
      expect(codes(limited)).toEqual(codes(clean));
      expect(JSON.stringify(limited.mixCalculator.items)).toBe(JSON.stringify(clean.mixCalculator.items));
      expect(limited.mixingOrder).toEqual(clean.mixingOrder);
    });

    test('limited AND selected: the three lines stay, unavailable, each with its own block', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-16', bermuda: true });
      await history(f.customerId, rec, ['2026-06-01']);
      const result = await plan(f.visit, { selectedConditionalProductIds: [rec.id] });
      const lines = result.mixCalculator.items.filter((item) => item.bermudaStep);
      expect(lines.map((l) => l.product.name).sort()).toEqual([FUS, NIS, REC].sort());
      for (const line of lines) expect(line.unavailable.reason).toMatch(/Bermuda removal is blocked/);
      const stepBlocks = result.propertyGate.blocks.filter((b) => b.code === 'lawn_bermuda_step_unavailable');
      expect(stepBlocks.map((b) => b.productName).sort()).toEqual([FUS, NIS, REC].sort());
      expect(codes(result)).toContain('lawn_v13_annual_limit');
    });

    test.each([[REC], [FUS], [NIS]])('%s inactive in the catalog and nothing selected: the three lines leave with a warning', async (name) => {
      setGates();
      await knex('products_catalog').where({ name }).update({ active: false });
      try {
        const result = await plan((await lawn({ bermuda: true })).visit);
        for (const step of [REC, FUS, NIS]) expect(optionNames(result)).not.toContain(step);
        expect(result.propertyGate.warnings.map((w) => w.code)).toContain('lawn_bermuda_step_unavailable');
        expect(codes(result)).not.toContain('lawn_bermuda_step_unavailable');
      } finally {
        await knex('products_catalog').where({ name }).update({ active: true });
      }
    });

    test('Recognition inactive AND selected: only the step lines block', async () => {
      setGates();
      await knex('products_catalog').where({ name: REC }).update({ active: false });
      try {
        const result = await plan((await lawn({ bermuda: true })).visit, { selectedConditionalProductIds: [fus.id] });
        expect(codes(result)).toContain('lawn_bermuda_step_unavailable');
        expect(result.propertyGate.blocks.filter((b) => b.code === 'lawn_bermuda_step_unavailable').every((b) => [FUS, NIS, null].includes(b.productName))).toBe(true);
      } finally {
        await knex('products_catalog').where({ name: REC }).update({ active: true });
      }
    });
  });

  describe('St. Augustine cultivar policy', () => {
    const stepOptions = (result) => optionNames(result).filter((name) => [REC, FUS, NIS].includes(name));

    test.each(['ProVista', 'Captiva', 'seville', 'Seville dwarf'])('%s never gets the step, and the plan says why', async (cultivar) => {
      setGates();
      const f = await lawn({ bermuda: true, acceptedEstimate: true, cultivar });
      const result = await plan(f.visit, { selectedConditionalProductIds: [rec.id, fus.id, nis.id] });
      expect(stepOptions(result)).toEqual([]);
      expect(result.bermudaRemoval).toBeUndefined();
      expect(result.propertyGate.warnings.map((w) => w.code)).toContain('lawn_bermuda_cultivar_excluded');
    });

    test.each(['Floratam', 'Palmetto', 'Raleigh', 'SunClipse'])('%s gets the step with no test-patch note', async (cultivar) => {
      setGates();
      const result = await plan((await lawn({ bermuda: true, cultivar })).visit, { selectedConditionalProductIds: [rec.id] });
      expect(stepOptions(result).sort()).toEqual([FUS, NIS, REC].sort());
      expect(JSON.stringify(result)).not.toMatch(/Test patch first/);
    });

    test.each(['CitraBlue', null, '', 'mystery sod'])('cultivar %p gets the step with a hard test-patch note on each of the three lines', async (cultivar) => {
      setGates();
      const result = await plan((await lawn({ bermuda: true, cultivar })).visit, { selectedConditionalProductIds: [rec.id] });
      const lines = result.mixCalculator.items.filter((item) => [REC, FUS, NIS].includes(item.product?.name));
      expect(lines).toHaveLength(3);
      for (const line of lines) {
        const note = line.gateNotes.find((n) => n.key === 'testPatchFirst');
        expect(note).toMatchObject({ severity: 'required' });
        expect(note.text).toMatch(/3 x 3 ft patch.*3 to 4 weeks/);
      }
      expect(result.propertyGate.warnings.filter((w) => w.code === 'lawn_v13_product_gate' && /Test patch first/.test(w.message))).toHaveLength(3);
    });

    test('Zoysia has no cultivar rule: even ProVista on file gets the step with no note', async () => {
      setGates();
      const result = await plan((await lawn({ grass: 'zoysia', bermuda: true, cultivar: 'ProVista' })).visit, { selectedConditionalProductIds: [rec.id] });
      expect(stepOptions(result).sort()).toEqual([FUS, NIS, REC].sort());
      expect(JSON.stringify(result)).not.toMatch(/Test patch first/);
    });
  });

  describe('limits: 2 sprays a year, 42 days apart', () => {
    test('the migration wrote the hard-block rows for both products and the label warning for Recognition', async () => {
      const rows = await knex('product_limits').whereIn('product_id', [rec.id, fus.id]).select('product_id', 'limit_type', 'limit_value', 'severity');
      const pick = (id) => rows.filter((row) => row.product_id === id).map((row) => `${row.limit_type}:${Number(row.limit_value)}:${row.severity}`).sort();
      expect(pick(rec.id)).toEqual(['annual_max_apps:2:hard_block', 'annual_max_rate:0.1437:warning', 'min_interval_days:42:hard_block']);
      expect(pick(fus.id)).toEqual(['annual_max_apps:2:hard_block', 'min_interval_days:42:hard_block']);
    });

    test('a second spray 41 days after the first is blocked; 42 days after is allowed', async () => {
      setGates();
      const early = await lawn({ date: '2026-06-10', bermuda: true });
      await history(early.customerId, rec, ['2026-04-30']);
      const blocked = await plan(early.visit, { selectedConditionalProductIds: [rec.id, fus.id] });
      expect(blocked.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit').message).toMatch(/only 41 days since last app \(min 42\)/);
      // Selected and limited: the three lines stay, unavailable, each with its own block.
      expect(codes(blocked)).toContain('lawn_bermuda_step_unavailable');
      for (const line of blocked.mixCalculator.items.filter((item) => item.bermudaStep)) expect(line.unavailable).toBeTruthy();
      const ok = await lawn({ date: '2026-06-11', bermuda: true });
      await history(ok.customerId, rec, ['2026-04-30']);
      const allowed = await plan(ok.visit, { selectedConditionalProductIds: [rec.id, fus.id] });
      expect(codes(allowed)).not.toContain('lawn_v13_annual_limit');
      expect(names(allowed.mixCalculator.items)).toEqual(expect.arrayContaining([REC, FUS]));
    });

    test('a third spray in the calendar year is blocked, and waits for next year', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await history(f.customerId, rec, ['2026-03-01', '2026-04-20']);
      const third = await plan(f.visit, { selectedConditionalProductIds: [rec.id] });
      const block = third.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit');
      expect(block.message).toMatch(/2\/2 applications this year — LIMIT REACHED/);
      for (const line of third.mixCalculator.items.filter((item) => item.bermudaStep)) expect(line.unavailable).toBeTruthy();
      // The count is per calendar year: the same two sprays do not count next year.
      const nextYear = await lawn({ date: '2027-04-13', bermuda: true });
      await history(nextYear.customerId, rec, ['2026-03-01', '2026-04-20']);
      const fresh = await plan(nextYear.visit, { selectedConditionalProductIds: [rec.id] });
      expect(codes(fresh)).not.toContain('lawn_v13_annual_limit');
    });
  });

  describe('the staged-row migration', () => {
    const count = async () => ({
      rows: Number((await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'").count('* as n').first()).n),
      limits: Number((await knex('product_limits').whereIn('product_id', [rec.id, fus.id]).count('* as n').first()).n),
    });

    test('12 rows (2 grasses x 2 windows x 3 products) and 5 limits; the other grasses get none', async () => {
      expect(await count()).toEqual({ rows: 12, limits: 5 });
      const onOtherGrasses = await knex('lawn_protocol_products as p')
        .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
        .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
        .whereRaw("p.gates->>'bermudaRemoval' = 'true'").whereIn('l.grass_track', ['bermuda', 'bahia']).count('* as n').first();
      expect(Number(onOtherGrasses.n)).toBe(0);
      const mayRows = await knex('lawn_protocol_products as p')
        .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
        .whereRaw("p.gates->>'bermudaRemoval' = 'true'").where('w.window_key', 'may_v13_tetrino_hose').count('* as n').first();
      expect(Number(mayRows.n)).toBe(0);
    });

    test('every row is a spot row that is not in the plan by default, with a catalog link', async () => {
      const rows = await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'");
      expect(rows.every((row) => row.application_mode === 'spot' && row.default_in_plan === false && row.product_id)).toBe(true);
    });

    test('up twice is a no-op; down removes exactly the 12 rows and 5 limits; up again restores them', async () => {
      await rowsMigration.up(knex);
      expect(await count()).toEqual({ rows: 12, limits: 5 });
      await rowsMigration.down(knex);
      expect(await count()).toEqual({ rows: 0, limits: 0 });
      await rowsMigration.up(knex);
      await programMigration.up(knex);
      expect(await count()).toEqual({ rows: 12, limits: 5 });
    });

    test('a row a completion actual references survives down (documented no-op for it)', async () => {
      const row = await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'").first();
      await knex('lawn_protocol_product_actuals').insert({ protocol_product_id: row.id, lawn_protocol_service_completion_id: require('crypto').randomUUID(), product_name: row.product_name });
      const hasActual = await knex('lawn_protocol_product_actuals').where({ protocol_product_id: row.id }).first();
      expect(hasActual).toBeTruthy();
      await rowsMigration.down(knex);
      const left = Number((await knex('lawn_protocol_products').whereRaw("gates->>'bermudaRemoval' = 'true'").count('* as n').first()).n);
      expect(left).toBe(1);
      await knex('lawn_protocol_product_actuals').where({ protocol_product_id: row.id }).del();
      await rowsMigration.down(knex);
      await rowsMigration.up(knex);
      await programMigration.up(knex);
      expect(await count()).toEqual({ rows: 12, limits: 5 });
    });
  });

  describe('completion: Recognition and Fusilade II are recorded together on a bermuda removal visit', () => {
    const submitted = (...items) => items.map((item) => ({ productId: item.id }));
    const check = async (f, ...items) => bermudaPairViolation(knex, submitted(...items), { serviceId: f.visit.id });

    test('on a visit that carries the step, one without the other is refused with a clear message; the surfactant is optional', async () => {
      setGates();
      for (const date of ['2026-04-14', '2026-06-16']) {
        const f = await lawn({ date, bermuda: true });
        expect(await check(f, rec)).toMatch(/Recognition goes on with Fusilade II/);
        expect(await check(f, fus)).toMatch(/Fusilade II is never applied without Recognition/);
        expect(await check(f, fus, nis)).toMatch(/without Recognition/);
        expect(await check(f, rec, fus)).toBeNull();
        expect(await check(f, rec, fus, nis)).toBeNull();
      }
      const viaEstimate = await lawn({ acceptedEstimate: true });
      expect(await check(viaEstimate, fus)).toMatch(/without Recognition/);
    });

    test('Fusilade II or Recognition alone on a visit that does NOT carry the step completes normally', async () => {
      setGates();
      const unflagged = await lawn({});
      expect(await check(unflagged, fus)).toBeNull();
      expect(await check(unflagged, rec)).toBeNull();
      const wrongMonth = await lawn({ date: '2026-05-12', bermuda: true });
      expect(await check(wrongMonth, fus)).toBeNull();
      const otherGrass = await lawn({ grass: 'bermuda', bermuda: true });
      expect(await check(otherGrass, fus)).toBeNull();
      const excluded = await lawn({ bermuda: true, cultivar: 'ProVista' });
      expect(await check(excluded, fus)).toBeNull();
      // No visit named, a malformed id, or an unknown visit: nothing is judged.
      expect(await bermudaPairViolation(knex, submitted(fus))).toBeNull();
      expect(await bermudaPairViolation(knex, submitted(fus), { serviceId: 'not-a-uuid' })).toBeNull();
      expect(await bermudaPairViolation(knex, submitted(fus), { serviceId: '99999999-9999-4999-8999-999999999999' })).toBeNull();
    });

    test('other products, no products, gate off and v13 off are never refused', async () => {
      setGates();
      const f = await lawn({ bermuda: true });
      expect(await check(f, nis)).toBeNull();
      expect(await bermudaPairViolation(knex, [], { serviceId: f.visit.id })).toBeNull();
      expect(await bermudaPairViolation(knex, undefined, { serviceId: f.visit.id })).toBeNull();
      expect(await bermudaPairViolation(knex, [{ productId: null }], { serviceId: f.visit.id })).toBeNull();
      setGates({ removal: false });
      expect(await check(f, rec)).toBeNull();
      setGates({ v13: false });
      expect(await check(f, fus)).toBeNull();
    });
  });

  describe('completion: the step\'s own limits (fresh attempts)', () => {
    const submitted = (...items) => items.map((item) => ({ productId: item.id }));
    const spray = async (customerId, propertyId, date) => {
      const [visit] = await knex('scheduled_services').insert({ customer_id: customerId, property_id: propertyId, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
      const [record] = await knex('service_records').insert({ customer_id: customerId, scheduled_service_id: visit.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
      await knex('property_application_history').insert({ customer_id: customerId, product_id: rec.id, application_date: date, service_record_id: record.id });
      return visit;
    };

    test('a 3rd spray this calendar year is refused with the limit message', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await spray(f.customerId, f.property.id, '2026-03-01');
      await spray(f.customerId, f.property.id, '2026-04-20');
      const message = await bermudaLimitViolation(knex, submitted(rec, fus, nis), { serviceId: f.visit.id });
      expect(message).toMatch(/2\/2 applications this year — LIMIT REACHED/);
    });

    test('a spray fewer than 42 days after the last one at that property is refused; 42 days is allowed', async () => {
      setGates();
      const early = await lawn({ date: '2026-06-10', bermuda: true });
      await spray(early.customerId, early.property.id, '2026-04-30');
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: early.visit.id })).toMatch(/only 41 days since last app \(min 42\)/);
      const ok = await lawn({ date: '2026-06-11', bermuda: true });
      await spray(ok.customerId, ok.property.id, '2026-04-30');
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: ok.visit.id })).toBeNull();
    });

    test('another property\'s sprays and this visit\'s own earlier rows do not count; a retry of the visit is not judged against itself', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      const [other] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '400 Other Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      await spray(f.customerId, other.id, '2026-03-01');
      await spray(f.customerId, other.id, '2026-04-20');
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: f.visit.id })).toBeNull();
      // This visit's own ledger row (a first attempt) is left out.
      const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: f.visit.id, service_date: '2026-06-20', service_type: 'Lawn fixture' }).returning('*');
      await knex('property_application_history').insert({ customer_id: f.customerId, product_id: rec.id, application_date: '2026-06-20', service_record_id: record.id });
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: f.visit.id })).toBeNull();
    });

    test('a visit that does not carry the step, no step product, gate off and v13 off are never refused', async () => {
      setGates();
      const unflagged = await lawn({ date: '2026-06-20' });
      await spray(unflagged.customerId, unflagged.property.id, '2026-03-01');
      await spray(unflagged.customerId, unflagged.property.id, '2026-04-20');
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: unflagged.visit.id })).toBeNull();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await spray(f.customerId, f.property.id, '2026-03-01');
      await spray(f.customerId, f.property.id, '2026-04-20');
      expect(await bermudaLimitViolation(knex, submitted(nis), { serviceId: f.visit.id })).toBeNull();
      expect(await bermudaLimitViolation(knex, [], { serviceId: f.visit.id })).toBeNull();
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: f.visit.id })).toMatch(/LIMIT REACHED/);
      setGates({ removal: false });
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: f.visit.id })).toBeNull();
      setGates({ v13: false });
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: f.visit.id })).toBeNull();
    });
  });

  describe('the step limits inside the completion transaction (20261006 r6)', () => {
    const submitted = (...items) => items.map((item) => ({ productId: item.id }));
    const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    const ledger = async (trx, f, visit, date) => {
      const [record] = await trx('service_records').insert({ customer_id: f.customerId, scheduled_service_id: visit.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
      await trx('property_application_history').insert({ customer_id: f.customerId, product_id: rec.id, application_date: date, service_record_id: record.id });
    };
    const priorSpray = async (f, date) => {
      const [visit] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: f.property.id, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
      await ledger(knex, f, visit, date);
    };

    test('two concurrent completions for one property when history allows ONE more spray: exactly one commits', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await priorSpray(f, '2026-03-01'); // 1 of 2 used
      const [second] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: f.property.id, scheduled_date: '2026-06-20', service_type: 'Lawn fixture' }).returning('*');
      // Both preflights pass: neither spray is on the ledger yet.
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: f.visit.id })).toBeNull();
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: second.id })).toBeNull();
      const run = (visit) => knex.transaction(async (trx) => {
        await enforceStepLimitsInTransaction(trx, submitted(rec, fus), { serviceId: visit.id });
        await sleep(300); // hold the transaction open: the other must wait on the property lock
        await ledger(trx, f, visit, '2026-06-20');
        return visit.id;
      });
      const results = await Promise.allSettled([run(f.visit), run(second)]);
      expect(results.filter((r) => r.status === 'fulfilled')).toHaveLength(1);
      const rejected = results.find((r) => r.status === 'rejected');
      expect(rejected.reason.code).toBe('lawn_bermuda_limit_reached');
      expect(rejected.reason.message).toMatch(/LIMIT REACHED|days since last app/);
      const sprays = await knex('property_application_history').where({ customer_id: f.customerId, product_id: rec.id });
      expect(sprays).toHaveLength(2); // the prior one plus exactly one of the two
    });

    test('the in-transaction check sees a spray committed AFTER the preflight', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await priorSpray(f, '2026-03-01');
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: f.visit.id })).toBeNull();
      await priorSpray(f, '2026-04-20'); // a concurrent completion commits its spray
      await expect(knex.transaction((trx) => enforceStepLimitsInTransaction(trx, submitted(rec, fus), { serviceId: f.visit.id })))
        .rejects.toMatchObject({ code: 'lawn_bermuda_limit_reached', message: expect.stringMatching(/2\/2 applications this year — LIMIT REACHED/) });
    });

    test('different properties of one customer do not serialize or block each other; a visit with no step, no step product, gate off and v13 off are untouched', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await priorSpray(f, '2026-03-01');
      await expect(knex.transaction((trx) => enforceStepLimitsInTransaction(trx, submitted(rec, fus), { serviceId: f.visit.id }))).resolves.toBeUndefined();
      await expect(knex.transaction((trx) => enforceStepLimitsInTransaction(trx, submitted(nis), { serviceId: f.visit.id }))).resolves.toBeUndefined();
      const unflagged = await lawn({ date: '2026-06-20' });
      await priorSpray(unflagged, '2026-03-01');
      await priorSpray(unflagged, '2026-04-20');
      await expect(knex.transaction((trx) => enforceStepLimitsInTransaction(trx, submitted(rec, fus), { serviceId: unflagged.visit.id }))).resolves.toBeUndefined();
      await priorSpray(f, '2026-04-20');
      setGates({ removal: false });
      await expect(knex.transaction((trx) => enforceStepLimitsInTransaction(trx, submitted(rec, fus), { serviceId: f.visit.id }))).resolves.toBeUndefined();
      setGates({ v13: false });
      await expect(knex.transaction((trx) => enforceStepLimitsInTransaction(trx, submitted(rec, fus), { serviceId: f.visit.id }))).resolves.toBeUndefined();
    });

    test('a propertyless visit of a one-property customer locks on that sole property: it serializes with an explicit-property completion', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await priorSpray(f, '2026-03-01'); // 1 of 2 used
      const [propertyless] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: null, scheduled_date: '2026-06-20', service_type: 'Lawn fixture' }).returning('*');
      const explicit = f.visit; // names the property
      const run = (visit) => knex.transaction(async (trx) => {
        await enforceStepLimitsInTransaction(trx, submitted(rec, fus), { serviceId: visit.id });
        await sleep(300);
        await ledger(trx, f, visit, '2026-06-20');
      });
      const results = await Promise.allSettled([run(propertyless), run(explicit)]);
      expect(results.filter((r) => r.status === 'fulfilled')).toHaveLength(1);
      expect(results.find((r) => r.status === 'rejected').reason.code).toBe('lawn_bermuda_limit_reached');
      expect(await knex('property_application_history').where({ customer_id: f.customerId, product_id: rec.id })).toHaveLength(2);
    });

    test('the propertyless visit is judged against that sole property\'s history', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await priorSpray(f, '2026-03-01');
      await priorSpray(f, '2026-04-20');
      const [propertyless] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: null, scheduled_date: '2026-06-20', service_type: 'Lawn fixture' }).returning('*');
      expect(await bermudaLimitViolation(knex, submitted(rec, fus), { serviceId: propertyless.id })).toMatch(/LIMIT REACHED/);
    });

    test('control: without the property lock the same two completions BOTH pass (the lock is what serializes them)', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await priorSpray(f, '2026-03-01');
      const [second] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: f.property.id, scheduled_date: '2026-06-20', service_type: 'Lawn fixture' }).returning('*');
      const unlocked = (visit) => knex.transaction(async (trx) => {
        const message = await bermudaLimitViolation(trx, submitted(rec, fus), { serviceId: visit.id });
        if (message) throw new Error(message);
        await sleep(300);
        await ledger(trx, f, visit, '2026-06-20');
      });
      const results = await Promise.allSettled([unlocked(f.visit), unlocked(second)]);
      expect(results.filter((r) => r.status === 'fulfilled')).toHaveLength(2);
    });
  });

  describe('application limits: the bermuda removal rows (20261006190300)', () => {
    const limits = require('../services/application-limits');
    const rowsFor = (product) => knex('product_limits').where({ product_id: product.id });

    test('the migration marks exactly the 5 rows; down clears them; up restores; other rows are never touched', async () => {
      const tagged = () => knex('product_limits').where({ match_value: 'bermuda_removal' });
      expect(await tagged()).toHaveLength(5);
      const celsius = await product('Celsius WG');
      await knex('product_limits').insert({ product_id: celsius.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 3, severity: 'hard_block', description: 'Celsius cap' });
      await programMigration.down(knex);
      expect(await tagged()).toHaveLength(0);
      await programMigration.up(knex);
      await programMigration.up(knex);
      expect(await tagged()).toHaveLength(5);
      expect((await rowsFor(celsius)).every((row) => row.match_value == null)).toBe(true);
    });

    // Two properties, one customer: a spray on the OTHER property, a spray at this property,
    // and one with an unknown property (no visit).
    async function twoProperties() {
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      const [other] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '200 Other Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      const ledger = async (propertyId, date, product = rec) => {
        const [visit] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: propertyId, scheduled_date: date, service_type: 'Lawn fixture' }).returning('*');
        const [record] = await knex('service_records').insert({ customer_id: f.customerId, scheduled_service_id: visit.id, service_date: date, service_type: 'Lawn fixture' }).returning('*');
        await knex('property_application_history').insert({ customer_id: f.customerId, product_id: product.id, application_date: date, service_record_id: record.id });
      };
      return { f, other, ledger };
    }
    const check = (f, propertyId, extra = {}, product = rec) => limits.checkLimits(f.customerId, product.id, '2026-06-20', knex, { program: 'bermuda_removal', propertyId, ...extra });

    test('the rows apply only to a caller that names the program; compliance and every other caller ignore them', async () => {
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await history(f.customerId, rec, ['2026-03-01', '2026-04-20']);
      setGates();
      expect((await check(f, f.property.id)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
      const noProgram = await limits.checkLimits(f.customerId, rec.id, '2026-06-20', knex, { propertyId: f.property.id });
      expect(noProgram.blocks).toEqual([]);
      expect(noProgram.warnings.filter((w) => w.type === 'annual_max_rate')).toEqual([]);
      expect((await limits.checkLimits(f.customerId, fus.id, '2026-06-20', knex)).blocks).toEqual([]);
      expect((await limits.getPropertyComplianceStatus(f.customerId)).blocks).toBe(0);
      // Gate off: even the named program is inert.
      setGates({ removal: false });
      expect((await check(f, f.property.id)).blocks).toEqual([]);
    });

    test('Fusilade II used on its own (bed or border work) does not consume the step\'s quota; Recognition sprays count for BOTH products', async () => {
      setGates();
      const bed = await lawn({ date: '2026-06-20', bermuda: true });
      await history(bed.customerId, fus, ['2026-03-01', '2026-04-20', '2026-06-10']);
      expect((await check(bed, bed.property.id, {}, fus)).blocks).toEqual([]);
      expect((await check(bed, bed.property.id, {}, rec)).blocks).toEqual([]);
      const mix = await lawn({ date: '2026-06-20', bermuda: true });
      await history(mix.customerId, rec, ['2026-03-01', '2026-04-20']);
      expect((await check(mix, mix.property.id, {}, fus)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
      expect((await check(mix, mix.property.id, {}, rec)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
    });

    test('with the treated property known, a spray at ANOTHER property does not count; this property and unknown-property rows do', async () => {
      setGates();
      const { f, other, ledger } = await twoProperties();
      await ledger(other.id, '2026-03-01');
      await ledger(other.id, '2026-04-20');
      expect((await check(f, f.property.id)).blocks).toEqual([]);
      expect((await check(f, other.id)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
      await ledger(f.property.id, '2026-03-02');
      await history(f.customerId, rec, ['2026-04-21']); // property unknown (no service record)
      expect((await check(f, f.property.id)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
    });

    test('with no property named, the whole customer counts', async () => {
      setGates();
      const { f, other, ledger } = await twoProperties();
      await ledger(other.id, '2026-03-01');
      await ledger(other.id, '2026-04-20');
      expect((await check(f, null)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
    });

    test('the 42-day interval is per property too; the visit being planned is left out', async () => {
      setGates();
      const { f, other, ledger } = await twoProperties();
      await ledger(other.id, '2026-06-10');
      expect((await check(f, f.property.id)).blocks).toEqual([]);
      expect((await check(f, other.id)).blocks.map((b) => b.type)).toEqual(['min_interval_days']);
      await ledger(f.property.id, '2026-06-10');
      const [mine] = await knex('scheduled_services').where({ property_id: f.property.id, scheduled_date: '2026-06-10' });
      expect((await check(f, f.property.id, { excludeScheduledServiceId: mine.id })).blocks).toEqual([]);
    });

    test('history is bounded at the date judged: an April plan rebuilt after a June spray is not withheld', async () => {
      setGates();
      const f = await lawn({ date: '2026-04-14', bermuda: true });
      await history(f.customerId, rec, ['2026-03-01', '2026-06-10', '2026-06-20']);
      const april = await limits.checkLimits(f.customerId, rec.id, '2026-04-14', knex, { program: 'bermuda_removal', propertyId: f.property.id });
      expect(april.blocks).toEqual([]);
      // One earlier spray counts normally; both June sprays count from June on.
      const june = await limits.checkLimits(f.customerId, rec.id, '2026-07-01', knex, { program: 'bermuda_removal', propertyId: f.property.id });
      expect(june.blocks.map((b) => b.type)).toEqual(expect.arrayContaining(['annual_max_apps']));
      const planned = await plan(f.visit);
      expect(codes(planned)).not.toContain('lawn_v13_annual_limit');
      expect(planned.propertyGate.warnings.map((w) => w.code)).not.toContain('lawn_bermuda_step_unavailable');
    });

    test('Recognition is counted by catalog id, not display name: a renamed Recognition still counts', async () => {
      setGates();
      const f = await lawn({ date: '2026-06-20', bermuda: true });
      await history(f.customerId, rec, ['2026-03-01', '2026-04-20']);
      await knex('products_catalog').where({ id: rec.id }).update({ name: 'Recognition (renamed by the office)' });
      try {
        expect((await check(f, f.property.id, {}, fus)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
        expect((await check(f, f.property.id, {}, rec)).blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
      } finally {
        await knex('products_catalog').where({ id: rec.id }).update({ name: REC });
      }
    });

    test('every other product keeps whole-customer history, property named or not', async () => {
      setGates();
      const { f, other, ledger } = await twoProperties();
      const celsius = await knex('products_catalog').where({ name: 'Celsius WG' }).first();
      await knex('product_limits').where({ product_id: celsius.id }).del();
      await knex('product_limits').insert({ product_id: celsius.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 2, severity: 'hard_block', description: 'Celsius cap' });
      await ledger(other.id, '2026-03-01', celsius);
      await ledger(other.id, '2026-04-20', celsius);
      const result = await limits.checkLimits(f.customerId, celsius.id, '2026-06-20', knex, { propertyId: f.property.id });
      expect(result.blocks.map((b) => b.type)).toEqual(['annual_max_apps']);
    });
  });

  describe('which lawn carries the step: track and property', () => {
    const { stepForVisit } = require('../services/lawn-bermuda-removal');
    const twoProps = async (changes = {}) => {
      const f = await lawn({ bermuda: true, ...changes });
      const [second] = await knex('customer_properties').insert({ customer_id: f.customerId, address_line1: '300 Second Street', city: 'Fixture City', zip: '34201', is_primary: false }).returning('*');
      const [secondVisit] = await knex('scheduled_services').insert({ customer_id: f.customerId, property_id: second.id, scheduled_date: changes.date || '2026-04-14', service_type: 'Lawn fixture' }).returning('*');
      return { f, second, secondVisit };
    };
    const step = (visit, trackKey = 'st_augustine', month = 'Apr') => stepForVisit(knex, visit, { trackKey, month });

    test('the track comes from the active profile: a ProVista St. Augustine profile asked as zoysia opens nothing; a zoysia profile asked as St. Augustine opens nothing', async () => {
      setGates();
      const aug = await lawn({ bermuda: true, cultivar: 'Floratam' });
      expect((await step(aug.visit, 'st_augustine')).active).toBe(true);
      expect((await step(aug.visit, 'zoysia')).active).toBe(false);
      const proVista = await lawn({ bermuda: true, cultivar: 'ProVista' });
      expect((await step(proVista.visit, 'zoysia')).active).toBe(false);
      expect((await step(proVista.visit, 'st_augustine')).excluded).toBe(true);
      const zoysia = await lawn({ grass: 'zoysia', bermuda: true });
      expect((await step(zoysia.visit, 'zoysia')).active).toBe(true);
      expect((await step(zoysia.visit, 'st_augustine')).active).toBe(false);
      const bahia = await lawn({ grass: 'bahia', bermuda: true });
      expect((await step(bahia.visit, 'st_augustine')).active).toBe(false);
    });

    test('a one-property customer: the visit with or without its property carries the step', async () => {
      setGates();
      const f = await lawn({ bermuda: true });
      expect((await step(f.visit)).active).toBe(true);
      expect((await step({ ...f.visit, property_id: null })).active).toBe(true);
    });

    test('a two-property customer: the step follows the PRIMARY property only; the second property and a visit with no property carry none', async () => {
      setGates();
      const { f, secondVisit } = await twoProps();
      expect((await step(f.visit)).active).toBe(true);
      expect((await step(secondVisit)).active).toBe(false);
      expect((await step({ ...f.visit, property_id: null })).active).toBe(false);
    });

    test('inactive properties do not count: a second property marked inactive leaves a one-property customer', async () => {
      setGates();
      const { f, second } = await twoProps();
      await knex('customer_properties').where({ id: second.id }).update({ active: false });
      expect((await step({ ...f.visit, property_id: null })).active).toBe(true);
    });

    test('estimate evidence counts only for the visit\'s property (or a property-less estimate of a one-property customer)', async () => {
      setGates();
      const estimateData = JSON.stringify({ engineRequest: { options: { bermudaSuppression: true } } });
      const { f, second, secondVisit } = await twoProps({ bermuda: false });
      await knex('estimates').insert({ customer_id: f.customerId, status: 'accepted', property_id: second.id, estimate_data: estimateData });
      // The estimate is for the second property; the profile speaks for the primary one: nothing carries.
      expect((await step(f.visit)).active).toBe(false);
      expect((await step(secondVisit)).active).toBe(false);
      await knex('estimates').del().where({ customer_id: f.customerId });
      await knex('estimates').insert({ customer_id: f.customerId, status: 'accepted', property_id: f.property.id, estimate_data: estimateData });
      expect((await step(f.visit)).active).toBe(true);
      expect((await step(secondVisit)).active).toBe(false);
      // No property on the estimate: counts only when the customer has one property.
      await knex('estimates').del().where({ customer_id: f.customerId });
      await knex('estimates').insert({ customer_id: f.customerId, status: 'accepted', estimate_data: estimateData });
      expect((await step(f.visit)).active).toBe(false);
      await knex('customer_properties').where({ id: second.id }).update({ active: false });
      expect((await step(f.visit)).active).toBe(true);
    });

    test('the step month is the visit\'s own: a June request on an October visit opens nothing', async () => {
      setGates();
      const october = await lawn({ date: '2026-10-12', bermuda: true });
      expect((await step(october.visit, 'st_augustine', 'Jun')).active).toBe(false);
      expect((await step(october.visit, 'st_augustine', 'Oct')).active).toBe(false); // the step runs April and June only
      const june = await lawn({ date: '2026-06-16', bermuda: true });
      expect((await step(june.visit, 'st_augustine', 'Jun')).active).toBe(true);
      expect((await step(june.visit, 'st_augustine', 'Apr')).active).toBe(false);
    });

    test('the plan follows the same rule: a visit at the second property gets no step', async () => {
      setGates();
      const { f, secondVisit } = await twoProps();
      expect((await plan(f.visit)).bermudaRemoval).toMatchObject({ active: true });
      const second = await plan(secondVisit);
      expect(second.bermudaRemoval).toBeUndefined();
      expect(optionNames(second)).not.toContain(REC);
    });
  });

  describe('the audit migration (20261006190200)', () => {
    const entries = () => knex('lawn_protocol_audit_log').where({ action: 'seed_v13_bermuda_removal' });

    test('one entry per affected protocol with a snapshot of the rows added; up twice is a no-op; down removes them; up restores', async () => {
      await auditMigration.down(knex);
      await auditMigration.up(knex);
      let rows = await entries();
      expect(rows).toHaveLength(2);
      for (const row of rows) {
        expect(row).toMatchObject({ actor_name: 'migration 20261006190100', entity_type: 'protocol' });
        const snapshot = typeof row.after_snapshot === 'string' ? JSON.parse(row.after_snapshot) : row.after_snapshot;
        expect(['swfl_st_augustine_10_10', 'swfl_zoysia_10_10']).toContain(snapshot.protocol_key);
        expect(snapshot.added_products).toHaveLength(6);
        expect(snapshot.added_products.map((p) => p.window_key).sort()).toEqual([
          ...Array(3).fill('apr_v13_spreader_feeding'), ...Array(3).fill('jun_v13_hose_blackout')].sort());
        expect(snapshot.added_products.every((p) => p.application_mode === 'spot')).toBe(true);
      }
      await auditMigration.up(knex);
      expect(await entries()).toHaveLength(2);
      await auditMigration.down(knex);
      expect(await entries()).toHaveLength(0);
      await auditMigration.up(knex);
      rows = await entries();
      expect(rows).toHaveLength(2);
    });

    test('down leaves every other audit entry alone', async () => {
      await knex('lawn_protocol_audit_log').insert({
        lawn_protocol_id: (await knex('lawn_protocols').first('id')).id, actor_name: 'someone else', entity_type: 'protocol',
        entity_id: (await knex('lawn_protocols').first('id')).id, action: 'seed_v13',
      });
      await auditMigration.down(knex);
      expect(Number((await knex('lawn_protocol_audit_log').where({ action: 'seed_v13' }).count('* as n').first()).n)).toBe(1);
      await auditMigration.up(knex);
    });
  });
});
