// Lawn protocol v13: three empty chemical groups are filled (migration 20261009176000), through the real migration on PostgreSQL (cloned
// schema). Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned: Gravex frac_group '3', Dylox 6.2 G irac_group '1B' and the Dimension MOP row (resolved by alias) hrac_group '3' are filled only
// where empty (null, '' or blanks); a value somebody wrote stays; Dylox 420 SL (moa_group only) and the decoy are untouched; a second up
// changes nothing; a missing catalog row skips only its own group; the write is one guarded statement; down leaves every catalog value
// (a value equal to the one written may be an administrator's) and removes only its own audit row.
const { createLawnHistoryDb } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009176000_lawn_v13_three_chemical_groups');

const GRAVEX = 'Gravex 20 EW';
const DYLOX = 'Dylox 6.2 G Granular Insecticide';
const SL = 'Dylox 420 SL T&O Insecticide';
const DIMENSION_MOP = 'LESCO Dimension 0.21% 18-0-10 50% PolyPlus OPTI45 MOP Pre-Emergent Plus Fertilizer';
const CATALOG_TABLES = ['products_catalog', 'product_aliases', 'lawn_protocol_audit_log'];

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 three chemical groups migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of CATALOG_TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    await knex.raw('ALTER TABLE ??.product_aliases ADD CONSTRAINT fixture_aliases_product FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)', [owned.schema, owned.schema]);
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const read = async (name, column) => (await knex('products_catalog').where({ name }).first(column))[column];
  const ours = () => knex('lawn_protocol_audit_log').where({ action: migration.ACTION });
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  const snapshot = async () => clean([await knex('products_catalog').orderBy('name'), await knex('lawn_protocol_audit_log').orderBy('id')]);

  // The catalog as production holds it: the three groups empty, Dylox 420 SL with moa_group only.
  async function reset({ gravex = true } = {}) {
    for (const table of ['lawn_protocol_audit_log', 'product_aliases', 'products_catalog']) await knex(table).del();
    const insert = async (row) => (await knex('products_catalog').insert({ active: true, ...row }).returning('*'))[0];
    if (gravex) ids.gravex = (await insert({ name: GRAVEX, category: 'fungicide' })).id;
    ids.dylox = (await insert({ name: DYLOX, category: 'insecticide', active_ingredient: 'trichlorfon 6.2%' })).id;
    ids.sl = (await insert({ name: SL, category: 'insecticide', moa_group: 'Group 1B' })).id;
    ids.dimension = (await insert({ name: 'Dimension MOP catalog row', category: 'fertilizer' })).id;
    await knex('product_aliases').insert({ product_id: ids.dimension, alias_name: DIMENSION_MOP });
  }

  describe('fresh path', () => {
    let before;
    beforeAll(async () => {
      await reset();
      before = clean(await knex('products_catalog').where({ name: SL }));
      await migration.up(knex);
    });

    test('the three groups are filled in the typed column, bare code; the Dimension row is found by alias', async () => {
      expect(await read(GRAVEX, 'frac_group')).toBe('3');
      expect(await read(DYLOX, 'irac_group')).toBe('1B');
      expect(await knex('products_catalog').where({ id: ids.dimension }).first('hrac_group', 'frac_group', 'irac_group', 'moa_group')).toEqual({ hrac_group: '3', frac_group: null, irac_group: null, moa_group: null });
      // Only the typed column: no second moa_group, which productGroups would read as the same group twice.
      expect(await knex('products_catalog').where({ name: GRAVEX }).first('moa_group', 'irac_group', 'hrac_group')).toEqual({ moa_group: null, irac_group: null, hrac_group: null });
      expect(await knex('products_catalog').where({ name: DYLOX }).first('moa_group', 'frac_group', 'hrac_group')).toEqual({ moa_group: null, frac_group: null, hrac_group: null });
    });

    test('Dylox 420 SL is not touched', async () => {
      expect(clean(await knex('products_catalog').where({ name: SL }))).toBe(before);
      expect(await read(SL, 'moa_group')).toBe('Group 1B');
    });

    test('one audit row; a second up changes nothing', async () => {
      const [audit] = await ours();
      expect(audit.after_snapshot.changes.map((c) => [c.name, c.column, c.value])).toEqual(migration.GROUPS.map((g) => [g.name, g.column, g.value]));
      const state = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(state);
    });

    test('down leaves every catalog value and removes only its own audit row', async () => {
      await knex('lawn_protocol_audit_log').insert({ actor_name: 'someone else', entity_type: 'catalog', entity_id: '00000000-0000-0000-0000-000000000001', action: 'other', changed_fields: '[]', before_snapshot: '{}', after_snapshot: '{}', metadata: '{}' });
      await migration.down(knex);
      expect(await read(GRAVEX, 'frac_group')).toBe('3');
      expect(await read(DYLOX, 'irac_group')).toBe('1B');
      expect(await knex('products_catalog').where({ id: ids.dimension }).first('hrac_group')).toEqual({ hrac_group: '3' });
      expect(await ours()).toHaveLength(0);
      expect(await knex('lawn_protocol_audit_log').where({ action: 'other' })).toHaveLength(1);
    });
  });

  describe('values that are not empty', () => {
    beforeEach(() => reset());

    test('a hand-written group stays; an empty string and blanks count as empty', async () => {
      await knex('products_catalog').where({ id: ids.gravex }).update({ frac_group: '7' });
      await knex('products_catalog').where({ id: ids.dylox }).update({ irac_group: '' });
      await knex('products_catalog').where({ id: ids.dimension }).update({ hrac_group: '   ' });
      await migration.up(knex);
      expect(await read(GRAVEX, 'frac_group')).toBe('7');
      expect(await read(DYLOX, 'irac_group')).toBe('1B');
      expect(await knex('products_catalog').where({ id: ids.dimension }).first('hrac_group')).toEqual({ hrac_group: '3' });
      expect((await ours())[0].after_snapshot.changes.map((c) => c.name)).toEqual([DYLOX, DIMENSION_MOP]);
    });

    test('when every group is already set, nothing is written and no audit row is made', async () => {
      await knex('products_catalog').where({ id: ids.gravex }).update({ frac_group: '3' });
      await knex('products_catalog').where({ id: ids.dylox }).update({ irac_group: '1B' });
      await knex('products_catalog').where({ id: ids.dimension }).update({ hrac_group: '3' });
      const state = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(state);
      expect(await ours()).toHaveLength(0);
    });

    test('each group is written by one UPDATE that carries the emptiness guard (so a concurrent edit is never overwritten)', async () => {
      const statements = [];
      const spy = (query) => statements.push(query.sql);
      knex.on('query', spy);
      try { await migration.up(knex); } finally { knex.removeListener('query', spy); }
      const updates = statements.filter((sql) => /^update\s+"?[\w]*"?\.?"?products_catalog/i.test(sql) || /update .*products_catalog/i.test(sql));
      expect(updates).toHaveLength(3);
      for (const sql of updates) expect(sql).toMatch(/is null or btrim\(.*\) = ''/i);
    });
  });

  test('a catalog row that is missing skips only its own group', async () => {
    await reset({ gravex: false });
    await migration.up(knex);
    expect(await read(DYLOX, 'irac_group')).toBe('1B');
    expect(await knex('products_catalog').where({ id: ids.dimension }).first('hrac_group')).toEqual({ hrac_group: '3' });
    expect(await knex('products_catalog').where({ name: GRAVEX })).toHaveLength(0);
  });
});
