// GATE_LAWN_V13 through the real plan engine and PostgreSQL (cloned schema):
// a visit plans from the staged v13 protocol or not at all, whatever the
// completion-default gates say. Pinned older visits and a missing staged row get
// no calculated products and a block; the staged visit gets the row's rate and
// its sunny-turf limit. Synthetic data only.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION } = require('../services/lawn-program');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const KEY = 'fixture_v13_lawn';
const OLD_VERSION = '2026.06';
const PREREQ = [['on', 'on'], ['on', 'off'], ['off', 'on'], ['off', 'off']];
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY'];

function setGates({ v13 = 'on', completion = 'off', history = 'off' } = {}) {
  for (const [name, value] of [['GATE_LAWN_V13', v13], ['GATE_LAWN_COMPLETION_DEFAULTS', completion], ['GATE_LAWN_PROPERTY_HISTORY', history]]) {
    if (value === 'on') process.env[name] = 'true'; else delete process.env[name];
  }
}

describeDb('the v13 plan through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  let tetrino;

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals']) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    [tetrino] = await knex('products_catalog').insert({
      name: 'Tetrino Insecticide', category: 'insecticide', default_rate_per_1000: 0.367, rate_unit: 'fl oz',
      label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'fl oz', active: true,
    }).returning('*');
    const [old] = await knex('lawn_protocols').insert({ protocol_key: KEY, version: OLD_VERSION, name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' }).returning('*');
    const [staged] = await knex('lawn_protocols').insert({ protocol_key: KEY, version: LAWN_V13_VERSION, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
    for (const [protocol, windowKey] of [[old, 'fixture_5'], [staged, 'may_v13']]) {
      const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 5, window_key: windowKey, title: windowKey, visit_type: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: window.id, product_id: tetrino.id, product_name: tetrino.name, role: 'insecticide', application_mode: 'broadcast',
        default_in_plan: true, rate_per_1000: 0.367, rate_unit: 'fl oz', gates: JSON.stringify(protocol === staged ? { sunnyTurfOnly: true } : {}),
      });
    }
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  });
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  async function plannedVisit(changes = {}) {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
    await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, grass_type: 'bermuda', track_key: 'bermuda', lawn_sqft: 10000 });
    return f.visit(0, { scheduled_date: '2026-05-12', ...changes });
  }
  const plan = (visit) => buildPlanForService(visit.id, { db: knex, includeCompletionDefaults: true });
  const codes = (result) => result.propertyGate.blocks.map((b) => b.code);
  const tetrinoItem = (result) => result.mixCalculator.items.find((item) => item.product?.name === 'Tetrino Insecticide');

  describe.each(PREREQ)('completion defaults %s, property history %s', (completion, history) => {
    const gates = (v13 = 'on') => setGates({ v13, completion, history });

    test('unpinned: the staged v13 protocol, its stated rate and its sunny-turf half (1.835 fl oz on 10,000 sq ft)', async () => {
      gates();
      const result = await plan(await plannedVisit());
      expect(result.protocol.structured.version).toBe(LAWN_V13_VERSION);
      expect(codes(result)).not.toContain('lawn_v13_protocol_missing');
      expect(tetrinoItem(result).mix).toMatchObject({ rateSource: 'protocol_rate', amount: 1.835 });
    });

    test('pinned to the staged v13 version: resolved and planned the same way', async () => {
      gates();
      const result = await plan(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: LAWN_V13_VERSION, lawn_protocol_window_key: 'may_v13' }));
      expect(result.protocol.structured.version).toBe(LAWN_V13_VERSION);
      expect(tetrinoItem(result).mix.amount).toBe(1.835);
    });

    test('pinned to an older version: that version resolves, no v13 products or rates, a block', async () => {
      gates();
      const result = await plan(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: OLD_VERSION, lawn_protocol_window_key: 'fixture_5' }));
      expect(result.protocol.structured.version).toBe(OLD_VERSION);
      expect(codes(result)).toContain('lawn_v13_protocol_missing');
      expect(result.mixCalculator.items).toEqual([]);
      expect(result.protocol.base).toEqual([]);
      expect(result.protocol.conditional).toEqual([]);
      expect(result.status).toBe('blocked');
      if (completion === 'on' && history === 'on') expect(result.completionDefaults.items ?? []).toEqual([]);
    });
  });

  test('no staged v13 row: no products, no amounts anywhere in the plan, a block', async () => {
    setGates();
    const staged = await knex('lawn_protocols').where({ protocol_key: KEY, version: LAWN_V13_VERSION }).first();
    await knex('lawn_protocols').where({ id: staged.id }).update({ status: 'archived' });
    try {
      const result = await plan(await plannedVisit());
      expect(codes(result)).toContain('lawn_v13_protocol_missing');
      expect(result.mixCalculator.items).toEqual([]);
      expect(result.mixCalculator.conditionalOptions).toEqual([]);
      expect(result.mixCalculator.materialCostSummary.total ?? 0).toBe(0);
      expect(result.protocol.base).toEqual([]);
      expect(result.protocol.conditional).toEqual([]);
      expect(JSON.stringify(result.mixCalculator.items) + JSON.stringify(result.protocol)).not.toMatch(/"amount":\s*[1-9]/);
    } finally {
      await knex('lawn_protocols').where({ id: staged.id }).update({ status: 'staged' });
    }
  });

  test('gate off: a visit pinned to the older version plans exactly as before, with no v13 block', async () => {
    setGates({ v13: 'off' });
    const result = await plan(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: OLD_VERSION, lawn_protocol_window_key: 'fixture_5' }));
    expect(codes(result)).not.toContain('lawn_v13_protocol_missing');
    expect(result.protocol.structured.version).toBe(OLD_VERSION);
  });
});
