// Lawn protocol v13 field rules follow-up (20261007155000) on PostgreSQL (cloned
// schema): Dismiss procurement is switched off and its open automatic restock
// requests settled; a rollback past 20261007150000 keeps the safety gates of a
// protocol a visit or a completion references. Synthetic data only.
const { randomUUID } = require('crypto');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const fieldRules = require('../models/migrations/20261007150000_lawn_v13_field_rules');
const followup = require('../models/migrations/20261007155000_lawn_v13_field_rules_followup');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const V13 = '2026.10-v13';
const { NUTRA, ACELEPRYN, DISMISS } = fieldRules.NAMES;
const TABLES = ['products_catalog', 'product_restock_requests', 'vendor_orders', 'vendors', 'notifications',
  'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_audit_log',
  'lawn_protocol_service_completions', 'lawn_protocol_product_actuals'];

describeDb('v13 field rules follow-up through PostgreSQL', () => {
  let owned;
  let knex;
  const product = {};

  async function request(productName, changes = {}) {
    const [row] = await knex('product_restock_requests').insert({ product_id: product[productName].id, status: 'open', source: 'auto_reorder', metadata: JSON.stringify({}), ...changes }).returning('*');
    return row;
  }
  const requestStatus = async (id) => (await knex('product_restock_requests').where({ id }).first('status')).status;
  const enabled = async (name) => (await knex('products_catalog').where({ id: product[name].id }).first('auto_reorder_enabled')).auto_reorder_enabled;

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [name, on] of [[DISMISS, true], ['Dismiss NXT', true], ['Dismiss off row', false], [NUTRA, false], [ACELEPRYN, false]]) {
      [product[name]] = await knex('products_catalog').insert({
        name: name === 'Dismiss off row' ? DISMISS : name, category: 'herbicide', active: true, auto_reorder_enabled: on,
        inventory_on_hand: 1, low_stock_threshold: 5, inventory_unit: 'each',
      }).returning('*');
    }
  });
  afterAll(async () => { if (owned) await owned.dispose(); });

  describe('Dismiss procurement', () => {
    const rows = {};
    test('up switches off the exact-name row and settles only its open automatic requests', async () => {
      rows.auto = await request(DISMISS);
      rows.manual = await request(DISMISS, { source: 'manual' });
      rows.ordered = await request(DISMISS, { status: 'ordered', source: 'manual' });
      rows.other = await request('Dismiss NXT');
      await knex('notifications').insert({ recipient_type: 'admin', category: 'procurement', title: 'Reorder Dismiss', metadata: JSON.stringify({ dedupeKey: `auto-reorder:${rows.auto.id}` }) });

      await followup.up(knex);

      expect(await enabled(DISMISS)).toBe(false);
      const stillActive = await knex('products_catalog').where({ id: product[DISMISS].id }).first('active');
      expect(stillActive.active).toBe(true);
      expect(await requestStatus(rows.auto.id)).toBe('cancelled');
      const cancelled = await knex('product_restock_requests').where({ id: rows.auto.id }).first();
      expect(cancelled.closed_at).not.toBeNull();
      expect(cancelled.metadata.autoOrderCancelled).toBe('dismiss_retired');
      expect(await requestStatus(rows.manual.id)).toBe('open');
      expect(await requestStatus(rows.ordered.id)).toBe('ordered');
      // Another product, and a Dismiss row that was already off, are untouched.
      expect(await enabled('Dismiss NXT')).toBe(true);
      expect(await requestStatus(rows.other.id)).toBe('open');
      expect((await knex('notifications').first('done_at')).done_at).not.toBeNull();
      const audit = await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules_followup' });
      expect(audit).toHaveLength(1);
      expect(audit[0].after_snapshot).toEqual({ autoReorderEnabled: false, cancelledRequestIds: [rows.auto.id] });
    });

    test('a second up changes nothing', async () => {
      await followup.up(knex);
      expect(await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules_followup' })).toHaveLength(1);
    });

    test('an open automatic request with an order already out stays open', async () => {
      const [second] = await knex('products_catalog').insert({ name: DISMISS, category: 'herbicide', active: true, auto_reorder_enabled: true }).returning('*');
      const live = await knex('product_restock_requests').insert({ product_id: second.id, status: 'open', source: 'auto_reorder', metadata: '{}' }).returning('*');
      const [vendor] = await knex('vendors').insert({ name: 'Fixture vendor' }).returning('*');
      await knex('vendor_orders').insert({ restock_request_id: live[0].id, vendor_id: vendor.id, adapter: 'fixture', status: 'placing' });
      await followup.up(knex);
      expect((await knex('products_catalog').where({ id: second.id }).first('auto_reorder_enabled')).auto_reorder_enabled).toBe(false);
      expect(await requestStatus(live[0].id)).toBe('open');
      await followup.down(knex);
      expect((await knex('products_catalog').where({ id: second.id }).first('auto_reorder_enabled')).auto_reorder_enabled).toBe(true);
    });

    test('down restores the switch where it is still off, never reopens a request, and keeps a switch the owner turned back on', async () => {
      await followup.up(knex);
      await knex('products_catalog').where({ id: product[DISMISS].id }).update({ auto_reorder_enabled: true });
      await followup.down(knex);
      expect(await enabled(DISMISS)).toBe(true);
      expect(await requestStatus(rows.auto.id)).toBe('cancelled');
      expect(await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules_followup' })).toHaveLength(0);

      await followup.up(knex);
      expect(await enabled(DISMISS)).toBe(false);
      await followup.down(knex);
      expect(await enabled(DISMISS)).toBe(true);
    });
  });

  describe('rollback past 20261007150000 keeps the gates of a referenced protocol', () => {
    const protocols = {};
    const gates = async (id) => (await knex('lawn_protocol_products').where({ id }).first('gates')).gates;

    async function stage(track) {
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: `followup_${track}`, version: V13, name: track, status: 'staged', grass_track: track, region: 'swfl' }).returning('*');
      const [june] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 6, window_key: 'jun_v13_hose_blackout', title: 'june', visit_type: 'x' }).returning('*');
      const [july] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 7, window_key: 'jul_v13_inspect_spot', title: 'july', visit_type: 'x' }).returning('*');
      const row = (win, name) => knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: win.id, product_id: product[name].id, product_name: name, role: 'x', application_mode: 'broadcast', default_in_plan: true, gates: JSON.stringify({}),
      }).returning('*').then((r) => r[0]);
      protocols[track] = { protocol, nutra: await row(june, NUTRA), acelepryn: await row(july, ACELEPRYN) };
    }

    beforeAll(async () => {
      for (const track of ['visit', 'completion', 'unused']) await stage(track);
      const f = await fixture(knex);
      await f.visit(0, { lawn_protocol_key: 'followup_visit', lawn_protocol_version: V13 });
      await knex('lawn_protocol_service_completions').insert({ service_record_id: randomUUID(), lawn_protocol_id: protocols.completion.protocol.id, protocol_key: 'followup_completion', protocol_version: V13 });
    });

    test('150000 up, follow-up up, then rolled back newest first: referenced protocols keep both keys, an unused one loses them', async () => {
      await fieldRules.up(knex);
      await followup.up(knex);
      for (const track of ['visit', 'completion', 'unused']) {
        expect(await gates(protocols[track].nutra.id)).toEqual({ northPortProductWindow: true });
        expect(await gates(protocols[track].acelepryn.id)).toEqual({ delayWateringOrMowingHours: 24 });
      }
      await followup.down(knex);
      await fieldRules.down(knex);
      for (const track of ['visit', 'completion']) {
        expect(await gates(protocols[track].nutra.id)).toEqual({ northPortProductWindow: true });
        expect(await gates(protocols[track].acelepryn.id)).toEqual({ delayWateringOrMowingHours: 24 });
      }
      expect(await gates(protocols.unused.nutra.id)).toEqual({});
      expect(await gates(protocols.unused.acelepryn.id)).toEqual({});
      expect(await knex('lawn_protocol_audit_log').whereIn('action', ['v13_field_rules', 'v13_field_rules_followup'])).toHaveLength(0);
    });

    test('up again after that rollback keeps the kept keys and re-adds the removed ones', async () => {
      await fieldRules.up(knex);
      expect(await gates(protocols.visit.nutra.id)).toEqual({ northPortProductWindow: true });
      expect(await gates(protocols.unused.nutra.id)).toEqual({ northPortProductWindow: true });
      await followup.up(knex);
      await followup.down(knex);
      await fieldRules.down(knex);
      expect(await gates(protocols.completion.acelepryn.id)).toEqual({ delayWateringOrMowingHours: 24 });
      expect(await gates(protocols.unused.acelepryn.id)).toEqual({});
    });
  });
});
