// Lawn protocol v13, Topchoice fire ant add-on: the rolling-year interval (migration 20261009101000, Codex round 1 on #6160),
// through the real migrations on PostgreSQL (cloned schema) and the real limit checker. Synthetic data only. Self-skips
// without DATABASE_URL.
//
// Also pinned: the ownPass note gate is written on the Topchoice rows the first migration inserted (only rows still matching its
// snapshot), removed again only where the gates still equal what was written, and the chain rolls back in order.
//
// Pinned: a hard 365-day interval is inserted beside the count limit (a weaker row is tightened, a row that already holds it is
// left alone); an October application then an April one is blocked, one 365 days after the last is allowed; a second up changes
// nothing; down removes only what up wrote; the in-order rollback (this, then 20261009100000) restores every row; a pinned protocol or a staff-edited Topchoice row keeps the interval beside the count limit that stays.
const { isDeepStrictEqual } = require('node:util');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const first = require('../models/migrations/20261009100000_lawn_v13_fire_ant_granule');
const followup = require('../models/migrations/20261009101000_lawn_v13_fire_ant_granule_followup');
const matrix = require('../models/migrations/20261007180000_lawn_v13_matrix_adds');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');
const limitChecker = require('../services/application-limits');

const GRANULE = first.GRANULE;
const ADVION = matrix.ADVION;
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_fu_a', 'fixture_fu_b'];
const [APR, OCT] = first.WINDOW_KEYS;
const ADVION_GATES = { trigger: 'fire_ants_optional_add_on', optionalAddOn: true, officePrices: true };
const OWN_PASS_GATES = { ...ADVION_GATES, ownPass: true };
const SEED_NOTE = 'Seeded for lawn outline estimate packets from verified product/label source.';
const TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_audit_log',
  'lawn_protocol_service_completions', 'product_limits', 'lawn_protocol_product_actuals', 'service_products', 'property_application_history'];

describe('the interval spec (no database)', () => {
  test('a hard 365-day minimum on the product, citing the Topchoice label', () => {
    expect(followup.LIMIT).toMatchObject({ match_type: 'product', limit_type: 'min_interval_days', limit_value: 365, limit_unit: 'days', severity: 'hard_block' });
    expect(followup.LIMIT.description).toMatch(/Topchoice label, EPA Reg\. No\. 432-1217, accepted 2018-03-20/);
    expect(first.LIMIT).toMatchObject({ limit_type: 'annual_max_apps', limit_value: 1 });
  });
});

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 Topchoice rolling-year interval through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [table, constraint, suffix] of [
      ['product_limits', 'fixture_limits_product', ''], ['product_aliases', 'fixture_aliases_product', ''],
      ['service_products', 'fixture_sp_product', ' ON DELETE SET NULL'], ['lawn_protocol_products', 'fixture_lpp_product', ''],
    ]) {
      await knex.raw(`ALTER TABLE ??.?? ADD CONSTRAINT ${constraint} FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)${suffix}`, [owned.schema, table, owned.schema]);
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const topLimits = () => knex('product_limits').where({ product_id: ids.top }).orderBy(['limit_type', 'id']);
  const intervalRows = () => knex('product_limits').where({ product_id: ids.top, limit_type: 'min_interval_days' });
  const ours = () => knex('lawn_protocol_audit_log').whereIn('action', [first.ACTION, first.CATALOG_ACTION, followup.ACTION]);
  const granuleRows = () => knex('lawn_protocol_products').where({ product_name: GRANULE }).orderBy('id');
  // The Topchoice rows by protocol key, with their gates.
  const granuleByProtocol = async () => {
    const rows = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
      .where({ 'p.product_name': GRANULE }).orderBy('p.id').select('p.id', 'p.gates', 'p.rate_per_1000', 'l.protocol_key');
    return rows.reduce((acc, row) => ({ ...acc, [row.protocol_key]: [...(acc[row.protocol_key] || []), row] }), {});
  };
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  async function snapshot() {
    return clean([
      await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']), await knex('lawn_protocol_windows').orderBy('id'),
      await knex('products_catalog').orderBy('name'), await knex('product_aliases').orderBy('alias_name'), await knex('product_limits').orderBy('id'),
      await knex('lawn_protocol_audit_log').orderBy('id'),
    ]);
  }

  async function reset({ topchoice = true } = {}) {
    for (const table of ['property_application_history', 'service_products', 'lawn_protocol_product_actuals', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products',
      'lawn_protocol_windows', 'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const [advion] = await knex('products_catalog').insert({ name: ADVION, category: 'insecticide', formulation: 'granular', epa_reg_number: '100-1481', rate_unit: 'lb', active: true }).returning('*');
    if (topchoice) {
      const [top] = await knex('products_catalog').insert({
        name: GRANULE, category: 'insecticide', product_type: 'pesticide', formulation: 'granular', epa_reg_number: '432-1217', restricted_use: false, default_rate_per_1000: 2,
        rate_unit: 'lb', irrigation_required: true, approved_for_service_report: true, label_source_note: SEED_NOTE, active: true,
      }).returning('*');
      ids.top = top.id;
    }
    for (const key of KEYS) {
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      for (const [windowKey, month] of [[APR, 4], [OCT, 10]]) {
        const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
        await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: advion.id, product_name: ADVION, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 0.0344, rate_unit: 'lb', default_in_plan: false, sort_order: 9, gates: JSON.stringify(ADVION_GATES) });
      }
    }
  }

  describe('up', () => {
    beforeAll(async () => { await reset(); await first.up(knex); await followup.up(knex); });

    test('a hard 365-day interval is inserted beside the 1-a-year count limit, which stays', async () => {
      const rows = await topLimits();
      expect(rows.map((r) => [r.limit_type, Number(r.limit_value), r.limit_unit, r.severity, r.match_type])).toEqual([
        ['annual_max_apps', 1, 'applications', 'hard_block', 'product'], ['min_interval_days', 365, 'days', 'hard_block', 'product'],
      ]);
      expect(rows[1].description).toMatch(/Topchoice label, EPA Reg\. No\. 432-1217, accepted 2018-03-20/);
    });

    test('ownPass is written on all four Topchoice rows (the exact gates), and on nothing else', async () => {
      const rows = await granuleRows();
      expect(rows).toHaveLength(KEYS.length * 2);
      for (const row of rows) expect(row.gates).toEqual(OWN_PASS_GATES);
      for (const row of await knex('lawn_protocol_products').where({ product_name: ADVION })) expect(row.gates).toEqual({ ...ADVION_GATES, retired: true });
      const [log] = await knex('lawn_protocol_audit_log').where({ action: followup.ACTION });
      expect(log.after_snapshot.rows).toHaveLength(KEYS.length * 2);
      for (const entry of log.after_snapshot.rows) expect([entry.gatesBefore, entry.gatesAfter]).toEqual([ADVION_GATES, OWN_PASS_GATES]);
    });

    test('one audit row; a second up changes nothing', async () => {
      expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toHaveLength(1);
      const before = await snapshot();
      await followup.up(knex);
      expect(await snapshot()).toBe(before);
    });

    describe('the real limit checker', () => {
      let customerId;
      beforeAll(async () => {
        const f = await fixture(knex);
        customerId = f.customerId;
        await knex('property_application_history').insert({ customer_id: customerId, product_id: ids.top, application_date: '2026-10-15', application_rate: 2, rate_unit: 'lb' });
      });
      const check = (day) => limitChecker.checkLimits(customerId, ids.top, new Date(`${day}T16:00:00Z`), knex);
      const types = (result) => result.blocks.map((b) => b.type).sort();

      test('October then April is blocked by the interval (the count limit alone lets it through: a new calendar year)', async () => {
        const april = await check('2027-04-15');
        expect(april.allowed).toBe(false);
        expect(types(april)).toEqual(['min_interval_days']);
        await knex('product_limits').where({ product_id: ids.top, limit_type: 'min_interval_days' }).del();
        const without = await check('2027-04-15');
        expect(without.allowed).toBe(true);
        await followup.down(knex);
        await followup.up(knex);
        expect((await intervalRows())).toHaveLength(1);
      });

      test('364 days after is blocked, 365 days after is allowed, and the same calendar year is blocked by both limits', async () => {
        expect(types(await check('2027-10-14'))).toEqual(['min_interval_days']);
        const ok = await check('2027-10-15');
        expect(ok.blocks).toEqual([]);
        expect(ok.allowed).toBe(true);
        expect(types(await check('2026-12-01'))).toEqual(['annual_max_apps', 'min_interval_days']);
      });

      test('April then the next April (366 days) is allowed', async () => {
        await knex('property_application_history').del();
        await knex('property_application_history').insert({ customer_id: customerId, product_id: ids.top, application_date: '2027-04-15', application_rate: 2, rate_unit: 'lb' });
        expect((await check('2028-04-15')).allowed).toBe(true);
        expect((await check('2028-04-14')).allowed).toBe(true);
        expect(types(await check('2027-12-31'))).toEqual(['annual_max_apps', 'min_interval_days']);
      });

      test('the closeout audit judges the same way, in either order of recording', async () => {
        await knex('property_application_history').del();
        await knex('property_application_history').insert({ customer_id: customerId, product_id: ids.top, application_date: '2026-10-15', application_rate: 2, rate_unit: 'lb' });
        const april = await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-04-15', knex);
        expect(april.map((v) => v.type)).toEqual(['min_interval_days']);
        expect(await limitChecker.auditHardCountLimits(customerId, ids.top, '2027-10-15', knex)).toEqual([]);
        // The April pass is recorded first, the October one after: the nearest application on the other side counts.
        await knex('property_application_history').del();
        await knex('property_application_history').insert({ customer_id: customerId, product_id: ids.top, application_date: '2027-04-15', application_rate: 2, rate_unit: 'lb' });
        expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2026-10-15', knex)).map((v) => v.type)).toEqual(['min_interval_days']);
      });
    });
  });

  describe('existing interval rows', () => {
    beforeEach(async () => { await reset(); await first.up(knex); });
    const insert = (fields) => knex('product_limits').insert({ product_id: ids.top, match_type: 'product', limit_type: 'min_interval_days', limit_unit: 'days', severity: 'hard_block', limit_value: 365, ...fields });

    test('a weaker row (84 days, a warning) is tightened to 365 hard, and down puts it back', async () => {
      await insert({ limit_value: 84, severity: 'warning', description: 'Hand-written.' });
      await followup.up(knex);
      const [tight] = await intervalRows();
      expect([Number(tight.limit_value), tight.severity]).toEqual([365, 'hard_block']);
      await followup.down(knex);
      const [back] = await intervalRows();
      expect([Number(back.limit_value), back.severity, back.description]).toEqual([84, 'warning', 'Hand-written.']);
    });

    test('a row that already holds 365 or more days as a hard block is left alone and no limit is recorded', async () => {
      await insert({ limit_value: 400, description: 'Owner row.' });
      await followup.up(knex);
      const rows = await intervalRows();
      expect(rows).toHaveLength(1);
      expect(rows[0].description).toBe('Owner row.');
      // Only the ownPass rows are recorded: no limit was inserted or tightened.
      const [log] = await knex('lawn_protocol_audit_log').where({ action: followup.ACTION });
      expect(log.after_snapshot.limits).toEqual({ inserted: [], updated: [] });
    });
  });

  describe('ownPass on rows staff edited before this ran', () => {
    beforeEach(async () => { await reset(); await first.up(knex); });

    test.each([
      ['rate', { rate_per_1000: 1.5 }],
      ['gates', { gates: JSON.stringify({ ...ADVION_GATES, officePrices: false }) }],
      ['order', { sort_order: 3 }],
    ])('a row whose %s was edited is left alone and logged; the other rows still get the note', async (_label, edit) => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      const [edited] = await granuleRows();
      await knex('lawn_protocol_products').where({ id: edited.id }).update(edit);
      const afterEdit = clean(await knex('lawn_protocol_products').where({ id: edited.id }));
      try {
        await followup.up(knex);
        expect(log).toHaveBeenCalledWith(expect.stringContaining(`the Topchoice row ${edited.id} was edited after it was inserted: ownPass not written`));
      } finally { log.mockRestore(); }
      expect(clean(await knex('lawn_protocol_products').where({ id: edited.id }))).toBe(afterEdit);
      const others = (await granuleRows()).filter((row) => row.id !== edited.id);
      expect(others).toHaveLength(KEYS.length * 2 - 1);
      for (const row of others) expect(row.gates).toEqual(OWN_PASS_GATES);
    });

    test('a row staff deleted is skipped without a complaint', async () => {
      const [gone] = await granuleRows();
      await knex('lawn_protocol_products').where({ id: gone.id }).del();
      await followup.up(knex);
      for (const row of await granuleRows()) expect(row.gates).toEqual(OWN_PASS_GATES);
    });
  });

  describe('down and the chain', () => {
    beforeEach(async () => { await reset(); });

    test('down alone removes only the interval: the count limit, the protocol rows and the catalog changes stay', async () => {
      await first.up(knex);
      const afterFirst = await snapshot();
      await followup.up(knex);
      await followup.down(knex);
      expect(await snapshot()).toBe(afterFirst);
    });

    test('in order (this down, then 20261009100000\'s) every row, limit and audit row is back to before either ran', async () => {
      const before = await snapshot();
      await first.up(knex);
      await followup.up(knex);
      expect(await intervalRows()).toHaveLength(1);
      await followup.down(knex);
      await first.down(knex);
      expect(await snapshot()).toBe(before);
      expect(await ours()).toEqual([]);
      expect(await granuleRows()).toEqual([]);
    });

    test('up again after the full rollback puts everything back; the chain rolls back again', async () => {
      const before = await snapshot();
      await first.up(knex); await followup.up(knex); await followup.down(knex); await first.down(knex);
      await first.up(knex); await followup.up(knex);
      expect(await intervalRows()).toHaveLength(1);
      expect(await granuleRows()).toHaveLength(KEYS.length * 2);
      await followup.down(knex); await first.down(knex);
      expect(await snapshot()).toBe(before);
    });

    test('a visit pinned to one protocol: the interval stays beside the count limit, and 20261009100000 leaves that protocol', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await first.up(knex); await followup.up(knex);
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
      try {
        await followup.down(knex);
        await first.down(knex);
        expect(await intervalRows()).toHaveLength(1);
        expect((await knex('product_limits').where({ product_id: ids.top, limit_type: 'annual_max_apps' }))).toHaveLength(1);
        expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toHaveLength(1);
        expect((await granuleRows()).length).toBe(2);
        expect(log).toHaveBeenCalledWith(expect.stringContaining('its ownPass note and the 365-day interval stay'));
      } finally {
        log.mockRestore();
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
    });

    test('a staff edit on an inserted Topchoice row (the rate, name unchanged): that protocol stays whole WITH ownPass on every Topchoice row, the interval and audit stay, the other protocol goes back', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await first.up(knex); await followup.up(knex);
      const [row] = await granuleRows();
      const key = (await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
        .where({ 'p.id': row.id }).first('l.protocol_key')).protocol_key;
      await knex('lawn_protocol_products').where({ id: row.id }).update({ rate_per_1000: 1.5 });
      try {
        await followup.down(knex);
        await first.down(knex);
      } finally { log.mockRestore(); }
      const byProtocol = await granuleByProtocol();
      expect(Object.keys(byProtocol)).toEqual([key]);
      // Both Topchoice rows of the kept protocol (the edited one and its sibling in the other window) still carry the note.
      expect(byProtocol[key]).toHaveLength(2);
      for (const kept of byProtocol[key]) expect(kept.gates).toEqual(OWN_PASS_GATES);
      expect(Number(byProtocol[key].find((r) => r.id === row.id).rate_per_1000)).toBe(1.5);
      expect(await intervalRows()).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: first.ACTION })).toHaveLength(1);
      expect((await knex('products_catalog').where({ id: ids.top }).first()).restricted_use).toBe(true);
    });

    test('a staff edit on a retired Advion row: that protocol keeps ownPass on both Topchoice rows, the interval and the audit rows; the other protocol goes back', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await first.up(knex); await followup.up(knex);
      const advion = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
        .where({ 'p.product_name': ADVION }).orderBy('p.id').first('p.id', 'l.protocol_key');
      await knex('lawn_protocol_products').where({ id: advion.id }).update({ gates: JSON.stringify({ ...ADVION_GATES, retired: true, edited: true }) });
      try {
        await followup.down(knex);
        await first.down(knex);
      } finally { log.mockRestore(); }
      const byProtocol = await granuleByProtocol();
      expect(Object.keys(byProtocol)).toEqual([advion.protocol_key]);
      expect(byProtocol[advion.protocol_key]).toHaveLength(2);
      for (const kept of byProtocol[advion.protocol_key]) expect(kept.gates).toEqual(OWN_PASS_GATES);
      expect(await intervalRows()).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: first.ACTION })).toHaveLength(1);
    });

    test('a retained protocol and a restored one in the same rollback: ownPass leaves only the restored protocol, before the first down runs', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await first.up(knex); await followup.up(knex);
      const [row] = await granuleRows();
      await knex('lawn_protocol_products').where({ id: row.id }).update({ rate_per_1000: 1.5 });
      try { await followup.down(knex); } finally { log.mockRestore(); }
      // After this down alone: the edited row's protocol still has ownPass on all its rows; the other protocol is at the snapshot.
      const byProtocol = await granuleByProtocol();
      const allGates = (rows, gates) => rows.every((r) => isDeepStrictEqual(r.gates, gates));
      const sets = Object.values(byProtocol);
      expect(sets).toHaveLength(2);
      expect(sets.filter((rows) => allGates(rows, OWN_PASS_GATES))).toHaveLength(1);
      expect(sets.filter((rows) => allGates(rows, ADVION_GATES))).toHaveLength(1);
    });

    test('after this down the Topchoice rows are exactly the first migration\'s snapshot (that is what lets its down delete them)', async () => {
      await first.up(knex);
      const snapshots = (await granuleRows()).map((row) => clean(row));
      await followup.up(knex);
      expect((await granuleRows()).map((row) => clean(row))).not.toEqual(snapshots);
      await followup.down(knex);
      expect((await granuleRows()).map((row) => clean(row))).toEqual(snapshots);
    });

    test('gates edited after ownPass was written: this down leaves that row, the interval stays, and the first down keeps the protocol', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await first.up(knex); await followup.up(knex);
      const [row] = await granuleRows();
      const edited = { ...OWN_PASS_GATES, extra: 'staff' };
      await knex('lawn_protocol_products').where({ id: row.id }).update({ gates: JSON.stringify(edited) });
      try {
        await followup.down(knex);
        await first.down(knex);
      } finally { log.mockRestore(); }
      expect((await knex('lawn_protocol_products').where({ id: row.id }).first()).gates).toEqual(edited);
      expect(await intervalRows()).toHaveLength(1);
      expect((await knex('products_catalog').where({ id: ids.top }).first()).restricted_use).toBe(true);
      // The protocol of the edited row is whole; the other protocol went back.
      const keys = (await granuleRows()).map((r) => r.id);
      expect(keys).toContain(row.id);
      expect(keys.length).toBe(2);
      // The sibling row of the kept protocol still carries the note.
      const sibling = (await granuleRows()).find((r) => r.id !== row.id);
      expect(sibling.gates).toEqual(OWN_PASS_GATES);
      expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toHaveLength(1);
    });

    test('ownPass removed by staff after it was written: the first down sees the snapshot again and rolls back normally', async () => {
      await first.up(knex);
      const before = await snapshot();
      await followup.up(knex);
      await knex('lawn_protocol_products').where({ product_name: GRANULE }).update({ gates: JSON.stringify(ADVION_GATES) });
      await followup.down(knex);
      await first.down(knex);
      expect(await granuleRows()).toEqual([]);
      expect(await intervalRows()).toEqual([]);
      expect(await ours()).toEqual([]);
      expect(before).toBeTruthy();
    });

    test('a pinned protocol keeps ownPass (this down leaves it whole, like the first), the other protocol goes back to the snapshot', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await first.up(knex); await followup.up(knex);
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
      try {
        await followup.down(knex);
        const rows = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
          .where({ 'p.product_name': GRANULE }).select('p.gates', 'l.protocol_key');
        for (const row of rows) expect(row.gates).toEqual(row.protocol_key === KEYS[0] ? OWN_PASS_GATES : ADVION_GATES);
        await first.down(knex);
        expect((await granuleRows()).length).toBe(2);
        expect(await intervalRows()).toHaveLength(1);
        // After both downs the pinned protocol still carries the note on both rows; the other protocol is gone.
        const byProtocol = await granuleByProtocol();
        expect(Object.keys(byProtocol)).toEqual([KEYS[0]]);
        for (const kept of byProtocol[KEYS[0]]) expect(kept.gates).toEqual(OWN_PASS_GATES);
        expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toHaveLength(1);
      } finally {
        log.mockRestore();
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
    });

    test('the first down alone, with this applied, keeps every protocol whole (its rows no longer match the snapshot); knex never rolls back in that order', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await first.up(knex); await followup.up(knex);
      try { await first.down(knex); } finally { log.mockRestore(); }
      expect(await granuleRows()).toHaveLength(KEYS.length * 2);
      for (const row of await granuleRows()) expect(row.gates).toEqual(OWN_PASS_GATES);
      expect(await knex('lawn_protocol_audit_log').where({ action: first.ACTION })).toHaveLength(KEYS.length);
      // Finishing in the right order afterwards restores everything.
      await followup.down(knex);
      await first.down(knex);
      expect(await granuleRows()).toEqual([]);
      expect(await ours()).toEqual([]);
    });

    test('an interval edited since (another value) stays when nothing blocks the rollback', async () => {
      await first.up(knex); await followup.up(knex);
      await knex('product_limits').where({ product_id: ids.top, limit_type: 'min_interval_days' }).update({ limit_value: 400 });
      await followup.down(knex);
      const [row] = await intervalRows();
      expect(Number(row.limit_value)).toBe(400);
      expect(await knex('lawn_protocol_audit_log').where({ action: followup.ACTION })).toEqual([]);
    });
  });

  describe('protocols the migration does not own', () => {
    test('no Topchoice row: nothing is written and it says so', async () => {
      await reset({ topchoice: false });
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      const before = await snapshot();
      try {
        await followup.up(knex);
        expect(log).toHaveBeenCalledWith(expect.stringContaining('not found in the catalog: nothing written'));
      } finally { log.mockRestore(); }
      expect(await snapshot()).toBe(before);
    });

    test('no v13 protocol: nothing is written', async () => {
      await reset();
      await knex('lawn_protocol_products').del(); await knex('lawn_protocol_windows').del(); await knex('lawn_protocols').del();
      await followup.up(knex);
      expect(await intervalRows()).toEqual([]);
    });
  });
});
