// GATE_LAWN_V13 through the real plan engine and PostgreSQL (cloned schema):
// a visit plans from the staged v13 protocol or not at all, whatever the
// completion-default gates say. Pinned older visits and a missing staged row get
// no calculated products and a block; the staged visit gets the row's rate and
// its sunny-turf limit. Synthetic data only.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const { LAWN_V13_VERSION, visitProtocolQuery } = require('../services/lawn-program');
const { getProtocolWindowContext } = require('../services/lawn-protocol-operating-layer');
const fs = require('fs');
const path = require('path');
const { buildLawnProtocolReportContext } = require('../services/service-report/dynamic-context');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const KEY = 'fixture_v13_lawn';
const OLD_VERSION = '2026.06';
const PREREQ = [['on', 'on'], ['on', 'off'], ['off', 'on'], ['off', 'off']];
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY'];

function setGates({ v13 = 'on', completion = 'off', history = 'off' } = {}) {
  for (const [name, value] of [['GATE_LAWN_V13', v13], ['GATE_LAWN_COMPLETION_DEFAULTS', completion], ['GATE_LAWN_PROPERTY_HISTORY', history]]) {
    if (value === 'on') process.env[name] = 'true'; else delete process.env[name];
  }
}

describeDb('the v13 plan through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  let tetrino;

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'product_limits', 'property_application_history']) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    [tetrino] = await knex('products_catalog').insert({
      name: 'Tetrino Insecticide', category: 'insecticide', default_rate_per_1000: 0.367, rate_unit: 'fl oz',
      label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'fl oz', active: true,
    }).returning('*');
    await knex('products_catalog').insert({
      name: 'Arena 50 WDG', category: 'insecticide', default_rate_per_1000: 0.29, rate_unit: 'oz',
      label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'oz', active: true,
    });
    const [old] = await knex('lawn_protocols').insert({ protocol_key: KEY, version: OLD_VERSION, name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' }).returning('*');
    const [staged] = await knex('lawn_protocols').insert({ protocol_key: KEY, version: LAWN_V13_VERSION, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
    for (const [protocol, windowKey] of [[old, 'fixture_5'], [staged, 'may_v13']]) {
      const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 5, window_key: windowKey, title: windowKey, visit_type: 'fixture' }).returning('*');
      await knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: window.id, product_id: tetrino.id, product_name: tetrino.name, role: 'insecticide', application_mode: 'broadcast',
        default_in_plan: true, rate_per_1000: 0.367, rate_unit: 'fl oz', gates: JSON.stringify(protocol === staged ? { sunnyTurfOnly: true, minDistanceFromWaterFt: 25, applyAlone: true } : {}),
      });
    }
    // Spot rows on the staged May window: backpack work the plan must never size.
    const [arena] = await knex('products_catalog').where({ name: 'Arena 50 WDG' });
    const [celsius] = await knex('products_catalog').insert({ name: 'Celsius WG', category: 'herbicide', default_rate_per_1000: 0.085, rate_unit: 'oz', label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'oz', active: true }).returning('*');
    const [surfactant] = await knex('products_catalog').insert({ name: 'LESCO 90/10 Nonionic Surfactant', category: 'adjuvant', default_rate_per_1000: 0.25, rate_unit: 'fl oz', label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'fl oz', active: true }).returning('*');
    const stagedWindow = await knex('lawn_protocol_windows').where({ lawn_protocol_id: staged.id }).first();
    for (const [product, rate, unit, gates] of [[arena, null, 'label_rate', { trigger: 'chinch' }], [celsius, 0.085, 'oz', {}], [surfactant, null, 'label_rate', { concentration: '0.25% v/v' }]]) {
      await knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: stagedWindow.id, product_id: product.id, product_name: product.name, role: 'post_emergent_spot', application_mode: 'spot',
        default_in_plan: false, rate_per_1000: rate, rate_unit: unit, carrier_gal_per_1000: 4, gates: JSON.stringify(gates),
      });
    }
    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
  });
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  async function plannedVisit(changes = {}, turf = { grass_type: 'bermuda', track_key: 'bermuda' }) {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
    await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, ...turf, lawn_sqft: 10000 });
    return f.visit(0, { scheduled_date: '2026-05-12', ...changes });
  }
  const plan = (visit) => buildPlanForService(visit.id, { db: knex, includeCompletionDefaults: true });
  const codes = (result) => result.propertyGate.blocks.map((b) => b.code);
  const tetrinoItem = (result) => result.mixCalculator.items.find((item) => item.product?.name === 'Tetrino Insecticide');

  describe.each(PREREQ)('completion defaults %s, property history %s', (completion, history) => {
    const gates = (v13 = 'on') => setGates({ v13, completion, history });

    test('unpinned: the staged v13 protocol, its stated rate and its sunny-turf half (1.835 fl oz on 10,000 sq ft)', async () => {
      gates();
      const result = await plan(await plannedVisit());
      expect(result.protocol.structured.version).toBe(LAWN_V13_VERSION);
      expect(codes(result)).not.toContain('lawn_v13_protocol_missing');
      expect(tetrinoItem(result).mix).toMatchObject({ rateSource: 'protocol_rate', amount: 1.835 });
    });

    test('pinned to the staged v13 version: resolved and planned the same way', async () => {
      gates();
      const result = await plan(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: LAWN_V13_VERSION, lawn_protocol_window_key: 'may_v13' }));
      expect(result.protocol.structured.version).toBe(LAWN_V13_VERSION);
      expect(tetrinoItem(result).mix.amount).toBe(1.835);
    });

    test('pinned to an older version: that version resolves, no v13 products or rates, a block', async () => {
      gates();
      const result = await plan(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: OLD_VERSION, lawn_protocol_window_key: 'fixture_5' }));
      expect(result.protocol.structured.version).toBe(OLD_VERSION);
      expect(codes(result)).toContain('lawn_v13_protocol_missing');
      expect(result.mixCalculator.items).toEqual([]);
      expect(result.protocol.base).toEqual([]);
      expect(result.protocol.conditional).toEqual([]);
      expect(result.status).toBe('blocked');
      if (completion === 'on' && history === 'on') expect(result.completionDefaults.items ?? []).toEqual([]);
    });
  });

  test('no staged v13 row: no products, no amounts anywhere in the plan, a block', async () => {
    setGates();
    const staged = await knex('lawn_protocols').where({ protocol_key: KEY, version: LAWN_V13_VERSION }).first();
    await knex('lawn_protocols').where({ id: staged.id }).update({ status: 'archived' });
    try {
      const result = await plan(await plannedVisit());
      expect(codes(result)).toContain('lawn_v13_protocol_missing');
      expect(result.mixCalculator.items).toEqual([]);
      expect(result.mixCalculator.conditionalOptions).toEqual([]);
      expect(result.mixCalculator.materialCostSummary.total ?? 0).toBe(0);
      expect(result.protocol.base).toEqual([]);
      expect(result.protocol.conditional).toEqual([]);
      expect(JSON.stringify(result.mixCalculator.items) + JSON.stringify(result.protocol)).not.toMatch(/"amount":\s*[1-9]/);
    } finally {
      await knex('lawn_protocols').where({ id: staged.id }).update({ status: 'staged' });
    }
  });

  // Celsius and Blindside are not labeled for bahiagrass, so v13 has no bahia track (owner 2026-10-06):
  // an explicit bahia lawn plans nothing and never borrows the St. Augustine program.
  describe.each(PREREQ)('an explicit bahia lawn: completion defaults %s, property history %s', (completion, history) => {
    test.each([
      ['grass_type', { grass_type: 'bahia', track_key: null }], ['track_key', { grass_type: null, track_key: 'bahia' }],
      ['grass_type bahia over track_key st_augustine', { grass_type: 'bahia', track_key: 'st_augustine' }],
      ['track_key bahia over grass_type st_augustine', { grass_type: 'st_augustine', track_key: 'bahia' }],
    ])('recorded by %s: the bahia block, no products, no amounts', async (_name, turf) => {
      setGates({ v13: 'on', completion, history });
      const result = await plan(await plannedVisit({}, turf));
      expect(codes(result)).toContain('lawn_v13_bahia_no_program');
      expect(result.status).toBe('blocked');
      expect(result.mixCalculator.items).toEqual([]);
      expect(result.protocol.base).toEqual([]);
      expect(result.protocol.conditional).toEqual([]);
      expect(JSON.stringify(result.mixCalculator.items) + JSON.stringify(result.protocol)).not.toMatch(/"amount":\s*[1-9]/);
    });

    test('a bahia lawn pinned to a protocol assignment reads no protocol window and no products', async () => {
      setGates({ v13: 'on', completion, history });
      const pinned = { lawn_protocol_key: KEY, lawn_protocol_version: LAWN_V13_VERSION, lawn_protocol_window_key: 'may_v13' };
      const result = await plan(await plannedVisit(pinned, { grass_type: 'bahia', track_key: 'st_augustine' }));
      expect(codes(result)).toContain('lawn_v13_bahia_no_program');
      expect(result.protocol.structured ?? null).toBeNull();
      expect(result.mixCalculator.items).toEqual([]);
      expect(result.protocol.base).toEqual([]);
      // The same assignment on a lawn that has a program is read as before.
      const fine = await plan(await plannedVisit(pinned));
      expect(fine.protocol.structured.version).toBe(LAWN_V13_VERSION);
    });

    test('a mixed lawn still plans from the one program (the any-grass fallback), with no bahia block', async () => {
      setGates({ v13: 'on', completion, history });
      const result = await plan(await plannedVisit({}, { grass_type: 'mixed', track_key: null }));
      expect(codes(result)).not.toContain('lawn_v13_bahia_no_program');
    });
  });

  test('gate off: an explicit bahia lawn carries no bahia block', async () => {
    setGates({ v13: 'off' });
    const result = await plan(await plannedVisit({}, { grass_type: 'bahia', track_key: null }));
    expect(codes(result)).not.toContain('lawn_v13_bahia_no_program');
  });

  test('gate off: a visit pinned to the older version plans exactly as before, with no v13 block', async () => {
    setGates({ v13: 'off' });
    const result = await plan(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: OLD_VERSION, lawn_protocol_window_key: 'fixture_5' }));
    expect(codes(result)).not.toContain('lawn_v13_protocol_missing');
    expect(result.protocol.structured.version).toBe(OLD_VERSION);
  });

  describe.each(PREREQ)('gate OFF with a visit pinned to the staged v13 protocol: completion defaults %s, property history %s', (completion, history) => {
    test('no calculated products, no amounts, the lawn_v13_gate_off block', async () => {
      setGates({ v13: 'off', completion, history });
      const result = await plan(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: LAWN_V13_VERSION, lawn_protocol_window_key: 'may_v13' }));
      expect(codes(result)).toContain('lawn_v13_gate_off');
      expect(result.status).toBe('blocked');
      expect(result.mixCalculator.items).toEqual([]);
      expect(result.mixCalculator.conditionalOptions).toEqual([]);
      expect(result.protocol.base).toEqual([]);
      expect(result.protocol.conditional).toEqual([]);
    });
  });

  test('a service report for a legacy completed record (no ledger row, no pin) never shows v13 as followed, gate on', async () => {
    setGates({ v13: 'on' });
    const visit = await plannedVisit();
    const record = { id: visit.id, customer_id: visit.customer_id, service_date: '2026-05-12', scheduled_service_id: visit.id };
    const context = await buildLawnProtocolReportContext(record, knex, new Date('2026-05-12T16:00:00Z'));
    expect(context.version).toBe(OLD_VERSION);
    expect(context.status).toBe('active');
    expect(context.window.key).toBe('fixture_5');
    // The planner, asked the same question for the same visit, reads the staged v13 protocol.
    expect((await plan(visit)).protocol.structured.version).toBe(LAWN_V13_VERSION);
  });

  test('a service report for a record whose ledger row names v13 still shows v13 (its own record)', async () => {
    setGates({ v13: 'on' });
    const visit = await plannedVisit();
    const staged = await knex('lawn_protocols').where({ protocol_key: KEY, version: LAWN_V13_VERSION }).first();
    const stagedWindow = await knex('lawn_protocol_windows').where({ lawn_protocol_id: staged.id }).first();
    const [serviceRecord] = await knex('service_records').insert({ customer_id: visit.customer_id, scheduled_service_id: visit.id, service_date: '2026-05-12', service_type: 'Lawn fixture' }).returning('*');
    await knex('lawn_protocol_service_completions').insert({
      service_record_id: serviceRecord.id, scheduled_service_id: visit.id, customer_id: visit.customer_id,
      lawn_protocol_id: staged.id, lawn_protocol_window_id: stagedWindow.id, protocol_key: KEY, protocol_version: LAWN_V13_VERSION, window_key: 'may_v13',
    });
    const context = await buildLawnProtocolReportContext({ id: serviceRecord.id, customer_id: visit.customer_id, service_date: '2026-05-12', scheduled_service_id: visit.id }, knex, new Date('2026-05-12T16:00:00Z'));
    expect(context.version).toBe(LAWN_V13_VERSION);
  });

  describe('restored Tetrino gates on the plan item', () => {
    test('the item carries its gates, a required water-distance warning shows on the plan, and alone there is no apply-alone block', async () => {
      setGates();
      const result = await plan(await plannedVisit());
      const item = tetrinoItem(result);
      expect(item.gates).toEqual({ sunnyTurfOnly: true, minDistanceFromWaterFt: 25, applyAlone: true });
      expect(item.gateNotes.map((n) => `${n.severity}:${n.key}`)).toEqual(['required:minDistanceFromWaterFt', 'note:applyAlone', 'note:sunnyTurfOnly']);
      const warning = result.propertyGate.warnings.find((w) => w.code === 'lawn_v13_product_gate');
      expect(warning).toMatchObject({ gate: 'minDistanceFromWaterFt', productName: 'Tetrino Insecticide', message: 'Tetrino Insecticide: Keep 25 ft from ponds, lakes and canals; skip that strip.' });
      expect(codes(result)).not.toContain('lawn_v13_apply_alone');
      expect(result.mixingOrder).toHaveLength(1);
    });

    test('another selected product beside the apply-alone Tetrino holds the mix: block, no combined mixing order', async () => {
      setGates();
      const visit = await plannedVisit();
      const result = await buildPlanForService(visit.id, { db: knex, selectedConditionalProductNames: ['Arena 50 WDG'] });
      expect(result.mixCalculator.items.map((i) => i.product.name).sort()).toEqual(['Arena 50 WDG', 'Tetrino Insecticide']);
      expect(codes(result)).toContain('lawn_v13_apply_alone');
      expect(result.status).toBe('blocked');
      expect(result.mixingOrder).toEqual([]);
      // The hold withholds the selection's quantities in the plan, as on the tank sheet.
      expect(result.mixCalculator.items.map((i) => i.mix)).toEqual([null, null]);
      expect(result.mixCalculator.items.every((i) => i.product.inventory.plannedAmount == null)).toBe(true);
      expect(result.mixCalculator.materialCostSummary.pricedLineCount ?? 0).toBe(0);
      expect(JSON.stringify(result.mixCalculator.nutrientProjection)).not.toMatch(/"amount":\s*[1-9]/);
    });

    test('gate off: the plan items carry no v13 field, and nothing is warned', async () => {
      setGates({ v13: 'off' });
      const result = await plan(await plannedVisit());
      expect(result.propertyGate.warnings.some((w) => w.code === 'lawn_v13_product_gate')).toBe(false);
      for (const item of [...result.protocol.base, ...result.protocol.conditional]) {
        expect('gates' in item || 'gateNotes' in item || 'spot' in item || 'unavailable' in item).toBe(false);
      }
    });
  });

  describe('the live assessment reads the visit\'s own assignment (visitProtocolQuery)', () => {
    const contextFor = (visit) => getProtocolWindowContext(knex, visitProtocolQuery({ serviceDate: new Date('2026-05-12T16:00:00Z'), grassTrack: 'bermuda', scheduledService: visit }));

    test('pinned to an older version: that version, never v13, even when its window key collides with a v13 window key', async () => {
      setGates();
      for (const windowKey of ['fixture_5', 'may_v13']) {
        const visit = await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: OLD_VERSION, lawn_protocol_window_key: windowKey });
        const context = await contextFor(visit);
        expect(context.protocol.version).toBe(OLD_VERSION);
        expect(context.window?.window_key ?? null).toBe(windowKey === 'fixture_5' ? 'fixture_5' : null);
      }
    });

    test('pinned to v13: v13; unpinned: the planning lookup takes the staged v13 version', async () => {
      setGates();
      expect((await contextFor(await plannedVisit({ lawn_protocol_key: KEY, lawn_protocol_version: LAWN_V13_VERSION, lawn_protocol_window_key: 'may_v13' }))).protocol.version).toBe(LAWN_V13_VERSION);
      const unpinned = await contextFor(await plannedVisit());
      expect(unpinned.protocol.version).toBe(LAWN_V13_VERSION);
      expect(unpinned.window.window_key).toBe('may_v13');
    });

    test('the route builds its lookup from the helper, not from the window key alone', () => {
      const source = fs.readFileSync(path.join(__dirname, '../routes/admin-lawn-assessment.js'), 'utf8');
      expect(source).toMatch(/getProtocolWindowContext\(db, visitProtocolQuery\(\{ serviceDate: visitDate, grassTrack: track, scheduledService \}\)\)/);
    });
  });

  describe('spot rows get no calculated quantity (the one chokepoint)', () => {
    const SPOTS = ['Arena 50 WDG', 'Celsius WG', 'LESCO 90/10 Nonionic Surfactant'];
    const select = { selectedConditionalProductNames: SPOTS };

    test('selected spot products stay selectable with a label-rate reference and the note, and carry no mix', async () => {
      setGates();
      const visit = await plannedVisit();
      const result = await buildPlanForService(visit.id, { db: knex, ...select });
      for (const name of SPOTS) {
        const item = result.mixCalculator.items.find((i) => i.product?.name === name);
        expect({ name, selected: item?.selected, mix: item?.mix }).toEqual({ name, selected: true, mix: null });
        expect(item.spot.note).toBe('Spot: enter the area treated and the amount used.');
      }
      expect(result.mixCalculator.items.find((i) => i.product?.name === 'Celsius WG').spot.reference).toBe('Label rate 0.085 oz per 1,000 sq ft');
      expect(result.mixCalculator.items.find((i) => i.product?.name === 'LESCO 90/10 Nonionic Surfactant').spot.reference).toBe('Label concentration 0.25% v/v');
      // Tetrino is apply-alone and these are selected beside it: the hold withholds its amount too.
      expect(codes(result)).toContain('lawn_v13_apply_alone');
      expect(tetrinoItem(result).mix).toBeNull();
    });

    test('the whole-lawn Tetrino still computes beside UNSELECTED spot options: 1.835 fl oz on the sunny half of 10,000 sq ft', async () => {
      setGates();
      const result = await plan(await plannedVisit());
      expect(codes(result)).not.toContain('lawn_v13_apply_alone');
      expect(tetrinoItem(result).mix.amount).toBe(1.835);
    });

    test('unselected spot options carry no planned amount either', async () => {
      setGates();
      const result = await plan(await plannedVisit());
      for (const item of result.mixCalculator.conditionalOptions.filter((i) => i.product && SPOTS.includes(i.product.name))) {
        expect({ name: item.product.name, mix: item.mix }).toEqual({ name: item.product.name, mix: null });
      }
    });

    test('completion defaults offer the spot products as options and prefill none of them', async () => {
      setGates({ completion: 'on', history: 'on' });
      const result = await buildPlanForService((await plannedVisit()).id, { db: knex, includeCompletionDefaults: true, ...select });
      expect(result.completionDefaults.items.map((i) => i.product.name)).toEqual(['Tetrino Insecticide']);
      expect(result.completionDefaults.options.map((o) => o.product.name)).toEqual(expect.arrayContaining(SPOTS));
      expect(result.completionDefaults.items.every((i) => !SPOTS.includes(i.product.name))).toBe(true);
    });
  });

  test('exact names are a hard rule: with Tetrino absent from the catalog the line stays unmatched and no other Insecticide stands in', async () => {
    setGates();
    await knex('products_catalog').where({ id: tetrino.id }).update({ active: false });
    // The stand-in a loose match would pick: it shares the word "Insecticide".
    const [acelepryn] = await knex('products_catalog').insert({ name: 'Acelepryn Insecticide', category: 'insecticide', default_rate_per_1000: 0.05, rate_unit: 'fl oz', label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'fl oz', active: true, cost_per_unit: 9 }).returning('*');
    try {
      const result = await plan(await plannedVisit());
      expect(result.mixCalculator.items.some((i) => i.product?.name === 'Tetrino Insecticide')).toBe(false);
      const line = result.protocol.base.find((i) => /^Tetrino/.test(i.raw));
      expect(line).toMatchObject({ matched: false, product: null, mix: null });
      expect(result.mixCalculator.items.every((i) => !i.product || i.product.name !== 'Acelepryn Insecticide')).toBe(true);
    } finally {
      await knex('products_catalog').where({ id: acelepryn.id }).del();
      await knex('products_catalog').where({ id: tetrino.id }).update({ active: true });
    }
  });

  describe('one decision per v13 line', () => {
    const lineFor = (result, name) => result.mixCalculator.items.find((i) => i.product?.name === name);

    test('a saved substitution is ignored: the line keeps its protocol product, rate and gates, and the plan says so', async () => {
      setGates();
      const visit = await plannedVisit();
      const [substitute] = await knex('products_catalog').insert({ name: 'Substitute Insecticide', category: 'insecticide', default_rate_per_1000: 2, rate_unit: 'fl oz', label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'fl oz', active: true }).returning('*');
      await knex('lawn_protocol_product_substitutions').insert({ scheduled_service_id: visit.id, original_product_id: tetrino.id, substitute_product_id: substitute.id, rate_per_1000: 2, rate_unit: 'fl oz', reason: 'out of stock' });
      try {
        const result = await buildPlanForService(visit.id, { db: knex });
        const tet = tetrinoItem(result);
        expect(tet.substitution).toBeNull();
        expect(tet.product.name).toBe('Tetrino Insecticide');
        expect(tet.mix).toMatchObject({ rateSource: 'protocol_rate', amount: 1.835 });
        expect(tet.gates).toMatchObject({ applyAlone: true });
        expect(result.propertyGate.warnings.find((w) => w.code === 'lawn_v13_substitution_ignored')).toMatchObject({ productName: 'Tetrino Insecticide', message: 'Substitution not applied: v13 line keeps its protocol product.' });
        expect(result.mixCalculator.items.some((i) => i.product?.name === 'Substitute Insecticide')).toBe(false);
      } finally {
        await knex('lawn_protocol_product_substitutions').where({ scheduled_service_id: visit.id }).del();
        await knex('products_catalog').where({ id: substitute.id }).del();
      }
    });

    test.each([['no product link', null], ['a link to a different catalog product', 'arena']])('an unlinked line (%s) is unavailable: no amount, never the catalog default, a plan warning', async (_label, link) => {
      setGates();
      const stagedRow = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
        .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id').where({ 'l.version': LAWN_V13_VERSION, 'p.product_name': 'Tetrino Insecticide' }).first('p.id', 'p.product_id');
      const arena = await knex('products_catalog').where({ name: 'Arena 50 WDG' }).first();
      await knex('lawn_protocol_products').where({ id: stagedRow.id }).update({ product_id: link === 'arena' ? arena.id : null });
      try {
        const result = await plan(await plannedVisit());
        const tet = tetrinoItem(result);
        expect(tet.mix).toBeNull();
        expect(tet.unavailable.reason).toMatch(/No protocol row is linked/);
        expect(result.propertyGate.warnings.find((w) => w.code === 'lawn_v13_line_unlinked')).toMatchObject({ productName: 'Tetrino Insecticide' });
        expect(JSON.stringify(result.mixCalculator.items.map((i) => i.mix))).not.toMatch(/"amount":\s*[1-9]/);
      } finally {
        await knex('lawn_protocol_products').where({ id: stagedRow.id }).update({ product_id: stagedRow.product_id });
      }
    });

    describe('application limits (product_limits over the customer\'s own history)', () => {
      async function withLimit({ product, limit, history }, run) {
        const visit = await plannedVisit();
        const [limitRow] = await knex('product_limits').insert({ product_id: product.id, severity: 'hard_block', ...limit }).returning('*');
        const rows = await knex('property_application_history').insert(history.map((h) => ({ customer_id: visit.customer_id, product_id: product.id, application_date: '2026-03-01', ...h }))).returning('*');
        try { return await run(visit); } finally {
          await knex('property_application_history').whereIn('id', rows.map((r) => r.id)).del();
          await knex('product_limits').where({ id: limitRow.id }).del();
        }
      }

      test('Celsius at its yearly cap: the selection is blocked with the existing message and carries no amount', async () => {
        setGates();
        const celsius = await knex('products_catalog').where({ name: 'Celsius WG' }).first();
        await withLimit({ product: celsius, limit: { limit_type: 'annual_max_rate', limit_value: 0.17, limit_unit: 'oz' }, history: [{ application_rate: 0.1 }, { application_rate: 0.08 }] }, async (visit) => {
          const result = await buildPlanForService(visit.id, { db: knex, selectedConditionalProductNames: ['Celsius WG'] });
          const block = result.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit');
          expect(block).toMatchObject({ productName: 'Celsius WG' });
          expect(block.message).toMatch(/Celsius WG: cumulative .* oz approaching\/exceeding max 0\.17\./);
          expect(result.status).toBe('blocked');
          const item = lineFor(result, 'Celsius WG');
          expect(item.mix).toBeNull();
          expect(item.unavailable.reason).toMatch(/application limit/);
        });
      });

      test('a whole-lawn row at an annual application cap computes nothing; unselected, the same product is not blocked', async () => {
        setGates();
        await withLimit({ product: tetrino, limit: { limit_type: 'annual_max_apps', limit_value: 1 }, history: [{ application_rate: 0.367 }] }, async (visit) => {
          const result = await buildPlanForService(visit.id, { db: knex });
          expect(result.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit').message).toMatch(/1\/1 applications this year — LIMIT REACHED/);
          expect(tetrinoItem(result).mix).toBeNull();
        });
        const celsius = await knex('products_catalog').where({ name: 'Celsius WG' }).first();
        await withLimit({ product: celsius, limit: { limit_type: 'annual_max_apps', limit_value: 1 }, history: [{ application_rate: 0.1 }] }, async (visit) => {
          const result = await buildPlanForService(visit.id, { db: knex });
          expect(result.propertyGate.blocks.map((b) => b.code)).not.toContain('lawn_v13_annual_limit');
        });
      });

      test('a warning-level limit (Celsius inside its minimum interval) shows its own message and does not block or touch the dose', async () => {
        setGates();
        const celsius = await knex('products_catalog').where({ name: 'Celsius WG' }).first();
        const recent = '2026-04-22'; // 20 days before the 2026-05-12 visit
        await withLimit({ product: celsius, limit: { limit_type: 'min_interval_days', limit_value: 60, severity: 'warning' }, history: [{ application_rate: 0.085, application_date: recent }] }, async (visit) => {
          const result = await buildPlanForService(visit.id, { db: knex, selectedConditionalProductNames: ['Celsius WG'] });
          const warning = result.propertyGate.warnings.find((w) => w.code === 'lawn_v13_limit_warning');
          expect(warning).toMatchObject({ productName: 'Celsius WG', limitType: 'min_interval_days', severity: 'warning' });
          expect(warning.message).toMatch(/Celsius WG: only 20 days since last app \(min 60\)\./);
          expect(result.propertyGate.blocks.map((b) => b.code)).not.toContain('lawn_v13_annual_limit');
          // Celsius is a spot row (no quantity either way); it stays selected and unblocked.
          const item = lineFor(result, 'Celsius WG');
          expect(item.selected).toBe(true);
          expect(item.unavailable).toBeNull();
          expect(item.mix).toBeNull();
        });
      });

      test('a warning-level limit on a whole-lawn row keeps its amount: Tetrino inside its minimum interval still plans 1.835 fl oz', async () => {
        setGates();
        const recent = '2026-04-22'; // 20 days before the 2026-05-12 visit
        await withLimit({ product: tetrino, limit: { limit_type: 'min_interval_days', limit_value: 60, severity: 'warning' }, history: [{ application_rate: 0.367, application_date: recent }] }, async (visit) => {
          const result = await buildPlanForService(visit.id, { db: knex });
          expect(result.propertyGate.warnings.find((w) => w.code === 'lawn_v13_limit_warning')).toMatchObject({ productName: 'Tetrino Insecticide', limitType: 'min_interval_days' });
          expect(result.propertyGate.blocks.map((b) => b.code)).not.toContain('lawn_v13_annual_limit');
          expect(tetrinoItem(result).mix.amount).toBe(1.835);
        });
      });

      test('gate off: no application-limit read and no v13 block, whatever product_limits say', async () => {
        setGates({ v13: 'off' });
        await withLimit({ product: tetrino, limit: { limit_type: 'annual_max_apps', limit_value: 1 }, history: [{ application_rate: 0.367 }] }, async (visit) => {
          const off = await buildPlanForService(visit.id, { db: knex });
          expect(off.propertyGate.blocks.map((b) => b.code)).not.toContain('lawn_v13_annual_limit');
          expect(off.propertyGate.warnings.map((w) => w.code)).not.toContain('lawn_v13_limit_warning');
        });
      });
    });

    test('gate off: no v13 field on any item, the item payload is the old one (key snapshot)', async () => {
      setGates({ v13: 'off' });
      const result = await plan(await plannedVisit());
      const OLD_KEYS = ['areaFactorBroadcast', 'areaFactorClean', 'areaFactorDefault', 'areaFactorHeavy', 'branch', 'branchGroupId', 'conditionFlag', 'conditional', 'matched', 'mix', 'product', 'raw', 'role', 'scope', 'selected', 'selectionReason', 'substitution'];
      const items = [...result.protocol.base, ...result.protocol.conditional];
      expect(items.length).toBeGreaterThan(0);
      for (const item of items) expect(Object.keys(item).sort()).toEqual(OLD_KEYS);
      expect(result.propertyGate.warnings.some((w) => /^lawn_v13_/.test(w.code))).toBe(false);
      expect(result.propertyGate.blocks.some((b) => /^lawn_v13_/.test(b.code))).toBe(false);
    });
  });
});
