// Places and trouble areas of the lawn Fast Complete sheet (GATE_LAWN_TROUBLE_AREAS, owner 2026-10-09), through
// PostgreSQL: the migration (up, up again, down, up), the trouble-area store, the place on the application ledger, and the
// v13 yearly limits judged per (property, place) by the SAME reader the plan and the completion use. Own cloned schema;
// synthetic data only. Skips without DATABASE_URL (CI runs it against the migrated database).
const { randomUUID } = require('crypto');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009110000_lawn_trouble_areas');
const { etDateString, addETDays } = require('../utils/datetime-et');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
// The preflight loads the whole completion module the first time (a cold transform takes several seconds).
jest.setTimeout(60000);
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_SPOT_RULES', 'GATE_LAWN_TROUBLE_AREAS', 'GATE_LAWN_TREATMENT_GUIDE'];
const ARENA = 'Arena 50 WDG';
const CELSIUS = 'Celsius WG';
const dayAgo = (n) => etDateString(addETDays(new Date(), -n));

describeDb('places and trouble areas through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  let limits;
  let areas;
  let world;
  const catalog = {};

  async function clone(table) {
    await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
    const columns = await knex(table).columnInfo();
    if (String(columns.id?.defaultValue || '').includes('nextval(')) {
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
      await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
    }
  }
  const gates = (on) => { for (const name of GATES) { if (on) process.env[name] = 'true'; else delete process.env[name]; } };
  const product = async (name, fields = {}) => {
    const [row] = await knex('products_catalog').insert({
      name, category: 'herbicide', default_rate_per_1000: 0.1, rate_unit: 'oz', label_verified_at: new Date(),
      inventory_on_hand: 1000, inventory_unit: 'oz', active: true, ...fields,
    }).returning('*');
    catalog[name] = row;
    return row;
  };
  // One ledger row: a spot application of a product on the fixture lawn, at a place (or none).
  let seq = 0;
  async function applied(name, { place = null, daysAgo = 5, rate = 0.1, unit = 'oz', property = world.property.id, retracted = false } = {}) {
    seq += 1;
    const [row] = await knex('property_application_history').insert({
      customer_id: world.customerId, property_id: property, product_id: catalog[name].id, application_date: dayAgo(daysAgo),
      application_rate: rate, rate_unit: unit, area_treated_sqft: 200, treated_place: place, notes: `row ${seq}`,
      retracted_at: retracted ? new Date() : null,
    }).returning('*');
    return row;
  }
  const check = (name, opts = {}) => limits.checkLimits(world.customerId, catalog[name].id, new Date(), knex, { propertyId: world.property.id, proposal: true, ...opts });
  const typesOf = (result) => result.blocks.map((b) => b.type).sort();

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions', 'service_products',
      'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'audit_log', 'product_limits', 'property_application_history']) {
      await clone(table);
    }
    // The clones come from a database that may already carry this migration: start without it, then run the real one.
    for (const table of ['service_products', 'property_application_history']) {
      if (await knex.schema.hasColumn(table, 'treated_place')) await knex.schema.alterTable(table, (t) => t.dropColumn('treated_place'));
    }
    await knex.raw('DROP TABLE IF EXISTS lawn_trouble_areas');
    await migration.up(knex);
    await product(ARENA, { category: 'insecticide', default_rate_per_1000: 0.147 });
    await product(CELSIUS, { default_rate_per_1000: 0.085 });
    await product('Plain Spot Fungicide', { category: 'fungicide' });
    await product('Certainty Turf Herbicide');
    await product('Blindside Herbicide');
    // Products whose cap is a stored product_limits row (a fungicide, a caterpillar product and a wetting agent): one a year.
    for (const [name, category] of [['Stored Cap Fungicide', 'fungicide'], ['Stored Cap Caterpillar Insecticide', 'insecticide'], ['Stored Cap Wetting Agent', 'adjuvant']]) {
      const row = await product(name, { category });
      await knex('product_limits').insert({ product_id: row.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 1, limit_unit: 'applications', severity: 'hard_block', description: `${name}: one a year.` });
    }
    limits = require('../services/application-limits');
    areas = require('../services/lawn-trouble-areas');
    world = await fixture(knex);
  }, 90000);
  afterAll(async () => { if (owned) await owned.dispose(); });
  beforeEach(async () => {
    require('../config/lawn-v13-count-caps').resetV13CapIdentity();
    gates(true);
    await knex('property_application_history').del();
    await knex('lawn_trouble_areas').del();
  });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  describe('the migration', () => {
    test('creates the store with its closed lists, the unique key and the two place columns; a second up changes nothing', async () => {
      const columns = await knex('lawn_trouble_areas').columnInfo();
      expect(Object.keys(columns)).toEqual(expect.arrayContaining(['id', 'customer_id', 'property_id', 'place', 'type', 'status', 'source', 'first_seen_on', 'last_seen_on', 'last_treated_on', 'first_service_record_id', 'last_service_record_id', 'cleared_at', 'cleared_by_technician_id', 'created_at', 'updated_at']));
      expect(await knex.schema.hasColumn('service_products', 'treated_place')).toBe(true);
      expect(await knex.schema.hasColumn('property_application_history', 'treated_place')).toBe(true);
      await expect(migration.up(knex)).resolves.toBeUndefined();
      const base = { customer_id: world.customerId, property_id: world.property.id, place: 'front', type: 'weeds', source: 'tech_tap', first_seen_on: dayAgo(1), last_seen_on: dayAgo(1) };
      await knex('lawn_trouble_areas').insert(base);
      await expect(knex('lawn_trouble_areas').insert(base)).rejects.toThrow(/uq_lawn_trouble_areas_place_type/);
      for (const bad of [{ place: 'middle' }, { type: 'moss' }, { status: 'gone' }, { source: 'robot' }]) {
        await expect(knex('lawn_trouble_areas').insert({ ...base, place: 'back', ...bad })).rejects.toThrow(/chk_lawn_trouble_areas/);
      }
    });

    test('down drops the store, the index and both columns; up restores them (round trip)', async () => {
      await migration.down(knex);
      expect(await knex.schema.hasTable('lawn_trouble_areas')).toBe(false);
      expect(await knex.schema.hasColumn('service_products', 'treated_place')).toBe(false);
      expect(await knex.schema.hasColumn('property_application_history', 'treated_place')).toBe(false);
      const index = await knex.raw("select 1 from pg_indexes where schemaname = ? and indexname = 'idx_pah_customer_property_place'", [owned.schema]);
      expect(index.rows).toHaveLength(0);
      await expect(migration.down(knex)).resolves.toBeUndefined();
      await migration.up(knex);
      expect(await knex.schema.hasTable('lawn_trouble_areas')).toBe(true);
      expect(await knex.schema.hasColumn('property_application_history', 'treated_place')).toBe(true);
    });
  });

  describe('the yearly count, judged per place', () => {
    test('two Celsius at the front close the front only; the back is offered; the whole lawn reads as capped', async () => {
      await applied(CELSIUS, { place: 'front' });
      await applied(CELSIUS, { place: 'front', daysAgo: 20 });
      expect(typesOf(await check(CELSIUS, { place: 'front' }))).toContain('annual_max_apps');
      expect(typesOf(await check(CELSIUS, { place: 'back' }))).not.toContain('annual_max_apps');
      expect(typesOf(await check(CELSIUS))).toContain('annual_max_apps');
    });

    test('a row with no place on record counts at EVERY place', async () => {
      await applied(CELSIUS, { place: null });
      await applied(CELSIUS, { place: null, daysAgo: 20 });
      for (const place of areas.PLACE_IDS) expect(typesOf(await check(CELSIUS, { place }))).toContain('annual_max_apps');
    });

    test('one placed row and one unplaced row: the placed place and the lawn are at 2, another place is at 1', async () => {
      await applied(CELSIUS, { place: 'front' });
      await applied(CELSIUS, { place: null, daysAgo: 20 });
      expect(typesOf(await check(CELSIUS, { place: 'front' }))).toContain('annual_max_apps');
      expect(typesOf(await check(CELSIUS, { place: 'back' }))).not.toContain('annual_max_apps');
    });

    test('a retracted row, and a row at another property, never count', async () => {
      const other = (await knex('customer_properties').insert({ customer_id: world.customerId, address_line1: '200 Fixture Street', city: 'Fixture City', zip: '34201' }).returning('*'))[0];
      await applied(CELSIUS, { place: 'front', retracted: true });
      await applied(CELSIUS, { place: 'front', property: other.id });
      await applied(CELSIUS, { place: 'front' });
      expect(typesOf(await check(CELSIUS, { place: 'front' }))).not.toContain('annual_max_apps');
    });

    test('gate off: a place is ignored, the read is the whole lawn exactly as before', async () => {
      await applied(CELSIUS, { place: 'front' });
      await applied(CELSIUS, { place: 'front', daysAgo: 20 });
      gates(false);
      process.env.GATE_LAWN_V13 = 'true';
      expect(typesOf(await check(CELSIUS, { place: 'back' }))).toContain('annual_max_apps');
      expect(await check(CELSIUS, { place: 'back' })).toEqual(await check(CELSIUS));
    });

    test('a product with no v13 cap and no stored limit is never blocked by a place', async () => {
      await applied('Plain Spot Fungicide', { place: 'front' });
      expect((await check('Plain Spot Fungicide', { place: 'front' })).blocks).toEqual([]);
    });
  });

  describe('Arena: the 56-day interval and the yearly amount, judged per place', () => {
    test('an application at the front inside the interval closes the front only', async () => {
      await applied(ARENA, { place: 'front', daysAgo: 10, rate: 0.147 });
      expect(typesOf(await check(ARENA, { place: 'front' }))).toContain('min_interval_days');
      expect(typesOf(await check(ARENA, { place: 'back' }))).not.toContain('min_interval_days');
      expect(typesOf(await check(ARENA))).toContain('min_interval_days');
    });

    test('a full-rate pass at the front fills the front\'s yearly amount; the back still has all of it', async () => {
      await applied(ARENA, { place: 'front', daysAgo: 100, rate: 0.294 });
      const front = await check(ARENA, { place: 'front' });
      const back = await check(ARENA, { place: 'back' });
      expect(front.blocks.some((b) => b.type === 'annual_max_rate')).toBe(true);
      expect(back.blocks.some((b) => b.type === 'annual_max_rate')).toBe(false);
    });

    test('an unplaced full-rate pass fills the amount at every place', async () => {
      await applied(ARENA, { place: null, daysAgo: 100, rate: 0.294 });
      for (const place of areas.PLACE_IDS) expect((await check(ARENA, { place })).blocks.some((b) => b.type === 'annual_max_rate')).toBe(true);
    });

    test('two half-rate passes at the front reach the count of 2 there, and not at the side', async () => {
      await applied(ARENA, { place: 'front', daysAgo: 100, rate: 0.147 });
      await applied(ARENA, { place: 'front', daysAgo: 60, rate: 0.147 });
      expect(typesOf(await check(ARENA, { place: 'front' }))).toContain('annual_max_apps');
      expect(typesOf(await check(ARENA, { place: 'left_side' }))).not.toContain('annual_max_apps');
    });
  });

  describe('the plan reader, the completion preflight and the closeout audit agree', () => {
    const svcOf = async () => {
      const visit = await world.visit(0);
      return { id: visit.id, customer_id: world.customerId, property_id: world.property.id, scheduled_date: visit.scheduled_date, service_type: 'Lawn fixture' };
    };

    test('cappedByPlace (the sheet) shows the front closed and the back open, the same as checkLimits', async () => {
      await applied(CELSIUS, { place: 'front' });
      await applied(CELSIUS, { place: 'front', daysAgo: 20 });
      const svc = await svcOf();
      const result = await areas.cappedByPlace({ knex, svc, products: [{ id: catalog[CELSIUS].id, name: CELSIUS }], rows: new Map() });
      const blocked = areas.blockedMap(result);
      expect(Object.keys(blocked[catalog[CELSIUS].id])).toEqual(['front']);
      expect(blocked[catalog[CELSIUS].id].front).toMatch(/LIMIT REACHED/);
    });

    test('with nothing capped lawn-wide, every place reads the lawn-wide answer and no place read is repeated', async () => {
      const svc = await svcOf();
      const spy = jest.spyOn(limits, 'checkLimits');
      const result = await areas.cappedByPlace({ knex, svc, products: [{ id: catalog[CELSIUS].id, name: CELSIUS }], rows: new Map() });
      expect(spy).toHaveBeenCalledTimes(1);
      expect(areas.blockedMap(result)).toEqual({});
      spy.mockRestore();
    });

    test('preflightPlaces refuses a spot row at the closed place, allows the open one, and asks for a place', async () => {
      await applied(CELSIUS, { place: 'front' });
      await applied(CELSIUS, { place: 'front', daysAgo: 20 });
      const svc = await svcOf();
      const row = (extra) => ({ productId: catalog[CELSIUS].id, name: CELSIUS, applicationMethod: 'spot_treatment', ...extra });
      expect(await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'back' })] })).toBeNull();
      const closed = await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'front' })] });
      expect(closed).toMatchObject({ status: 400, payload: { code: 'lawn_place_limit', place: 'front', limitType: 'annual_max_apps' } });
      expect(closed.payload.error).toMatch(/LIMIT REACHED/);
      expect(await areas.preflightPlaces({ knex, svc, products: [row({})] })).toMatchObject({ status: 400, payload: { code: 'lawn_place_required' } });
      expect(await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'roof' })] })).toMatchObject({ status: 400, payload: { code: 'lawn_place_invalid' } });
      // A whole-lawn row is not judged by place.
      expect(await areas.preflightPlaces({ knex, svc, products: [row({ applicationMethod: 'broadcast_spray' })] })).toBeNull();
    });

    // One row per way a spot treatment reaches the sheet: the product is at its yearly count at the FRONT, so /complete refuses
    // the front and accepts the back (the sheet tests prove the tech can reach the back in the counted taps).
    test.each([
      ['Weed spots lead (Celsius WG)', CELSIUS, 2],
      ['Weed spots member (Certainty)', 'Certainty Turf Herbicide', 2],
      ['Weed spots replacement (Blindside)', 'Blindside Herbicide', 2],
      ['chinch (Arena 50 WDG)', ARENA, 2],
      ['fungus card (a stored cap)', 'Stored Cap Fungicide', 1],
      ['caterpillar card (a stored cap)', 'Stored Cap Caterpillar Insecticide', 1],
      ['dry-spot card (a stored cap)', 'Stored Cap Wetting Agent', 1],
      ['a search-added spot row (a stored cap)', 'Stored Cap Fungicide', 1],
    ])('%s: /complete refuses the front and accepts the back', async (_label, name, rows) => {
      for (let i = 0; i < rows; i += 1) await applied(name, { place: 'front', daysAgo: 100 - i * 60, rate: 0.147 });
      const svc = await svcOf();
      const row = (areaPlace) => ({ productId: catalog[name].id, name, applicationMethod: 'spot_treatment', areaPlace });
      expect(await areas.preflightPlaces({ knex, svc, products: [row('front')] })).toMatchObject({ status: 400, payload: { code: 'lawn_place_limit', place: 'front' } });
      expect(await areas.preflightPlaces({ knex, svc, products: [row('back')] })).toBeNull();
    });

    // A typed QUANTITY on a small spot: the preflight and the closeout audit size the row the same way (the recorded rate when it
    // is readable, else the quantity over the row's own area), so a large amount on a small spot cannot pass the Arena yearly amount.
    describe('a typed quantity on a spot, against the Arena yearly amount (0.294 oz per 1,000 sq ft)', () => {
      const typed = (extra) => ({ productId: catalog[ARENA].id, name: ARENA, applicationMethod: 'spot_treatment', areaPlace: 'front', areaValue: 100, areaUnit: 'sqft', amountUnit: 'oz', ...extra });
      // The same inputs recorded on the ledger as the completion writes them, then audited.
      const audited = async (row) => {
        const { baseQuantityUnit } = require('../services/inventory-units');
        const record = (await knex('service_records').insert({ customer_id: world.customerId, scheduled_service_id: (await world.visit(0)).id, service_date: dayAgo(0), service_type: 'Lawn fixture' }).returning('*'))[0];
        await knex('property_application_history').insert({
          customer_id: world.customerId, property_id: world.property.id, product_id: catalog[ARENA].id, application_date: dayAgo(0), service_record_id: record.id,
          application_rate: row.rate || null, rate_unit: row.rateUnit || null, quantity_applied: row.totalAmount, quantity_unit: baseQuantityUnit(row.amountUnit),
          area_treated_sqft: Math.round(row.areaValue), treated_place: 'front',
        });
        const found = await limits.auditHardCountLimits(world.customerId, catalog[ARENA].id, dayAgo(0), knex, { propertyId: world.property.id, place: 'front', excludeScheduledServiceId: null });
        await knex('property_application_history').where({ service_record_id: record.id }).del();
        return found.some((v) => v.type === 'annual_max_rate');
      };
      const visit = async () => ({ ...(await world.visit(0)), customer_id: world.customerId, property_id: world.property.id });

      test.each([
        ['0.05 oz on 100 sq ft is 0.5 oz per 1,000: over the cap', 0.05, true],
        ['0.02 oz on 100 sq ft is 0.2 oz per 1,000: under the cap', 0.02, false],
        ['0.0294 oz on 100 sq ft is exactly the cap: allowed', 0.0294, false],
      ])('%s', async (_label, totalAmount, refused) => {
        const row = typed({ totalAmount });
        const result = await areas.preflightPlaces({ knex, svc: await visit(), products: [row] });
        if (refused) expect(result).toMatchObject({ status: 400, payload: { code: 'lawn_place_limit', limitType: 'annual_max_rate', place: 'front' } });
        else expect(result).toBeNull();
        // The audit, given the row as the ledger would hold it, reaches the same verdict.
        expect(await audited(row)).toBe(refused);
      });

      test('the same quantity on a larger spot is under the cap (the row\'s OWN area decides)', async () => {
        expect(await areas.preflightPlaces({ knex, svc: await visit(), products: [typed({ totalAmount: 0.05, areaValue: 1000 })] })).toBeNull();
      });

      test('a stated rate wins over the quantity, as it does for a recorded row; a quantity on a row with no area falls back to the program\'s dose', async () => {
        const rateRow = typed({ totalAmount: 5, rate: 0.147, rateUnit: 'oz' });
        expect(await areas.preflightPlaces({ knex, svc: await visit(), products: [rateRow] })).toBeNull();
        expect(await audited(rateRow)).toBe(false);
        const noArea = typed({ totalAmount: 5, areaValue: undefined, areaUnit: undefined });
        expect(await areas.preflightPlaces({ knex, svc: await visit(), products: [noArea] })).toBeNull();
      });
    });

    test('a shared active-ingredient cap broken at the chosen place never refuses here (it stays an advisory)', async () => {
      const [ai] = await knex('products_catalog').insert({ name: 'Shared AI fixture', category: 'herbicide', active_ingredient: 'Zzzzine', default_rate_per_1000: 0.5, rate_unit: 'oz', label_verified_at: new Date(), inventory_on_hand: 1000, inventory_unit: 'oz', active: true }).returning('*');
      catalog['Shared AI fixture'] = ai;
      await knex('product_limits').insert({ product_id: ai.id, match_type: 'active_ingredient', match_value: 'Zzzzine', limit_type: 'annual_max_rate', limit_value: 1, limit_unit: 'oz/1000sf/year', severity: 'hard_block', description: 'fixture' });
      await applied('Shared AI fixture', { place: 'front', rate: 1 });
      const checked = await check('Shared AI fixture', { place: 'front' });
      expect(checked.blocks.some((b) => b.matchType === 'active_ingredient')).toBe(true);
      const svc = await svcOf();
      expect(await areas.preflightPlaces({ knex, svc, products: [{ productId: ai.id, name: 'Shared AI fixture', applicationMethod: 'spot_treatment', areaPlace: 'front', rate: 0.5, rateUnit: 'oz' }] })).toBeNull();
    });

    // Which chinch rungs are chinch-only is read from the staged rows' triggers, never the name (real SQL).
    describe('chinch-only rungs and the ladder, from the staged rows', () => {
      const guide = require('../services/lawn-treatment-guide');
      const stage = async (rows) => {
        const [protocol] = await knex('lawn_protocols').insert({ protocol_key: `fixture_${randomUUID().slice(0, 6)}`, version: `v-${randomUUID().slice(0, 6)}`, name: 'Fixture', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
        const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month: 5, window_key: `w_${randomUUID().slice(0, 6)}`, title: 'w', visit_type: 'fixture' }).returning('*');
        for (const [name, trigger] of rows) {
          await knex('lawn_protocol_products').insert({
            lawn_protocol_window_id: window.id, product_id: catalog[name].id, product_name: name, role: 'insecticide_spot', application_mode: 'spot',
            default_in_plan: false, rate_per_1000: 0.1, rate_unit: 'oz', gates: JSON.stringify(trigger ? { trigger } : {}),
          });
        }
        return { id: protocol.id };
      };
      const FIRST = 'chinch_20_to_25_per_sqft';
      const SECOND = 'chinch_second_product_caterpillars_or_mole_cricket_nymphs';
      beforeAll(async () => { await knex('lawn_protocol_products').del(); });

      test('the first rung is chinch-only when every row staged for it carries a first-rung trigger; a second staged purpose, or a later rung, is not', async () => {
        const structured = await stage([[ARENA, FIRST], [ARENA, FIRST], ['Stored Cap Caterpillar Insecticide', SECOND], ['Stored Cap Caterpillar Insecticide', 'caterpillars']]);
        const found = await guide.chinchLadderIds({ structured, knex });
        expect(found.sort()).toEqual([catalog[ARENA].id, catalog['Stored Cap Caterpillar Insecticide'].id].sort());
        const products = [{ productId: catalog[ARENA].id, rung: 0 }, { productId: catalog['Stored Cap Caterpillar Insecticide'].id, rung: 1 }];
        expect(await guide.chinchOnlyIdsOf({ products, structured, knex })).toEqual([catalog[ARENA].id]);
        const mixed = await stage([[ARENA, FIRST], [ARENA, null]]);
        expect(await guide.chinchOnlyIdsOf({ products: [{ productId: catalog[ARENA].id, rung: 0 }], structured: mixed, knex })).toEqual([]);
      });

      test('chinchLadderSets gives the ladder and its chinch-only rungs in one read; no chinch rows or no protocol gives both empty', async () => {
        const structured = await stage([[ARENA, FIRST], [ARENA, FIRST], ['Stored Cap Caterpillar Insecticide', SECOND]]);
        const sets = await guide.chinchLadderSets({ structured, knex });
        expect(sets.ladder.sort()).toEqual([catalog[ARENA].id, catalog['Stored Cap Caterpillar Insecticide'].id].sort());
        expect(sets.only).toEqual([catalog[ARENA].id]);
        expect(await guide.chinchLadderSets({ structured: await stage([[CELSIUS, null]]), knex })).toEqual({ ladder: [], only: [] });
        expect(await guide.chinchLadderSets({ structured: null, knex })).toEqual({ ladder: [], only: [] });
      });

      test('a protocol with no chinch rows has an empty ladder', async () => {
        expect(await guide.chinchLadderIds({ structured: await stage([[CELSIUS, null]]), knex })).toEqual([]);
        expect(await guide.chinchLadderIds({ structured: null, knex })).toEqual([]);
      });
    });

    // The method is resolved by the very function the completion stores it with (real catalog rows, real SQL).
    describe('which rows are spot rows', () => {
      const svcRow = async () => svcOf();
      const row = (extra) => ({ productId: catalog[CELSIUS].id, name: CELSIUS, ...extra });

      test('no method on a herbicide (the lawn default is spot), and the `method` alias: a place is required; an explicit non-spot method on it, or a non-herbicide, is not a spot row', async () => {
        const svc = await svcRow();
        const go = (rows) => areas.preflightPlaces({ knex, svc, products: rows });
        expect(await go([row({})])).toMatchObject({ status: 400, payload: { code: 'lawn_place_required' } });
        expect(await go([row({ method: 'Spot treatment' })])).toMatchObject({ status: 400, payload: { code: 'lawn_place_required' } });
        expect(await go([row({ areaPlace: 'roof' })])).toMatchObject({ status: 400, payload: { code: 'lawn_place_invalid' } });
        expect(await go([row({ applicationMethod: 'broadcast_spray' }), row({ method: 'Granular broadcast' })])).toBeNull();
        // A fungicide with no method defaults to a broadcast on the lawn line: no place asked.
        expect(await go([{ productId: catalog['Plain Spot Fungicide'].id, name: 'Plain Spot Fungicide' }])).toBeNull();
      });

      test('the limit is read for an inferred spot row at its place', async () => {
        await applied(CELSIUS, { place: 'front' });
        await applied(CELSIUS, { place: 'front', daysAgo: 20 });
        const svc = await svcRow();
        expect(await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'front' })] })).toMatchObject({ status: 400, payload: { code: 'lawn_place_limit', place: 'front' } });
        expect(await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'back' })] })).toBeNull();
      });
    });

    // A take-all row opened by the guide CARD may go only on a mapped take-all place; a Search row maps a new one.
    describe('take-all rows and the mapped places', () => {
      const lawnFast = require('../services/lawn-fast-complete');
      const row = (extra) => ({ productId: catalog['Plain Spot Fungicide'].id, name: 'Plain Spot Fungicide', applicationMethod: 'spot_treatment', troubleType: 'take_all', ...extra });
      const mapBack = async () => {
        const visit = await world.visit(-10);
        const record = await world.record(visit);
        await knex.transaction((trx) => areas.recordFromCompletion(trx, { svc: visit, record, rows: [{ place: 'back', type: 'take_all', source: 'tech_tap' }] }));
      };
      const confirm = (...ids) => jest.spyOn(lawnFast, 'troubleTypeIdsFor').mockResolvedValue({ takeAll: new Set(ids), chinch: new Set() });
      afterEach(() => jest.restoreAllMocks());

      test('a card row at the mapped place passes; at an unmapped place it is refused with the reason; a Search row at an unmapped place passes', async () => {
        await mapBack();
        confirm(catalog['Plain Spot Fungicide'].id.toLowerCase());
        const svc = await svcOf();
        const go = (extra) => areas.preflightPlaces({ knex, svc, products: [row(extra)] });
        expect(await go({ areaPlace: 'back', troubleSource: 'guide_card' })).toBeNull();
        expect(await go({ areaPlace: 'front', troubleSource: 'guide_card' })).toMatchObject({
          status: 400, payload: { code: 'lawn_place_not_mapped', place: 'front', error: expect.stringMatching(/mapped take-all areas only/) },
        });
        expect(await go({ areaPlace: 'front', troubleSource: 'tech_tap' })).toBeNull();
        expect(await go({ areaPlace: 'front' })).toBeNull();
      });

      test('a cleared area is not mapped; a claim on a product the server does not identify as take-all enforces nothing; no area on file maps nothing', async () => {
        await mapBack();
        const svc = await svcOf();
        const [area] = await knex('lawn_trouble_areas').where({ place: 'back', type: 'take_all' });
        await areas.clearArea(knex, { areaId: area.id, propertyId: world.property.id });
        confirm(catalog['Plain Spot Fungicide'].id.toLowerCase());
        expect(await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'back', troubleSource: 'guide_card' })] })).toMatchObject({ status: 400, payload: { code: 'lawn_place_not_mapped' } });
        jest.restoreAllMocks();
        confirm();
        expect(await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'front', troubleSource: 'guide_card' })] })).toBeNull();
      });

      test('a failed take-all lookup enforces nothing (the claim is unconfirmed, so it is stored as plain fungus)', async () => {
        jest.spyOn(lawnFast, 'troubleTypeIdsFor').mockRejectedValue(new Error('plan unavailable'));
        const svc = await svcOf();
        expect(await areas.preflightPlaces({ knex, svc, products: [row({ areaPlace: 'front', troubleSource: 'guide_card' })] })).toBeNull();
      });
    });

    test('the closeout audit judges a recorded spot application at its place, not the lawn', async () => {
      await applied(CELSIUS, { place: 'front' });
      await applied(CELSIUS, { place: 'front', daysAgo: 20 });
      const day = dayAgo(0);
      const audit = (place) => limits.auditHardCountLimits(world.customerId, catalog[CELSIUS].id, day, knex, { propertyId: world.property.id, ...(place ? { place } : {}) });
      expect((await audit('back')).map((v) => v.type)).not.toContain('annual_max_apps');
      expect((await audit('front')).map((v) => v.type)).toContain('annual_max_apps');
      expect((await audit()).map((v) => v.type)).toContain('annual_max_apps');
    });
  });

  describe('the ledger carries the place', () => {
    test('createComplianceRecords copies a product record\'s place, and writes none for a row without one', async () => {
      const visit = await world.visit(-1);
      const record = await world.record(visit);
      const [placed] = await knex('service_products').insert({ service_record_id: record.id, product_id: catalog[CELSIUS].id, product_name: CELSIUS, application_method: 'spot_treatment', treated_place: 'left_side', application_rate: 0.1, rate_unit: 'oz' }).returning('*');
      const [whole] = await knex('service_products').insert({ service_record_id: record.id, product_id: catalog[ARENA].id, product_name: ARENA, application_method: 'broadcast_spray', application_rate: 0.1, rate_unit: 'oz' }).returning('*');
      await require('../services/compliance').createComplianceRecords(record.id, { trx: knex });
      const rows = await knex('property_application_history').where({ service_record_id: record.id });
      expect(rows.find((r) => r.service_product_id === placed.id).treated_place).toBe('left_side');
      expect(rows.find((r) => r.service_product_id === whole.id).treated_place).toBeNull();
    });
  });

  describe('the trouble-area store', () => {
    const rowsOf = () => knex('lawn_trouble_areas').orderBy('place').orderBy('type');
    const recordOn = async (offset) => {
      const visit = await world.visit(offset);
      return { visit, record: await world.record(visit) };
    };
    const write = async (rows, { visit, record }) => knex.transaction((trx) => areas.recordFromCompletion(trx, { svc: visit, record, rows }));

    test('the first writer wins (first seen, source); a later visit moves last seen, last treated and the last record', async () => {
      const first = await recordOn(-20);
      await write([{ place: 'front', type: 'fungus', source: 'guide_card' }], first);
      const second = await recordOn(-3);
      await write([{ place: 'front', type: 'fungus', source: 'tech_tap' }], second);
      const [row] = await rowsOf();
      expect(row).toMatchObject({ place: 'front', type: 'fungus', status: 'active', source: 'guide_card' });
      expect(etDateString(row.first_seen_on)).toBe(dayAgo(20));
      expect(etDateString(row.last_seen_on)).toBe(dayAgo(3));
      expect(etDateString(row.last_treated_on)).toBe(dayAgo(3));
      expect(row.first_service_record_id).toBe(first.record.id);
      expect(row.last_service_record_id).toBe(second.record.id);
    });

    test('a retry or a resume of the same completion writes no second row; a backdated record does not move the last treatment back', async () => {
      const newer = await recordOn(-3);
      await write([{ place: 'back', type: 'weeds', source: 'tech_tap' }, { place: 'back', type: 'weeds', source: 'tech_tap' }], newer);
      await write([{ place: 'back', type: 'weeds', source: 'tech_tap' }], newer);
      const older = await recordOn(-30);
      await write([{ place: 'back', type: 'weeds', source: 'tech_tap' }], older);
      const rows = await rowsOf();
      expect(rows).toHaveLength(1);
      expect(rows[0].last_service_record_id).toBe(newer.record.id);
      expect(etDateString(rows[0].last_treated_on)).toBe(dayAgo(3));
    });

    test('rows outside the closed lists, a visit with no property and no rows write nothing', async () => {
      const visit = await recordOn(-1);
      await write([{ place: 'roof', type: 'weeds' }, { place: 'front', type: 'moss' }], visit);
      await write([], visit);
      await knex.transaction((trx) => areas.recordFromCompletion(trx, { svc: { ...visit.visit, property_id: null }, record: visit.record, rows: [{ place: 'front', type: 'weeds' }] }));
      expect(await rowsOf()).toEqual([]);
    });

    test('clearing hides the area from the sheet; only an area of the visit\'s own lawn clears; treating it again reactivates it', async () => {
      const first = await recordOn(-10);
      await write([{ place: 'right_side', type: 'chinch', source: 'tech_tap' }, { place: 'front', type: 'weeds', source: 'tech_tap' }], first);
      expect((await areas.loadActive(knex, world.property.id)).map((a) => `${a.place}:${a.type}`).sort()).toEqual(['front:weeds', 'right_side:chinch']);
      const [target] = await rowsOf().where({ place: 'right_side' });
      const other = (await knex('customer_properties').insert({ customer_id: world.customerId, address_line1: '300 Fixture Street', city: 'Fixture City', zip: '34201' }).returning('*'))[0];
      expect(await areas.clearArea(knex, { areaId: target.id, propertyId: other.id })).toBeNull();
      expect(await areas.clearArea(knex, { areaId: 'not-a-uuid', propertyId: world.property.id })).toBeNull();
      expect(await areas.clearArea(knex, { areaId: target.id, propertyId: world.property.id, technicianId: randomUUID() })).toMatchObject({ place: 'right_side', type: 'chinch' });
      expect(await areas.clearArea(knex, { areaId: target.id, propertyId: world.property.id })).toBeNull();
      expect((await areas.loadActive(knex, world.property.id)).map((a) => a.place)).toEqual(['front']);
      const cleared = (await rowsOf().where({ place: 'right_side' }))[0];
      expect(cleared).toMatchObject({ status: 'cleared' });
      expect(cleared.cleared_at).toBeTruthy();
      await write([{ place: 'right_side', type: 'chinch', source: 'tech_tap' }], await recordOn(0));
      const back = (await rowsOf().where({ place: 'right_side' }))[0];
      expect(back).toMatchObject({ status: 'active', cleared_at: null, cleared_by_technician_id: null });
    });

    test('a backdated treatment keeps a later clear; a treatment after the clear brings the area back', async () => {
      await write([{ place: 'back', type: 'fungus', source: 'tech_tap' }], await recordOn(-20));
      const [area] = await rowsOf();
      expect(await areas.clearArea(knex, { areaId: area.id, propertyId: world.property.id, technicianId: randomUUID() })).toBeTruthy();
      // Cleared nine days ago.
      await knex('lawn_trouble_areas').where({ id: area.id }).update({ cleared_at: `${dayAgo(9)}T15:00:00Z` });
      // A visit from twelve days ago, completed late: before the clear, so the area stays cleared; the dates still merge.
      const old = await recordOn(-12);
      await write([{ place: 'back', type: 'fungus', source: 'tech_tap' }], old);
      let [row] = await rowsOf();
      expect(row).toMatchObject({ status: 'cleared' });
      expect(row.cleared_at).toBeTruthy();
      expect(row.cleared_by_technician_id).toBeTruthy();
      expect(etDateString(row.last_treated_on)).toBe(dayAgo(12));
      expect(row.last_service_record_id).toBe(old.record.id);
      expect(await areas.loadActive(knex, world.property.id)).toEqual([]);
      // A visit from three days ago is after the clear: active again, the clear's marks gone.
      await write([{ place: 'back', type: 'fungus', source: 'tech_tap' }], await recordOn(-3));
      [row] = await rowsOf();
      expect(row).toMatchObject({ status: 'active', cleared_at: null, cleared_by_technician_id: null });
      expect(etDateString(row.last_treated_on)).toBe(dayAgo(3));
      expect((await areas.loadActive(knex, world.property.id)).map((a) => a.place)).toEqual(['back']);
    });

    test('a treatment on the very day of the clear brings it back (the tech cleared it, then treated it again)', async () => {
      await write([{ place: 'front', type: 'weeds', source: 'tech_tap' }], await recordOn(-5));
      const [area] = await rowsOf();
      await areas.clearArea(knex, { areaId: area.id, propertyId: world.property.id });
      await write([{ place: 'front', type: 'weeds', source: 'tech_tap' }], await recordOn(0));
      expect((await rowsOf())[0]).toMatchObject({ status: 'active', cleared_at: null });
    });

    test('the context block lists the closed places, the known areas and what a limit closes; gate off sends nothing', async () => {
      await write([{ place: 'back', type: 'fungus', source: 'tech_tap' }], await recordOn(-6));
      await applied(CELSIUS, { place: 'front' });
      await applied(CELSIUS, { place: 'front', daysAgo: 20 });
      const svc = await world.visit(0);
      const failures = new Set();
      const { troubleAreas } = await areas.buildContextBlock({ knex, svc, products: [{ id: catalog[CELSIUS].id, name: CELSIUS }], rows: new Map(), readFailures: failures });
      expect(troubleAreas.places.map((p) => p.label)).toEqual(['Front', 'Back', 'Left side', 'Right side']);
      expect(troubleAreas.known).toEqual([expect.objectContaining({ place: 'back', placeLabel: 'Back', type: 'fungus', typeLabel: 'Fungus', lastTreatedOn: dayAgo(6) })]);
      expect(Object.keys(troubleAreas.blocked[catalog[CELSIUS].id])).toEqual(['front']);
      expect([...failures]).toEqual([]);
      gates(false);
      expect(await areas.buildContextBlock({ knex, svc, products: [], rows: new Map(), readFailures: failures })).toEqual({});
    });
  });
});
