// Lawn protocol v13, final pass part 2 (migration 20261009151000): the Blindside catalog rate and ONE application a year on the
// staged Blindside rows, through the real migration on PostgreSQL (cloned schema). Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned: an empty catalog unit becomes 'oz' and an empty default rate 0.149 only when the unit is oz; any other value stays and a
// catalog row at 0.149 oz writes nothing; every non-retired staged Blindside row that holds exactly 2 becomes 1 (gate and counter
// each on their own), a retired row, an edited figure, another product and an older version stay; a second up writes nothing; down
// restores exactly, and not while a visit references the protocol or for a figure somebody has edited; the older downs
// (20261007175000, 20261007177000, 20261007179000) skip a row at 1 and still work on a row at 2 (the order after this down()).
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009151000_lawn_v13_final_pass_blindside_catalog');
const countCapsRows = require('../models/migrations/20261007175000_lawn_v13_count_caps_protocol_rows');
const clamp = require('../models/migrations/20261007177000_lawn_v13_cap_clamp_and_kb_dismiss');
const blindsideRow = require('../models/migrations/20261007179000_lawn_v13_blindside_protocol_row');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');

const V13 = staged.V13_VERSION;
const BLINDSIDE = 'Blindside Herbicide';
const CELSIUS = 'Celsius WG';
const JAN = 'jan_v13_pre_m_hose';
const FEB = 'feb_v13_spreader_green_up';
const DEC = 'dec_v13_spreader_feeding';
const KEYS = [['fixture_bc_a', 'st_augustine'], ['fixture_bc_b', 'bermuda']];
const TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_audit_log',
  'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'service_products'];
const GATES = { trigger: 'celsius_annual_cap_reached', annualMaxApps: 2 };
const parse = (value) => (typeof value === 'string' ? JSON.parse(value) : value);

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 final pass part 2 (Blindside catalog + one application a year) through PostgreSQL', () => {
  let owned;
  let knex;
  let log;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });
  beforeEach(() => { log = jest.spyOn(console, 'log').mockImplementation(() => {}); });
  afterEach(() => { log.mockRestore(); });

  const catalogRow = (name = BLINDSIDE) => knex('products_catalog').where({ name }).first();
  const rows = (windowKey, name, version = V13) => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'w.window_key': windowKey, 'p.product_name': name, 'l.version': version })
    .orderBy(['l.protocol_key', 'p.id']).select('p.*', 'l.protocol_key');
  const figures = (row) => [parse(row.gates).annualMaxApps, parse(row.annual_counter).maxApplications];
  const audits = (action) => knex('lawn_protocol_audit_log').where({ action });
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  const snapshot = async () => clean([await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']),
    await knex('products_catalog').orderBy('name'), await knex('lawn_protocol_audit_log').orderBy('id')]);

  async function reset({ catalog = { default_rate_per_1000: null, rate_unit: null }, alias = false } = {}) {
    for (const table of ['service_products', 'lawn_protocol_product_actuals', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const [blindside] = await knex('products_catalog').insert({ name: alias ? 'Blindside (old name)' : BLINDSIDE, category: 'herbicide', active: true, ...catalog }).returning('*');
    const [celsius] = await knex('products_catalog').insert({ name: CELSIUS, category: 'herbicide', active: true }).returning('*');
    ids.blindside = blindside.id;
    if (alias) await knex('product_aliases').insert({ product_id: blindside.id, alias_name: BLINDSIDE });
    for (const [key, track] of KEYS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: track, region: 'swfl' });
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: track, region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const window = {};
      for (const [windowKey, month] of [[JAN, 1], [FEB, 2], [DEC, 12]]) {
        [window[windowKey]] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      }
      const add = (windowKey, name, productId, gates, counter) => knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: window[windowKey].id, product_id: productId, product_name: name, role: 'post_emergent_spot', application_mode: 'spot', rate_unit: 'label_rate',
        default_in_plan: false, carrier_gal_per_1000: 1, mixing: JSON.stringify({}), report_copy: JSON.stringify({ role: 'post_emergent_spot' }),
        gates: JSON.stringify(gates), annual_counter: JSON.stringify(counter), sort_order: 9,
      });
      await add(JAN, BLINDSIDE, blindside.id, GATES, { maxApplications: 2 });
      await add(DEC, BLINDSIDE, blindside.id, GATES, { maxApplications: 2 });
      await add(FEB, BLINDSIDE, blindside.id, { ...GATES, retired: true }, { maxApplications: 2 });
      await add(JAN, CELSIUS, celsius.id, { annualMaxApps: 2 }, { maxApplications: 2 });
    }
    const [old] = await knex('lawn_protocols').where({ protocol_key: KEYS[0][0], version: '2026.06' });
    const [oldWindow] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: old.id, month: 12, window_key: DEC, title: 'old', visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
    await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: oldWindow.id, product_id: blindside.id, product_name: BLINDSIDE, role: 'post_emergent_spot', application_mode: 'spot',
      rate_unit: 'label_rate', default_in_plan: false, gates: JSON.stringify(GATES), annual_counter: JSON.stringify({ maxApplications: 2 }) });
  }

  describe('catalog rate', () => {
    test('an empty unit becomes oz and an empty default rate 0.149; one audit row; the second up writes nothing', async () => {
      await reset();
      await migration.up(knex);
      const row = await catalogRow();
      expect([row.rate_unit, Number(row.default_rate_per_1000)]).toEqual(['oz', 0.149]);
      const [audit] = await audits(migration.ACTION_CATALOG);
      expect(Object.keys(parse(audit.after_snapshot).fields).sort()).toEqual(['default_rate_per_1000', 'rate_unit']);
      const after = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(after);
    });

    test('production state (0.149 oz) writes nothing and no audit row for the catalog', async () => {
      await reset({ catalog: { default_rate_per_1000: 0.149, rate_unit: 'oz' } });
      await migration.up(knex);
      expect(await audits(migration.ACTION_CATALOG)).toEqual([]);
      const row = await catalogRow();
      expect([row.rate_unit, Number(row.default_rate_per_1000)]).toEqual(['oz', 0.149]);
    });

    test.each([
      ['another rate in oz', { default_rate_per_1000: 0.2, rate_unit: 'oz' }, ['oz', 0.2]],
      ['a rate in another unit', { default_rate_per_1000: 5, rate_unit: 'fl oz' }, ['fl oz', 5]],
      ['an empty rate in another unit', { default_rate_per_1000: null, rate_unit: 'lb' }, ['lb', null]],
    ])('%s is someone\'s own number and stays', async (_label, catalog, expected) => {
      await reset({ catalog });
      await migration.up(knex);
      const row = await catalogRow();
      expect([row.rate_unit, row.default_rate_per_1000 == null ? null : Number(row.default_rate_per_1000)]).toEqual(expected);
      expect(await audits(migration.ACTION_CATALOG)).toEqual([]);
    });

    test('an empty rate with the unit already oz gets 0.149 and nothing else', async () => {
      await reset({ catalog: { default_rate_per_1000: null, rate_unit: 'oz' } });
      await migration.up(knex);
      const [audit] = await audits(migration.ACTION_CATALOG);
      expect(Object.keys(parse(audit.after_snapshot).fields)).toEqual(['default_rate_per_1000']);
    });

    test('the row is found through an exact alias when no catalog row carries the name', async () => {
      await reset({ alias: true });
      await migration.up(knex);
      const row = await knex('products_catalog').where({ id: ids.blindside }).first();
      expect([row.rate_unit, Number(row.default_rate_per_1000)]).toEqual(['oz', 0.149]);
    });

    test('no Blindside row and no alias: a log line, no write, the staged figures are still handled', async () => {
      await reset();
      await knex('lawn_protocol_products').update({ product_id: null });
      await knex('products_catalog').where({ name: BLINDSIDE }).del();
      await migration.up(knex);
      expect(log).toHaveBeenCalledWith(expect.stringContaining('no catalog row or alias for Blindside Herbicide'));
      expect(await audits(migration.ACTION_CATALOG)).toEqual([]);
      expect((await rows(JAN, BLINDSIDE)).map(figures)).toEqual([[1, 1], [1, 1]]);
    });
  });

  describe('one application a year on the staged rows', () => {
    let before;
    beforeAll(async () => { await reset(); before = await snapshot(); await migration.up(knex); });

    test('every non-retired Blindside row of a v13 protocol goes from 2 to 1 (gate and counter); everything else stays', async () => {
      for (const windowKey of [JAN, DEC]) for (const row of await rows(windowKey, BLINDSIDE)) expect(figures(row)).toEqual([1, 1]);
      for (const row of await rows(FEB, BLINDSIDE)) { expect(parse(row.gates).retired).toBe(true); expect(figures(row)).toEqual([2, 2]); }
      for (const row of await rows(JAN, CELSIUS)) expect(figures(row)).toEqual([2, 2]);
      for (const row of await rows(DEC, BLINDSIDE, '2026.06')) expect(figures(row)).toEqual([2, 2]);
      const row = (await rows(JAN, BLINDSIDE))[0];
      expect(parse(row.gates)).toEqual({ trigger: 'celsius_annual_cap_reached', annualMaxApps: 1 });
    });

    test('one audit row per protocol lists the changed rows', async () => {
      const found = await audits(migration.ACTION_CAP);
      expect(found).toHaveLength(KEYS.length);
      for (const audit of found) {
        const after = parse(audit.after_snapshot);
        expect(after.cap).toBe(1);
        expect(after.rows).toHaveLength(2);
        expect(after.rows.every((r) => r.gate && r.counter)).toBe(true);
      }
    });

    test('a second up writes nothing', async () => {
      const after = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(after);
    });

    test('down restores the exact starting state', async () => {
      await migration.down(knex);
      expect(await snapshot()).toBe(before);
      expect(await audits(migration.ACTION_CAP)).toEqual([]);
      await migration.up(knex);
    });
  });

  describe('edits and guards', () => {
    test('only a figure that holds exactly 2 changes: an edited gate or counter stays, the other figure of the row still changes', async () => {
      await reset();
      const [row] = await rows(JAN, BLINDSIDE);
      await knex('lawn_protocol_products').where({ id: row.id }).update({ gates: JSON.stringify({ ...GATES, annualMaxApps: 3 }) });
      await migration.up(knex);
      expect(figures((await rows(JAN, BLINDSIDE))[0])).toEqual([3, 1]);
      await migration.down(knex);
      expect(figures((await rows(JAN, BLINDSIDE))[0])).toEqual([3, 2]);
    });

    test('a row matched by the product id under another name is handled too', async () => {
      await reset();
      await knex('lawn_protocol_products').where({ lawn_protocol_window_id: (await rows(DEC, BLINDSIDE))[0].lawn_protocol_window_id }).update({ product_name: 'Blindside (renamed)' });
      await migration.up(knex);
      expect(figures((await rows(DEC, 'Blindside (renamed)'))[0])).toEqual([1, 1]);
    });

    test('down leaves a figure somebody has changed since and a row they deleted', async () => {
      await reset();
      await migration.up(knex);
      const [edited, gone] = await rows(JAN, BLINDSIDE);
      await knex('lawn_protocol_products').where({ id: edited.id }).update({ annual_counter: JSON.stringify({ maxApplications: 5 }) });
      await knex('lawn_protocol_products').where({ id: gone.id }).del();
      await migration.down(knex);
      expect(figures((await rows(JAN, BLINDSIDE))[0])).toEqual([2, 5]);
      expect(await audits(migration.ACTION_CAP)).toEqual([]);
    });

    test('down does nothing while a visit references a v13 protocol, and finishes once it does not', async () => {
      await reset();
      await migration.up(knex);
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0][0], lawn_protocol_version: V13 });
      try {
        await migration.down(knex);
        expect(figures((await rows(JAN, BLINDSIDE))[0])).toEqual([1, 1]);
        expect(await audits(migration.ACTION_CAP)).toHaveLength(KEYS.length);
        expect((await catalogRow()).rate_unit).toBe('oz');
        expect(log).toHaveBeenCalledWith(expect.stringContaining('the catalog rate and the staged figures stay'));
      } finally {
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
      await migration.down(knex);
      expect(figures((await rows(JAN, BLINDSIDE))[0])).toEqual([2, 2]);
      expect((await catalogRow()).rate_unit).toBeNull();
    });

    test('down restores a catalog field only while it still holds the written value', async () => {
      await reset();
      await migration.up(knex);
      await knex('products_catalog').where({ id: ids.blindside }).update({ default_rate_per_1000: 0.2 });
      await migration.down(knex);
      const row = await catalogRow();
      expect([row.rate_unit, Number(row.default_rate_per_1000)]).toEqual([null, 0.2]);
    });

    test('a database without the staged tables only gets the catalog write', async () => {
      await reset();
      await knex.raw('ALTER TABLE ??.lawn_protocol_products RENAME TO lawn_protocol_products_away', [owned.schema]);
      try { await migration.up(knex); } finally { await knex.raw('ALTER TABLE ??.lawn_protocol_products_away RENAME TO lawn_protocol_products', [owned.schema]); }
      expect((await catalogRow()).rate_unit).toBe('oz');
      expect(await audits(migration.ACTION_CAP)).toEqual([]);
    });
  });

  describe('the older downs after this migration', () => {
    async function fabricate(action, afterSnapshot, row) {
      await knex('lawn_protocol_audit_log').insert({ lawn_protocol_id: null, actor_name: 'fixture', entity_type: 'protocol', entity_id: row.id, action,
        changed_fields: JSON.stringify(['products']), before_snapshot: JSON.stringify({}), after_snapshot: JSON.stringify(afterSnapshot), metadata: JSON.stringify({}) });
    }

    test('20261007175000, 20261007177000 and 20261007179000 skip a row at 1 (nothing deleted, nothing wrongly restored)', async () => {
      await reset();
      await migration.up(knex);
      const [row] = await rows(JAN, BLINDSIDE);
      await fabricate('v13_count_caps_protocol_rows', { cap: 2, rows: [{ id: row.id, gate: true, counter: true }] }, row);
      await countCapsRows.down(knex);
      expect(figures((await rows(JAN, BLINDSIDE))[0])).toEqual([1, 1]);
      await fabricate(clamp._CLAMP_ACTION, {}, row);
      await knex('lawn_protocol_audit_log').where({ action: clamp._CLAMP_ACTION }).update({ before_snapshot: JSON.stringify({ rows: [{ id: row.id, gate: 3, counter: 3 }] }) });
      await clamp.down(knex);
      expect(figures((await rows(JAN, BLINDSIDE))[0])).toEqual([1, 1]);
      await fabricate('v13_blindside_protocol_row', { blindsideRows: [row.id], cap: 2 }, row);
      await blindsideRow.down(knex);
      expect(await knex('lawn_protocol_products').where({ id: row.id }).first()).toBeTruthy();
    });

    test('after this down() has put the 2 back, 20261007179000 deletes its inserted row as before and 20261007175000 removes its keys', async () => {
      await reset();
      await migration.up(knex);
      const [row] = await rows(JAN, BLINDSIDE);
      await fabricate('v13_count_caps_protocol_rows', { cap: 2, rows: [{ id: row.id, gate: true, counter: true }] }, row);
      await fabricate('v13_blindside_protocol_row', { blindsideRows: [row.id], cap: 2 }, row);
      await migration.down(knex);
      await blindsideRow.down(knex);
      expect(await knex('lawn_protocol_products').where({ id: row.id }).first()).toBeUndefined();
      const [other] = await rows(DEC, BLINDSIDE);
      await fabricate('v13_count_caps_protocol_rows', { cap: 2, rows: [{ id: other.id, gate: true, counter: true }] }, other);
      await countCapsRows.down(knex);
      expect(figures((await rows(DEC, BLINDSIDE)).find((r) => r.id === other.id))).toEqual([undefined, undefined]);
    });
  });
});
