// Lawn protocol v13: the fire ant add-on changes from Advion Fire Ant Bait to Topchoice Granular Insecticide
// (migration 20261009100000, owner 2026-10-09), through the real migration on PostgreSQL (cloned schema).
// Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned: the existing Topchoice catalog row gets only the label facts it lacks (restricted use, the 2 lb maximum, a label
// note, a watering rule where none is stored) with its approval, copy, price and re-entry text untouched; the product limit
// is inserted or tightened; each v13 protocol's April and October Advion row is retired (not deleted) and a Topchoice row
// stands beside it; the Advion catalog row is not touched; a second up changes nothing; with no Topchoice row nothing is
// written; down restores exactly, leaves a protocol a visit or a completion is pinned to, and never touches a value it did
// not write.
const { randomUUID } = require('crypto');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009100000_lawn_v13_fire_ant_granule');
const matrix = require('../models/migrations/20261007180000_lawn_v13_matrix_adds');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');
const { validateRule } = require('../services/service-report/lawn-watering-rule');
const { activeProtocolProducts } = require('../services/lawn-protocol-retired');

const GRANULE = migration.GRANULE;
const ADVION = matrix.ADVION;
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_fa_a', 'fixture_fa_b'];
const [APR, OCT] = migration.WINDOW_KEYS;
const JUL = 'jul_v13_inspect_spot';
const ADVION_GATES = { trigger: 'fire_ants_optional_add_on', optionalAddOn: true, officePrices: true };
const ADVION_ALIASES = ['Advion Fire Ant Insecticide Bait 25 lb.', 'Syngenta Advion Fire Ant Insecticide Bait 2 lb.'];
const TOPCHOICE_ALIASES = ['Topchoice', 'Topchoice BROADCAST', 'Topchoice fall app'];
const SEED_NOTE = 'Seeded for lawn outline estimate packets from verified product/label source.';
const CATALOG_TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products',
  'lawn_protocol_audit_log', 'lawn_protocol_service_completions', 'product_limits', 'lawn_protocol_product_actuals', 'service_products'];
const retired = (row) => (typeof row.gates === 'string' ? JSON.parse(row.gates) : row.gates).retired === true;
// The row as prod and a migrated database hold it before this migration (not approved by this change, priced, own copy).
const TOPCHOICE = {
  name: GRANULE, category: 'insecticide', product_type: 'pesticide', formulation: 'granular', active_ingredient: 'Fipronil 0.0143%', epa_reg_number: '432-1217',
  container_size: '50 lb', best_price: 91.55, needs_pricing: false, restricted_use: false, default_rate_per_1000: 2, rate_unit: 'lb', irrigation_required: true,
  approved_for_service_report: true, approved_for_public_page: true, approved_for_estimate_packet: true, content_status: 'approved_for_portal', customer_visibility: 'portal_only',
  public_summary: 'Topchoice may be used for documented fire ant history.', service_report_summary: 'Topchoice was used for fire ant management.',
  customer_precaution_summary: 'People and pets should remain off treated areas until the application has dried, unless the label or technician instructions require a longer interval.',
  reentry_summary: 'Follow the product label and technician service report before re-entering treated areas.',
  reentry_text: 'Follow the product label and technician service report before re-entering treated areas.', label_source_note: SEED_NOTE, active: true,
};
// Every column this migration promises not to touch.
const UNTOUCHED = ['name', 'epa_reg_number', 'best_price', 'needs_pricing', 'default_rate_per_1000', 'rate_unit', 'irrigation_required', 'approved_for_service_report', 'approved_for_public_page',
  'approved_for_estimate_packet', 'content_status', 'customer_visibility', 'public_summary', 'service_report_summary', 'customer_precaution_summary', 'reentry_summary', 'reentry_text', 'rei_hours', 'active'];

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 fire ant add-on (Topchoice) migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of CATALOG_TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    // LIKE copies no foreign keys; the protocol rows and limits are pinned to the product through them.
    for (const [table, constraint, suffix] of [
      ['product_limits', 'fixture_limits_product', ''], ['product_aliases', 'fixture_aliases_product', ''],
      ['service_products', 'fixture_sp_product', ' ON DELETE SET NULL'], ['lawn_protocol_products', 'fixture_lpp_product', ''],
    ]) {
      await knex.raw(`ALTER TABLE ??.?? ADD CONSTRAINT ${constraint} FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)${suffix}`, [owned.schema, table, owned.schema]);
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const granule = () => knex('products_catalog').where({ name: GRANULE }).first();
  const rowsIn = (windowKey, name) => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'w.window_key': windowKey, 'p.product_name': name, 'l.version': V13 })
    .orderBy(['l.protocol_key', 'p.id']).select('p.*', 'l.protocol_key');
  const ours = () => knex('lawn_protocol_audit_log').whereIn('action', [migration.ACTION, migration.CATALOG_ACTION]);
  const limits = (name) => knex('product_limits').whereIn('product_id', knex('products_catalog').where({ name }).select('id')).orderBy('id');
  const aliases = (name) => knex('product_aliases').whereIn('product_id', knex('products_catalog').where({ name }).select('id')).orderBy('alias_name').pluck('alias_name');
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  async function snapshot() {
    return clean([
      await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']), await knex('lawn_protocol_windows').orderBy('id'),
      await knex('products_catalog').orderBy('name'), await knex('product_aliases').orderBy('alias_name'), await knex('product_limits').orderBy('id'),
      await knex('lawn_protocol_audit_log').orderBy('id'),
    ]);
  }

  // A clean fixture: the catalog and two v13 protocols as 20261007180000 and its rounds leave them (Advion rows in
  // April and October, a decoy Advion row in July, a Headway row beside it), the existing Topchoice row (unless
  // `topchoice` is false), and an older protocol version.
  async function reset({ topchoice = true } = {}) {
    for (const table of ['service_products', 'lawn_protocol_product_actuals', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const [advion] = await knex('products_catalog').insert({
      name: ADVION, category: 'insecticide', formulation: 'granular', epa_reg_number: '100-1481', default_rate_per_1000: 0.0344, rate_unit: 'lb',
      approved_for_service_report: true, active: true,
    }).returning('*');
    const [headway] = await knex('products_catalog').insert({ name: matrix.HEAD, category: 'fungicide', active: true }).returning('*');
    ids.advion = advion.id; ids.headway = headway.id;
    for (const alias of ADVION_ALIASES) await knex('product_aliases').insert({ product_id: advion.id, alias_name: alias });
    await knex('product_limits').insert({ product_id: advion.id, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 4, limit_unit: 'applications', severity: 'hard_block' });
    if (topchoice) {
      const [top] = await knex('products_catalog').insert(TOPCHOICE).returning('*');
      ids.top = top.id;
      for (const alias of TOPCHOICE_ALIASES) await knex('product_aliases').insert({ product_id: top.id, alias_name: alias });
    }
    for (const key of KEYS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' });
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      for (const [windowKey, month] of [[APR, 4], [OCT, 10], [JUL, 7]]) {
        const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
        await knex('lawn_protocol_products').insert([
          { lawn_protocol_window_id: window.id, product_id: headway.id, product_name: matrix.HEAD, role: 'fungicide_spot', application_mode: 'spot', rate_unit: 'label_rate', default_in_plan: false, sort_order: 7, gates: JSON.stringify({ trigger: 'fixture' }) },
          { lawn_protocol_window_id: window.id, product_id: advion.id, product_name: ADVION, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 0.0344, rate_unit: 'lb', default_in_plan: false, sort_order: 9, gates: JSON.stringify(ADVION_GATES) },
        ]);
      }
    }
    const [old] = await knex('lawn_protocols').where({ protocol_key: KEYS[0], version: '2026.06' });
    const [oldWindow] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: old.id, month: 4, window_key: APR, title: APR, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
    await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: oldWindow.id, product_id: advion.id, product_name: ADVION, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 0.0344, rate_unit: 'lb', default_in_plan: false, sort_order: 9, gates: JSON.stringify(ADVION_GATES) });
  }

  describe('fresh path: the existing Topchoice row', () => {
    let before;
    let untouchedBefore;
    beforeAll(async () => {
      await reset();
      const top = await granule();
      untouchedBefore = Object.fromEntries(UNTOUCHED.map((column) => [column, top[column]]));
      before = {
        advion: clean(await knex('products_catalog').where({ name: ADVION })), advionAliases: await aliases(ADVION), advionLimits: clean(await limits(ADVION)),
        topAliases: await aliases(GRANULE),
      };
      await migration.up(knex);
    });

    test('the row gets restricted use, the 2 lb maximums and a label note appended to its own note; no row is inserted', async () => {
      expect(await knex('products_catalog').where({ name: GRANULE })).toHaveLength(1);
      const row = await granule();
      expect(row.id).toBe(ids.top);
      expect(row.restricted_use).toBe(true);
      expect([row.max_label_rate_per_1000, row.max_annual_per_1000].map(Number)).toEqual([2, 2]);
      expect(row.label_source_note).toBe(`${SEED_NOTE} ${migration.LABEL_NOTE}`);
      expect(row.label_source_note).toContain('Topchoice label, EPA Reg. No. 432-1217, accepted 2018-03-20');
    });

    test('a watering rule is stored where there was none: a valid water-in, sourced to the label sentence, program default amount', async () => {
      const row = await granule();
      expect(row.post_application_watering).toEqual(migration.WATERING_RULE);
      expect(validateRule(row.post_application_watering).valid).toBe(true);
      expect(row.post_application_watering).toMatchObject({ mode: 'water_in', water_in_inches: 0.25, water_in_by_hours: 24, source: 'label' });
    });

    test('nothing else on the row moves: approval flags, copy, precaution and re-entry text, price, rate, EPA number, aliases', async () => {
      const row = await granule();
      for (const column of UNTOUCHED) expect({ column, value: row[column] }).toEqual({ column, value: untouchedBefore[column] });
      expect(Number(row.best_price)).toBe(91.55);
      expect(row.customer_precaution_summary).toBe(TOPCHOICE.customer_precaution_summary);
      expect(await aliases(GRANULE)).toEqual(before.topAliases);
    });

    test('one product limit: at most 1 application a year, a hard block matched on the product', async () => {
      const rows = await limits(GRANULE);
      expect(rows).toHaveLength(1);
      expect(rows[0]).toMatchObject({ match_type: 'product', limit_type: 'annual_max_apps', limit_unit: 'applications', severity: 'hard_block' });
      expect(Number(rows[0].limit_value)).toBe(1);
      expect(rows[0].description).toMatch(/Topchoice label, EPA Reg\. No\. 432-1217, accepted 2018-03-20/);
    });

    test('every v13 protocol: the April and October Advion rows are retired (kept, with their id) and a Topchoice row stands beside each', async () => {
      for (const windowKey of [APR, OCT]) {
        const old = await rowsIn(windowKey, ADVION);
        expect(old).toHaveLength(KEYS.length);
        for (const row of old) {
          expect(retired(row)).toBe(true);
          expect(row.gates).toEqual({ ...ADVION_GATES, retired: true });
          expect(Number(row.rate_per_1000)).toBe(0.0344);
        }
        const added = await rowsIn(windowKey, GRANULE);
        expect(added).toHaveLength(KEYS.length);
        for (const row of added) {
          expect(row).toMatchObject({ product_id: ids.top, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_unit: 'lb', default_in_plan: false, carrier_gal_per_1000: null });
          expect(Number(row.rate_per_1000)).toBe(2);
          expect(row.gates).toEqual(ADVION_GATES);
          expect(row.sort_order).toBe(10);
          expect(retired(row)).toBe(false);
        }
      }
    });

    test('the planning readers see Topchoice and not Advion', async () => {
      for (const windowKey of [APR, OCT]) {
        const names = await activeProtocolProducts(knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
          .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id').where({ 'w.window_key': windowKey, 'l.version': V13 }), 'p').pluck('p.product_name');
        expect(names).toContain(GRANULE);
        expect(names).not.toContain(ADVION);
        expect(names).toContain(matrix.HEAD);
      }
    });

    test('nothing else moves: the July decoy Advion row, the Headway rows, the older protocol version and the Advion catalog row, aliases and limits', async () => {
      for (const row of await rowsIn(JUL, ADVION)) expect(row.gates).toEqual(ADVION_GATES);
      expect(await rowsIn(JUL, GRANULE)).toEqual([]);
      for (const windowKey of [APR, OCT, JUL]) for (const row of await rowsIn(windowKey, matrix.HEAD)) expect(row.gates).toEqual({ trigger: 'fixture' });
      const oldRows = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
        .where({ 'l.version': '2026.06', 'p.product_name': ADVION }).select('p.*');
      expect(oldRows).toHaveLength(1);
      expect(oldRows[0].gates).toEqual(ADVION_GATES);
      expect(clean(await knex('products_catalog').where({ name: ADVION }))).toBe(before.advion);
      expect(await aliases(ADVION)).toEqual(before.advionAliases);
      expect(clean(await limits(ADVION))).toBe(before.advionLimits);
    });

    test('audit: one protocol row each (2 retired, 2 inserted) and one catalog row with every column before and after, and the limit', async () => {
      const logs = await knex('lawn_protocol_audit_log').where({ action: migration.ACTION });
      expect(logs).toHaveLength(KEYS.length);
      for (const log of logs) {
        expect(log.after_snapshot.retired.map((r) => r.window).sort()).toEqual([APR, OCT].sort());
        expect(log.after_snapshot.inserted.map((r) => r.windowKey).sort()).toEqual([APR, OCT].sort());
      }
      const [catalog] = await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION });
      expect(catalog.after_snapshot.productId).toBe(ids.top);
      expect(catalog.after_snapshot.changes.map((c) => [c.column, c.before])).toEqual([
        ['restricted_use', false], ['max_label_rate_per_1000', null], ['max_annual_per_1000', null], ['label_source_note', SEED_NOTE], ['post_application_watering', null],
      ]);
      expect(catalog.after_snapshot.limits.inserted).toHaveLength(1);
    });

    test('a second up changes nothing: the same rows, the same audit rows', async () => {
      const first = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(first);
    });
  });

  describe('down', () => {
    beforeEach(async () => { await reset(); });

    test('restores every row exactly: the Advion rows un-retired, the Topchoice rows, limit and every written column back, all audit rows removed', async () => {
      const before = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).not.toBe(before);
      await migration.down(knex);
      expect(await snapshot()).toBe(before);
      expect(await ours()).toEqual([]);
      const row = await granule();
      expect(row).toBeDefined();
      expect(row).toMatchObject({ restricted_use: false, max_label_rate_per_1000: null, max_annual_per_1000: null, post_application_watering: null, label_source_note: SEED_NOTE });
      for (const windowKey of [APR, OCT]) for (const advion of await rowsIn(windowKey, ADVION)) expect(advion.gates).toEqual(ADVION_GATES);
    });

    test('up again after down puts the swap back; down again restores', async () => {
      await migration.up(knex);
      await migration.down(knex);
      await migration.up(knex);
      for (const row of await rowsIn(APR, GRANULE)) expect(row.product_name).toBe(GRANULE);
      for (const row of await rowsIn(APR, ADVION)) expect(retired(row)).toBe(true);
      await migration.down(knex);
      for (const row of await rowsIn(APR, ADVION)) expect(retired(row)).toBe(false);
      expect(await rowsIn(APR, GRANULE)).toEqual([]);
      expect((await granule()).restricted_use).toBe(false);
    });

    test('a visit pinned to one protocol leaves that protocol, its audit row and the catalog changes; the other protocol goes back', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await migration.up(knex);
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
      try {
        await migration.down(knex);
        expect((await rowsIn(APR, GRANULE)).map((r) => r.protocol_key)).toEqual([KEYS[0]]);
        expect((await rowsIn(APR, ADVION)).map((r) => [r.protocol_key, retired(r)])).toEqual([[KEYS[0], true], [KEYS[1], false]]);
        expect((await granule()).restricted_use).toBe(true);
        expect(await limits(GRANULE)).toHaveLength(1);
        expect(await knex('lawn_protocol_audit_log').where({ action: migration.ACTION })).toHaveLength(1);
        expect(await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION })).toHaveLength(1);
        expect(log).toHaveBeenCalledWith(expect.stringContaining(`rollback skipped for protocol ${KEYS[0]}`));
      } finally {
        log.mockRestore();
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
      await migration.down(knex);
      expect((await granule()).restricted_use).toBe(false);
      expect(await rowsIn(APR, GRANULE)).toEqual([]);
    });

    test('a completion on the protocol leaves it too', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await migration.up(knex);
      const [protocol] = await knex('lawn_protocols').where({ protocol_key: KEYS[1], version: V13 });
      await knex('lawn_protocol_service_completions').insert({ service_record_id: randomUUID(), lawn_protocol_id: protocol.id, protocol_key: KEYS[1], protocol_version: V13 });
      try {
        await migration.down(knex);
        expect((await rowsIn(OCT, GRANULE)).map((r) => r.protocol_key)).toEqual([KEYS[1]]);
        expect((await granule()).restricted_use).toBe(true);
      } finally {
        log.mockRestore();
        await knex('lawn_protocol_service_completions').del();
      }
    });

    test('a completion actual on a Topchoice protocol row leaves that protocol whole', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await migration.up(knex);
      const [row] = await rowsIn(APR, GRANULE);
      await knex('lawn_protocol_product_actuals').insert({ lawn_protocol_service_completion_id: randomUUID(), protocol_product_id: row.id, product_id: row.product_id, product_name: GRANULE });
      try {
        await migration.down(knex);
        expect((await rowsIn(APR, GRANULE)).map((r) => r.protocol_key)).toContain(row.protocol_key);
        expect(retired((await rowsIn(APR, ADVION)).find((r) => r.protocol_key === row.protocol_key))).toBe(true);
        expect((await granule()).restricted_use).toBe(true);
      } finally {
        log.mockRestore();
        await knex('lawn_protocol_product_actuals').del();
      }
    });

    // Every row, catalog column and audit row is as up() left it: nothing was deleted, restored or un-retired.
    async function expectLeftWhole(protocolKey, whole) {
      // By product id: one case renames the row.
      for (const windowKey of [APR, OCT]) {
        const rows = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
          .where({ 'w.window_key': windowKey, 'l.version': V13, 'l.protocol_key': protocolKey, 'p.product_id': ids.top }).select('p.id');
        expect(rows).toHaveLength(1);
      }
      for (const windowKey of [APR, OCT]) expect(retired((await rowsIn(windowKey, ADVION)).find((r) => r.protocol_key === protocolKey))).toBe(true);
      expect((await granule()).restricted_use).toBe(true);
      expect(await limits(GRANULE)).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.ACTION, lawn_protocol_id: whole })).toHaveLength(1);
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION })).toHaveLength(1);
    }
    const protocolIdOf = async (key) => (await knex('lawn_protocols').where({ protocol_key: key, version: V13 }).first('id')).id;

    test.each([
      ['its rate', { rate_per_1000: 1.5 }],
      ['its gates', { gates: JSON.stringify({ ...ADVION_GATES, officePrices: false }) }],
      ['its order', { sort_order: 3 }],
      ['its role', { role: 'insecticide_spot' }],
      ['its mode', { application_mode: 'spot' }],
      ['its default-in-plan flag', { default_in_plan: true }],
      ['its carrier', { carrier_gal_per_1000: 4 }],
      ['its mixing', { mixing: JSON.stringify({ note: 'staff' }) }],
      ['its name', { product_name: 'Renamed by an admin' }],
    ])('staff edited %s on an inserted Topchoice row (product name unchanged unless named): the whole protocol is left, nothing is deleted or un-retired', async (_label, edit) => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await migration.up(knex);
      const [edited] = await rowsIn(APR, GRANULE);
      const [other] = await rowsIn(APR, GRANULE).then((rows) => rows.filter((r) => r.protocol_key !== edited.protocol_key));
      await knex('lawn_protocol_products').where({ id: edited.id }).update(edit);
      const afterEdit = clean(await knex('lawn_protocol_products').where({ id: edited.id }));
      try {
        await migration.down(knex);
      } finally { log.mockRestore(); }
      // The edited row is exactly as the staff left it, and so is everything of its protocol.
      expect(clean(await knex('lawn_protocol_products').where({ id: edited.id }))).toBe(afterEdit);
      await expectLeftWhole(edited.protocol_key, await protocolIdOf(edited.protocol_key));
      // The other protocol was untouched by staff and goes back; the catalog changes stay (a protocol was left).
      expect((await rowsIn(APR, GRANULE)).map((r) => r.protocol_key)).not.toContain(other.protocol_key);
      expect(retired((await rowsIn(APR, ADVION)).find((r) => r.protocol_key === other.protocol_key))).toBe(false);
    });

    test('the skip is logged, and a later down after the staff edit is undone finishes the rollback', async () => {
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      await migration.up(knex);
      const [edited] = await rowsIn(OCT, GRANULE);
      await knex('lawn_protocol_products').where({ id: edited.id }).update({ rate_per_1000: 1.5 });
      try {
        await migration.down(knex);
        expect(log).toHaveBeenCalledWith(expect.stringContaining(`rollback skipped for protocol ${edited.protocol_key}: the Topchoice row was edited after it was inserted`));
      } finally { log.mockRestore(); }
      await knex('lawn_protocol_products').where({ id: edited.id }).update({ rate_per_1000: 2 });
      await migration.down(knex);
      expect(await rowsIn(OCT, GRANULE)).toEqual([]);
      expect((await granule()).restricted_use).toBe(false);
      expect(await ours()).toEqual([]);
    });

    test('a retired Advion row that staff edited (extra gate, or un-retired by hand) keeps the whole protocol', async () => {
      for (const edit of [(g) => ({ ...g, edited: true }), (g) => { const { retired: _r, ...rest } = g; return rest; }]) {
        await reset();
        const log = jest.spyOn(console, 'log').mockImplementation(() => {});
        await migration.up(knex);
        const [oldA] = await rowsIn(APR, ADVION);
        const gates = edit({ ...ADVION_GATES, retired: true });
        await knex('lawn_protocol_products').where({ id: oldA.id }).update({ gates: JSON.stringify(gates) });
        try {
          await migration.down(knex);
          expect(log).toHaveBeenCalledWith(expect.stringContaining('a retired Advion row was edited after it was retired'));
        } finally { log.mockRestore(); }
        expect((await knex('lawn_protocol_products').where({ id: oldA.id }).first()).gates).toEqual(gates);
        expect((await rowsIn(APR, GRANULE)).map((r) => r.protocol_key)).toContain(oldA.protocol_key);
        expect((await granule()).restricted_use).toBe(true);
      }
    });

    test('a Topchoice protocol row staff deleted, or an Advion row staff deleted, does not stop the rest from going back', async () => {
      await migration.up(knex);
      const [gone] = await rowsIn(APR, GRANULE);
      await knex('lawn_protocol_products').where({ id: gone.id }).del();
      const [advionGone] = await rowsIn(OCT, ADVION);
      await knex('lawn_protocol_products').where({ id: advionGone.id }).del();
      await migration.down(knex);
      expect(await rowsIn(APR, GRANULE)).toEqual([]);
      expect(await rowsIn(OCT, GRANULE)).toEqual([]);
      expect((await granule()).restricted_use).toBe(false);
      expect(await ours()).toEqual([]);
    });

    test('a catalog column edited since stays; the others go back', async () => {
      await migration.up(knex);
      const edited = `${SEED_NOTE} ${migration.LABEL_NOTE} Edited by staff.`;
      await knex('products_catalog').where({ name: GRANULE }).update({ label_source_note: edited, max_annual_per_1000: 3 });
      await migration.down(knex);
      const row = await granule();
      expect(row.label_source_note).toBe(edited);
      expect(Number(row.max_annual_per_1000)).toBe(3);
      expect(row).toMatchObject({ restricted_use: false, max_label_rate_per_1000: null, post_application_watering: null });
    });

    test('a limit edited since stays', async () => {
      await migration.up(knex);
      await knex('product_limits').whereIn('product_id', [ids.top]).update({ limit_value: 2 });
      await migration.down(knex);
      const [row] = await limits(GRANULE);
      expect(Number(row.limit_value)).toBe(2);
    });

    test('the catalog row itself is never deleted, whatever happened to it', async () => {
      await migration.up(knex);
      await knex('products_catalog').where({ name: GRANULE }).update({ best_price: 50 });
      await migration.down(knex);
      expect(await granule()).toBeDefined();
    });
  });

  describe('the Topchoice row already carries some of the facts', () => {
    beforeEach(async () => { await reset(); });

    test('a stored watering rule, a different maximum and restricted use already true are left as they are; the note and the limit are still added', async () => {
      const rule = { mode: 'hold', hold_hours: 1, source: 'owner', label_note: 'Owner edit.', verified_at: '2026-10-09T00:00:00.000Z', verified_by: 'owner' };
      await knex('products_catalog').where({ name: GRANULE }).update({ restricted_use: true, max_label_rate_per_1000: 2.5, max_annual_per_1000: 2.5, post_application_watering: JSON.stringify(rule) });
      await migration.up(knex);
      const row = await granule();
      expect(row.post_application_watering).toEqual(rule);
      expect([row.max_label_rate_per_1000, row.max_annual_per_1000].map(Number)).toEqual([2.5, 2.5]);
      expect(row.label_source_note).toBe(`${SEED_NOTE} ${migration.LABEL_NOTE}`);
      const [log] = await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION });
      expect(log.after_snapshot.changes.map((c) => c.column)).toEqual(['label_source_note']);
      await migration.down(knex);
      expect((await granule()).post_application_watering).toEqual(rule);
      expect((await granule()).label_source_note).toBe(SEED_NOTE);
    });

    test('a row that already holds every fact and a hard block writes no catalog audit row and no second limit', async () => {
      await knex('products_catalog').where({ name: GRANULE }).update({ restricted_use: true, max_label_rate_per_1000: 2, max_annual_per_1000: 2, label_source_note: migration.LABEL_NOTE, post_application_watering: JSON.stringify(migration.WATERING_RULE) });
      await knex('product_limits').insert({ product_id: ids.top, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 1, limit_unit: 'applications', severity: 'hard_block', description: 'Owner row.' });
      await migration.up(knex);
      expect(await knex('lawn_protocol_audit_log').where({ action: migration.CATALOG_ACTION })).toEqual([]);
      const rows = await limits(GRANULE);
      expect(rows).toHaveLength(1);
      expect(rows[0].description).toBe('Owner row.');
      for (const row of await rowsIn(APR, GRANULE)) expect(row.product_id).toBe(ids.top);
    });

    test('a weaker existing limit (4 a year, not a hard block) is tightened to 1 hard block, and down puts it back', async () => {
      await knex('product_limits').insert({ product_id: ids.top, match_type: 'product', limit_type: 'annual_max_apps', limit_value: 4, limit_unit: 'applications', severity: 'warning', description: 'Hand-written.' });
      await migration.up(knex);
      const [tight] = await limits(GRANULE);
      expect(Number(tight.limit_value)).toBe(1);
      expect(tight.severity).toBe('hard_block');
      await migration.down(knex);
      const [back] = await limits(GRANULE);
      expect(Number(back.limit_value)).toBe(4);
      expect(back).toMatchObject({ severity: 'warning', description: 'Hand-written.' });
    });

    test('a row that is only reachable through an alias is resolved, and the protocol rows point at it', async () => {
      await knex('products_catalog').where({ name: GRANULE }).update({ name: 'Topchoice (SiteOne title)' });
      await knex('product_aliases').insert({ product_id: ids.top, alias_name: GRANULE });
      await migration.up(knex);
      expect(await knex('products_catalog').where({ name: GRANULE })).toEqual([]);
      for (const row of await rowsIn(APR, GRANULE)) expect(row.product_id).toBe(ids.top);
      expect((await knex('products_catalog').where({ id: ids.top }).first()).restricted_use).toBe(true);
    });
  });

  describe('protocols the migration does not own', () => {
    test('no Topchoice row in the catalog: nothing is written, the Advion rows stay in the plan, and it says so', async () => {
      await reset({ topchoice: false });
      const log = jest.spyOn(console, 'log').mockImplementation(() => {});
      const before = await snapshot();
      try {
        await migration.up(knex);
        expect(log).toHaveBeenCalledWith(expect.stringContaining('Topchoice Granular Insecticide not found in the catalog: nothing written'));
      } finally { log.mockRestore(); }
      expect(await snapshot()).toBe(before);
      expect(await ours()).toEqual([]);
      expect(await granule()).toBeUndefined();
      for (const row of await rowsIn(APR, ADVION)) expect(retired(row)).toBe(false);
    });

    test('no v13 protocol: nothing is written, not even the catalog changes', async () => {
      await reset();
      await knex('lawn_protocol_products').del(); await knex('lawn_protocol_windows').del(); await knex('lawn_protocols').where({ version: V13 }).del();
      await migration.up(knex);
      expect((await granule()).restricted_use).toBe(false);
      expect(await ours()).toEqual([]);
    });

    test('a window without an active Advion row gets no Topchoice row; an Advion row already retired by hand is skipped; the other protocol still swaps', async () => {
      await reset();
      const [aprA, aprB] = await rowsIn(APR, ADVION);
      await knex('lawn_protocol_products').where({ id: aprA.id }).update({ gates: JSON.stringify({ ...ADVION_GATES, retired: true }) });
      await knex('lawn_protocol_products').where({ id: aprB.id }).del();
      const [octA] = await rowsIn(OCT, ADVION);
      await migration.up(knex);
      expect(await rowsIn(APR, GRANULE)).toEqual([]);
      expect(await rowsIn(OCT, GRANULE)).toHaveLength(KEYS.length);
      expect((await knex('lawn_protocol_products').where({ id: aprA.id }).first()).gates).toEqual({ ...ADVION_GATES, retired: true });
      expect(retired(await knex('lawn_protocol_products').where({ id: octA.id }).first())).toBe(true);
    });

    test('a window that already has a Topchoice row gets no second one, and its Advion row is still retired', async () => {
      await reset();
      const [aprA] = await rowsIn(APR, ADVION);
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: aprA.lawn_protocol_window_id, product_id: ids.top, product_name: GRANULE, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 2, rate_unit: 'lb', default_in_plan: false, sort_order: 20, gates: JSON.stringify(ADVION_GATES) });
      await migration.up(knex);
      expect((await rowsIn(APR, GRANULE)).filter((r) => r.protocol_key === aprA.protocol_key)).toHaveLength(1);
      expect(retired(await knex('lawn_protocol_products').where({ id: aprA.id }).first())).toBe(true);
    });
  });
});
