// Lawn protocol v13 field rules round 7 (20261007158000) on PostgreSQL (cloned schema): a Dismiss
// row a completion actual references is retired from the window's products without losing the
// link, and the staged window goals stop naming the repeat sedge spots. Synthetic data only.
const { randomUUID } = require('crypto');
const { createLawnHistoryDb } = require('./helpers/lawn-history-db');
const { getProtocolWindowContext, summarizeProtocolContext } = require('../services/lawn-protocol-operating-layer');
const migration = require('../models/migrations/20261007158000_lawn_v13_field_rules_round7');

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;
const V13 = '2026.10-v13';
const DISMISS = 'Dismiss 64 oz';
const VELISTA = 'Velista';
const TABLES = ['products_catalog', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
  'lawn_protocol_audit_log', 'lawn_protocol_product_actuals'];

describeDb('v13 field rules round 7 through PostgreSQL', () => {
  let owned;
  let knex;
  let protocol;
  let november;
  let december;
  let dismissRow;
  let velistaRow;
  let actualId;

  const goalOf = async (id) => (await knex('lawn_protocol_windows').where({ id }).first('goal')).goal;
  const novemberContext = () => getProtocolWindowContext(knex, { serviceDate: new Date('2026-11-12T17:00:00Z'), grassTrack: 'bermuda', region: 'swfl', planning: true, windowKey: 'nov_v13_spreader_feeding', protocolKey: 'fixture_round7', protocolVersion: V13 });

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    [protocol] = await knex('lawn_protocols').insert({
      protocol_key: 'fixture_round7', version: V13, name: 'Fixture', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01',
    }).returning('*');
    const window = (month, key, goal) => knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: key, title: key, visit_type: 'x', goal }).returning('*').then((r) => r[0]);
    november = await window(11, 'nov_v13_spreader_feeding', 'One spreader feeding; mapped large patch spots; repeat sedge spots.');
    december = await window(12, 'dec_v13_spreader_feeding', 'One spreader feeding; active large patch, weed and repeat sedge spots.');
    const row = (name, changes = {}) => knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: november.id, product_name: name, role: 'x', application_mode: 'spot', default_in_plan: false, gates: JSON.stringify({}), sort_order: 1, ...changes,
    }).returning('*').then((r) => r[0]);
    dismissRow = await row(DISMISS, { sort_order: 9, gates: JSON.stringify({ novToMarOnly: true }) });
    velistaRow = await row(VELISTA);
    [{ id: actualId }] = await knex('lawn_protocol_product_actuals').insert({
      lawn_protocol_service_completion_id: randomUUID(), protocol_product_id: dismissRow.id, product_name: DISMISS, role: 'x', actual_rate_per_1000: 0.1, actual_rate_unit: 'fl oz',
    }).returning('id');
  });
  afterAll(async () => { if (owned) await owned.dispose(); });

  test('before: the window offers Dismiss', async () => {
    expect((await novemberContext()).products.map((p) => p.product_name)).toEqual(expect.arrayContaining([DISMISS, VELISTA]));
  });

  test('up retires the referenced row in place, and the plan context no longer offers it', async () => {
    await migration.up(knex);
    const stored = await knex('lawn_protocol_products').where({ id: dismissRow.id }).first();
    expect(stored.gates).toEqual({ novToMarOnly: true, retired: true });
    const context = await novemberContext();
    expect(context.products.map((p) => p.product_name)).toEqual([VELISTA]);
    expect(summarizeProtocolContext(context).products.map((p) => p.protocolProductName)).toEqual([VELISTA]);
    expect((await knex('lawn_protocol_products').where({ id: velistaRow.id }).first()).gates).toEqual({});
  });

  test('the historical actual keeps its link, name and rates', async () => {
    const actual = await knex('lawn_protocol_product_actuals').where({ id: actualId }).first();
    expect(actual).toMatchObject({ protocol_product_id: dismissRow.id, product_name: DISMISS, actual_rate_unit: 'fl oz' });
    expect(Number(actual.actual_rate_per_1000)).toBeCloseTo(0.1);
  });

  test('the window goals drop the repeat sedge spots, as the recipe does', async () => {
    expect(await goalOf(november.id)).toBe('One spreader feeding; mapped large patch spots.');
    expect(await goalOf(december.id)).toBe('One spreader feeding; active large patch and weed spots.');
    expect(migration.editedGoal('One spreader feeding; light weed spots.')).toBe('One spreader feeding; light weed spots.');
  });

  test('a second up changes nothing and writes no second audit row', async () => {
    await migration.up(knex);
    expect(await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules_r7' })).toHaveLength(1);
  });

  test('down un-retires only while still retired and restores a goal only while it reads what up wrote', async () => {
    await knex('lawn_protocol_windows').where({ id: december.id }).update({ goal: 'Owner edited December goal.' });
    await migration.down(knex);
    expect((await knex('lawn_protocol_products').where({ id: dismissRow.id }).first()).gates).toEqual({ novToMarOnly: true });
    expect(await goalOf(november.id)).toBe('One spreader feeding; mapped large patch spots; repeat sedge spots.');
    expect(await goalOf(december.id)).toBe('Owner edited December goal.');
    expect(await knex('lawn_protocol_audit_log').where({ action: 'v13_field_rules_r7' })).toHaveLength(0);
    expect((await novemberContext()).products.map((p) => p.product_name)).toEqual(expect.arrayContaining([DISMISS]));
  });
});
