// Lawn protocol v13, final advisor pass (migration 20261009150000, owner 2026-10-09), through the real migration on PostgreSQL
// (cloned schema). Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned: every active Blindside row at its staged state becomes 0.115 oz (a retired row, and a row with another rate, are not
// touched); November gets the December weed rows in their exact shape (Blindside at 0.115 oz); insert-if-missing; no Pythium row is
// written (the Pythium pair stays Artavia twice, recipe text only); an unresolvable product skips its write with a log; a second up
// changes nothing; down restores exactly and leaves a protocol that a visit, a completion, an edit or a completion actual holds;
// the older Blindside down() (20261007179000) still works with the new rate on the row.
const { randomUUID } = require('crypto');
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const migration = require('../models/migrations/20261009150000_lawn_v13_final_pass');
const blindsideRowMigration = require('../models/migrations/20261007179000_lawn_v13_blindside_protocol_row');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');

const V13 = staged.V13_VERSION;
const N = staged.NAMES;
const { BLINDSIDE, WINDOWS } = migration;
const KEYS = [['fixture_fp_a', 'st_augustine'], ['fixture_fp_b', 'bahia']];
const JAN = 'jan_v13_pre_m_hose';
const FEB = 'feb_v13_spreader_green_up';
const JUN = 'jun_v13_hose_blackout';
const MONTHS = [[JAN, 1], [FEB, 2], [JUN, 6], [WINDOWS.NOV, 11], [WINDOWS.DEC, 12]];
const TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_audit_log',
  'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'service_products'];
const CELSIUS_GATES = { stressGate: true, annualCounter: 'celsius_oz_per_1000', annualMaxApps: 2 };
const BLINDSIDE_GATES = { trigger: 'celsius_annual_cap_reached', annualMaxApps: 2 };
const parse = (value) => (typeof value === 'string' ? JSON.parse(value) : value);
const retired = (row) => parse(row.gates).retired === true;

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 final pass migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const rowsIn = (windowKey, name, version = V13) => knex('lawn_protocol_products as p')
    .join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
    .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'w.window_key': windowKey, 'p.product_name': name, 'l.version': version })
    .orderBy(['l.protocol_key', 'p.id']).select('p.*', 'l.protocol_key');
  const ours = () => knex('lawn_protocol_audit_log').where({ action: migration.ACTION });
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  const snapshot = async () => clean([
    await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']), await knex('lawn_protocol_windows').orderBy('id'),
    await knex('products_catalog').orderBy('name'), await knex('lawn_protocol_audit_log').orderBy('id'),
  ]);

  // Two v13 protocols as the earlier migrations leave them (the second is the bahia key: whatever the grass track), and an older version.
  async function reset({ without = [] } = {}) {
    for (const table of ['service_products', 'lawn_protocol_product_actuals', 'lawn_protocol_audit_log', 'lawn_protocol_products', 'lawn_protocol_windows',
      'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const names = [N.CEL, N.CER, N.NIS, BLINDSIDE, 'Headway Fungicide', N.VEL, N.ART];
    for (const name of names.filter((n) => !without.includes(n))) {
      const [made] = await knex('products_catalog').insert({ name, category: 'herbicide', active: true }).returning('*');
      ids[name] = made.id;
    }
    for (const [key, track] of KEYS) {
      await knex('lawn_protocols').insert({ protocol_key: key, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: track, region: 'swfl' });
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: track, region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      const window = {};
      for (const [windowKey, month] of MONTHS) {
        [window[windowKey]] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
      }
      const add = (windowKey, name, { gates, annual_counter: counter, report_copy: copy, ...fields }) => knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: window[windowKey].id, product_id: ids[name] || null, product_name: name, role: 'post_emergent_spot', application_mode: 'spot', default_in_plan: false,
        carrier_gal_per_1000: 1, mixing: JSON.stringify({}), ...fields,
        gates: JSON.stringify(gates || {}), annual_counter: JSON.stringify(counter || {}), report_copy: JSON.stringify(copy || { role: fields.role || 'post_emergent_spot' }),
      });
      // December, the shape November copies (the rows as 20261007179000 and the staging migration leave them).
      await add(WINDOWS.DEC, N.CEL, { rate_per_1000: 0.085, rate_unit: 'oz', gates: CELSIUS_GATES, annual_counter: { counter: 'celsius_oz_per_1000', maxApplications: 2 }, sort_order: 55 });
      await add(WINDOWS.DEC, N.CER, { rate_per_1000: 0.028, rate_unit: 'oz', gates: { tankMixWith: 'Celsius WG', annualMaxApps: 2 }, annual_counter: { maxApplications: 2 }, sort_order: 56 });
      await add(WINDOWS.DEC, N.NIS, { role: 'adjuvant_spot', rate_unit: 'label_rate', gates: { tankMixWith: 'Celsius WG', concentration: '0.25% v/v' }, report_copy: { role: 'adjuvant_spot' }, sort_order: 57 });
      await add(WINDOWS.DEC, BLINDSIDE, { rate_unit: 'label_rate', gates: BLINDSIDE_GATES, annual_counter: { maxApplications: 2 }, sort_order: 59 });
      // Blindside as staged in January (active) and February (retired).
      await add(JAN, BLINDSIDE, { rate_unit: 'label_rate', gates: BLINDSIDE_GATES, annual_counter: { maxApplications: 2 }, sort_order: 8 });
      await add(FEB, BLINDSIDE, { rate_unit: 'label_rate', gates: { ...BLINDSIDE_GATES, retired: true }, annual_counter: { maxApplications: 2 }, sort_order: 9 });
      // November: the three rows it has (nutrition, Velista, Gravex).
      await add(WINDOWS.NOV, 'Fixture nutrition', { role: 'nutrition', application_mode: 'broadcast', rate_unit: 'lb_n', default_in_plan: true, carrier_gal_per_1000: null, sort_order: 50 });
      await add(WINDOWS.NOV, N.VEL, { role: 'fungicide_spot', rate_unit: 'label_rate', carrier_gal_per_1000: 2, gates: { trigger: 'mapped_large_patch' }, sort_order: 51 });
      await add(WINDOWS.NOV, 'Gravex 20 EW', { role: 'fungicide_spot', rate_unit: 'label_rate', carrier_gal_per_1000: 2, gates: { trigger: 'dollar_spot_rust' }, sort_order: 52 });
    }
    // The older protocol version has the same Blindside row: it is not v13 and is never touched.
    const [old] = await knex('lawn_protocols').where({ protocol_key: KEYS[0][0], version: '2026.06' });
    const [oldWindow] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: old.id, month: 12, window_key: WINDOWS.DEC, title: 'old', visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
    await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: oldWindow.id, product_id: ids[BLINDSIDE], product_name: BLINDSIDE, role: 'post_emergent_spot', application_mode: 'spot', rate_unit: 'label_rate', default_in_plan: false });
  }

  describe('up', () => {
    let before;
    beforeAll(async () => { await reset(); before = await snapshot(); await migration.up(knex); });

    test('every active Blindside row at its staged state is 0.115 oz; the retired row and the older version are untouched', async () => {
      for (const windowKey of [JAN, WINDOWS.DEC]) {
        const rows = await rowsIn(windowKey, BLINDSIDE);
        expect(rows).toHaveLength(KEYS.length);
        for (const row of rows) {
          expect([Number(row.rate_per_1000), row.rate_unit]).toEqual([0.115, 'oz']);
          expect(row.gates).toEqual(BLINDSIDE_GATES);
        }
      }
      for (const row of await rowsIn(FEB, BLINDSIDE)) {
        expect(retired(row)).toBe(true);
        expect([row.rate_per_1000, row.rate_unit]).toEqual([null, 'label_rate']);
      }
      const [old] = await rowsIn(WINDOWS.DEC, BLINDSIDE, '2026.06');
      expect([old.rate_per_1000, old.rate_unit]).toEqual([null, 'label_rate']);
    });

    test('November gets the four December weed rows in the December shape, after its own rows, in the December order; Blindside at 0.115 oz', async () => {
      for (const [key] of KEYS) {
        const nov = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
          .where({ 'l.protocol_key': key, 'l.version': V13, 'w.window_key': WINDOWS.NOV }).orderBy('p.sort_order').select('p.*');
        expect(nov.map((r) => r.product_name)).toEqual(['Fixture nutrition', N.VEL, 'Gravex 20 EW', N.CEL, N.CER, N.NIS, BLINDSIDE]);
        expect(nov.map((r) => r.sort_order)).toEqual([50, 51, 52, 53, 54, 55, 56]);
        for (const row of nov.slice(3)) {
          const december = (await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
            .where({ 'l.protocol_key': key, 'l.version': V13, 'w.window_key': WINDOWS.DEC, 'p.product_name': row.product_name }).select('p.*'))[0];
          for (const column of ['product_id', 'role', 'application_mode', 'carrier_gal_per_1000', 'default_in_plan', 'gates', 'annual_counter', 'mixing', 'report_copy']) {
            expect({ name: row.product_name, column, value: row[column] }).toEqual({ name: row.product_name, column, value: december[column] });
          }
          expect(row.product_id).toBe(ids[row.product_name]);
          expect(row.default_in_plan).toBe(false);
          if (row.product_name === BLINDSIDE) expect([Number(row.rate_per_1000), row.rate_unit]).toEqual([0.115, 'oz']);
          else expect([row.rate_per_1000 == null ? null : Number(row.rate_per_1000), row.rate_unit]).toEqual([december.rate_per_1000 == null ? null : Number(december.rate_per_1000), december.rate_unit]);
        }
      }
    });

    test('no Pythium row is written: June has no Headway or other new row (the Pythium pair is recipe text only)', async () => {
      const june = await knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').where('w.window_key', JUN).select('p.*');
      expect(june).toEqual([]);
      expect(await knex('lawn_protocol_products').where({ product_name: 'Headway Fungicide' })).toEqual([]);
    });

    test('audit: one row per protocol with the ids and the values before and after', async () => {
      const logs = await ours();
      expect(logs).toHaveLength(KEYS.length);
      for (const log of logs) {
        const after = log.after_snapshot;
        expect(after.rates.map((r) => r.window).sort()).toEqual([JAN, WINDOWS.DEC].sort());
        for (const rate of after.rates) {
          expect(rate.before).toEqual({ rate_per_1000: null, rate_unit: 'label_rate' });
          expect(rate.after).toEqual({ rate_per_1000: 0.115, rate_unit: 'oz' });
        }
        expect(after.inserted.map((r) => r.kind)).toEqual(Array(4).fill('november_weed'));
        for (const made of after.inserted) expect(made.owned.product_name).toBe(made.product_name);
        expect(log.before_snapshot.rates).toHaveLength(2);
      }
    });

    test('a second up changes nothing: the same rows, the same audit rows', async () => {
      const first = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).toBe(first);
      expect(first).not.toBe(before);
    });
  });

  describe('what it will not write', () => {
    let log;
    beforeEach(() => { log = jest.spyOn(console, 'log').mockImplementation(() => {}); });
    afterEach(() => log.mockRestore());

    test('a product that cannot be resolved skips its own write with a log line; the rest is written', async () => {
      await reset({ without: [N.NIS] });
      await migration.up(knex);
      expect(await rowsIn(WINDOWS.NOV, N.NIS)).toEqual([]);
      expect(await rowsIn(WINDOWS.NOV, N.CEL)).toHaveLength(KEYS.length);
      expect(await rowsIn(WINDOWS.NOV, BLINDSIDE)).toHaveLength(KEYS.length);
      expect(log).toHaveBeenCalledWith(expect.stringContaining(`${N.NIS} not found in the catalog`));
    });

    test('an exact alias resolves a product whose catalog name changed', async () => {
      await reset();
      await knex('products_catalog').where({ id: ids[BLINDSIDE] }).update({ name: 'Blindside renamed away' });
      await knex('product_aliases').insert({ product_id: ids[BLINDSIDE], alias_name: BLINDSIDE });
      await migration.up(knex);
      expect((await rowsIn(WINDOWS.NOV, BLINDSIDE))[0].product_id).toBe(ids[BLINDSIDE]);
    });

    test('insert-if-missing: a November row that exists (even retired) is not duplicated; a Blindside row with another rate keeps it', async () => {
      await reset();
      const [protocolA] = await knex('lawn_protocols').where({ protocol_key: KEYS[0][0], version: V13 });
      const novA = await knex('lawn_protocol_windows').where({ lawn_protocol_id: protocolA.id, window_key: WINDOWS.NOV }).first();
      await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: novA.id, product_id: ids[N.CEL], product_name: N.CEL, role: 'post_emergent_spot', application_mode: 'spot', rate_per_1000: 0.085,
        rate_unit: 'oz', default_in_plan: false, gates: JSON.stringify({ retired: true }), sort_order: 53 });
      const janA = await knex('lawn_protocol_windows').where({ lawn_protocol_id: protocolA.id, window_key: JAN }).first();
      await knex('lawn_protocol_products').where({ lawn_protocol_window_id: janA.id, product_name: BLINDSIDE }).update({ rate_per_1000: 0.2, rate_unit: 'oz' });
      await migration.up(knex);
      const celsius = (await rowsIn(WINDOWS.NOV, N.CEL)).filter((r) => r.protocol_key === KEYS[0][0]);
      expect(celsius).toHaveLength(1);
      expect(retired(celsius[0])).toBe(true);
      const [jan] = (await rowsIn(JAN, BLINDSIDE)).filter((r) => r.protocol_key === KEYS[0][0]);
      expect([Number(jan.rate_per_1000), jan.rate_unit]).toEqual([0.2, 'oz']);
      expect(log).toHaveBeenCalledWith(expect.stringContaining('already states 0.2000 oz: left as it is'));
    });

    test('no December row to copy (retired there): November gets no row for that product', async () => {
      await reset();
      await knex('lawn_protocol_products').where({ product_name: N.NIS }).update({ gates: JSON.stringify({ retired: true }) });
      await migration.up(knex);
      expect(await rowsIn(WINDOWS.NOV, N.NIS)).toEqual([]);
      expect(await rowsIn(WINDOWS.NOV, N.CEL)).toHaveLength(KEYS.length);
    });

    test('no v13 protocol: nothing is written and nothing throws', async () => {
      await reset();
      await knex('lawn_protocols').where({ version: V13 }).del();
      await expect(migration.up(knex)).resolves.toBeUndefined();
      expect(await ours()).toEqual([]);
    });
  });

  describe('down', () => {
    let log;
    beforeEach(async () => { log = jest.spyOn(console, 'log').mockImplementation(() => {}); await reset(); });
    afterEach(() => log.mockRestore());

    test('restores every row exactly: the rates back, the inserted rows gone, every audit row removed; up again and down again work', async () => {
      const before = await snapshot();
      await migration.up(knex);
      expect(await snapshot()).not.toBe(before);
      await migration.down(knex);
      expect(await snapshot()).toBe(before);
      expect(await ours()).toEqual([]);
      await migration.up(knex);
      expect(await rowsIn(WINDOWS.NOV, BLINDSIDE)).toHaveLength(KEYS.length);
      await migration.down(knex);
      expect(await snapshot()).toBe(before);
    });

    test('a visit pinned to one protocol leaves that protocol and its audit row; the other protocol goes back', async () => {
      await migration.up(knex);
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0][0], lawn_protocol_version: V13 });
      try {
        await migration.down(knex);
        expect((await rowsIn(WINDOWS.NOV, BLINDSIDE)).map((r) => r.protocol_key)).toEqual([KEYS[0][0]]);
        expect((await rowsIn(JAN, BLINDSIDE)).map((r) => [r.protocol_key, Number(r.rate_per_1000) || null])).toEqual([[KEYS[0][0], 0.115], [KEYS[1][0], null]]);
        expect(await ours()).toHaveLength(1);
        expect(log).toHaveBeenCalledWith(expect.stringContaining(`rollback skipped for protocol ${KEYS[0][0]}`));
      } finally {
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
      await migration.down(knex);
      expect(await ours()).toEqual([]);
      expect(await rowsIn(WINDOWS.NOV, BLINDSIDE)).toEqual([]);
    });

    test('a completion on the protocol leaves it too', async () => {
      await migration.up(knex);
      const [protocol] = await knex('lawn_protocols').where({ protocol_key: KEYS[1][0], version: V13 });
      await knex('lawn_protocol_service_completions').insert({ service_record_id: randomUUID(), lawn_protocol_id: protocol.id, protocol_key: KEYS[1][0], protocol_version: V13 });
      try {
        await migration.down(knex);
        expect((await rowsIn(WINDOWS.NOV, N.CEL)).map((r) => r.protocol_key)).toEqual([KEYS[1][0]]);
        expect((await ours()).map((r) => r.lawn_protocol_id)).toEqual([protocol.id]);
      } finally {
        await knex('lawn_protocol_service_completions').del();
      }
    });

    // Every row and audit row is as up() left it: nothing was deleted or restored.
    async function expectLeftWhole(protocolKey, after) {
      const [protocol] = await knex('lawn_protocols').where({ protocol_key: protocolKey, version: V13 });
      await migration.down(knex);
      expect((await ours()).map((r) => r.lawn_protocol_id)).toEqual([protocol.id]);
      const mine = (await rowsIn(WINDOWS.NOV, BLINDSIDE)).filter((r) => r.protocol_key === protocolKey);
      expect(mine).toHaveLength(1);
      expect(clean(await knex('lawn_protocol_products').where('lawn_protocol_window_id', 'in', knex('lawn_protocol_windows').where({ lawn_protocol_id: protocol.id }).select('id')).orderBy('id'))).toBe(after);
    }
    const stateOf = async (protocolKey) => {
      const [protocol] = await knex('lawn_protocols').where({ protocol_key: protocolKey, version: V13 });
      return clean(await knex('lawn_protocol_products').where('lawn_protocol_window_id', 'in', knex('lawn_protocol_windows').where({ lawn_protocol_id: protocol.id }).select('id')).orderBy('id'));
    };

    test.each([
      ['an inserted row whose gate was edited', (key) => knex('lawn_protocol_products').where({ product_name: N.CEL })
        .whereIn('lawn_protocol_window_id', knex('lawn_protocol_windows').where({ window_key: WINDOWS.NOV }).whereIn('lawn_protocol_id', knex('lawn_protocols').where({ protocol_key: key, version: V13 }).select('id')).select('id'))
        .update({ gates: JSON.stringify({ ...CELSIUS_GATES, annualMaxApps: 3 }) })],
      ['an inserted row that was renamed', (key) => knex('lawn_protocol_products').where({ product_name: N.CER })
        .whereIn('lawn_protocol_window_id', knex('lawn_protocol_windows').where({ window_key: WINDOWS.NOV }).whereIn('lawn_protocol_id', knex('lawn_protocols').where({ protocol_key: key, version: V13 }).select('id')).select('id'))
        .update({ product_name: 'Certainty renamed' })],
      ['a Blindside rate that was edited', (key) => knex('lawn_protocol_products').where({ product_name: BLINDSIDE })
        .whereIn('lawn_protocol_window_id', knex('lawn_protocol_windows').where({ window_key: JAN }).whereIn('lawn_protocol_id', knex('lawn_protocols').where({ protocol_key: key, version: V13 }).select('id')).select('id'))
        .update({ rate_per_1000: 0.1 })],
    ])('%s leaves that whole protocol as it is; the other protocol goes back', async (_name, edit) => {
      await migration.up(knex);
      await edit(KEYS[0][0]);
      const after = await stateOf(KEYS[0][0]);
      await expectLeftWhole(KEYS[0][0], after);
      expect(await rowsIn(WINDOWS.NOV, BLINDSIDE).then((rows) => rows.map((r) => r.protocol_key))).toEqual([KEYS[0][0]]);
      expect(log).toHaveBeenCalledWith(expect.stringContaining('rollback skipped'));
    });

    test('a completion actual on an inserted row leaves that protocol whole', async () => {
      await migration.up(knex);
      const [row] = (await rowsIn(WINDOWS.NOV, N.CEL)).filter((r) => r.protocol_key === KEYS[0][0]);
      await knex('lawn_protocol_product_actuals').insert({ lawn_protocol_service_completion_id: randomUUID(), protocol_product_id: row.id, product_id: row.product_id, product_name: N.CEL });
      try {
        const after = await stateOf(KEYS[0][0]);
        await expectLeftWhole(KEYS[0][0], after);
      } finally {
        await knex('lawn_protocol_product_actuals').del();
      }
    });

    test('a row staff deleted is not a blocker: the rest still reverts', async () => {
      await migration.up(knex);
      await knex('lawn_protocol_products').where({ product_name: N.NIS }).whereIn('lawn_protocol_window_id', knex('lawn_protocol_windows').where({ window_key: WINDOWS.NOV }).select('id')).del();
      await migration.down(knex);
      expect(await ours()).toEqual([]);
      expect(await rowsIn(WINDOWS.NOV, BLINDSIDE)).toEqual([]);
      expect((await rowsIn(JAN, BLINDSIDE)).map((r) => r.rate_per_1000)).toEqual([null, null]);
    });
  });

  describe('the older Blindside migration (20261007179000) still works on a row with the new rate', () => {
    test('its down() deletes the row it inserted although the rate is now 0.115 oz (it reads gates, counter, default_in_plan and name, never the rate)', async () => {
      await reset();
      const [row] = (await rowsIn(WINDOWS.DEC, BLINDSIDE)).filter((r) => r.protocol_key === KEYS[0][0]);
      const [protocol] = await knex('lawn_protocols').where({ protocol_key: KEYS[0][0], version: V13 });
      await knex('lawn_protocol_audit_log').insert({
        lawn_protocol_id: protocol.id, entity_type: 'protocol', entity_id: protocol.id, action: 'v13_blindside_protocol_row', changed_fields: JSON.stringify(['products']),
        before_snapshot: JSON.stringify({}), after_snapshot: JSON.stringify({ blindsideRows: [row.id], cap: 2 }), metadata: JSON.stringify({}),
      });
      await migration.up(knex);
      expect(Number((await knex('lawn_protocol_products').where({ id: row.id }).first()).rate_per_1000)).toBe(0.115);
      await blindsideRowMigration.down(knex);
      expect(await knex('lawn_protocol_products').where({ id: row.id })).toEqual([]);
      // Its own rollback removed its audit row only; this migration's rows and audit rows stand.
      expect(await ours()).toHaveLength(KEYS.length);
      expect(await rowsIn(WINDOWS.NOV, BLINDSIDE)).toHaveLength(KEYS.length);
    });
  });
});
