// Lawn protocol v13 before the GATE_LAWN_V13 flip, through the real plan engine,
// the real application-limits reader and the two real migrations on PostgreSQL
// (cloned schema). Synthetic data only.
//
// 1. One yearly prodiamine cap across formulations (20261006140000): earlier
//    applications of any prodiamine product count toward the next one.
// 2. The 9x plan April step (20261006150000 + the recipe's cadenceVariants): the
//    visit's plan picks Dimension 0.21% 18-0-10 (9x) or the 24-0-11 (12x), the
//    same way in the plan, the completion defaults and the tank sheet.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const { buildPlanForService } = require('../services/waveguard-plan-engine');
const applicationLimits = require('../services/application-limits');
const capMigration = require('../models/migrations/20261006140000_lawn_v13_prodiamine_year_cap');
const aprilMigration = require('../models/migrations/20261006150000_lawn_v13_april_9x_branch');
const { LAWN_V13_VERSION } = require('../services/lawn-program');

const STW_4FL = 'LESCO Stonewall 4FL Prodiamine 40.7% Pre-Emergent Liquid Herbicide';
const STW_15 = 'LESCO Stonewall 0.43% 15-0-15 50% PolyPlus OPTI45 Pre-Emergent Plus Fertilizer';
const WDG = 'Prodiamine 65 WDG';
const F24 = 'LESCO 24-0-11 with PolyPlus OPTI';
const DIMENSION = aprilMigration.DIMENSION;
const GATES = ['GATE_LAWN_V13', 'GATE_LAWN_COMPLETION_DEFAULTS', 'GATE_LAWN_PROPERTY_HISTORY'];
const KEY = 'fixture_v13_preflip';

describe('prodiamine cap derivation (no database)', () => {
  const { aiPerRateUnit, CAP_LB_AI_PER_1000 } = capMigration;
  const cap = (row) => { const ai = aiPerRateUnit(row); return ai && { unit: ai.unit, value: Math.round((CAP_LB_AI_PER_1000 / ai.aiPerUnit) * 10000) / 10000 }; };

  test('the label cap (1.5 lb ai/acre) written in each product\'s own unit', () => {
    expect(cap({ name: STW_4FL, active_ingredient: 'Prodiamine', rate_unit: 'fl oz' })).toEqual({ unit: 'fl oz', value: 1.1019 });
    expect(cap({ name: WDG, active_ingredient: 'Prodiamine 65.0%', rate_unit: 'oz' })).toEqual({ unit: 'oz', value: 0.8476 });
    expect(cap({ name: STW_15, active_ingredient: 'Prodiamine', rate_unit: 'lb' })).toEqual({ unit: 'lb', value: 8.0082 });
    expect(cap({ name: 'LESCO Stonewall 0-0-7', active_ingredient: 'Prodiamine 0.43%', rate_unit: 'lb' })).toEqual({ unit: 'lb', value: 8.0082 });
  });

  test('a row with no stated strength or an unusable unit gets no cap row', () => {
    expect(aiPerRateUnit({ name: 'Prodiamine Mystery', active_ingredient: 'Prodiamine', rate_unit: 'lb' })).toBeNull();
    expect(aiPerRateUnit({ name: 'Prodiamine 65 WDG', active_ingredient: 'Prodiamine 65.0%', rate_unit: null })).toBeNull();
    expect(aiPerRateUnit({ name: 'Prodiamine 4L', active_ingredient: 'Prodiamine', rate_unit: 'gal' })).toBeNull();
  });

  test('the v13 season (January 4FL, October granular) is under the cap by design', () => {
    expect((0.5 / 1.1019) + (4.02 / 8.0082)).toBeLessThan(1);
  });
});

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 pre-flip fixes through PostgreSQL', () => {
  const saved = Object.fromEntries(GATES.map((name) => [name, process.env[name]]));
  let owned;
  let knex;
  const catalog = {};

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of ['technicians', 'products_catalog', 'product_aliases', 'lawn_protocol_product_substitutions',
      'equipment_systems', 'equipment_calibrations', 'municipality_ordinances', 'property_nutrient_ledger',
      'service_products', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_gates',
      'lawn_protocol_service_completions', 'lawn_protocol_product_actuals', 'lawn_protocol_audit_log', 'product_limits',
      'property_application_history', 'services']) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    const product = async (name, fields) => {
      const [row] = await knex('products_catalog').insert({
        name, category: 'herbicide', label_verified_at: new Date(), inventory_on_hand: 100000, inventory_unit: fields.rate_unit, active: true, ...fields,
      }).returning('*');
      catalog[name] = row;
      return row;
    };
    await product(STW_4FL, { active_ingredient: 'Prodiamine', formulation: 'liquid', default_rate_per_1000: 0.5, rate_unit: 'fl oz' });
    await product(STW_15, { active_ingredient: 'Prodiamine', formulation: 'granular', default_rate_per_1000: 4.02, rate_unit: 'lb', analysis_n: 15, analysis_p: 0, analysis_k: 15 });
    await product(WDG, { active_ingredient: 'Prodiamine 65.0%', formulation: 'WDG', default_rate_per_1000: 0.37, rate_unit: 'oz' });
    await product(F24, { category: 'fertilizer', formulation: 'granular', default_rate_per_1000: 4.2, rate_unit: 'lb', analysis_n: 24, analysis_p: 0, analysis_k: 11 });
    await product(DIMENSION, { active_ingredient: 'Dithiopyr', formulation: 'granular', default_rate_per_1000: 2.78, rate_unit: 'lb', analysis_n: 18, analysis_p: 0, analysis_k: 10 });

    await knex('lawn_protocols').insert({ protocol_key: KEY, version: '2026.06', name: 'Fixture old', status: 'active', grass_track: 'bermuda', region: 'swfl' });
    const [staged] = await knex('lawn_protocols').insert({ protocol_key: KEY, version: LAWN_V13_VERSION, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
    const windows = {};
    for (const [month, windowKey, mode, carrier] of [[1, 'jan_v13_pre_m_hose', 'main_reel_plus_spot_backpack', 1], [4, aprilMigration.APRIL_WINDOW, 'spreader_plus_spot_backpack', null], [10, 'oct_v13_spreader_fall', 'spreader_plus_spot_backpack', null]]) {
      [windows[month]] = await knex('lawn_protocol_windows').insert({
        lawn_protocol_id: staged.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: mode, default_carrier_gal_per_1000: carrier,
      }).returning('*');
    }
    const row = (window, name, fields) => knex('lawn_protocol_products').insert({
      lawn_protocol_window_id: windows[window].id, product_id: catalog[name].id, product_name: name, application_mode: 'broadcast', default_in_plan: true, ...fields,
    });
    await row(1, STW_4FL, { role: 'pre_emergent', rate_per_1000: 0.5, rate_unit: 'fl oz', carrier_gal_per_1000: 1, gates: JSON.stringify({ annualCounter: 'prodiamine_oz_per_1000' }) });
    await row(10, STW_15, { role: 'fall_pre_emergent_nutrition', rate_per_1000: 4.02, rate_unit: 'lb', gates: JSON.stringify({ targetN: '0.6 lb N/1000', annualCounter: 'prodiamine_oz_per_1000' }) });
    await row(4, F24, { role: 'nutrition', rate_unit: 'lb_n', sort_order: 1, gates: JSON.stringify({ targetN: '0.5 lb N/1000', blackoutSensitive: true, northPortBlocked: true }) });
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});

    // The real migrations, run over the fixture catalog and the fixture staged protocol.
    await capMigration.up(knex);
    await aprilMigration.up(knex);

    const [equipment] = await knex('equipment_systems').insert({ name: 'Fixture rig', system_type: 'skid', tank_capacity_gal: 110, active: true }).returning('*');
    await knex('equipment_calibrations').insert({ equipment_system_id: equipment.id, carrier_gal_per_1000: 1, active: true });
    await knex('services').insert([
      { service_key: 'lawn_care_6week', name: 'Every 6 Weeks Lawn Care Service', category: 'lawn_care' },
      { service_key: 'lawn_care_monthly', name: 'Monthly Lawn Care Service', category: 'lawn_care' },
    ]).catch(() => { /* a catalog row needing more columns: the visit's service_type carries the cadence instead */ });
  });
  afterAll(async () => { if (owned) await owned.dispose(); });
  afterEach(() => {
    for (const name of GATES) { if (saved[name] === undefined) delete process.env[name]; else process.env[name] = saved[name]; }
  });

  function setGates({ completion = 'off', history = 'off' } = {}) {
    process.env.GATE_LAWN_V13 = 'true';
    for (const [name, value] of [['GATE_LAWN_COMPLETION_DEFAULTS', completion], ['GATE_LAWN_PROPERTY_HISTORY', history]]) {
      if (value === 'on') process.env[name] = 'true'; else delete process.env[name];
    }
  }

  async function visit(scheduledDate, changes = {}) {
    const f = await fixture(knex);
    await knex('customers').where({ id: f.customerId }).update({ address_line1: f.property.address_line1, city: f.property.city, zip: f.property.zip, state: f.property.state, waveguard_tier: 'Silver' });
    await knex('customer_turf_profiles').insert({ customer_id: f.customerId, active: true, grass_type: 'bermuda', track_key: 'bermuda', lawn_sqft: 10000 });
    const scheduled = await f.visit(0, { scheduled_date: scheduledDate, ...changes });
    return { scheduled, customerId: f.customerId };
  }
  const applied = (customerId, name, date, rate, unit, extra = {}) => knex('property_application_history').insert({
    customer_id: customerId, product_id: catalog[name].id, application_date: date, application_rate: rate, rate_unit: unit,
    active_ingredient: catalog[name].active_ingredient, ...extra,
  });
  const plan = (scheduled, options = {}) => buildPlanForService(scheduled.id, { db: knex, includeCompletionDefaults: true, ...options });
  const item = (result, name) => result.mixCalculator.items.find((entry) => entry.product?.name === name);
  const codes = (result) => result.propertyGate.blocks.map((block) => block.code);
  const warningCodes = (result) => result.propertyGate.warnings.map((warning) => warning.code);

  describe('the migrations', () => {
    test('one cap row per prodiamine product in its own unit, none for another ingredient', async () => {
      const rows = await knex('product_limits').where({ match_type: 'active_ingredient' }).orderBy('limit_value');
      expect(rows.map((r) => [r.product_id, Number(r.limit_value), r.limit_unit, r.limit_type, r.severity, r.match_value])).toEqual([
        [catalog[WDG].id, 0.8476, 'oz/1000sf/year', 'annual_max_rate', 'hard_block', 'prodiamine'],
        [catalog[STW_4FL].id, 1.1019, 'fl oz/1000sf/year', 'annual_max_rate', 'hard_block', 'prodiamine'],
        [catalog[STW_15].id, 8.0082, 'lb/1000sf/year', 'annual_max_rate', 'hard_block', 'prodiamine'],
      ]);
    });

    test('every prodiamine catalog row carries a cap row (a new prodiamine product without one fails here)', async () => {
      const uncapped = await knex('products_catalog as pc')
        .whereRaw("pc.active_ingredient ILIKE 'prodiamine%'")
        .whereNotExists(knex('product_limits as pl').whereRaw('pl.product_id = pc.id').where({ match_type: 'active_ingredient', match_value: 'prodiamine' }))
        .select('pc.name');
      expect(uncapped).toEqual([]);
    });

    test('a second up changes nothing; down removes only its rows; up again restores them', async () => {
      const count = async () => Number((await knex('product_limits').where({ match_type: 'active_ingredient' }).count('* as n'))[0].n);
      const aprilRows = async () => Number((await knex('lawn_protocol_products').where({ product_name: DIMENSION }).count('* as n'))[0].n);
      await capMigration.up(knex); await aprilMigration.up(knex);
      expect([await count(), await aprilRows()]).toEqual([3, 1]);
      await aprilMigration.down(knex); await capMigration.down(knex);
      expect([await count(), await aprilRows()]).toEqual([0, 0]);
      expect((await knex('lawn_protocol_products').where({ product_name: F24 }).first()).gates).toEqual({ targetN: '0.5 lb N/1000', blackoutSensitive: true, northPortBlocked: true });
      await capMigration.up(knex); await aprilMigration.up(knex);
      expect([await count(), await aprilRows()]).toEqual([3, 1]);
    });

    test('April rows: the 9x row mirrors the 24-0-11 row and carries its plan; the 24-0-11 row is marked 12x', async () => {
      const rows = await knex('lawn_protocol_products').whereIn('product_name', [F24, DIMENSION]).orderBy('product_name');
      const dimension = rows.find((r) => r.product_name === DIMENSION);
      const f24 = rows.find((r) => r.product_name === F24);
      expect(dimension).toMatchObject({ product_id: catalog[DIMENSION].id, role: 'nutrition', rate_unit: 'lb_n', default_in_plan: true });
      expect(dimension.gates).toEqual({ targetN: '0.5 lb N/1000', blackoutSensitive: true, northPortBlocked: true, planVisitsPerYear: 9 });
      expect(f24.gates).toEqual({ targetN: '0.5 lb N/1000', blackoutSensitive: true, northPortBlocked: true, planVisitsPerYear: 12 });
    });
  });

  describe('the yearly prodiamine cap across formulations', () => {
    test('Prodiamine 65 WDG history near the cap blocks the January Stonewall 4FL: no amount, a block naming the cap', async () => {
      setGates();
      const { scheduled, customerId } = await visit('2026-01-12');
      await applied(customerId, WDG, '2026-01-05', 0.8, 'oz');
      const result = await plan(scheduled);
      expect(codes(result)).toContain('lawn_v13_annual_limit');
      const block = result.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit');
      expect(block.message).toMatch(/prodiamine across all products this year is 94\.4% of the yearly label cap; this application brings it to 139\.8% — THIS APPLICATION WOULD EXCEED IT/);
      expect(item(result, STW_4FL).mix).toBeNull();
      expect(item(result, STW_4FL).unavailable.reason).toMatch(/application limit is reached/);
      expect(result.status).toBe('blocked');
    });

    test('January 4FL plus October granular at the v13 rates stays under: the October plan computes 40.2 lb with no cap block or warning', async () => {
      setGates();
      const { scheduled, customerId } = await visit('2026-10-12');
      await applied(customerId, STW_4FL, '2026-01-12', 0.5, 'fl oz');
      const result = await plan(scheduled);
      expect(codes(result)).not.toContain('lawn_v13_annual_limit');
      expect(result.propertyGate.warnings.some((w) => /yearly label cap/.test(w.message))).toBe(false);
      expect(item(result, STW_15).mix).toMatchObject({ amount: 40.2 });
    });

    test('two formulations add up: 69% already used plus the October granular is 119%, a block', async () => {
      setGates();
      const { scheduled, customerId } = await visit('2026-10-12');
      await applied(customerId, WDG, '2026-03-02', 0.2, 'oz'); // 23.6%
      await applied(customerId, STW_4FL, '2026-01-12', 0.5, 'fl oz'); // 45.4%
      const result = await plan(scheduled);
      expect(codes(result)).toContain('lawn_v13_annual_limit');
      expect(result.propertyGate.blocks.find((b) => b.code === 'lawn_v13_annual_limit').message).toMatch(/is 69% of the yearly label cap; this application brings it to 119\.2%/);
      expect(item(result, STW_15).mix).toBeNull();
    });

    test('a season already at 82.6% of the cap warns (no application being planned) and does not block', async () => {
      const { customerId } = await visit('2026-10-20');
      await applied(customerId, WDG, '2026-03-02', 0.7, 'oz');
      const result = await applicationLimits.checkLimits(customerId, catalog[STW_4FL].id, new Date('2026-10-20T16:00:00Z'), knex);
      expect(result.blocks).toEqual([]);
      expect(result.warnings[0]).toMatchObject({ type: 'annual_max_rate', current: 82.6 });
      expect(result.warnings[0].message).toMatch(/across all products this year is 82\.6% of the yearly label cap\./);
    });

    test('checkLimits without a proposed application (completion, the compliance page) sizes the season only: 95.6% after January plus October warns, never blocks', async () => {
      const { customerId } = await visit('2026-10-20');
      await applied(customerId, STW_4FL, '2026-01-12', 0.5, 'fl oz');
      await applied(customerId, STW_15, '2026-10-12', 4.02, 'lb');
      const result = await applicationLimits.checkLimits(customerId, catalog[STW_15].id, new Date('2026-10-20T16:00:00Z'), knex);
      expect(result.blocks).toEqual([]);
      expect(result.warnings).toEqual([expect.objectContaining({ type: 'annual_max_rate', current: 95.6, max: 100 })]);
    });

    test('earlier applications are sized from the recorded rate, else quantity over area, else the standard rate', async () => {
      const { customerId } = await visit('2026-10-20');
      await applied(customerId, WDG, '2026-02-01', null, null, { quantity_applied: 4.2, quantity_unit: 'oz', area_treated_sqft: 5000 }); // 0.84 oz/1000 = 99.1%
      const byQuantity = await applicationLimits.checkLimits(customerId, catalog[STW_4FL].id, new Date('2026-10-20T16:00:00Z'), knex);
      expect(byQuantity.blocks).toEqual([]);
      expect(byQuantity.warnings[0]).toMatchObject({ current: 99.1 });
      const { customerId: other } = await visit('2026-10-20');
      await applied(other, STW_4FL, '2026-02-01', null, null); // standard 0.5 fl oz = 45.4%, flagged
      const byDefault = await applicationLimits.checkLimits(other, catalog[STW_15].id, new Date('2026-10-20T16:00:00Z'), knex, { proposed: { ratePer1000: 4.02, unit: 'lb' } });
      expect(byDefault.blocks).toEqual([]);
      expect(byDefault.warnings).toEqual([]);
    });

    test('retracted rows and last year\'s rows do not count; the planned visit\'s own ledger rows are left out of a re-plan', async () => {
      const { scheduled, customerId } = await visit('2026-10-12');
      await applied(customerId, WDG, '2026-03-02', 0.84, 'oz', { retracted_at: new Date() });
      await applied(customerId, WDG, '2025-03-02', 0.84, 'oz');
      const [record] = await knex('service_records').insert({ customer_id: customerId, scheduled_service_id: scheduled.id, service_date: '2026-10-12', service_type: 'Lawn fixture' }).returning('*');
      await applied(customerId, STW_15, '2026-10-12', 4.02, 'lb', { service_record_id: record.id });
      const proposed = { ratePer1000: 4.02, unit: 'lb' };
      const date = new Date('2026-10-12T16:00:00Z');
      // The visit's own row (50.2%) plus the application planned again (50.2%) would read 100.4%.
      expect((await applicationLimits.checkLimits(customerId, catalog[STW_15].id, date, knex, { proposed })).blocks).toHaveLength(1);
      const excluded = await applicationLimits.checkLimits(customerId, catalog[STW_15].id, date, knex, { proposed, excludeScheduledServiceId: scheduled.id });
      expect(excluded.blocks).toEqual([]);
      expect(excluded.warnings).toEqual([]);
    });

    test('an earlier prodiamine application whose product has no cap row is named, never counted as nothing', async () => {
      const { customerId } = await visit('2026-10-20');
      const [stray] = await knex('products_catalog').insert({ name: 'Prodiamine Stray 1G', category: 'herbicide', active_ingredient: 'Prodiamine', rate_unit: 'lb', active: true }).returning('*');
      await knex('property_application_history').insert({ customer_id: customerId, product_id: stray.id, application_date: '2026-02-01', application_rate: 1, rate_unit: 'lb' });
      const result = await applicationLimits.checkLimits(customerId, catalog[STW_4FL].id, new Date('2026-10-20T16:00:00Z'), knex);
      expect(result.warnings[0].message).toMatch(/1 earlier application could not be sized and was not counted/);
    });
  });

  describe('the April step by the visit\'s plan', () => {
    test.each([['Every 6 Weeks Lawn Care Service', DIMENSION, 27.778, F24], ['Monthly Lawn Care Service', F24, 20.833, DIMENSION]])(
      '%s: plans %s (%s lb on 10,000 sq ft) and not %s',
      async (serviceType, expected, amount, other) => {
        setGates();
        const { scheduled } = await visit('2026-04-14', { service_type: serviceType });
        const result = await plan(scheduled);
        const selected = result.mixCalculator.items.filter((entry) => entry.selected && entry.product);
        expect(selected.map((entry) => entry.product.name)).toEqual([expected]);
        expect(item(result, expected).mix).toMatchObject({ amount, amountUnit: 'lb' });
        expect(item(result, other)).toBeUndefined();
        expect(warningCodes(result)).not.toContain('lawn_v13_plan_cadence_unknown');
      });

    test('the catalog service the visit is booked under outranks its service_type text', async () => {
      const nine = await knex('services').where({ service_key: 'lawn_care_6week' }).first();
      if (!nine) return; // the fixture catalog row needed more columns; the text path above covers the resolver
      setGates();
      const { scheduled } = await visit('2026-04-14', { service_type: 'Lawn Care', service_id: nine.id });
      const result = await plan(scheduled);
      expect(result.mixCalculator.items.filter((entry) => entry.selected && entry.product).map((entry) => entry.product.name)).toEqual([DIMENSION]);
    });

    test('an unknown plan keeps the 12x step (24-0-11) and the plan says so, naming the 9x product', async () => {
      setGates();
      const { scheduled } = await visit('2026-04-14', { service_type: 'Lawn fixture' });
      const result = await plan(scheduled);
      expect(result.mixCalculator.items.filter((entry) => entry.selected && entry.product).map((entry) => entry.product.name)).toEqual([F24]);
      const warning = result.propertyGate.warnings.find((w) => w.code === 'lawn_v13_plan_cadence_unknown');
      expect(warning.message).toContain(DIMENSION);
      expect(warning.message).toMatch(/keeps the 12x step/);
    });

    test('a retired 6x plan keeps the 12x step too, with no warning (its cadence is known)', async () => {
      setGates();
      const { scheduled } = await visit('2026-04-14', { service_type: 'Bi-Monthly Lawn Care Service' });
      const result = await plan(scheduled);
      expect(result.mixCalculator.items.filter((entry) => entry.selected && entry.product).map((entry) => entry.product.name)).toEqual([F24]);
      expect(warningCodes(result)).not.toContain('lawn_v13_plan_cadence_unknown');
    });

    test('other months never ask: a January visit on an unknown plan carries no cadence warning', async () => {
      setGates();
      const { scheduled } = await visit('2026-01-12', { service_type: 'Lawn fixture' });
      expect(warningCodes(await plan(scheduled))).not.toContain('lawn_v13_plan_cadence_unknown');
    });

    test('completion defaults prefill the plan\'s own product: Dimension on 9x, 24-0-11 on 12x', async () => {
      setGates({ completion: 'on', history: 'on' });
      for (const [serviceType, expected] of [['Every 6 Weeks Lawn Care Service', DIMENSION], ['Monthly Lawn Care Service', F24]]) {
        const { scheduled } = await visit('2026-04-14', { service_type: serviceType });
        const result = await plan(scheduled);
        expect(result.completionDefaults.items.map((entry) => entry.product.name)).toEqual([expected]);
        expect(result.completionDefaults.items[0].mix.amount).toBeGreaterThan(0);
      }
    });
  });
});
