// Lawn protocol v13, Topchoice fire ant add-on: the facts migration (20261009103000, Codex round 3 on #6160), through the real
// migrations on PostgreSQL (cloned schema) and the real limit checker. Synthetic data only. Self-skips without DATABASE_URL.
//
// Pinned:
//   1. the Topchoice catalog corrections and both count limits are global facts: after ANY partial or full rollback the product is
//      still restricted use with its rule, rates and both product-matched hard limits; only the v13 protocol rows revert;
//   2. every v13 April and October window that holds a Topchoice row holds exactly one ACTIVE row of the governed shape: a stale,
//      retired or duplicate row is never overwritten, a governed row is inserted beside it and a stale active row is retired;
//      legacy protocols' Topchoice rows are never read or changed;
//   3. ownPass is never missing on an active v13 Topchoice add-on row in any rollback state; pinned and staff-edited protocols stay whole.
const { createLawnHistoryDb, fixture } = require('./helpers/lawn-history-db');
const first = require('../models/migrations/20261009100000_lawn_v13_fire_ant_granule');
const followup = require('../models/migrations/20261009101000_lawn_v13_fire_ant_granule_followup');
const guard = require('../models/migrations/20261009102000_lawn_v13_fire_ant_granule_guard');
const facts = require('../models/migrations/20261009103000_lawn_v13_fire_ant_granule_facts');
const matrix = require('../models/migrations/20261007180000_lawn_v13_matrix_adds');
const staged = require('../models/migrations/20261005120000_lawn_protocol_v13_staged');
const limitChecker = require('../services/application-limits');

const GRANULE = first.GRANULE;
const ADVION = matrix.ADVION;
const V13 = staged.V13_VERSION;
const KEYS = ['fixture_ft_a', 'fixture_ft_b'];
const [APR, OCT] = first.WINDOW_KEYS;
const ADVION_GATES = { trigger: 'fire_ants_optional_add_on', optionalAddOn: true, officePrices: true };
const OWN_PASS_GATES = { ...ADVION_GATES, ownPass: true };
const SEED_NOTE = 'Seeded for lawn outline estimate packets from verified product/label source.';
const TABLES = ['products_catalog', 'product_aliases', 'lawn_protocols', 'lawn_protocol_windows', 'lawn_protocol_products', 'lawn_protocol_audit_log',
  'lawn_protocol_service_completions', 'product_limits', 'lawn_protocol_product_actuals', 'service_products', 'property_application_history'];
// The legacy (non-v13) Topchoice rows as prod holds them: role fire_ant, annualMaxApps and restrictedUse in the gates.
const LEGACY_GATES = { trigger: 'documented_fire_ant_history', annualMaxApps: 1, restrictedUse: true };

const describeDb = process.env.DATABASE_URL ? describe : describe.skip;

describeDb('v13 Topchoice facts migration through PostgreSQL', () => {
  let owned;
  let knex;
  const ids = {};
  let legacy;

  beforeAll(async () => {
    owned = await createLawnHistoryDb(); knex = owned.knex;
    for (const table of TABLES) {
      await knex.raw('CREATE TABLE ??.?? (LIKE public.?? INCLUDING ALL)', [owned.schema, table, table]);
      const columns = await knex(table).columnInfo();
      if (String(columns.id?.defaultValue || '').includes('nextval(')) {
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id DROP DEFAULT', [owned.schema, table]);
        await knex.raw('ALTER TABLE ??.?? ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', [owned.schema, table]);
      }
    }
    for (const [table, constraint, suffix] of [
      ['product_limits', 'fixture_limits_product', ''], ['product_aliases', 'fixture_aliases_product', ''],
      ['service_products', 'fixture_sp_product', ' ON DELETE SET NULL'], ['lawn_protocol_products', 'fixture_lpp_product', ''],
    ]) {
      await knex.raw(`ALTER TABLE ??.?? ADD CONSTRAINT ${constraint} FOREIGN KEY (product_id) REFERENCES ??.products_catalog (id)${suffix}`, [owned.schema, table, owned.schema]);
    }
    await knex.raw('ALTER TABLE ??.lawn_protocol_audit_log ALTER COLUMN lawn_protocol_id DROP NOT NULL', [owned.schema]).catch(() => {});
  }, 60000);
  afterAll(async () => { if (owned) await owned.dispose(); });

  const topCatalog = () => knex('products_catalog').where({ id: ids.top }).first();
  const limitsOf = () => knex('product_limits').where({ product_id: ids.top }).orderBy(['limit_type', 'id']);
  const topRows = () => knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id').join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id')
    .where({ 'p.product_name': GRANULE, 'l.version': V13 }).orderBy('p.id').select('p.*', 'w.window_key', 'l.protocol_key');
  const activeTopRows = async () => (await topRows()).filter((row) => row.gates.retired !== true);
  const byProtocol = async () => (await activeTopRows()).reduce((acc, row) => ({ ...acc, [row.protocol_key]: [...(acc[row.protocol_key] || []), row] }), {});
  const clean = (state) => JSON.stringify(state, (key, value) => (key === 'updated_at' ? undefined : value));
  const upAll = async () => { await first.up(knex); await followup.up(knex); await guard.up(knex); await facts.up(knex); };
  const downs = { facts: () => facts.down(knex), guard: () => guard.down(knex), followup: () => followup.down(knex), first: () => first.down(knex) };
  const quiet = async (fn) => {
    const log = jest.spyOn(console, 'log').mockImplementation(() => {});
    try { await fn(); } finally { log.mockRestore(); }
  };
  async function snapshot() {
    return clean([
      await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']), await knex('lawn_protocol_windows').orderBy('id'),
      await knex('products_catalog').orderBy('name'), await knex('product_limits').orderBy('id'), await knex('lawn_protocol_audit_log').orderBy('id'),
    ]);
  }

  // The global facts the first two migrations wrote and must never be weakened by a rollback.
  async function expectGlobalFactsStay() {
    const row = await topCatalog();
    expect(row.restricted_use).toBe(true);
    expect([Number(row.max_label_rate_per_1000), Number(row.max_annual_per_1000)]).toEqual([2, 2]);
    expect(row.post_application_watering).toMatchObject({ mode: 'water_in', source: 'label' });
    expect(row.label_source_note).toContain(first.LABEL);
    const limits = await limitsOf();
    expect(limits.map((r) => [r.limit_type, r.match_type, r.severity, Number(r.limit_value)])).toEqual([
      ['annual_max_apps', 'product', 'hard_block', 1], ['min_interval_days', 'product', 'hard_block', 365],
    ]);
  }
  // ownPass is never missing on an active add-on row.
  async function expectEveryActiveRowCarriesOwnPass() {
    for (const row of await activeTopRows()) expect({ id: row.id, ownPass: row.gates.ownPass }).toEqual({ id: row.id, ownPass: true });
  }

  // `windowRow(protocolKey, windowKey)` returns the fields of a Topchoice row to plant before the first migration ran.
  async function reset({ plant = {}, noAdvion = [] } = {}) {
    for (const table of ['property_application_history', 'service_products', 'lawn_protocol_product_actuals', 'product_limits', 'lawn_protocol_audit_log', 'lawn_protocol_products',
      'lawn_protocol_windows', 'lawn_protocol_service_completions', 'lawn_protocols', 'product_aliases', 'products_catalog']) await knex(table).del();
    await knex('scheduled_services').update({ lawn_protocol_key: null, lawn_protocol_version: null });
    const [advion] = await knex('products_catalog').insert({ name: ADVION, category: 'insecticide', formulation: 'granular', epa_reg_number: '100-1481', rate_unit: 'lb', active: true }).returning('*');
    const [top] = await knex('products_catalog').insert({
      name: GRANULE, category: 'insecticide', product_type: 'pesticide', formulation: 'granular', epa_reg_number: '432-1217', restricted_use: false, default_rate_per_1000: 2,
      rate_unit: 'lb', irrigation_required: true, approved_for_service_report: true, label_source_note: SEED_NOTE, active: true,
    }).returning('*');
    ids.top = top.id;
    for (const key of KEYS) {
      const [protocol] = await knex('lawn_protocols').insert({ protocol_key: key, version: V13, name: 'Fixture v13', status: 'staged', grass_track: 'bermuda', region: 'swfl', effective_from: '2000-01-01' }).returning('*');
      for (const [windowKey, month] of [[APR, 4], [OCT, 10]]) {
        const [window] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: protocol.id, month, window_key: windowKey, title: windowKey, visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
        if (!noAdvion.includes(`${key}/${windowKey}`)) {
          await knex('lawn_protocol_products').insert({ lawn_protocol_window_id: window.id, product_id: advion.id, product_name: ADVION, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 0.0344, rate_unit: 'lb', default_in_plan: false, sort_order: 9, gates: JSON.stringify(ADVION_GATES) });
        }
        const planted = plant[`${key}/${windowKey}`];
        if (planted) {
          await knex('lawn_protocol_products').insert({
            lawn_protocol_window_id: window.id, product_id: top.id, product_name: GRANULE, role: 'insecticide_optional_addon', application_mode: 'broadcast', rate_per_1000: 2, rate_unit: 'lb',
            default_in_plan: false, sort_order: 20, gates: JSON.stringify(ADVION_GATES), ...planted,
          });
        }
      }
    }
    // Legacy protocols as prod holds them: another version, role fire_ant, Topchoice rows in windows of their own (one named like a v13 window).
    const [old] = await knex('lawn_protocols').insert({ protocol_key: 'fixture_legacy', version: '2026.06', name: 'Legacy', status: 'active', grass_track: 'bahia', region: 'swfl' }).returning('*');
    const [legacyApr] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: old.id, month: 4, window_key: 'apr_insect_fire_ant', title: 'legacy apr', visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
    const [legacySame] = await knex('lawn_protocol_windows').insert({ lawn_protocol_id: old.id, month: 4, window_key: APR, title: 'legacy named like v13', visit_type: 'fixture', production_mode: 'fixture' }).returning('*');
    for (const window of [legacyApr, legacySame]) {
      await knex('lawn_protocol_products').insert({
        lawn_protocol_window_id: window.id, product_id: top.id, product_name: 'TopChoice', role: 'fire_ant', application_mode: 'broadcast', rate_per_1000: 2, rate_unit: 'lb',
        default_in_plan: false, sort_order: 4, gates: JSON.stringify(LEGACY_GATES),
      });
    }
    legacy = clean(await knex('lawn_protocol_products').where({ product_name: 'TopChoice' }).orderBy('id'));
  }

  // ── 1. global facts ──────────────────────────────────────────────────────────
  describe('finding 2: the catalog corrections and both limits are global facts', () => {
    beforeEach(async () => { await reset(); });

    test('before: the first migration reverts the catalog and the count limit and the follow-up the interval (why this exists)', async () => {
      await first.up(knex); await followup.up(knex); await guard.up(knex);
      await guard.down(knex); await followup.down(knex); await first.down(knex);
      const row = await topCatalog();
      expect(row.restricted_use).toBe(false);
      expect(row.post_application_watering).toBeNull();
      expect(await limitsOf()).toEqual([]);
    });

    test('after: the first two migrations\' catalog and limit entries are emptied (the originals are kept), and the ownership is recorded', async () => {
      await upAll();
      const [catalog] = await knex('lawn_protocol_audit_log').where({ action: first.CATALOG_ACTION });
      expect(catalog.after_snapshot.changes).toEqual([]);
      expect(catalog.after_snapshot.limits).toEqual({ inserted: [], updated: [] });
      expect(catalog.after_snapshot.keptLive.changes.map((c) => c.column).sort()).toEqual(['label_source_note', 'max_annual_per_1000', 'max_label_rate_per_1000', 'post_application_watering', 'restricted_use']);
      expect(catalog.after_snapshot.keptLive.limits.inserted).toHaveLength(1);
      const [fu] = await knex('lawn_protocol_audit_log').where({ action: followup.ACTION });
      expect(fu.after_snapshot.limits).toEqual({ inserted: [], updated: [] });
      expect(fu.after_snapshot.keptLimits.inserted).toHaveLength(1);
      expect(fu.after_snapshot.keptLive.rows).toHaveLength(KEYS.length * 2);
      const [own] = await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_OWNERSHIP });
      expect(own.after_snapshot).toMatchObject({ productId: ids.top, catalogLogs: [catalog.id], followupLogs: [fu.id] });
      await expectGlobalFactsStay();
    });

    test.each([
      ['facts down only', ['facts']],
      ['facts and guard', ['facts', 'guard']],
      ['facts, guard and follow-up', ['facts', 'guard', 'followup']],
      ['the follow-up alone (migrate:down --name)', ['followup']],
      ['the first alone (migrate:down --name)', ['first']],
      ['all four, in order', ['facts', 'guard', 'followup', 'first']],
    ])('after %s: Topchoice is still restricted use with its rule, rates and both product-matched hard limits; ownPass is on every active row', async (_label, steps) => {
      await upAll();
      for (const step of steps) await quiet(downs[step]);
      await expectGlobalFactsStay();
      await expectEveryActiveRowCarriesOwnPass();
    });

    test('all four down in order: only the protocol rows revert (the Topchoice rows go, the Advion rows come back)', async () => {
      await upAll();
      await quiet(async () => { await downs.facts(); await downs.guard(); await downs.followup(); await downs.first(); });
      expect(await topRows()).toEqual([]);
      for (const advion of await knex('lawn_protocol_products').where({ product_name: ADVION })) expect(advion.gates).toEqual(ADVION_GATES);
      await expectGlobalFactsStay();
    });

    test('a visit pinned to one protocol: after every partial and the full rollback the facts stay and the pinned protocol keeps its rows with ownPass', async () => {
      await upAll();
      const f = await fixture(knex);
      const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
      try {
        for (const step of ['facts', 'guard', 'followup', 'first']) {
          await quiet(downs[step]);
          await expectGlobalFactsStay();
          await expectEveryActiveRowCarriesOwnPass();
        }
        expect(Object.keys(await byProtocol())).toEqual([KEYS[0]]);
      } finally {
        await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
      }
    });

    test('a staff-edited Topchoice row: the protocol stays whole, the facts stay', async () => {
      await upAll();
      const [row] = await activeTopRows();
      await knex('lawn_protocol_products').where({ id: row.id }).update({ sort_order: 3 });
      await quiet(async () => { await downs.facts(); await downs.guard(); await downs.followup(); await downs.first(); });
      expect(Object.keys(await byProtocol())).toEqual([row.protocol_key]);
      await expectGlobalFactsStay();
    });

    test('the real limit checker still enforces both limits through the full rollback (planner and closeout audit)', async () => {
      await upAll();
      const { customerId } = await fixture(knex);
      await knex('property_application_history').insert({ customer_id: customerId, product_id: ids.top, application_date: '2026-10-15', application_rate: 2, rate_unit: 'lb' });
      await quiet(async () => { await downs.facts(); await downs.guard(); await downs.followup(); await downs.first(); });
      const plan = await limitChecker.checkLimits(customerId, ids.top, new Date('2027-04-15T16:00:00Z'), knex);
      expect(plan.blocks.map((b) => b.type)).toEqual(['min_interval_days']);
      expect((await limitChecker.auditHardCountLimits(customerId, ids.top, '2026-12-01', knex)).map((v) => v.type).sort()).toEqual(['annual_max_apps', 'min_interval_days']);
    });

    test('a second up changes nothing, and the facts down leaves the ownership audit row', async () => {
      await upAll();
      const before = await snapshot();
      await facts.up(knex);
      expect(await snapshot()).toBe(before);
      await facts.down(knex);
      expect(await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_OWNERSHIP })).toHaveLength(1);
      await facts.up(knex);
      expect(await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_OWNERSHIP })).toHaveLength(1);
    });

    test('without a v13 protocol or a Topchoice row nothing is written', async () => {
      await first.up(knex); await followup.up(knex); await guard.up(knex);
      await knex('products_catalog').where({ id: ids.top }).update({ name: 'Renamed away' });
      let before = await snapshot();
      await quiet(() => facts.up(knex));
      expect(await snapshot()).toBe(before);
      await knex('products_catalog').where({ id: ids.top }).update({ name: GRANULE });
      await knex('lawn_protocols').where({ version: V13 }).update({ version: '2026.06' });
      before = await snapshot();
      await facts.up(knex);
      expect(await snapshot()).toBe(before);
    });
  });

  // ── 2. the governed row in each window ──────────────────────────────────────
  describe('finding 3: exactly one active governed Topchoice row where the window holds a Topchoice row', () => {
    const A = `${KEYS[0]}/${APR}`;
    const governedIn = async (key, windowKey) => (await activeTopRows()).filter((row) => row.protocol_key === key && row.window_key === windowKey);

    test('rows the first migration inserted are complete: nothing is inserted, retired or recorded', async () => {
      await reset();
      await upAll();
      expect(await topRows()).toHaveLength(KEYS.length * 2);
      expect(await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_ROWS })).toEqual([]);
    });

    test.each([
      ['a retired Topchoice row', { gates: JSON.stringify({ ...ADVION_GATES, retired: true }) }],
      ['a row at another rate', { rate_per_1000: 1.5 }],
      ['a row in another unit', { rate_unit: 'oz' }],
      ['a spot-mode row', { application_mode: 'spot' }],
      ['a row with another role', { role: 'insecticide_spot' }],
      ['a row in the plan by default', { default_in_plan: true }],
      ['a row without the optional add-on gates', { gates: JSON.stringify({ trigger: 'fixture' }) }],
      ['a row with the office-price gate off', { gates: JSON.stringify({ ...ADVION_GATES, officePrices: false }) }],
    ])('%s already in the window: a governed row is inserted beside it, the stale row is kept (retired when it was active), nothing is overwritten', async (_label, planted) => {
      await reset({ plant: { [A]: planted } });
      const [pre] = await topRows();
      const preBefore = await knex('lawn_protocol_products').where({ id: pre.id }).first();
      await upAll();
      const rows = await governedIn(KEYS[0], APR);
      expect(rows).toHaveLength(1);
      expect(rows[0].id).not.toBe(pre.id);
      expect(rows[0]).toMatchObject({ role: first.ROW.role, application_mode: 'broadcast', rate_unit: 'lb', default_in_plan: false, product_name: GRANULE });
      expect(Number(rows[0].rate_per_1000)).toBe(2);
      expect(rows[0].gates).toEqual(OWN_PASS_GATES);
      const stale = await knex('lawn_protocol_products').where({ id: pre.id }).first();
      // Same row, same id, every column but the gates as planted (plus the retired flag and ownPass where this or the guard wrote them).
      for (const column of ['product_id', 'role', 'application_mode', 'rate_per_1000', 'rate_unit', 'default_in_plan', 'sort_order', 'lawn_protocol_window_id']) {
        expect({ column, value: stale[column] }).toEqual({ column, value: preBefore[column] });
      }
      expect(stale.gates.retired).toBe(true);
      expect(await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_ROWS })).toHaveLength(1);
    });

    test('the audit row records the inserted row (with its snapshot) and the retired row\'s gates before and after', async () => {
      await reset({ plant: { [A]: { rate_per_1000: 1.5 } } });
      await upAll();
      const [log] = await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_ROWS });
      expect(log.after_snapshot.inserted).toHaveLength(1);
      expect(log.after_snapshot.inserted[0]).toMatchObject({ windowKey: APR });
      expect(log.after_snapshot.inserted[0].owned.gates).toEqual(OWN_PASS_GATES);
      expect(log.after_snapshot.retired).toHaveLength(1);
      expect(log.after_snapshot.retired[0].gatesAfter).toEqual({ ...log.after_snapshot.retired[0].gatesBefore, retired: true });
    });

    test('a second complete Topchoice row in the same window is retired (exactly one active row), the lower id stays', async () => {
      await reset({ plant: { [A]: { gates: JSON.stringify(OWN_PASS_GATES) } } });
      const [pre] = await topRows();
      await upAll();
      const rows = await governedIn(KEYS[0], APR);
      expect(rows.map((row) => row.id)).toEqual([pre.id]);
    });

    test('a window that holds no Topchoice row at all is left alone (the replacement rule of the first migration decides there)', async () => {
      await reset({ noAdvion: [`${KEYS[1]}/${OCT}`] });
      await upAll();
      expect(await governedIn(KEYS[1], OCT)).toEqual([]);
      expect(await governedIn(KEYS[1], APR)).toHaveLength(1);
    });

    test('legacy protocols\' Topchoice rows (role fire_ant, another version, one in a window named like a v13 window) are never read or changed', async () => {
      await reset({ plant: { [A]: { rate_per_1000: 1.5 } } });
      await upAll();
      expect(clean(await knex('lawn_protocol_products').where({ product_name: 'TopChoice' }).orderBy('id'))).toBe(legacy);
      for (const step of ['facts', 'guard', 'followup', 'first']) await quiet(downs[step]);
      expect(clean(await knex('lawn_protocol_products').where({ product_name: 'TopChoice' }).orderBy('id'))).toBe(legacy);
    });

    test('a second up changes nothing', async () => {
      await reset({ plant: { [A]: { rate_per_1000: 1.5 } } });
      await upAll();
      const before = await snapshot();
      await facts.up(knex);
      expect(await snapshot()).toBe(before);
    });

    test('the plan sees exactly one Topchoice row in the window (a retired row is out of every planning reader)', async () => {
      await reset({ plant: { [A]: { rate_per_1000: 1.5 } } });
      await upAll();
      const { activeProtocolProducts } = require('../services/lawn-protocol-retired');
      const names = await activeProtocolProducts(knex('lawn_protocol_products as p').join('lawn_protocol_windows as w', 'p.lawn_protocol_window_id', 'w.id')
        .join('lawn_protocols as l', 'w.lawn_protocol_id', 'l.id').where({ 'w.window_key': APR, 'l.protocol_key': KEYS[0], 'l.version': V13 }), 'p').pluck('p.product_name');
      expect(names.filter((name) => name === GRANULE)).toHaveLength(1);
      expect(names).not.toContain(ADVION);
    });

    describe('rollback of the rows', () => {
      beforeEach(async () => { await reset({ plant: { [A]: { rate_per_1000: 1.5 } } }); });

      test('the facts down alone restores the stale row and removes the inserted one exactly', async () => {
        await first.up(knex); await followup.up(knex); await guard.up(knex);
        const before = await snapshot();
        await facts.up(knex);
        expect(await snapshot()).not.toBe(before);
        await facts.down(knex);
        // The ownership change stays (catalog and limit entries stay emptied); every protocol row is as before.
        expect(clean(await knex('lawn_protocol_products').orderBy(['product_name', 'sort_order', 'id']))).toBe(JSON.parse(before)[0] && clean(JSON.parse(before)[0]));
        expect(await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_ROWS })).toEqual([]);
      });

      test('all four down in order: the planted row (a staff edit) keeps its protocol whole with ownPass; the other protocol reverts', async () => {
        await upAll();
        await quiet(async () => { await downs.facts(); await downs.guard(); await downs.followup(); await downs.first(); });
        expect(Object.keys(await byProtocol())).toEqual([KEYS[0]]);
        await expectEveryActiveRowCarriesOwnPass();
        await expectGlobalFactsStay();
      });

      test('a visit pinned to the protocol: the facts down leaves the inserted and the retired rows as they are', async () => {
        await upAll();
        const f = await fixture(knex);
        const pinned = await f.visit(0, { lawn_protocol_key: KEYS[0], lawn_protocol_version: V13 });
        try {
          const before = clean(await topRows());
          await quiet(downs.facts);
          expect(clean(await topRows())).toBe(before);
          expect(await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_ROWS })).toHaveLength(1);
          await expectEveryActiveRowCarriesOwnPass();
        } finally {
          await knex('scheduled_services').where({ id: pinned.id }).update({ lawn_protocol_key: null, lawn_protocol_version: null });
        }
      });

      test('staff edited the inserted row, or the retired row\'s gates: the protocol\'s entries stay (nothing is half-restored)', async () => {
        for (const edit of ['inserted', 'retired']) {
          await reset({ plant: { [A]: { rate_per_1000: 1.5 } } });
          await upAll();
          const [log] = await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_ROWS });
          const id = edit === 'inserted' ? log.after_snapshot.inserted[0].id : log.after_snapshot.retired[0].rowId;
          const row = await knex('lawn_protocol_products').where({ id }).first();
          await knex('lawn_protocol_products').where({ id }).update(edit === 'inserted' ? { sort_order: 99 } : { gates: JSON.stringify({ ...row.gates, edited: true }) });
          const before = clean(await topRows());
          await quiet(downs.facts);
          expect(clean(await topRows())).toBe(before);
          expect(await knex('lawn_protocol_audit_log').where({ action: facts.ACTION_ROWS })).toHaveLength(1);
        }
      });
    });
  });
});
