jest.mock('../services/estimate-first-application-invoice', () => ({
  // Owner ruling — REFUSE AFTER A VOID: billing-lane.js's
  // combinedInvoiceVoidedWithoutLiveReplacement reuses the REAL, pure
  // isAutoGeneratedPayPerApplicationInvoice (no DB, no side effects) to
  // recognize a voided combined invoice's notes — only the DB-backed
  // lookup itself is mocked below.
  ...jest.requireActual('../services/estimate-first-application-invoice'),
  findFirstApplicationInvoiceForEstimateService: jest.fn(),
}));

const {
  shouldAttemptPrepaidReceipt,
  resolveScheduledServiceCharge,
} = require('../routes/admin-schedule')._test;
const { findFirstApplicationInvoiceForEstimateService } = require('../services/estimate-first-application-invoice');
const { predictCompletionBilling } = require('../services/billing-lane');

afterEach(() => {
  jest.clearAllMocks();
});

describe('shouldAttemptPrepaidReceipt', () => {
  const ok = { gateEnabled: true, emailReceipt: true, applyToSeries: false, prepaidAmount: 80 };

  test('attempts when gated on, requested, single visit, positive amount', () => {
    expect(shouldAttemptPrepaidReceipt(ok)).toEqual({ attempt: true, reason: null });
  });

  test('does not attempt when the operator did not request a receipt', () => {
    expect(shouldAttemptPrepaidReceipt({ ...ok, emailReceipt: false }))
      .toEqual({ attempt: false, reason: 'not_requested' });
    // undefined (flag absent in body) is also "not requested", not a crash.
    expect(shouldAttemptPrepaidReceipt({ ...ok, emailReceipt: undefined }))
      .toEqual({ attempt: false, reason: 'not_requested' });
    // Only a strict true opts in — a truthy string must not trigger a send.
    expect(shouldAttemptPrepaidReceipt({ ...ok, emailReceipt: 'yes' }))
      .toEqual({ attempt: false, reason: 'not_requested' });
  });

  test('not-requested takes precedence over a disabled gate', () => {
    expect(shouldAttemptPrepaidReceipt({ ...ok, emailReceipt: false, gateEnabled: false }))
      .toEqual({ attempt: false, reason: 'not_requested' });
  });

  test('does not attempt when the gate is off (fail-closed)', () => {
    expect(shouldAttemptPrepaidReceipt({ ...ok, gateEnabled: false }))
      .toEqual({ attempt: false, reason: 'disabled' });
  });

  test('does not attempt for a whole-series prepayment', () => {
    expect(shouldAttemptPrepaidReceipt({ ...ok, applyToSeries: true }))
      .toEqual({ attempt: false, reason: 'series_unsupported' });
  });

  test('does not attempt when no money was recorded', () => {
    expect(shouldAttemptPrepaidReceipt({ ...ok, prepaidAmount: 0 }))
      .toEqual({ attempt: false, reason: 'no_prepaid_amount' });
    expect(shouldAttemptPrepaidReceipt({ ...ok, prepaidAmount: -5 }))
      .toEqual({ attempt: false, reason: 'no_prepaid_amount' });
    expect(shouldAttemptPrepaidReceipt({ ...ok, prepaidAmount: NaN }))
      .toEqual({ attempt: false, reason: 'no_prepaid_amount' });
  });
});

describe('resolveScheduledServiceCharge', () => {
  test('an explicit estimate price wins over everything', async () => {
    expect(await resolveScheduledServiceCharge({ estimatedPrice: 129, isCallback: false, monthlyRate: 49 }))
      .toBe(129);
    // even on a callback, an explicitly-set price is honoured
    expect(await resolveScheduledServiceCharge({ estimatedPrice: 129, isCallback: true, monthlyRate: 49 }))
      .toBe(129);
  });

  test('a non-callback recurring visit falls back to the monthly rate', async () => {
    expect(await resolveScheduledServiceCharge({ estimatedPrice: null, isCallback: false, monthlyRate: 49 }))
      .toBe(49);
  });

  test('a callback (re-service) is free even with a monthly rate', async () => {
    expect(await resolveScheduledServiceCharge({ estimatedPrice: null, isCallback: true, monthlyRate: 49 }))
      .toBe(0);
  });

  test('a zero/negative estimate price falls through to the monthly rate', async () => {
    expect(await resolveScheduledServiceCharge({ estimatedPrice: 0, isCallback: false, monthlyRate: 49 }))
      .toBe(49);
    expect(await resolveScheduledServiceCharge({ estimatedPrice: -10, isCallback: false, monthlyRate: 49 }))
      .toBe(49);
  });

  test('nothing chargeable returns 0', async () => {
    expect(await resolveScheduledServiceCharge({ estimatedPrice: null, isCallback: false, monthlyRate: 0 }))
      .toBe(0);
    expect(await resolveScheduledServiceCharge({ estimatedPrice: null, isCallback: false, monthlyRate: null }))
      .toBe(0);
  });

  // Owner ruling — REMOVE THE CHARGE NOW FEE FALLBACK (2026-09-27): Charge
  // Now / prepaid-receipt minting must NEVER bill an unpriced visit from the
  // customer-level per_application_fee — that is main's original behavior,
  // restored here.
  //
  // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13,
  // codex pre-push P1): a bare 0 for an unpriced, non-callback,
  // non-always-free per_application visit is not "nothing chargeable" — it
  // is EXACTLY the shape completion bills the acceptance fee for
  // (completionInvoiceAmount's own per_application branch, billing-lane.js).
  // A caller with extraLineItems (or an existing invoice already on the
  // row) could otherwise mint/reuse an extras-only invoice attached to the
  // visit — complete-scheduled-service.js's existingCompletionInvoice
  // lookup then finds it and never re-runs the fee decision, losing the
  // fee outright rather than merely deferring it. This resolver now returns
  // the SAME kind of structured refusal a covered sibling visit already
  // does (round-8 P1) for this exact shape, unconditionally — every caller
  // must check `.refused` before treating a 0 as "nothing to mint, but
  // reuse/extras are fine."
  test('an unpriced, non-callback, non-always-free per_application visit refuses the whole mint — completion bills the fee, not Charge Now', async () => {
    const result = await resolveScheduledServiceCharge({
      estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
    });
    expect(result).toEqual({
      refused: true,
      reason: 'per_application_fee_at_completion',
      message: expect.stringMatching(/bills its application fee at completion/i),
    });
  });

  // A callback is unaffected either way — still free, and never reaches the
  // per_application refusal (isCallback excludes it, mirroring completion
  // itself, which never bills a callback the fee).
  test('a callback per_application visit is unaffected — free, never refused', async () => {
    expect(await resolveScheduledServiceCharge({
      estimatedPrice: null, isCallback: true, monthlyRate: 74.7, billingMode: 'per_application',
    })).toBe(0);
  });

  test('a zero estimatedPrice refuses the same way as null — never a bare 0, never the acceptance fee', async () => {
    const result = await resolveScheduledServiceCharge({
      estimatedPrice: 0, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
    });
    expect(result).toEqual({
      refused: true,
      reason: 'per_application_fee_at_completion',
      message: expect.stringMatching(/bills its application fee at completion/i),
    });
  });

  // Owner ruling: this used to be a parity test proving predictCompletionBilling
  // (the schedule sheet's preview of what COMPLETION will bill) and
  // resolveScheduledServiceCharge (what Charge Now actually mints) agreed on
  // the same fixture. They now deliberately DIVERGE for an unpriced
  // per_application visit — completion still bills the acceptance fee
  // (predictCompletionBilling is completion's own prediction, untouched by
  // this ruling), but Charge Now refuses the WHOLE mint outright (round 13
  // — not just a bare 0 a caller's extras could clear). MobileCheckoutSheet's
  // own tests pin the client-side half of this (no preview of the fee, and
  // no Add Service/Item pickers offered for this shape either).
  test('completion still predicts the acceptance fee; Charge Now refuses the whole mint — the two deliberately diverge', async () => {
    const fixture = {
      estimatedPrice: 0, isCallback: false, monthlyRate: null, billingMode: 'per_application',
      perApplicationFee: 97.2, serviceType: 'Quarterly Pest Control',
    };

    // "Preview" — what the schedule payload hands the client as
    // billingLane.prediction; grossAmount is the fee a checkout sheet
    // stacks extras on top of. Completion's own precedence, unaffected.
    const prediction = predictCompletionBilling({
      ...fixture,
      lane: 'per_application',
      autopayActive: false,
      isRecurring: false,
      payerBilled: false,
      prepaidAmount: null,
      prepaidMethod: null,
    });
    expect(prediction.grossAmount).toBe(97.2);

    // "Mint" — resolveScheduledServiceCharge no longer takes perApplicationFee
    // at all (passing it, as a stale caller might, is simply ignored), and
    // now refuses this shape outright rather than resolving 0.
    const mintResult = await resolveScheduledServiceCharge(fixture);
    expect(mintResult).toEqual({
      refused: true,
      reason: 'per_application_fee_at_completion',
      message: expect.stringMatching(/bills its application fee at completion/i),
    });
  });

  test('an explicit non-monthly, non-per_application lane still never falls back to the lingering monthly rate', async () => {
    expect(await resolveScheduledServiceCharge({
      estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_visit',
    })).toBe(0);
  });

  // Owner ruling — REFUSE EXTRAS-ONLY MINTS: scoped to per_application ONLY
  // — checked against monthly_membership, the other lane with an
  // unpriced-visit fallback. That lane's fallback is `monthlyRate`, read by
  // THIS SAME resolver's completionInvoiceAmount call with the exact inputs
  // completion itself reads: if completion would bill the rate, `amount`
  // is ALREADY positive here — no fee-removal divergence for that lane
  // exists at all, so the ordinary "amount > 0" mint path (with extras
  // stacked on top, same as always) already covers it. No refusal, no gap.
  test('an unpriced monthly_membership visit has no equivalent gap — it mints the monthly rate normally, extras included', async () => {
    expect(await resolveScheduledServiceCharge({
      estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'monthly_membership',
    })).toBe(74.7);
    // With no rate on file either, it resolves a plain 0 (not refused) —
    // completion bills nothing for it either, so there's nothing for
    // extras to suppress.
    expect(await resolveScheduledServiceCharge({
      estimatedPrice: null, isCallback: false, monthlyRate: 0, billingMode: 'monthly_membership',
    })).toBe(0);
  });

  // An always-free type (estimate/follow-up/re-service) is unaffected by
  // the round-13 refusal, exactly like it's unaffected by every other
  // per_application exclusion in this lane (isSiblingCoverageEligibleVisit,
  // predictCompletionBilling) — completion bills nothing for it either, so
  // there's nothing for an extras-only mint to suppress.
  test('an unpriced always-free-type visit under an explicit per_application lane is unaffected — bills nothing, never refused', async () => {
    expect(await resolveScheduledServiceCharge({
      estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
      serviceType: 'Pest Control Follow-Up',
    })).toBe(0);
    // An explicit price still wins over everything, same as it always has
    // over isCallback on this resolver.
    expect(await resolveScheduledServiceCharge({
      estimatedPrice: 50, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
      serviceType: 'Pest Control Follow-Up',
    })).toBe(50);
  });

  // Owner ruling — REFUSE EXTRAS-ONLY MINTS: a genuinely billable
  // per_application type (not always-free) refuses too, even with no
  // svc/dbConn passed — this is a pure shape gate, not a DB lookup, so the
  // sibling-coverage guard below never even asks.
  test('a genuinely billable per_application type refuses too, even with no svc/dbConn passed', async () => {
    const result = await resolveScheduledServiceCharge({
      estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
      serviceType: 'Quarterly Pest Control',
    });
    expect(result).toEqual({
      refused: true,
      reason: 'per_application_fee_at_completion',
      message: expect.stringMatching(/bills its application fee at completion/i),
    });
    expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
  });

  // Codex pre-push P1 (this branch): a same-day combined per-application
  // accept invoices the RESERVED sibling row for the whole trip and leaves
  // THIS, the PROMOTED row, deliberately unpriced — but the customer can
  // still carry an established per_application_fee from an earlier accept
  // (estimate-converter.js preserves it on an add-on accept). Without a
  // sibling-coverage check, Charge Now / the prepaid receipt would mint
  // that unrelated fee for a trip the sibling's invoice already covers.
  describe('sibling-covered same-trip visit', () => {
    const SVC = { id: 'svc-lawn', customer_id: 'cust-1', source_estimate_id: 'est-1', scheduled_date: '2026-09-27' };
    // Owner ruling — REFUSE AFTER A VOID: a null-invoice verdict now also
    // runs billing-lane.js's combinedInvoiceVoidedWithoutLiveReplacement
    // fail-closed guard, whose own 'invoices as i' query is AWAITED
    // DIRECTLY (thenable — mirrors knex's `.select()`), never through
    // `.first()`. `dbConnInvoiceRows` (reset in beforeEach below) resolves
    // it to "nothing on the estimate" (empty array) by default, preserving
    // every EXISTING verdict below; a test may reassign it to opt into a
    // voided-invoice fixture.
    let dbConnInvoiceRows = [];
    beforeEach(() => { dbConnInvoiceRows = []; });
    const DB_CONN = () => {
      const q = {};
      ['join', 'where', 'whereNot', 'whereNull', 'whereNotIn', 'whereIn', 'orderBy', 'forUpdate', 'noWait', 'select'].forEach((m) => { q[m] = () => q; });
      q.first = async () => undefined;
      q.then = (resolve, reject) => Promise.resolve(dbConnInvoiceRows).then(resolve, reject);
      q.catch = (reject) => Promise.resolve(dbConnInvoiceRows).catch(reject);
      return q;
    };

    // Owner decision (round-8 P1, narrow + fail closed): a definitive
    // 'covered' verdict is now a flat structured refusal, not a $0 that a
    // caller with checkout extras could mint an extras-only invoice past —
    // see admin-schedule-charge-now-sibling-refusal.test.js for the
    // route-level "no extras-only mint on a covered visit" coverage.
    test('a sibling-covered unpriced per_application visit refuses to mint the lingering acceptance fee', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
        liveBeside: null,
      });
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({
        refused: true,
        reason: 'sibling_invoice_covered',
        message: expect.stringMatching(/combined trip invoice/i),
      });
    });

    test('an explicit own price still wins over sibling coverage', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
        liveBeside: null,
      });
      expect(await resolveScheduledServiceCharge({
        estimatedPrice: 40, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      })).toBe(40);
      expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
    });

    // Owner ruling — REFUSE EXTRAS-ONLY MINTS FOR THE FEE SHAPE (round 13):
    // this used to prove an own-row match falls through to 0 (the removed
    // fee fallback). A bare 0 for this shape is now itself refused
    // outright — completion bills the acceptance fee for it, so any 0 that
    // let a caller's extras (or an existing invoice reuse) slip past would
    // silently drop that fee. Same structured refusal as any other
    // 'none'-verdict per_application visit with no own price.
    test('a match naming this visit\'s OWN row (not a sibling) still refuses the whole mint — no fee, no extras-only mint', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: SVC.id, status: 'sent', total: 97.2 },
        liveBeside: null,
      });
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({
        refused: true,
        reason: 'per_application_fee_at_completion',
        message: expect.stringMatching(/bills its application fee at completion/i),
      });
    });

    test('no sibling match still refuses the whole mint — no fee, no extras-only mint', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({
        refused: true,
        reason: 'per_application_fee_at_completion',
        message: expect.stringMatching(/bills its application fee at completion/i),
      });
    });

    // Owner ruling — REFUSE AFTER A VOID: the estimate's recognized combined
    // invoice is voided (findFirstApplicationInvoiceForEstimateService's
    // own query excludes 'void' entirely, so it reports 'none' exactly like
    // "nothing was ever minted") — the Mark-prepaid / Charge Now resolver
    // must refuse the lingering acceptance fee here too, never mint it on
    // top of a trip the reserved row still bills once.
    test('a voided combined invoice with no live recognized replacement returns a structured refusal, never the lingering fee', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      dbConnInvoiceRows = [{
        id: 'inv-void', invoice_number: 'WPC-TEST-0099', status: 'void', title: 'First application',
        notes: 'Auto-generated from accepted estimate #est-1 — customer selected pay per application — first application.',
      }];
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({ refused: true, reason: 'sibling_invoice_needs_review', message: expect.stringMatching(/manual review/i) });
    });

    // Codex pre-push P0: a MINT decision must fail CLOSED on a lookup
    // failure, unlike the read-only schedule prediction — completion's own
    // mint refuses (throws, retryable) rather than risk minting a duplicate
    // when its equivalent lookup errors. Falling through to bill the fee
    // here would do exactly what completion refuses to do.
    //
    // Codex ROUND 2 P1: a bare 0 here is NOT "nothing chargeable" — it's
    // indistinguishable from a confirmed-covered $0, and a caller with
    // extraLineItems could mint an extras-only invoice past that lie. The
    // resolver now returns a structured refusal instead, which every
    // caller must check before treating the result as a priceable amount.
    test('a lookup failure returns a structured refusal (never a bare 0, never a false mint)', async () => {
      findFirstApplicationInvoiceForEstimateService.mockRejectedValue(new Error('db down'));
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({ refused: true, reason: 'sibling_lookup_failed', message: expect.stringMatching(/refresh and try again/i) });
    });

    // Codex pre-push P0: findFirstApplicationInvoiceForEstimateService
    // deliberately surfaces a refunded/canceled match ahead of any live
    // replacement (liveBeside) — completion parks THAT shape for a human
    // (manual-billing alert), it never re-mints. Treating it as "no
    // sibling, bill the fee" here would mint a THIRD invoice for a trip
    // that may still have a live collectible one riding as liveBeside.
    test('a terminal/refunded sibling match returns a structured refusal too — that stays completion\'s own manual-billing alert, not a remint', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: { id: 'inv-1', scheduled_service_id: 'svc-pest', status: 'refunded', total: 153.6 },
        liveBeside: { id: 'inv-2', scheduled_service_id: 'svc-pest', status: 'sent', total: 153.6 },
      });
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({ refused: true, reason: 'sibling_invoice_needs_review', message: expect.stringMatching(/manual review/i) });
    });

    // Codex pre-push P0 (round 2): findFirstApplicationInvoiceForEstimateService
    // returns { invoice: null, canceledSetupFee } when a canceled acceptance
    // invoice carried the one-time setup fee with no live replacement —
    // completion parks that shape for manual billing rather than reminting.
    // The resolver must refuse the fee here too, or Charge Now would mint
    // only the per-application charge and silently drop the fee.
    test('a canceled acceptance invoice carrying the setup fee (no live replacement) returns a structured refusal, not just a partial mint', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({
        invoice: null,
        liveBeside: null,
        canceledSetupFee: { id: 'inv-3', invoice_number: 'WPC-2026-0400', status: 'canceled' },
      });
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({ refused: true, reason: 'sibling_invoice_needs_review', message: expect.stringMatching(/manual review/i) });
    });

    // Owner ruling — REFUSE EXTRAS-ONLY MINTS: the per_application refusal
    // is a pure shape gate (isCallback / isAlwaysFreeServiceType / hasOwnPrice
    // only) — it fires even with no svc/dbConn passed, unlike the
    // sibling-coverage lookup (which is skipped here, as before).
    test('without svc/dbConn (a caller that has neither) skips the sibling lookup but still refuses the fee shape', async () => {
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: null, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care',
      });
      expect(result).toEqual({
        refused: true,
        reason: 'per_application_fee_at_completion',
        message: expect.stringMatching(/bills its application fee at completion/i),
      });
      expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
    });

    // Codex pre-push P1 (round 3): completion-pricing's discount engine
    // freezes a fully-discounted application at a genuine $0 net by
    // stamping a positive primary_line_price alongside the $0
    // estimated_price (pinned for real by completion-pricing.postgres.test.js's
    // "fully discounted application stays zero" case). This resolver must
    // treat that as the visit's OWN price — never fall into the
    // sibling-coverage lookup (unrelated) or the acceptance fee (wrong).
    test('a provenance-backed $0 (a positive primary_line_price on the row) bills nothing — never the sibling lookup', async () => {
      expect(await resolveScheduledServiceCharge({
        estimatedPrice: 0, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care',
        svc: { ...SVC, primary_line_price: 100 }, dbConn: DB_CONN,
      })).toBe(0);
      expect(findFirstApplicationInvoiceForEstimateService).not.toHaveBeenCalled();
    });

    // Without a positive primary_line_price on the row, a bare stamped 0 is
    // the DIFFERENT, indistinguishable-from-null shape (the sibling-covered
    // same-trip PROMOTED row leaves both columns null) and still defers to
    // the sibling lookup exactly as before this change — once that lookup
    // confirms 'none', it now refuses the whole mint outright (round 13)
    // instead of resolving the (removed) fee.
    test('a bare stamped $0 with no primary_line_price still defers to the sibling lookup, then refuses the whole mint', async () => {
      findFirstApplicationInvoiceForEstimateService.mockResolvedValue({ invoice: null, liveBeside: null });
      const result = await resolveScheduledServiceCharge({
        estimatedPrice: 0, isCallback: false, monthlyRate: 74.7, billingMode: 'per_application',
        serviceType: 'Every 6 Weeks Lawn Care', svc: SVC, dbConn: DB_CONN,
      });
      expect(result).toEqual({
        refused: true,
        reason: 'per_application_fee_at_completion',
        message: expect.stringMatching(/bills its application fee at completion/i),
      });
      expect(findFirstApplicationInvoiceForEstimateService).toHaveBeenCalled();
    });
  });
});
